### ISSUE TITLE
DOMLauncher - chokes icetray-inspect (Trac #1078)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1072]
Either `DOMLauncher (PMTResponseSimulator)`, `I3ConditionalModule` or `icetray-inspect` is broken.

Temporary fix in r135699/IceCube.

```text
[ 61%] Generating html from icetray-inspect of DOMLauncher
Traceback (most recent call last):
  File "/build/buildslave/yaoguai/simulation_docs/build/bin/icetray-inspect", line 240, in <module>
    if display_config(mod, 'Python I3Module', py_modules[mod]):
  File "/build/buildslave/yaoguai/simulation_docs/build/bin/icetray-inspect", line 159, in display_config
    config = i3inspect.get_configuration(mod)
  File "/build/buildslave/yaoguai/simulation_docs/build/lib/icecube/icetray/i3inspect.py", line 138, in get_configuration
    return module(I3Context()).configuration
Boost.Python.ArgumentError: Python argument types in
    None.None(PMTResponseSimulator)
did not match C++ signature:
    None(PythonModule<I3ConditionalModule> {lvalue})
make[3]: *** [DOMLauncher/CMakeFiles/DOMLauncher-DOMLauncher-inspect] Error 1
make[2]: *** [DOMLauncher/CMakeFiles/DOMLauncher-DOMLauncher-inspect.dir/all] Error 2
make[1]: *** [CMakeFiles/docs.dir/rule] Error 2
make: *** [docs] Error 2
```

Migrated from https://code.icecube.wisc.edu/ticket/1078
```json
{
    "status": "closed", 
    "changetime": "2016-03-18T21:14:10", 
    "description": "Either `DOMLauncher (PMTResponseSimulator)`, `I3ConditionalModule` or `icetray-inspect` is broken.\n\nTemporary fix in r135699/IceCube.\n\n{{{\n[ 61%] Generating html from icetray-inspect of DOMLauncher\nTraceback (most recent call last):\n  File \"/build/buildslave/yaoguai/simulation_docs/build/bin/icetray-inspect\", line 240, in <module>\n    if display_config(mod, 'Python I3Module', py_modules[mod]):\n  File \"/build/buildslave/yaoguai/simulation_docs/build/bin/icetray-inspect\", line 159, in display_config\n    config = i3inspect.get_configuration(mod)\n  File \"/build/buildslave/yaoguai/simulation_docs/build/lib/icecube/icetray/i3inspect.py\", line 138, in get_configuration\n    return module(I3Context()).configuration\nBoost.Python.ArgumentError: Python argument types in\n    None.None(PMTResponseSimulator)\ndid not match C++ signature:\n    None(PythonModule<I3ConditionalModule> {lvalue})\nmake[3]: *** [DOMLauncher/CMakeFiles/DOMLauncher-DOMLauncher-inspect] Error 1\nmake[2]: *** [DOMLauncher/CMakeFiles/DOMLauncher-DOMLauncher-inspect.dir/all] Error 2\nmake[1]: *** [CMakeFiles/docs.dir/rule] Error 2\nmake: *** [docs] Error 2\n}}}", 
    "reporter": "nega", 
    "cc": "cweaver, jvansanten", 
    "resolution": "fixed", 
    "_ts": "1458335650323600", 
    "component": "combo simulation", 
    "summary": "DOMLauncher - chokes icetray-inspect", 
    "priority": "blocker", 
    "keywords": "DOMLauncher PMTResponceSimulator icetray-inspect documentation", 
    "time": "2015-07-30T04:35:21", 
    "milestone": "", 
    "owner": "sflis", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20150730T04:38:21: nega changed cc from "cweaver" to "cweaver, jvs"

**Comment by icecube-trac** [comment]
Trac update at 20150730T04:38:43: nega changed cc from "cweaver, jvs" to "cweaver, jvansanten"

**Comment by icecube-trac** [comment]
Trac update at 20150730T11:05:28: jvansanten commented:

> The issue here is that `I3ConditionalModule` is only exposed via `PythonModule<I3ConditionalModule>`, but `PMTResponseSimulator` is a real instance of `I3ConditonalModule`, not `PythonModule<I3ConditionalModule>`. If we want to be able to instantiate `I3Module` subclasses cleanly from Python, we need to rework the `I3Module` pybindings to use inheritance correctly. The task would be similar to r129295 in phys-services, with the additional complication that `I3Module` has protected methods.

**Comment by icecube-trac** [comment]
Trac update at 20150818T15:52:54: sflis commented:

> Looking at jvs comment maybe somebody with write access to the icetray repository should fix it? Maybe jvansanten or somebody else can volenteer?

**Comment by icecube-trac** [comment]
Trac update at 20150818T18:10:41: 
* icecube changed resolution from "" to "fixed"
* icecube commented:

> Is fixed with r136417/IceCube.


* icecube changed status from "new" to "closed"
* nega changed _comment0 from "Is fixed with r136417." to "1439921732319548"

**Comment by icecube-trac** [comment]
Trac update at 20160318T21:14:10: 
* olivas changed milestone from "offline V15-12-00" to ""
* olivas commented:

> Milestone offline V15-12-00 deleted
