### ISSUE TITLE
[trigger-sim] failing examples/scripts (Trac #1138)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1132]
The following scripts and examples fail:

resources/examples/change_trigger_settings.py
Traceback (most recent call last):
  File "change_trigger_settings.py", line 8, in <module>
    tkey.Source = dataclasses.I3Trigger.IN_ICE
AttributeError: *** The dynamism of this class has been disabled
*** Attribute (Source) does not exist in class TriggerKey

resources/examples/GCD_changetime.py
Traceback (most recent call last):
  File "GCD_changetime.py", line 44, in <module>
    end_time.SetDaqTime(2010,228241778063632575)
AttributeError: 'I3Time' object has no attribute 'SetDaqTime'

resources/examples/GCD_retrig.py
Traceback (most recent call last):
  File "GCD_retrig.py", line 28, in <module>
    i3ds.triggerStatus.clear()
AttributeError: 'I3DetectorStatus' object has no attribute 'triggerStatus'

resources/pffilt_retrigger/retrigger_retriggered.py
Traceback (most recent call last):
  File "./retrigger_retriggered.py", line 7, in <module>
    from icecube.examples_simulation.configure_simulation import configure_triggers
ImportError: cannot import name configure_triggers

resources/scripts/AtDeepCoreThresholdTest.py
Traceback (most recent call last):
  File "./AtDeepCoreThresholdTest.py", line 26, in <module>
    time = detstat.endTime
AttributeError: 'I3DetectorStatus' object has no attribute 'endTime'
es/scripts/AtDeepCoreThresholdTest.py

(Most of the other scripts in the directory resources/scripts fail with the same error. I do not list those duplicates.)

resources/scripts/GlobalTriggerSim_NoTrigger.py
INFO (I3Tray): GT: FilterMode = False (I3Tray.py:220 in __call__)
FATAL (trigger-sim): object in frame at "I3DetectorStatus" doesn't exist.  (I3Frame.h:352 in const T& I3Frame::Get(const string&, typename boost::disable_if<is_shared_ptr<Service> >::type*) const [with T = I3DetectorStatus; std::string = std::basic_string<char>; typename boost::disable_if<is_shared_ptr<Service> >::type = void])
ERROR (I3Module): GT: Exception thrown (I3Module.cxx:114 in void I3Module::Do(void (I3Module::*)()))
Traceback (most recent call last):
  File "resources/scripts/GlobalTriggerSim_NoTrigger.py", line 19, in <module>
    tray.Execute(100)
  File "/home/hdembinski/Code/icecube/icesim/debug.trunk/lib/I3Tray.py", line 232, in Execute
    super(I3Tray, self).Execute(args[0])
RuntimeError: object in frame at "I3DetectorStatus" doesn't exist.  (in const T& I3Frame::Get(const string&, typename boost::disable_if<is_shared_ptr<Service> >::type*) const [with T = I3DetectorStatus; std::string = std::basic_string<char>; typename boost::disable_if<is_shared_ptr<Service> >::type = void])

Migrated from https://code.icecube.wisc.edu/ticket/1138
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:11:45", 
    "description": "The following scripts and examples fail:\n\nresources/examples/change_trigger_settings.py\nTraceback (most recent call last):\n  File \"change_trigger_settings.py\", line 8, in <module>\n    tkey.Source = dataclasses.I3Trigger.IN_ICE\nAttributeError: *** The dynamism of this class has been disabled\n*** Attribute (Source) does not exist in class TriggerKey\n\nresources/examples/GCD_changetime.py\nTraceback (most recent call last):\n  File \"GCD_changetime.py\", line 44, in <module>\n    end_time.SetDaqTime(2010,228241778063632575)\nAttributeError: 'I3Time' object has no attribute 'SetDaqTime'\n\nresources/examples/GCD_retrig.py\nTraceback (most recent call last):\n  File \"GCD_retrig.py\", line 28, in <module>\n    i3ds.triggerStatus.clear()\nAttributeError: 'I3DetectorStatus' object has no attribute 'triggerStatus'\n\nresources/pffilt_retrigger/retrigger_retriggered.py\nTraceback (most recent call last):\n  File \"./retrigger_retriggered.py\", line 7, in <module>\n    from icecube.examples_simulation.configure_simulation import configure_triggers\nImportError: cannot import name configure_triggers\n\nresources/scripts/AtDeepCoreThresholdTest.py\nTraceback (most recent call last):\n  File \"./AtDeepCoreThresholdTest.py\", line 26, in <module>\n    time = detstat.endTime\nAttributeError: 'I3DetectorStatus' object has no attribute 'endTime'\nes/scripts/AtDeepCoreThresholdTest.py\n\n(Most of the other scripts in the directory resources/scripts fail with the same error. I do not list those duplicates.)\n\nresources/scripts/GlobalTriggerSim_NoTrigger.py\nINFO (I3Tray): GT: FilterMode = False (I3Tray.py:220 in __call__)\nFATAL (trigger-sim): object in frame at \"I3DetectorStatus\" doesn't exist.  (I3Frame.h:352 in const T& I3Frame::Get(const string&, typename boost::disable_if<is_shared_ptr<Service> >::type*) const [with T = I3DetectorStatus; std::string = std::basic_string<char>; typename boost::disable_if<is_shared_ptr<Service> >::type = void])\nERROR (I3Module): GT: Exception thrown (I3Module.cxx:114 in void I3Module::Do(void (I3Module::*)()))\nTraceback (most recent call last):\n  File \"resources/scripts/GlobalTriggerSim_NoTrigger.py\", line 19, in <module>\n    tray.Execute(100)\n  File \"/home/hdembinski/Code/icecube/icesim/debug.trunk/lib/I3Tray.py\", line 232, in Execute\n    super(I3Tray, self).Execute(args[0])\nRuntimeError: object in frame at \"I3DetectorStatus\" doesn't exist.  (in const T& I3Frame::Get(const string&, typename boost::disable_if<is_shared_ptr<Service> >::type*) const [with T = I3DetectorStatus; std::string = std::basic_string<char>; typename boost::disable_if<is_shared_ptr<Service> >::type = void])", 
    "reporter": "hdembinski", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1550067105393059", 
    "component": "combo simulation", 
    "summary": "[trigger-sim] failing examples/scripts", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2015-08-17T21:27:56", 
    "milestone": "", 
    "owner": "olivas", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20151209T16:40:27: olivas changed milestone from "" to "IceSim 5.0"

**Comment by icecube-trac** [comment]
Trac update at 20160119T04:21:01: 
* olivas changed status from "new" to "closed"
* olivas changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:11:45: 
* olivas changed milestone from "IceSim 5.0" to ""
* olivas commented:

> Milestone IceSim 5.0 deleted
