### ISSUE TITLE
CoincSuite application.py example doesn't run (Trac #1160)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1154]
Here is the error I get when I naively try to run the script:

```text
INFO (Python): Using CoincSuite Recombinations (coincsuite.py:82 in Complete)
Traceback (most recent call last):
  File "application.py", line 48, in <module>
    FitName = 'LFit')
  File "/home/jtatar/StrikeTeam/IceRec/build/lib/I3Tray.py", line 204, in AddSegment
    return _segment(self, _name, **kwargs)
  File "/home/jtatar/StrikeTeam/IceRec/build/lib/icecube/CoincSuite/coincsuite.py", line 169, in Complete
    mininame = lilliput.add_minuit_simplex_minimizer_service(tray)
NameError: global name 'lilliput' is not defined

```

* The RunParameters class is not being used anywhere in the script.
* The script tries to read /CoincSuite/resources/data/example_scenario.i3.bz2.  Directory and file do not exist.
* Please add detailed comments to the code and a better summary at the top as to what the script does exactly.

 

Migrated from https://code.icecube.wisc.edu/ticket/1160
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:11:57", 
    "description": "Here is the error I get when I naively try to run the script:\n\n{{{\nINFO (Python): Using CoincSuite Recombinations (coincsuite.py:82 in Complete)\nTraceback (most recent call last):\n  File \"application.py\", line 48, in <module>\n    FitName = 'LFit')\n  File \"/home/jtatar/StrikeTeam/IceRec/build/lib/I3Tray.py\", line 204, in AddSegment\n    return _segment(self, _name, **kwargs)\n  File \"/home/jtatar/StrikeTeam/IceRec/build/lib/icecube/CoincSuite/coincsuite.py\", line 169, in Complete\n    mininame = lilliput.add_minuit_simplex_minimizer_service(tray)\nNameError: global name 'lilliput' is not defined\n\n}}}\n\n* The RunParameters class is not being used anywhere in the script.\n* The script tries to read /CoincSuite/resources/data/example_scenario.i3.bz2.  Directory and file do not exist.\n* Please add detailed comments to the code and a better summary at the top as to what the script does exactly.\n\n ", 
    "reporter": "jtatar", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1550067117911749", 
    "component": "combo reconstruction", 
    "summary": "CoincSuite application.py example doesn't run", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2015-08-18T17:42:53", 
    "milestone": "", 
    "owner": "mzoll", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20150821T09:32:51: 
* mzoll commented:

> forgotten import, would have been easy to fix


* mzoll changed resolution from "" to "fixed"
* mzoll changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:11:57: 
* olivas changed milestone from "IceRec V5" to ""
* olivas commented:

> Milestone IceRec V5 deleted
