### ISSUE TITLE
CoincSuite split_recombine.py example doesn't run (Trac #1162)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1156]
Here is the error message:

```text
INFO (Python): Using CoincSuite Recombinations (coincsuite.py:82 in Complete)
Traceback (most recent call last):
  File "split_recombine.py", line 77, in <module>
    Split_Recombine( tray, "Split_Recombine", params)
  File "split_recombine.py", line 58, in Split_Recombine
    SplitPulses = "MaskedOfflinePulses")
  File "/home/jtatar/StrikeTeam/IceRec/build/lib/I3Tray.py", line 204, in AddSegment
    return _segment(self, _name, **kwargs)
  File "/home/jtatar/StrikeTeam/IceRec/build/lib/icecube/CoincSuite/coincsuite.py", line 169, in Complete
    mininame = lilliput.add_minuit_simplex_minimizer_service(tray)
NameError: global name 'lilliput' is not defined

```

* Default input file does not exist.
* Please add a better summary of what script does at top of script.

Migrated from https://code.icecube.wisc.edu/ticket/1162
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:11:57", 
    "description": "Here is the error message:\n\n\n{{{\nINFO (Python): Using CoincSuite Recombinations (coincsuite.py:82 in Complete)\nTraceback (most recent call last):\n  File \"split_recombine.py\", line 77, in <module>\n    Split_Recombine( tray, \"Split_Recombine\", params)\n  File \"split_recombine.py\", line 58, in Split_Recombine\n    SplitPulses = \"MaskedOfflinePulses\")\n  File \"/home/jtatar/StrikeTeam/IceRec/build/lib/I3Tray.py\", line 204, in AddSegment\n    return _segment(self, _name, **kwargs)\n  File \"/home/jtatar/StrikeTeam/IceRec/build/lib/icecube/CoincSuite/coincsuite.py\", line 169, in Complete\n    mininame = lilliput.add_minuit_simplex_minimizer_service(tray)\nNameError: global name 'lilliput' is not defined\n\n}}}\n\n* Default input file does not exist.\n* Please add a better summary of what script does at top of script.", 
    "reporter": "jtatar", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1550067117911749", 
    "component": "combo reconstruction", 
    "summary": "CoincSuite split_recombine.py example doesn't run", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2015-08-18T18:26:13", 
    "milestone": "", 
    "owner": "mzoll", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160220T02:26:31: 
* mzoll changed resolution from "" to "fixed"
* mzoll commented:

> fixed with 142181


* mzoll changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:11:57: 
* olivas changed milestone from "IceRec V5" to ""
* olivas commented:

> Milestone IceRec V5 deleted
