### ISSUE TITLE
[VHESelfVeto] example is broken,  other details (Trac #1164)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1158]
I.- resources/:

1.- examples/analysis.py:
 
1.1.- if a number of frames is given (tray.Execute(100)), the result is:

NOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:519 in void I3Tray::Execute(unsigned int))
0 events total
0 events passed the veto
0 events were vetoed
0 events could not find a vertex

is this expected(0 events)?, if so, please write down some notes.

1.2.- Without giving the number of frames, it works well:

NOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:481 in void I3Tray::Execute())
WARN (I3TableWriter): 1 SubEventStreams ['ice_top',] were seen but not booked because they were not passed as part of the 'SubEventStreams' parameter of I3TableWriter (which was configured as ['in_ice',]). To book events from these streams, add them to the 'SubEventStreams' parameter of I3TableWriter. (I3TableWriter.cxx:450 in void I3TableWriter::Finish())
149 events total
0 events passed the veto
44 events were vetoed
105 events could not find a vertex
                              qtot_total: 126467 calls to physics     15.26s user      0.22s system

2.- examples/runveto.py, shows a FATAL

Loading VHESelfVeto.......................................ok
FATAL (icetray): Attempt to set parameter BoundaryWidth that doesn't exist (I3ConfigurationImpl.cxx:65 in void I3ConfigurationImpl::Set(const std::string&, const boost::python::api::object&))
Traceback (most recent call last):
  File "resources/examples/runveto.py", line 16, in <module>
    tray.AddModule('VHESelfVeto', 'selfveto', TimeWindow=5000, VertexThreshold=100, BoundaryWidth=50,VetoThreshold=20, Pulses=pulses)
  File "/scratch/gmaggi/icerectrunk/build/lib/I3Tray.py", line 140, in AddModule
    super(I3Tray, self).SetParameter(_name, k, v)
RuntimeError: Attempt to set parameter BoundaryWidth that doesn't exist (in void I3ConfigurationImpl::Set(const std::string&, const boost::python::api::object&))

Both examples were Ran like:
python $I3_SRC/VHESelfVeto/resources/examples/file.py here.i3 /data/exp/IceCube/2011/filtered/level2/0630/Level2_IC86.2011_data_Run00118390_0630_GCD.i3.gz /data/exp/IceCube/2011/filtered/level2/0630/Level2_IC86.2011_data_Run00118390_Part00000000.i3.bz2 

3.- examples/test is missing according : http://software.icecube.wisc.edu/icerec_trunk/code_reviews.html , it would allow the user to run the module without passing arguments by command line.

4.- examples/index.dox is missing. Include information please in: http://software.icecube.wisc.edu/icerec_trunk/metaproject/index.html 

Migrated from https://code.icecube.wisc.edu/ticket/1164
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:11:57", 
    "description": "I.- resources/:\n\n1.- examples/analysis.py:\n \n1.1.- if a number of frames is given (tray.Execute(100)), the result is:\n\nNOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:519 in void I3Tray::Execute(unsigned int))\n0 events total\n0 events passed the veto\n0 events were vetoed\n0 events could not find a vertex\n\nis this expected(0 events)?, if so, please write down some notes.\n\n1.2.- Without giving the number of frames, it works well:\n\nNOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:481 in void I3Tray::Execute())\nWARN (I3TableWriter): 1 SubEventStreams ['ice_top',] were seen but not booked because they were not passed as part of the 'SubEventStreams' parameter of I3TableWriter (which was configured as ['in_ice',]). To book events from these streams, add them to the 'SubEventStreams' parameter of I3TableWriter. (I3TableWriter.cxx:450 in void I3TableWriter::Finish())\n149 events total\n0 events passed the veto\n44 events were vetoed\n105 events could not find a vertex\n                              qtot_total: 126467 calls to physics     15.26s user      0.22s system\n\n2.- examples/runveto.py, shows a FATAL\n\nLoading VHESelfVeto.......................................ok\nFATAL (icetray): Attempt to set parameter BoundaryWidth that doesn't exist (I3ConfigurationImpl.cxx:65 in void I3ConfigurationImpl::Set(const std::string&, const boost::python::api::object&))\nTraceback (most recent call last):\n  File \"resources/examples/runveto.py\", line 16, in <module>\n    tray.AddModule('VHESelfVeto', 'selfveto', TimeWindow=5000, VertexThreshold=100, BoundaryWidth=50,VetoThreshold=20, Pulses=pulses)\n  File \"/scratch/gmaggi/icerectrunk/build/lib/I3Tray.py\", line 140, in AddModule\n    super(I3Tray, self).SetParameter(_name, k, v)\nRuntimeError: Attempt to set parameter BoundaryWidth that doesn't exist (in void I3ConfigurationImpl::Set(const std::string&, const boost::python::api::object&))\n\nBoth examples were Ran like:\npython $I3_SRC/VHESelfVeto/resources/examples/file.py here.i3 /data/exp/IceCube/2011/filtered/level2/0630/Level2_IC86.2011_data_Run00118390_0630_GCD.i3.gz /data/exp/IceCube/2011/filtered/level2/0630/Level2_IC86.2011_data_Run00118390_Part00000000.i3.bz2 \n\n3.- examples/test is missing according : http://software.icecube.wisc.edu/icerec_trunk/code_reviews.html , it would allow the user to run the module without passing arguments by command line.\n\n4.- examples/index.dox is missing. Include information please in: http://software.icecube.wisc.edu/icerec_trunk/metaproject/index.html ", 
    "reporter": "gmaggi", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1550067117911749", 
    "component": "combo reconstruction", 
    "summary": "[VHESelfVeto] example is broken,  other details", 
    "priority": "critical", 
    "keywords": "veto VHE HomogenizedQTot", 
    "time": "2015-08-18T18:39:48", 
    "milestone": "", 
    "owner": "claudio.kopper", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20150820T18:31:36: 
* gmaggi changed status from "new" to "assigned"
* gmaggi changed owner from "claudio.kopper@icecube.wisc.edu" to "ckopper"

**Comment by icecube-trac** [comment]
Trac update at 20150820T19:02:07: gmaggi changed owner from "ckopper" to "claudio.kopper"

**Comment by icecube-trac** [comment]
Trac update at 20160314T21:35:23: claudio.kopper changed priority from "blocker" to "critical"

**Comment by icecube-trac** [comment]
Trac update at 20160406T22:50:35: 
* claudio.kopper changed status from "assigned" to "closed"
* claudio.kopper commented:

> the output of "0 events" when using this with tray.Execute(100) is expected - events passing the veto are rare, so there are none in the first 100 frames. So this WORKSFORME.
> 
> The issue with runveto.py is fixed in r144347
> 
> 


* claudio.kopper changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:11:57: 
* olivas commented:

> Milestone IceRec V5 deleted


* olivas changed milestone from "IceRec V5" to ""
