### ISSUE TITLE
neutrino-generator example scripts not working (Trac #1174)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1168]
1.  NuGGenie.py

Script doesn't run.  It may be as simple of a fix as having NuFlavors --> NuFlavor and assigning NuFlavor a string rather than a list.  Please check.

2.  NuGenPropagate.py

This is the error I get when I try to run the script on a CORSIKA file:

```text
 (EarthModelService.cxx:161 in void earthmodel::EarthModelService::Init())
Traceback (most recent call last):
  File "NuGenPropagate.py", line 95, in <module>
    injectionmode)
Boost.Python.ArgumentError: Python argument types in
    Steering.__init__(Steering, EarthModelService, SimMode, VTXGenMode, str)
did not match C++ signature:
    __init__(boost::python::api::object)
    __init__(_object*, I3Context)
    __init__(_object*, boost::shared_ptr<earthmodel::EarthModelService>)
    __init__(_object*, boost::shared_ptr<earthmodel::EarthModelService>, nugen::SimMode, nugen::VTXGenMode, nugen::InjectionMode)

```

3.  NuGenProp2.py

See error below.  Please provide an input file that does not have I3MCWeightDict already.  Otherwise make script take a file as an input and throw an error if input file is not provided as argument.

```text
INFO (I3NuG): initial_primary is not interacted, fill final interaction with probability (I3NuGWeightedEvent.cxx:129 in virtual bool I3NuGWeightedEvent::MakeNeutrinoPropagation(nugen::ParticlePtr, bool))
FATAL (I3PropagatorModule): Frame already contains a key 'I3MCWeightDict' (I3PropagatorModule.cxx:270 in virtual void I3PropagatorModule::DAQ(I3FramePtr))
ERROR (I3Module): I3PropagatorModule_0000: Exception thrown (I3Module.cxx:114 in void I3Module::Do(void (I3Module::*)()))
Traceback (most recent call last):
  File "NuGenProp2.py", line 220, in <module>
    tray.Execute()
  File "/home/jtatar/StrikeTeam/IceSim/build/lib/I3Tray.py", line 234, in Execute
    super(I3Tray, self).Execute()
RuntimeError: Frame already contains a key 'I3MCWeightDict' (in virtual void I3PropagatorModule::DAQ(I3FramePtr))

```

4.  ApplyPropWeight.py

The following wget of file fails.  Please update the link.  Once the required propagation_weights.tgz file is received, please test the example script to ensure that it runs.

wget http://www.icecube.wisc.edu/~hoshina/propagation_weights.tgz

Migrated from https://code.icecube.wisc.edu/ticket/1174
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:11:45", 
    "description": "1.  NuGGenie.py\n\nScript doesn't run.  It may be as simple of a fix as having NuFlavors --> NuFlavor and assigning NuFlavor a string rather than a list.  Please check.\n\n\n2.  NuGenPropagate.py\n\nThis is the error I get when I try to run the script on a CORSIKA file:\n\n{{{\n (EarthModelService.cxx:161 in void earthmodel::EarthModelService::Init())\nTraceback (most recent call last):\n  File \"NuGenPropagate.py\", line 95, in <module>\n    injectionmode)\nBoost.Python.ArgumentError: Python argument types in\n    Steering.__init__(Steering, EarthModelService, SimMode, VTXGenMode, str)\ndid not match C++ signature:\n    __init__(boost::python::api::object)\n    __init__(_object*, I3Context)\n    __init__(_object*, boost::shared_ptr<earthmodel::EarthModelService>)\n    __init__(_object*, boost::shared_ptr<earthmodel::EarthModelService>, nugen::SimMode, nugen::VTXGenMode, nugen::InjectionMode)\n\n}}}\n\n\n3.  NuGenProp2.py\n\nSee error below.  Please provide an input file that does not have I3MCWeightDict already.  Otherwise make script take a file as an input and throw an error if input file is not provided as argument.\n\n{{{\nINFO (I3NuG): initial_primary is not interacted, fill final interaction with probability (I3NuGWeightedEvent.cxx:129 in virtual bool I3NuGWeightedEvent::MakeNeutrinoPropagation(nugen::ParticlePtr, bool))\nFATAL (I3PropagatorModule): Frame already contains a key 'I3MCWeightDict' (I3PropagatorModule.cxx:270 in virtual void I3PropagatorModule::DAQ(I3FramePtr))\nERROR (I3Module): I3PropagatorModule_0000: Exception thrown (I3Module.cxx:114 in void I3Module::Do(void (I3Module::*)()))\nTraceback (most recent call last):\n  File \"NuGenProp2.py\", line 220, in <module>\n    tray.Execute()\n  File \"/home/jtatar/StrikeTeam/IceSim/build/lib/I3Tray.py\", line 234, in Execute\n    super(I3Tray, self).Execute()\nRuntimeError: Frame already contains a key 'I3MCWeightDict' (in virtual void I3PropagatorModule::DAQ(I3FramePtr))\n\n}}}\n\n\n4.  ApplyPropWeight.py\n\nThe following wget of file fails.  Please update the link.  Once the required propagation_weights.tgz file is received, please test the example script to ensure that it runs.\n\nwget http://www.icecube.wisc.edu/~hoshina/propagation_weights.tgz", 
    "reporter": "jtatar", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1550067105393059", 
    "component": "combo simulation", 
    "summary": "neutrino-generator example scripts not working", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2015-08-18T22:50:20", 
    "milestone": "", 
    "owner": "hoshina", 
    "type": "cleanup"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20150922T01:40:00: olivas changed milestone from "IceSim 4.2" to "IceSim 5.0"

**Comment by icecube-trac** [comment]
Trac update at 20150929T00:07:57: 
* hoshina changed type from "defect" to "cleanup"
* hoshina changed status from "new" to "closed"
* hoshina changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:11:45: 
* olivas commented:

> Milestone IceSim 5.0 deleted


* olivas changed milestone from "IceSim 5.0" to ""
