### ISSUE TITLE
[coinc-twc] example scrip does not work + missing documentation (Trac #1234)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1228]
1) example testCoincTWC.py does *not* work. 

Loading libflat-ntuple....................................FATAL (I3Tray): Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /home/tpalczewski/code-sprint/IceRec-V5/build/lib/libflat-ntuple.so: cannot open shared object file: No such file or directory (I3Tray.py:36 in load)
Traceback (most recent call last):
  File "testCoincTWC.py", line 15, in <module>
    load("libflat-ntuple")
  File "/home/tpalczewski/code-sprint/IceRec-V5/build/lib/I3Tray.py", line 36, in load
    % (sys.exc_info()[0], sys.exc_info()[1]), "I3Tray")
  File "/home/tpalczewski/code-sprint/IceRec-V5/build/lib/icecube/icetray/i3logging.py", line 150, in log_fatal
    raise RuntimeError(message + " (in " + tb[2] + ")")
RuntimeError: Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /home/tpalczewski/code-sprint/IceRec-V5/build/lib/libflat-ntuple.so: cannot open shared object file: No such file or directory (in load)

script tries to use the deprecated libflat-ntuple library. 

In addition tests should be placed in the resources/test directory. 

2) BTW the resources/scripts directory is empty. 

3) Please convert RELEASE_NOTES to .rst format. 

Migrated from https://code.icecube.wisc.edu/ticket/1234
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:11:57", 
    "description": "1) example testCoincTWC.py does *not* work. \n\nLoading libflat-ntuple....................................FATAL (I3Tray): Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /home/tpalczewski/code-sprint/IceRec-V5/build/lib/libflat-ntuple.so: cannot open shared object file: No such file or directory (I3Tray.py:36 in load)\nTraceback (most recent call last):\n  File \"testCoincTWC.py\", line 15, in <module>\n    load(\"libflat-ntuple\")\n  File \"/home/tpalczewski/code-sprint/IceRec-V5/build/lib/I3Tray.py\", line 36, in load\n    % (sys.exc_info()[0], sys.exc_info()[1]), \"I3Tray\")\n  File \"/home/tpalczewski/code-sprint/IceRec-V5/build/lib/icecube/icetray/i3logging.py\", line 150, in log_fatal\n    raise RuntimeError(message + \" (in \" + tb[2] + \")\")\nRuntimeError: Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /home/tpalczewski/code-sprint/IceRec-V5/build/lib/libflat-ntuple.so: cannot open shared object file: No such file or directory (in load)\n\nscript tries to use the deprecated libflat-ntuple library. \n\nIn addition tests should be placed in the resources/test directory. \n\n2) BTW the resources/scripts directory is empty. \n\n3) Please convert RELEASE_NOTES to .rst format. \n", 
    "reporter": "tpalczewski", 
    "cc": "Sam.DeRidder@UGent.be", 
    "resolution": "fixed", 
    "_ts": "1550067117911749", 
    "component": "combo reconstruction", 
    "summary": "[coinc-twc] example scrip does not work + missing documentation", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2015-08-20T06:51:30", 
    "milestone": "", 
    "owner": "sderidder", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20151123T21:22:35: 
* sderidder changed cc from "" to "Sam.DeRidder@UGent.be"
* sderidder commented:

> All these remarks are included now. This was mainly finally making these scripts up to date with the new software.


* sderidder changed resolution from "" to "fixed"
* sderidder changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:11:57: 
* olivas changed milestone from "IceRec V5" to ""
* olivas commented:

> Milestone IceRec V5 deleted
