### ISSUE TITLE
CommonVaribales is not executable in IC2012-L2_V13-01-00_IceSim4compat_V3 (Trac #1331)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1323]
the execution of the CommonVariables project, shipped with IC2012-L2_V13-01-00_IceSim4compat_V3

which is 
http://code.icecube.wisc.edu/svn/projects/CommonVariables/releases/V00-01-00

fails because somebody checked in the project files of this revision with a locale that uses non standard ascii encoded characters.

http://code.icecube.wisc.edu/projects/icecube/browser/IceCube/projects/CommonVariables/releases/V00-01-00/python/track_characteristics/__init__.py#L8

the svn attributes svn::version and svn::revision will be in the checkout filled with the stored and frozen values for this release, which is

# Version: $Revision$                                                                                                                       
# Date:    $Date: 2012-09-24 14:28:05 -0500 (mån, 24 sep 2012) $

The 'å' character in the date-tag will make this code fail as no encoding has specified at the head of the file.

SOLUTION:
------------
Incremental release with a non-swedish locale and check in these files again!

== SVN INfo ===

/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3 $ svn info src/CommonVariables/
Path: src/CommonVariables
Working Copy Root Path: /mnt/lfs3/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/src/CommonVariables
URL: http://code.icecube.wisc.edu/svn/projects/CommonVariables/releases/V00-01-00
Repository Root: http://code.icecube.wisc.edu/svn
Repository UUID: 16731396-06f5-0310-8873-f7f720988828
Revision: 137310
Node Kind: directory
Schedule: normal
Last Changed Author: jacobi
Last Changed Rev: 93524
Last Changed Date: 2012-09-26 04:18:58 -0500 (ons, 26 sep 2012)

== Error ==

Traceback (most recent call last):
  File "/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/src/WIMPprod/python/drivers/WIMP_SMT1_stdL2_complete.py", line 186, in <module>
    from icecube.filter_2012 import process as L2
  File "/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/build/lib/icecube/filter_2012/process.py", line 25, in <module>
    from icecube.filter_2012.level2_Reconstruction_Muon import OfflineMuonReco
  File "/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/build/lib/icecube/filter_2012/level2_Reconstruction_Muon.py", line 120, in <module>
    from icecube.common_variables import hit_multiplicity, hit_statistics, track_characteristics, direct_hits
  File "/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/build/lib/icecube/common_variables/__init__.py", line 36, in <module>
    from . import track_characteristics
  File "/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/build/lib/icecube/common_variables/track_characteristics/__init__.py", line 60, in <module>
    from .segments import I3TrackCharacteristicsCalculatorSegment
  File "/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/build/lib/icecube/common_variables/track_characteristics/segments.py", line 8
SyntaxError: Non-ASCII character '\xc3' in file /data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/build/lib/icecube/common_variables/track_characteristics/segments.py on line 8, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

Migrated from https://code.icecube.wisc.edu/ticket/1331
```json
{
    "status": "closed", 
    "changetime": "2015-09-08T09:51:29", 
    "description": "the execution of the CommonVariables project, shipped with IC2012-L2_V13-01-00_IceSim4compat_V3\n\nwhich is \nhttp://code.icecube.wisc.edu/svn/projects/CommonVariables/releases/V00-01-00\n\nfails because somebody checked in the project files of this revision with a locale that uses non standard ascii encoded characters.\n\nhttp://code.icecube.wisc.edu/projects/icecube/browser/IceCube/projects/CommonVariables/releases/V00-01-00/python/track_characteristics/__init__.py#L8\n\nthe svn attributes svn::version and svn::revision will be in the checkout filled with the stored and frozen values for this release, which is\n\n# Version: $Revision$                                                                                                                       \n# Date:    $Date: 2012-09-24 14:28:05 -0500 (m\u00e5n, 24 sep 2012) $\n\nThe '\u00e5' character in the date-tag will make this code fail as no encoding has specified at the head of the file.\n\n\nSOLUTION:\n------------\nIncremental release with a non-swedish locale and check in these files again!\n\n== SVN INfo ===\n\n/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3 $ svn info src/CommonVariables/\nPath: src/CommonVariables\nWorking Copy Root Path: /mnt/lfs3/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/src/CommonVariables\nURL: http://code.icecube.wisc.edu/svn/projects/CommonVariables/releases/V00-01-00\nRepository Root: http://code.icecube.wisc.edu/svn\nRepository UUID: 16731396-06f5-0310-8873-f7f720988828\nRevision: 137310\nNode Kind: directory\nSchedule: normal\nLast Changed Author: jacobi\nLast Changed Rev: 93524\nLast Changed Date: 2012-09-26 04:18:58 -0500 (ons, 26 sep 2012)\n\n== Error ==\n\nTraceback (most recent call last):\n  File \"/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/src/WIMPprod/python/drivers/WIMP_SMT1_stdL2_complete.py\", line 186, in <module>\n    from icecube.filter_2012 import process as L2\n  File \"/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/build/lib/icecube/filter_2012/process.py\", line 25, in <module>\n    from icecube.filter_2012.level2_Reconstruction_Muon import OfflineMuonReco\n  File \"/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/build/lib/icecube/filter_2012/level2_Reconstruction_Muon.py\", line 120, in <module>\n    from icecube.common_variables import hit_multiplicity, hit_statistics, track_characteristics, direct_hits\n  File \"/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/build/lib/icecube/common_variables/__init__.py\", line 36, in <module>\n    from . import track_characteristics\n  File \"/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/build/lib/icecube/common_variables/track_characteristics/__init__.py\", line 60, in <module>\n    from .segments import I3TrackCharacteristicsCalculatorSegment\n  File \"/data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/build/lib/icecube/common_variables/track_characteristics/segments.py\", line 8\nSyntaxError: Non-ASCII character '\\xc3' in file /data/user/mzoll/i3/meta-projects/icerec/IC2012-L2_V13-01-00_IceSim4compat_V3/build/lib/icecube/common_variables/track_characteristics/segments.py on line 8, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details\n\n", 
    "reporter": "mzoll", 
    "cc": "martin.wolf@fysik.su.se, emanuel.jacobi@icecube.wisc.edu", 
    "resolution": "invalid", 
    "_ts": "1441705889206343", 
    "component": "combo reconstruction", 
    "summary": "CommonVaribales is not executable in IC2012-L2_V13-01-00_IceSim4compat_V3", 
    "priority": "major", 
    "keywords": "CommonVariables", 
    "time": "2015-09-08T09:00:43", 
    "milestone": "", 
    "owner": "dschulz", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20150908T09:43:25: 
* mzoll changed resolution from "" to "invalid"
* mzoll changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20150908T09:51:29: mzoll commented:

> it came out that this was a user side setting that was messed up with the locale, which was forwarded from the local machine to the server-client.
> 
> stopping this forwarding should fix the problem.
> 
> read here https://askubuntu.com/questions/144235/locale-variables-have-no-effect-in-remote-shell-perl-warning-setting-locale-f/144448https://code.icecube.wisc.edu/ticket/144448
> 
>
