### ISSUE TITLE
segfault when starting steamshovel (Trac #1378)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1370]
A strange problem:
If I start the environment with ./env-shell.sh, then run steamshovel, it segfaults right at the beginning. With "./env-shell.sh steamshovel file.i3" it starts up fine.
System: Ubuntu 15.04
icerec version: trunk, Revision: 138186

backtrace:

(gdb) run selfveto-results.i3
Starting program: /home/berghaus/events/steamshovel selfveto-results.i3
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
ERROR (steamshovel): Problem loading icecube python bindings:
ImportError: No module named icecube.dataio
Are there unbuilt pybindings? (embed.cpp:64 in scripting::PyInterpreter::PyInterpreter(char*))
terminate called after throwing an instance of 'boost::python::error_already_set'

Program received signal SIGABRT, Aborted.
0x00007fffeaefd267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
https://code.icecube.wisc.edu/ticket/0  0x00007fffeaefd267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007fffeaefeeca in __GI_abort () at abort.c:89
#2  0x00007ffff792706d in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7924ee6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7924f31 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7925199 in __cxa_rethrow () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00000000004e23a2 in scripting::PyInterpreter::PyInterpreter(char*) ()
#7  0x0000000000473fbd in main ()

Migrated from https://code.icecube.wisc.edu/ticket/1378
```json
{
    "status": "closed", 
    "changetime": "2015-10-05T15:28:27", 
    "description": "A strange problem:\nIf I start the environment with ./env-shell.sh, then run steamshovel, it segfaults right at the beginning. With \"./env-shell.sh steamshovel file.i3\" it starts up fine.\nSystem: Ubuntu 15.04\nicerec version: trunk, Revision: 138186\n\nbacktrace:\n\n(gdb) run selfveto-results.i3\nStarting program: /home/berghaus/events/steamshovel selfveto-results.i3\n[Thread debugging using libthread_db enabled]\nUsing host libthread_db library \"/lib/x86_64-linux-gnu/libthread_db.so.1\".\nERROR (steamshovel): Problem loading icecube python bindings:\nImportError: No module named icecube.dataio\nAre there unbuilt pybindings? (embed.cpp:64 in scripting::PyInterpreter::PyInterpreter(char*))\nterminate called after throwing an instance of 'boost::python::error_already_set'\n\nProgram received signal SIGABRT, Aborted.\n0x00007fffeaefd267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55\n55\t../sysdeps/unix/sysv/linux/raise.c: No such file or directory.\n(gdb) bt\n#0  0x00007fffeaefd267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55\n#1  0x00007fffeaefeeca in __GI_abort () at abort.c:89\n#2  0x00007ffff792706d in __gnu_cxx::__verbose_terminate_handler() ()\n   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6\n#3  0x00007ffff7924ee6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6\n#4  0x00007ffff7924f31 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6\n#5  0x00007ffff7925199 in __cxa_rethrow () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6\n#6  0x00000000004e23a2 in scripting::PyInterpreter::PyInterpreter(char*) ()\n#7  0x0000000000473fbd in main ()\n", 
    "reporter": "berghaus", 
    "cc": "", 
    "resolution": "invalid", 
    "_ts": "1444058907340211", 
    "component": "combo core", 
    "summary": "segfault when starting steamshovel", 
    "priority": "normal", 
    "keywords": "steamshovel", 
    "time": "2015-10-05T07:29:14", 
    "milestone": "", 
    "owner": "hdembinski", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20151005T07:31:14: 
* berghaus changed keywords from "" to "steamshovel"
* berghaus changed component from "cmake" to "icerec"

**Comment by icecube-trac** [comment]
Trac update at 20151005T14:47:35: 
* hdembinski changed owner from "" to "hdembinski"
* hdembinski changed status from "new" to "assigned"

**Comment by icecube-trac** [comment]
Trac update at 20151005T15:19:17: 
* david.schultz changed component from "icerec" to "icecube offline"
* david.schultz commented:

> The `dataio` import error indicates an environment issue, or maybe something not quite right with env-shell.sh

**Comment by icecube-trac** [comment]
Trac update at 20151005T15:21:40: hdembinski commented:

> Javier suggested that this is a problem with .bashrc and .bash_profile. In one of the two you are probably overriding PYTHONPATH or LD_LIBRARY_PATH. Please check these scripts and try again.

**Comment by icecube-trac** [comment]
Trac update at 20151005T15:26:58: berghaus commented:

> Yes, that solved it. I had set PYTHONPATH to some place where it had no business pointing to. Sorry about that!

**Comment by icecube-trac** [comment]
Trac update at 20151005T15:28:27: 
* david.schultz changed status from "assigned" to "closed"
* david.schultz changed resolution from "" to "invalid"
