### ISSUE TITLE
steamshovel recopulsewaveform (Trac #1380)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1372]
And another strange problem:
For older files (IC86-I and earlier), the calibrated waveform plotter gives an error apparently related to the calibration frame (even though it's in there and can be accessed by python scripts). For newer files (tested IC86-III) it works ok.

ERROR (Artist): Python exception in PyArtist::create
Traceback (most recent call last):
  File "/home/berghaus/icerec/build/lib/icecube/steamshovel/artists/mplart/AbstractMPLArtist.py", line 83, in create
    self.create_plot( frame, fig )
  File "/home/berghaus/icerec/build/lib/icecube/steamshovel/artists/RecoPulseWaveform.py", line 33, in create_plot
    calib = frame['I3Calibration']
KeyError: I3Calibration (PyArtist.cpp:154 in virtual void scripting::shovelart::PyArtist::create(I3FramePtr, SceneGroup*, const SceneState&))

Migrated from https://code.icecube.wisc.edu/ticket/1380
```json
{
    "status": "closed", 
    "changetime": "2015-10-06T16:08:56", 
    "description": "And another strange problem:\nFor older files (IC86-I and earlier), the calibrated waveform plotter gives an error apparently related to the calibration frame (even though it's in there and can be accessed by python scripts). For newer files (tested IC86-III) it works ok.\n\nERROR (Artist): Python exception in PyArtist::create\nTraceback (most recent call last):\n  File \"/home/berghaus/icerec/build/lib/icecube/steamshovel/artists/mplart/AbstractMPLArtist.py\", line 83, in create\n    self.create_plot( frame, fig )\n  File \"/home/berghaus/icerec/build/lib/icecube/steamshovel/artists/RecoPulseWaveform.py\", line 33, in create_plot\n    calib = frame['I3Calibration']\nKeyError: I3Calibration (PyArtist.cpp:154 in virtual void scripting::shovelart::PyArtist::create(I3FramePtr, SceneGroup*, const SceneState&))\n", 
    "reporter": "berghaus", 
    "cc": "", 
    "resolution": "worksforme", 
    "_ts": "1444147736633303", 
    "component": "combo reconstruction", 
    "summary": "steamshovel recopulsewaveform", 
    "priority": "normal", 
    "keywords": "steamshovel", 
    "time": "2015-10-05T08:25:32", 
    "milestone": "", 
    "owner": "hdembinski", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20151005T14:49:37: 
* hdembinski changed owner from "" to "hdembinski"
* hdembinski changed status from "new" to "assigned"
* hdembinski commented:

> Hi Patrick, could you please provide a path with test file?

**Comment by icecube-trac** [comment]
Trac update at 20151005T14:57:40: berghaus commented:

> Here is one:
> 
> /data/user/berghaus/icerec_04-04-00/proc/pev86.i3.gz
>

**Comment by icecube-trac** [comment]
Trac update at 20151005T15:43:11: hdembinski changed status from "assigned" to "accepted"

**Comment by icecube-trac** [comment]
Trac update at 20151005T16:19:39: hdembinski commented:

> This might be debris from an earlier change that was fixed. Please try this:
> 
> 1) Click Menu "Window", then "Configuration". Remove anything in the line under "Performance". I guess that "I3Calibration" is listed there.
> 2) Restart steamshovel and try again.
> 
> I used to put I3Calibration into the Performance field by default, because it makes browsing faster, and because I thought that no artist was using it, but some artists do. So that default was changed to ignore nothing. I suppose you used that version with the wrong default at some point and then it was stored into your user configuration.

**Comment by icecube-trac** [comment]
Trac update at 20151006T16:08:56: 
* hdembinski changed status from "accepted" to "closed"
* hdembinski changed resolution from "" to "worksforme"
