### ISSUE TITLE
steamshovel crash reproducibility (Trac #1392)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1384]
It seems there is a simple way to provoke the steamshovel crash:

- Add Bubbles (not ChargeBubbles)
- Pick pulses (e.g. OfflineIceTopVEMPulses)
- Remove bubbles
- Program received signal SIGSEGV, Segmentation fault.

(gdb) bt
https://code.icecube.wisc.edu/ticket/0  0x00007ffff3884241 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#1  0x00007ffff53be552 in boost::python::converter::shared_ptr_deleter::operator()(void const*) ()
   from /home/berghaus/i3/ports/lib/boost-1.38.0/libboost_python-mt.so
#2  0x00007ffff1258842 in SphereObject::~SphereObject() ()
   from /home/berghaus/icerec/build/lib/libshovelart.so
#3  0x00007ffff1261456 in SceneGroup::~SceneGroup() ()
   from /home/berghaus/icerec/build/lib/libshovelart.so
#4  0x00007ffff1261509 in SceneGroup::~SceneGroup() ()
   from /home/berghaus/icerec/build/lib/libshovelart.so
#5  0x00000000004bbbb2 in std::_Rb_tree<boost::shared_ptr<SceneGroup>, boost::shared_ptr<SceneGroup>, std::_Identity<boost::shared_ptr<SceneGroup> >, std::less<boost::shared_ptr<SceneGroup> >, std::allocator<boost::shared_ptr<SceneGroup> > >::_M_erase(std::_Rb_tree_node<boost::shared_ptr<SceneGroup> >*) ()
#6  0x00007ffff1262b39 in Scene::dropOutputs(boost::shared_ptr<Artist>) ()
   from /home/berghaus/icerec/build/lib/libshovelart.so
#7  0x00007ffff1263709 in Scene::dropSource(boost::shared_ptr<Artist>) ()
   from /home/berghaus/icerec/build/lib/libshovelart.so
#8  0x00007ffff126ad04 in Scenario::remove(boost::shared_ptr<Artist>) ()
   from /home/berghaus/icerec/build/lib/libshovelart.so
#9  0x00000000004c5692 in ScenarioWidget::removeSelection() ()

Migrated from https://code.icecube.wisc.edu/ticket/1392
```json
{
    "status": "closed", 
    "changetime": "2015-10-14T15:47:25", 
    "description": "It seems there is a simple way to provoke the steamshovel crash:\n\n- Add Bubbles (not ChargeBubbles)\n- Pick pulses (e.g. OfflineIceTopVEMPulses)\n- Remove bubbles\n- Program received signal SIGSEGV, Segmentation fault.\n\n(gdb) bt\n#0  0x00007ffff3884241 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#1  0x00007ffff53be552 in boost::python::converter::shared_ptr_deleter::operator()(void const*) ()\n   from /home/berghaus/i3/ports/lib/boost-1.38.0/libboost_python-mt.so\n#2  0x00007ffff1258842 in SphereObject::~SphereObject() ()\n   from /home/berghaus/icerec/build/lib/libshovelart.so\n#3  0x00007ffff1261456 in SceneGroup::~SceneGroup() ()\n   from /home/berghaus/icerec/build/lib/libshovelart.so\n#4  0x00007ffff1261509 in SceneGroup::~SceneGroup() ()\n   from /home/berghaus/icerec/build/lib/libshovelart.so\n#5  0x00000000004bbbb2 in std::_Rb_tree<boost::shared_ptr<SceneGroup>, boost::shared_ptr<SceneGroup>, std::_Identity<boost::shared_ptr<SceneGroup> >, std::less<boost::shared_ptr<SceneGroup> >, std::allocator<boost::shared_ptr<SceneGroup> > >::_M_erase(std::_Rb_tree_node<boost::shared_ptr<SceneGroup> >*) ()\n#6  0x00007ffff1262b39 in Scene::dropOutputs(boost::shared_ptr<Artist>) ()\n   from /home/berghaus/icerec/build/lib/libshovelart.so\n#7  0x00007ffff1263709 in Scene::dropSource(boost::shared_ptr<Artist>) ()\n   from /home/berghaus/icerec/build/lib/libshovelart.so\n#8  0x00007ffff126ad04 in Scenario::remove(boost::shared_ptr<Artist>) ()\n   from /home/berghaus/icerec/build/lib/libshovelart.so\n#9  0x00000000004c5692 in ScenarioWidget::removeSelection() ()\n", 
    "reporter": "berghaus", 
    "cc": "", 
    "resolution": "worksforme", 
    "_ts": "1444837645884416", 
    "component": "combo core", 
    "summary": "steamshovel crash reproducibility", 
    "priority": "minor", 
    "keywords": "steamshovel", 
    "time": "2015-10-09T12:52:41", 
    "milestone": "", 
    "owner": "hdembinski", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20151009T14:50:55: hdembinski commented:

> Please update to the latest trunk again, it should be okay again. That was a mistake introduced recently by me.

**Comment by icecube-trac** [comment]
Trac update at 20151009T15:06:46: berghaus commented:

> I updated this morning:
> 
> [17:02:53 pb] ~/icerec/src $ svn update steamshovel 
> Updating 'steamshovel':
> At revision 138415.
>

**Comment by icecube-trac** [comment]
Trac update at 20151009T16:01:44: hdembinski commented:

> Ok, your version is up to date.
> 
> Still, I cannot reproduce this neither on my computer (Ubuntu 14.04, boost-1.55, Python 2.7.6), nor on cobalt (boost-1.38, Python 2.7.3).

**Comment by icecube-trac** [comment]
Trac update at 20151009T16:03:50: 
* hdembinski changed status from "new" to "accepted"
* hdembinski changed owner from "" to "hdembinski"

**Comment by icecube-trac** [comment]
Trac update at 20151012T06:35:27: berghaus commented:

> This seems to be a very minor problem and specific to my system, so I would say that it should just be ignored (for the time being at least). Thanks for looking into it!

**Comment by icecube-trac** [comment]
Trac update at 20151014T15:47:25: 
* hdembinski changed resolution from "" to "worksforme"
* hdembinski changed status from "accepted" to "closed"
