### ISSUE TITLE
alas, another steamshovel segfault (Trac #1393)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1385]
This time when looking at true MC energy losses:

```text
Program terminated with signal SIGSEGV, Segmentation fault.
https://code.icecube.wisc.edu/ticket/0  0x00007f154e0ee241 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
(gdb) bt
https://code.icecube.wisc.edu/ticket/0  0x00007f154e0ee241 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#1  0x00007f154fc28552 in boost::python::converter::shared_ptr_deleter::operator()(void const*) ()
   from /home/berghaus/i3/ports/lib/boost-1.38.0/libboost_python-mt.so
#2  0x0000000000493efa in void qMetaTypeDeleteHelper<boost::shared_ptr<ColorMap> >(boost::shared_ptr<ColorMap>*) ()
#3  0x00007f154beb83f3 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#4  0x00007f154c985f0d in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#5  0x00007f154c988ad1 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#6  0x00007f154c988bc3 in QStandardItem::~QStandardItem() ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#7  0x00007f154c9889e8 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#8  0x00007f154c988bc3 in QStandardItem::~QStandardItem() ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#9  0x00007f154c988db4 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#10 0x00007f154c989049 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#11 0x00007f154bead597 in QObject::~QObject() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#12 0x00007f154be87105 in QAbstractItemModel::~QAbstractItemModel() ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#13 0x00007f154c985ec9 in QStandardItemModel::~QStandardItemModel() ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#14 0x00007f154beaad18 in QObjectPrivate::deleteChildren() ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#15 0x00007f154c4187f3 in QWidget::~QWidget() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#16 0x0000000000493278 in ColorMapEditor::~ColorMapEditor() ()
#17 0x00007f154beac908 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#18 0x00007f154c4192e3 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#19 0x00007f154c3c59bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#20 0x00007f154c3cc4d8 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#21 0x00000000004adbf8 in SteamshovelApp::notify(QObject*, QEvent*) ()
#22 0x00007f154be931cd in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#23 0x00007f154be96a71 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
---Type <return> to continue, or q <return> to quit--- 
#24 0x00007f154bec26ee in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#25 0x00007f1542677c3d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007f1542677f20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007f1542677fcc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007f154bec285e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#29 0x00007f154c46dc66 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4
#30 0x00007f154be91d21 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#31 0x00007f154be92085 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#32 0x00007f154be97b09 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#33 0x0000000000475900 in main ()
```

Migrated from https://code.icecube.wisc.edu/ticket/1393
```json
{
    "status": "closed", 
    "changetime": "2016-03-18T21:14:09", 
    "description": "This time when looking at true MC energy losses:\n\n{{{\nProgram terminated with signal SIGSEGV, Segmentation fault.\n#0  0x00007f154e0ee241 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n(gdb) bt\n#0  0x00007f154e0ee241 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#1  0x00007f154fc28552 in boost::python::converter::shared_ptr_deleter::operator()(void const*) ()\n   from /home/berghaus/i3/ports/lib/boost-1.38.0/libboost_python-mt.so\n#2  0x0000000000493efa in void qMetaTypeDeleteHelper<boost::shared_ptr<ColorMap> >(boost::shared_ptr<ColorMap>*) ()\n#3  0x00007f154beb83f3 in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n#4  0x00007f154c985f0d in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4\n#5  0x00007f154c988ad1 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4\n#6  0x00007f154c988bc3 in QStandardItem::~QStandardItem() ()\n   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4\n#7  0x00007f154c9889e8 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4\n#8  0x00007f154c988bc3 in QStandardItem::~QStandardItem() ()\n   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4\n#9  0x00007f154c988db4 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4\n#10 0x00007f154c989049 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4\n#11 0x00007f154bead597 in QObject::~QObject() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n#12 0x00007f154be87105 in QAbstractItemModel::~QAbstractItemModel() ()\n   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n#13 0x00007f154c985ec9 in QStandardItemModel::~QStandardItemModel() ()\n   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4\n#14 0x00007f154beaad18 in QObjectPrivate::deleteChildren() ()\n   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n#15 0x00007f154c4187f3 in QWidget::~QWidget() () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4\n#16 0x0000000000493278 in ColorMapEditor::~ColorMapEditor() ()\n#17 0x00007f154beac908 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n#18 0x00007f154c4192e3 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4\n#19 0x00007f154c3c59bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()\n   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4\n#20 0x00007f154c3cc4d8 in QApplication::notify(QObject*, QEvent*) ()\n   from /usr/lib/x86_64-linux-gnu/libQtGui.so.4\n#21 0x00000000004adbf8 in SteamshovelApp::notify(QObject*, QEvent*) ()\n#22 0x00007f154be931cd in QCoreApplication::notifyInternal(QObject*, QEvent*) ()\n   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n#23 0x00007f154be96a71 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()\n   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n---Type <return> to continue, or q <return> to quit--- \n#24 0x00007f154bec26ee in ?? () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n#25 0x00007f1542677c3d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0\n#26 0x00007f1542677f20 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0\n#27 0x00007f1542677fcc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0\n#28 0x00007f154bec285e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n#29 0x00007f154c46dc66 in ?? () from /usr/lib/x86_64-linux-gnu/libQtGui.so.4\n#30 0x00007f154be91d21 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()\n   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n#31 0x00007f154be92085 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()\n   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n#32 0x00007f154be97b09 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n#33 0x0000000000475900 in main ()\n}}}", 
    "reporter": "berghaus", 
    "cc": "", 
    "resolution": "invalid", 
    "_ts": "1458335649133028", 
    "component": "combo core", 
    "summary": "alas, another steamshovel segfault", 
    "priority": "minor", 
    "keywords": "steamshovel", 
    "time": "2015-10-12T08:54:03", 
    "milestone": "", 
    "owner": "hdembinski", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20151012T09:11:10: 
* berghaus commented:

> Addendum: Happens when changing colormap for energy losses, so it can be easily avoided. Priority changed to minor.


* berghaus changed priority from "normal" to "minor"

**Comment by icecube-trac** [comment]
Trac update at 20151029T11:04:35: 
* olivas changed owner from "" to "hdembinski"
* olivas changed status from "new" to "assigned"

**Comment by icecube-trac** [comment]
Trac update at 20151114T18:13:19: hdembinski commented:

> Could you provide a detailed test case, which allows me to reproduce the bug? I don't get random crashes on my machine.

**Comment by icecube-trac** [comment]
Trac update at 20151209T17:12:04: 
* hdembinski changed status from "assigned" to "closed"
* hdembinski commented:

> since no test case was provided, i am tempted to close this bug as invalid.


* hdembinski changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20151209T17:13:06: 
* hdembinski commented:

> whoops, not closed yet!


* hdembinski changed status from "closed" to "reopened"
* hdembinski changed resolution from "fixed" to ""

**Comment by icecube-trac** [comment]
Trac update at 20151209T18:05:29: david.schultz changed milestone from "" to "January 2016"

**Comment by icecube-trac** [comment]
Trac update at 20160127T17:01:09: hdembinski commented:

> January is almost over, any news on this bug?

**Comment by icecube-trac** [comment]
Trac update at 20160127T17:08:08: 
* hdembinski changed resolution from "" to "invalid"
* hdembinski changed status from "reopened" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20160318T21:14:09: 
* olivas commented:

> Milestone January 2016 deleted


* olivas changed milestone from "January 2016" to ""
