### ISSUE TITLE
[WaveCalibrator] munmap_chunk: invalid pointer (Trac #1406)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1398]
With gcc 5.2, boost 1.57:

```text
dschultz@tide2:~/Documents/offline_software/trunk/build/WaveCalibrator$ python resources/test/test_example_scripts.py 
['/home/dschultz/Documents/offline_software/trunk/build/WaveCalibrator/resources/examples/simple_example.py', '/home/dschultz/test-data/sim/GeoCalibDetectorStatus_2013.56429_V1.i3.gz', '/home/dschultz/test-data/sim/Level2_IC86.2011_corsika.010281.001664.00.i3.bz2', './output.i3.gz']
INFO (I3Module): Opened file /home/dschultz/test-data/sim/GeoCalibDetectorStatus_2013.56429_V1.i3.gz (I3Reader.cxx:180 in void I3Reader::OpenNextFile())
INFO (I3ConditionalModule): Compressing at level 6 (I3WriterBase.cxx:103 in virtual void I3WriterBase::Configure())
*** Error in `python': munmap_chunk(): invalid pointer: 0x0000000000fdedd8 ***
F
======================================================================
FAIL: test_simple_example (__main__.TestSimpleExample)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "resources/test/test_example_scripts.py", line 18, in test_simple_example
    self.run_example('simple_example.py', gcd_file, input_file, output_file)
  File "/home/dschultz/Documents/offline_software/trunk/build/lib/icecube/icetray/I3Test.py", line 70, in run_example
    "Example %s did not finish successfully." % script)
AssertionError: Example /home/dschultz/Documents/offline_software/trunk/build/WaveCalibrator/resources/examples/simple_example.py did not finish successfully.

----------------------------------------------------------------------
Ran 1 test in 0.255s

FAILED (failures=1)
```

Migrated from https://code.icecube.wisc.edu/ticket/1406
```json
{
    "status": "closed", 
    "changetime": "2016-03-18T21:14:10", 
    "description": "With gcc 5.2, boost 1.57:\n\n{{{\ndschultz@tide2:~/Documents/offline_software/trunk/build/WaveCalibrator$ python resources/test/test_example_scripts.py \n['/home/dschultz/Documents/offline_software/trunk/build/WaveCalibrator/resources/examples/simple_example.py', '/home/dschultz/test-data/sim/GeoCalibDetectorStatus_2013.56429_V1.i3.gz', '/home/dschultz/test-data/sim/Level2_IC86.2011_corsika.010281.001664.00.i3.bz2', './output.i3.gz']\nINFO (I3Module): Opened file /home/dschultz/test-data/sim/GeoCalibDetectorStatus_2013.56429_V1.i3.gz (I3Reader.cxx:180 in void I3Reader::OpenNextFile())\nINFO (I3ConditionalModule): Compressing at level 6 (I3WriterBase.cxx:103 in virtual void I3WriterBase::Configure())\n*** Error in `python': munmap_chunk(): invalid pointer: 0x0000000000fdedd8 ***\nF\n======================================================================\nFAIL: test_simple_example (__main__.TestSimpleExample)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"resources/test/test_example_scripts.py\", line 18, in test_simple_example\n    self.run_example('simple_example.py', gcd_file, input_file, output_file)\n  File \"/home/dschultz/Documents/offline_software/trunk/build/lib/icecube/icetray/I3Test.py\", line 70, in run_example\n    \"Example %s did not finish successfully.\" % script)\nAssertionError: Example /home/dschultz/Documents/offline_software/trunk/build/WaveCalibrator/resources/examples/simple_example.py did not finish successfully.\n\n----------------------------------------------------------------------\nRan 1 test in 0.255s\n\nFAILED (failures=1)\n}}}", 
    "reporter": "david.schultz", 
    "cc": "olivas, nega", 
    "resolution": "invalid", 
    "_ts": "1458335650323600", 
    "component": "combo core", 
    "summary": "[WaveCalibrator] munmap_chunk: invalid pointer", 
    "priority": "critical", 
    "keywords": "", 
    "time": "2015-10-18T13:54:57", 
    "milestone": "", 
    "owner": "jbraun", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20151018T20:17:45: 
* david.schultz changed resolution from "" to "invalid"
* david.schultz commented:

> my fault I think.  I was testing memory tracking and this is a bug for me.


* david.schultz changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20160318T21:14:10: 
* olivas commented:

> Milestone offline V15-12-00 deleted


* olivas changed milestone from "offline V15-12-00" to ""
