### ISSUE TITLE
[dataclasses] mctree old->new conversion error (Trac #1459)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1451]
For file: `/data/ana/Cscd/StartingEvents/NuGen/NuMu/2011_domeff_099/l3/9/l3_00008635.i3.bz2`

```text
FATAL (Tree): Assertion failed: insertResult.second (I3MCTree_impl.h:475 in void TreeBase::Tree<T, Key, Hash>::append_child(const Key&, const T&) [with T = I3Particle, Key = I3ParticleID, Hash = __gnu_cxx::hash<I3ParticleID>])
ERROR (PythonFunction): Error running python function as module: (PythonFunction.cxx:173 in virtual void PythonFunction::Process())
ERROR (I3Module): CollectStats: Exception thrown (I3Module.cxx:113 in void I3Module::Do(void (I3Module::*)()))
Traceback (most recent call last):
  File "track_veto.py", line 333, in <module>
    tray.Execute()
  File "/data/user/nwandkowsky/tarballs/icerec.V04-11-02/build/lib/I3Tray.py", line 234, in Execute
    super(I3Tray, self).Execute()
  File "track_veto.py", line 248, in collectStats
    print frame["I3MCTree"]
```

I'm investigating now.

Migrated from https://code.icecube.wisc.edu/ticket/1459
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:11:57", 
    "description": "For file: `/data/ana/Cscd/StartingEvents/NuGen/NuMu/2011_domeff_099/l3/9/l3_00008635.i3.bz2`\n\n{{{\nFATAL (Tree): Assertion failed: insertResult.second (I3MCTree_impl.h:475 in void TreeBase::Tree<T, Key, Hash>::append_child(const Key&, const T&) [with T = I3Particle, Key = I3ParticleID, Hash = __gnu_cxx::hash<I3ParticleID>])\nERROR (PythonFunction): Error running python function as module: (PythonFunction.cxx:173 in virtual void PythonFunction::Process())\nERROR (I3Module): CollectStats: Exception thrown (I3Module.cxx:113 in void I3Module::Do(void (I3Module::*)()))\nTraceback (most recent call last):\n  File \"track_veto.py\", line 333, in <module>\n    tray.Execute()\n  File \"/data/user/nwandkowsky/tarballs/icerec.V04-11-02/build/lib/I3Tray.py\", line 234, in Execute\n    super(I3Tray, self).Execute()\n  File \"track_veto.py\", line 248, in collectStats\n    print frame[\"I3MCTree\"]\n}}}\n\nI'm investigating now.", 
    "reporter": "david.schultz", 
    "cc": "nwandkowsky", 
    "resolution": "fixed", 
    "_ts": "1550067117911749", 
    "component": "combo core", 
    "summary": "[dataclasses] mctree old->new conversion error", 
    "priority": "blocker", 
    "keywords": "mctree", 
    "time": "2015-12-01T17:50:07", 
    "milestone": "", 
    "owner": "olivas", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20151201T17:50:13: david.schultz changed status from "new" to "accepted"

**Comment by icecube-trac** [comment]
Trac update at 20151201T18:13:17: 
* david.schultz changed owner from "david.schultz" to "olivas"
* david.schultz changed status from "accepted" to "assigned"
* david.schultz commented:

> apparently, this was fixed in r138288/IceCube.
> 
> So, new icerec release?


* david.schultz changed milestone from "offline V15-11-00" to "IceRec V5"
* david.schultz changed cc from "nwandkowsky, olivas" to "nwandkowsky"

**Comment by icecube-trac** [comment]
Trac update at 20151201T18:18:10: olivas commented:

> Perhaps an incremental release of IceRec v4.

**Comment by icecube-trac** [comment]
Trac update at 20160217T21:22:01: 
* olivas changed status from "assigned" to "closed"
* olivas commented:

> We're working on a new release now, so no need for this ticket anymore.


* olivas changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:11:57: 
* olivas changed milestone from "IceRec V5" to ""
* olivas commented:

> Milestone IceRec V5 deleted
