### ISSUE TITLE
[cvmfs] gfortran issue and nugen (Trac #1501)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1493]
I'm getting th following error when attempting to run nugen:

Loading neutrino-generator................................FATAL (I3Tray): Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /cvmfs/icecube.opensciencegrid.org/py2-v2/Ubuntu_14_x86_64/tools/gfortran/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/i3ports/lib/libPythia6.so) (I3Tray.py:34 in load)
Traceback (most recent call last):
  File "/cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/simulation/V04-00-12/neutrino-generator/resources/scripts/NuGen.py", line 13, in <module>
    from icecube import icetray, dataclasses, phys_services, sim_services, dataio, neutrino_generator
  File "/cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/simulation/V04-00-12/lib/icecube/neutrino_generator/__init__.py", line 6, in <module>
    I3Tray.load("neutrino-generator")
  File "/cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/simulation/V04-00-12/lib/I3Tray.py", line 34, in load
    icetray.logging.log_fatal("Failed to load library (%s): %s" % (sys.exc_info()[0], sys.exc_info()[1]), "I3Tray")
  File "/cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/simulation/V04-00-12/lib/icecube/icetray/i3logging.py", line 150, in log_fatal
    raise RuntimeError(message + " (in " + tb[2] + ")")
RuntimeError: Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /cvmfs/icecube.opensciencegrid.org/py2-v2/Ubuntu_14_x86_64/tools/gfortran/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/i3ports/lib/libPythia6.so) (in load)

Seems like an inconsistent toolset where the pythia lib was built against a different version of gfortran than was bundled with the distribution.

Migrated from https://code.icecube.wisc.edu/ticket/1501
```json
{
    "status": "closed", 
    "changetime": "2016-03-18T21:14:15", 
    "description": "I'm getting th following error when attempting to run nugen:\n\nLoading neutrino-generator................................FATAL (I3Tray): Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /cvmfs/icecube.opensciencegrid.org/py2-v2/Ubuntu_14_x86_64/tools/gfortran/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/i3ports/lib/libPythia6.so) (I3Tray.py:34 in load)\nTraceback (most recent call last):\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/simulation/V04-00-12/neutrino-generator/resources/scripts/NuGen.py\", line 13, in <module>\n    from icecube import icetray, dataclasses, phys_services, sim_services, dataio, neutrino_generator\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/simulation/V04-00-12/lib/icecube/neutrino_generator/__init__.py\", line 6, in <module>\n    I3Tray.load(\"neutrino-generator\")\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/simulation/V04-00-12/lib/I3Tray.py\", line 34, in load\n    icetray.logging.log_fatal(\"Failed to load library (%s): %s\" % (sys.exc_info()[0], sys.exc_info()[1]), \"I3Tray\")\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/simulation/V04-00-12/lib/icecube/icetray/i3logging.py\", line 150, in log_fatal\n    raise RuntimeError(message + \" (in \" + tb[2] + \")\")\nRuntimeError: Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /cvmfs/icecube.opensciencegrid.org/py2-v2/Ubuntu_14_x86_64/tools/gfortran/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/i3ports/lib/libPythia6.so) (in load)\n\nSeems like an inconsistent toolset where the pythia lib was built against a different version of gfortran than was bundled with the distribution.\n", 
    "reporter": "olivas", 
    "cc": "", 
    "resolution": "invalid", 
    "_ts": "1458335655846260", 
    "component": "cvmfs", 
    "summary": "[cvmfs] gfortran issue and nugen", 
    "priority": "major", 
    "keywords": "", 
    "time": "2016-01-06T23:24:29", 
    "milestone": "", 
    "owner": "david.schultz", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160106T23:41:21: david.schultz commented:

> As far as I can tell, the file in cvmfs is the same as the one on the build machine.
> 
> Note that I've never actually tested things that linked against Pythia, so it could be something special in Pythia throwing a fit.
> 
> What happens if you install gfortran on the local machine?  Does the error go away?
> 
> As a future note, it would be great if we could switch to pythia 8.1 or newer, since it uses c++.

**Comment by icecube-trac** [comment]
Trac update at 20160107T16:01:35: olivas commented:

> I agree w.r.t. pythia8, but that depends on the genie team.  genie is the only reason pythia is in our stack.
> 
> This was a fresh install of ubuntu with a software update afterwards.  On a fresh install pre-update I don't get the same error on import.  I'm updating now to see if that was in fact the cause.
>

**Comment by icecube-trac** [comment]
Trac update at 20160107T17:07:22: 
* olivas commented:

> Another software update on my laptop fixed the problem.  This was an update on the host OS...not the VM...so who knows?  I'm calling this a heisenbug and closing the ticket.


* olivas changed status from "new" to "closed"
* olivas changed resolution from "" to "invalid"

**Comment by icecube-trac** [comment]
Trac update at 20160318T21:14:15: 
* olivas changed milestone from "February 2016" to ""
* olivas commented:

> Milestone February 2016 deleted
