### ISSUE TITLE
[filterscripts] SimulationFiltering is broken (Trac #1527)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1519]
$ filterscripts/resources/scripts/SimulationFiltering.py -h
Traceback (most recent call last):
  File "filterscripts/resources/scripts/SimulationFiltering.py", line 5, in <module>
    from icecube import icetray, dataclasses, dataio, filter_tools, trigger_sim
  File "/home/olivas/icecube/combo-pristine/build/lib/icecube/filter_tools/__init__.py", line 7, in <module>
    from icecube.filter_tools.PnfResplitter import PnfResplitter
  File "/home/olivas/icecube/combo-pristine/build/lib/icecube/filter_tools/PnfResplitter.py", line 1, in <module>
    from icecube import icetray, dataclasses, dataio, phys_services, dst
ImportError: cannot import name dst

This is one the trunk of combo.  That import fails because dst does build.  It doesn't build because healpix-cxx isn't included in any of the standard meta-projects anymore, including combo, which is conditional needed by dst.

Why did we remove this again?  Can the current dst project truly live without healpix-cxx?

Migrated from https://code.icecube.wisc.edu/ticket/1527
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:11:45", 
    "description": "$ filterscripts/resources/scripts/SimulationFiltering.py -h\nTraceback (most recent call last):\n  File \"filterscripts/resources/scripts/SimulationFiltering.py\", line 5, in <module>\n    from icecube import icetray, dataclasses, dataio, filter_tools, trigger_sim\n  File \"/home/olivas/icecube/combo-pristine/build/lib/icecube/filter_tools/__init__.py\", line 7, in <module>\n    from icecube.filter_tools.PnfResplitter import PnfResplitter\n  File \"/home/olivas/icecube/combo-pristine/build/lib/icecube/filter_tools/PnfResplitter.py\", line 1, in <module>\n    from icecube import icetray, dataclasses, dataio, phys_services, dst\nImportError: cannot import name dst\n\n\nThis is one the trunk of combo.  That import fails because dst does build.  It doesn't build because healpix-cxx isn't included in any of the standard meta-projects anymore, including combo, which is conditional needed by dst.\n\nWhy did we remove this again?  Can the current dst project truly live without healpix-cxx?", 
    "reporter": "olivas", 
    "cc": "nega, david.schultz", 
    "resolution": "fixed", 
    "_ts": "1550067105393059", 
    "component": "combo simulation", 
    "summary": "[filterscripts] SimulationFiltering is broken", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2016-01-22T22:55:53", 
    "milestone": "", 
    "owner": "juancarlos", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160125T15:58:28: juancarlos commented:

> healpix-cxx was moved from projects to tools. So I guess it only gets built if healpix-cxx is installed in the tools. Maybe we need to make it a hard fail rather than a conditional build and make heapix-cxx get installed by default with the tools?

**Comment by icecube-trac** [comment]
Trac update at 20160125T16:05:29: david.schultz commented:

> But if it's a hard fail everyone building icerec will need to install healpix-cxx to do any work at all.  That seems less than desirable.
> 
> Probably just a documentation issue for those that want to run filtering.  Maybe also a cmake dependence in filterscripts, so it won't build either (though I can argue that you can run filtering and ignore DST, thus not needing healpix).

**Comment by icecube-trac** [comment]
Trac update at 20160125T17:22:39: 
* juancarlos changed status from "new" to "closed"
* juancarlos commented:

> On further inspection, it looks like the PnfResplitter.py module does not actually use dst at all. I removed the import which should solve this ticket.


* juancarlos changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:11:45: 
* olivas changed milestone from "IceSim 5.0" to ""
* olivas commented:

> Milestone IceSim 5.0 deleted
