### ISSUE TITLE
[bayesian-priors] tests gone wild! (Trac #1561)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1553]
I don't remember when or how I last ran tests, but it looks like it's getting lost in ROOT-land...

```text
[zinc:~] ps xa |grep python
15542 ?        Rl   9017:22 python /home/nega/i3/combo/src/bayesian-priors/resources/tests/test_bayesian.py
```

```text
[zinc:~] sudo strace -p 15542 2>&1| head
Process 15542 attached
rt_sigreturn()                          = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=15542, si_uid=1000} ---
write(2, "\n *** Break *** write on a pipe "..., 55) = -1 EPIPE (Broken pipe)
rt_sigreturn()                          = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=15542, si_uid=1000} ---
write(2, "\n *** Break *** write on a pipe "..., 55) = -1 EPIPE (Broken pipe)
rt_sigreturn()                          = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=15542, si_uid=1000} ---
write(2, "\n *** Break *** write on a pipe "..., 55) = -1 EPIPE (Broken pipe)
[zinc:~] 
```

```text
https://code.icecube.wisc.edu/ticket/0  0x00007f5d8d5eb4fd in write () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f5d8d56dbff in _IO_new_file_write (f=0x7f5d8d8b9640 <_IO_2_1_stderr_>, data=0x7fffeed13760, n=92)
    at fileops.c:1251
#2  0x00007f5d8d56e39f in new_do_write (to_do=92, 
    data=0x7fffeed13760 "NOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:473 in void I3Tray::Execute(unsigned int))\n", fp=0x7f5d8d8b9640 <_IO_2_1_stderr_>) at fileops.c:506
#3  _IO_new_file_xsputn (f=0x7f5d8d8b9640 <_IO_2_1_stderr_>, data=<optimized out>, n=92) at fileops.c:1330
#4  0x00007f5d8d563488 in __GI__IO_fputs (
    str=0x7fffeed13760 "NOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:473 in void I3Tray::Execute(unsigned int))\n", fp=0x7f5d8d8b9640 <_IO_2_1_stderr_>) at iofputs.c:40
#5  0x00007f5d8bbf4b55 in I3PrintfLogger::Log (this=0x199fbb0, level=I3LOG_NOTICE, unit="I3Tray", 
    file="../../src/icetray/private/icetray/I3Tray.cxx", line=473, func="void I3Tray::Execute(unsigned int)", 
    message="I3Tray finishing...") at ../../src/icetray/private/icetray/I3PrintfLogger.cxx:85
#6  0x00007f5d8bbaef4c in I3Tray::Execute (this=0x22eab00, maxCount=4294967295)
    at ../../src/icetray/private/icetray/I3Tray.cxx:473
#7  0x00007f5d8bbae939 in I3Tray::Execute (this=0x22eab00) at ../../src/icetray/private/icetray/I3Tray.cxx:439
#8  0x00007f5d8bcdde86 in boost::python::detail::invoke<int, void (I3Tray::*)(), boost::python::arg_from_python<I3Tray&> > (f=@0x19a6e28: (void (I3Tray::*)(I3Tray * const)) 0x7f5d8bbae918 <I3Tray::Execute()>, tc=...)
    at /usr/include/boost/python/detail/invoke.hpp:94
#9  0x00007f5d8bcdc0a4 in boost::python::detail::caller_arity<1u>::impl<void (I3Tray::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, I3Tray&> >::operator() (this=0x19a6e28, 
    args_=(<I3Tray(segments_in_order=[], last_added='<function test at 0x7f5d8143f398>_0000') at remote 0x7f5d7d7e4418>,)) at /usr/include/boost/python/detail/caller.hpp:223
#10 0x00007f5d8bcda1d3 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (I3Tray::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, I3Tray&> > >::operator() (
    this=0x19a6e20, 
    args=(<I3Tray(segments_in_order=[], last_added='<function test at 0x7f5d8143f398>_0000') at remote 0x7f5d7d7e4418>,), kw=0x0) at /usr/include/boost/python/object/py_function.hpp:38
#11 0x00007f5d8ae9078d in boost::python::objects::function::call(_object*, _object*) const ()
   from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0
#12 0x00007f5d8ae909a8 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0
#13 0x00007f5d8ae9a653 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0
#14 0x00007f5d665e87d8 in boost::python::detail::translate_exception<not_found_exception, void (*)(not_found_exc---Type <return> to continue, or q <return> to quit---
eption const&)>::operator() (this=0x1d1a2a8, handler=..., f=..., 
    translate=0x7f5d665c1baf <translate(not_found_exception const&)>)
    at /usr/include/boost/python/detail/translate_exception.hpp:48
#15 0x00007f5d665e5c67 in boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(not_found_exception const&)> >::operator()<bool, boost::python::detail::translate_exception<not_found_exception, void (*)(not_found_exception const&)>, boost::_bi::list2<boost::python::detail::exception_handler const&, boost::function0<void> const&> > (this=0x1d1a2b0, f=..., a=...) at /usr/include/boost/bind/bind.hpp:382
#16 0x00007f5d665e0f41 in boost::_bi::bind_t<bool, boost::python::detail::translate_exception<not_found_exception, void (*)(not_found_exception const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(not_found_exception const&)> > >::operator()<boost::python::detail::exception_handler, boost::function0<void> > (this=0x1d1a2a8, a1=..., a2=...) at /usr/include/boost/bind/bind_template.hpp:102
#17 0x00007f5d665dbd5f in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<not_found_exception, void (*)(not_found_exception const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(not_found_exception const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke (function_obj_ptr=..., a0=..., a1=...)
    at /usr/include/boost/function/function_template.hpp:132
#18 0x00007f5d8ae9a3fd in boost::python::handle_exception_impl(boost::function0<void>) ()
   from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0
#19 0x00007f5d8ae8f189 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0
#20 0x00000000004cd9ab in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>)
    at ../Objects/abstract.c:2529
#21 do_call (nk=<optimized out>, na=<optimized out>, pp_stack=<optimized out>, func=<optimized out>)
    at ../Python/ceval.c:4253
#22 call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4058
#23 PyEval_EvalFrameEx () at ../Python/ceval.c:2681
#24 0x00000000004cb6b1 in PyEval_EvalCodeEx () at ../Python/ceval.c:3267
#25 0x00000000004ce7d3 in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, 
    pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4131
#26 call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4056
#27 PyEval_EvalFrameEx () at ../Python/ceval.c:2681
#28 0x00000000004cb6b1 in PyEval_EvalCodeEx () at ../Python/ceval.c:3267
#29 0x000000000050481f in PyEval_EvalCode (
    locals={'load': <function at remote 0x7f5d80461500>, 'dataio': <module at remote 0x7f5d8db47440>, 'bayesian_priors': <module at remote 0x7f5d80474ec0>, 'icetray': <module at remote 0x7f5d8c8df590>, 'NaN': <float at remot---Type <return> to continue, or q <return> to quit---
e 0x1a590a0>, '__package__': None, 'platform': <module at remote 0x7f5d8c8d1b40>, 'I3Tray': <Boost.Python.class at remote 0x19f7e00>, 'test': <function at remote 0x7f5d8143f398>, '__doc__': '\nUnit test for Bayesian Priors. This runs bayes on a Level3 nugen\nfile with identical parameters as the original result in the file, \nand compares the two. Future Improvements to bayes may cause \nthis test to fail.\n', 'files': ['GeoCalibDetectorStatus_IC86.55697_corrected_V2.i3.gz', 'Level3_nugen_numu_IC86.2012.011069.000000_20events.i3.bz2'], 'UpgoingEvents': <function at remote 0x7f5d8143f2a8>, '__builtins__': <module at remote 0x7f5d8dcabb08>, '__file__': '/home/nega/i3/combo/src/bayesian-priors/resources/tests/test_bayesian.py', 'inspect': <module at remote 0x7f5d8db3c130>, 'sys': <module at remote 0x7f5...(truncated), 
    globals={'load': <function at remote 0x7f5d80461500>, 'dataio': <module at remote 0x7f5d8db47440>, 'bayesian_priors': <module at remote 0x7f5d80474ec0>, 'icetray': <module at remote 0x7f5d8c8df590>, 'NaN': <float at remote 0x1a590a0>, '__package__': None, 'platform': <module at remote 0x7f5d8c8d1b40>, 'I3Tray': <Boost.Python.class at remote 0x19f7e00>, 'test': <function at remote 0x7f5d8143f398>, '__doc__': '\nUnit test for Bayesian Priors. This runs bayes on a Level3 nugen\nfile with identical parameters as the original result in the file, \nand compares the two. Future Improvements to bayes may cause \nthis test to fail.\n', 'files': ['GeoCalibDetectorStatus_IC86.55697_corrected_V2.i3.gz', 'Level3_nugen_numu_IC86.2012.011069.000000_20events.i3.bz2'], 'UpgoingEvents': <function at remote 0x7f5d8143f2a8>, '__builtins__': <module at remote 0x7f5d8dcabb08>, '__file__': '/home/nega/i3/combo/src/bayesian-priors/resources/tests/test_bayesian.py', 'inspect': <module at remote 0x7f5d8db3c130>, 'sys': <module at remote 0x7f5...(truncated), co=0x7f5d8dbe6db0) at ../Python/ceval.c:669
#30 run_mod.lto_priv () at ../Python/pythonrun.c:1371
#31 0x00000000004fc182 in PyRun_FileExFlags () at ../Python/pythonrun.c:1357
#32 0x00000000004fb247 in PyRun_SimpleFileExFlags () at ../Python/pythonrun.c:949
#33 0x000000000049aa6e in Py_Main () at ../Modules/main.c:640
#34 0x00007f5d8d514a40 in __libc_start_main (main=0x49a500 <main>, argc=2, argv=0x7fffeed144c8, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffeed144b8)
    at libc-start.c:289
#35 0x000000000049a429 in _start ()
```

Migrated from https://code.icecube.wisc.edu/ticket/1561
```json
{
    "status": "closed", 
    "changetime": "2016-04-28T16:28:49", 
    "description": "I don't remember when or how I last ran tests, but it looks like it's getting lost in ROOT-land...\n\n{{{\n[zinc:~] ps xa |grep python\n15542 ?        Rl   9017:22 python /home/nega/i3/combo/src/bayesian-priors/resources/tests/test_bayesian.py\n}}}\n\n{{{\n[zinc:~] sudo strace -p 15542 2>&1| head\nProcess 15542 attached\nrt_sigreturn()                          = -1 EPIPE (Broken pipe)\n--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=15542, si_uid=1000} ---\nwrite(2, \"\\n *** Break *** write on a pipe \"..., 55) = -1 EPIPE (Broken pipe)\nrt_sigreturn()                          = -1 EPIPE (Broken pipe)\n--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=15542, si_uid=1000} ---\nwrite(2, \"\\n *** Break *** write on a pipe \"..., 55) = -1 EPIPE (Broken pipe)\nrt_sigreturn()                          = -1 EPIPE (Broken pipe)\n--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=15542, si_uid=1000} ---\nwrite(2, \"\\n *** Break *** write on a pipe \"..., 55) = -1 EPIPE (Broken pipe)\n[zinc:~] \n}}}\n\n{{{\n#0  0x00007f5d8d5eb4fd in write () at ../sysdeps/unix/syscall-template.S:81\n#1  0x00007f5d8d56dbff in _IO_new_file_write (f=0x7f5d8d8b9640 <_IO_2_1_stderr_>, data=0x7fffeed13760, n=92)\n    at fileops.c:1251\n#2  0x00007f5d8d56e39f in new_do_write (to_do=92, \n    data=0x7fffeed13760 \"NOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:473 in void I3Tray::Execute(unsigned int))\\n\", fp=0x7f5d8d8b9640 <_IO_2_1_stderr_>) at fileops.c:506\n#3  _IO_new_file_xsputn (f=0x7f5d8d8b9640 <_IO_2_1_stderr_>, data=<optimized out>, n=92) at fileops.c:1330\n#4  0x00007f5d8d563488 in __GI__IO_fputs (\n    str=0x7fffeed13760 \"NOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:473 in void I3Tray::Execute(unsigned int))\\n\", fp=0x7f5d8d8b9640 <_IO_2_1_stderr_>) at iofputs.c:40\n#5  0x00007f5d8bbf4b55 in I3PrintfLogger::Log (this=0x199fbb0, level=I3LOG_NOTICE, unit=\"I3Tray\", \n    file=\"../../src/icetray/private/icetray/I3Tray.cxx\", line=473, func=\"void I3Tray::Execute(unsigned int)\", \n    message=\"I3Tray finishing...\") at ../../src/icetray/private/icetray/I3PrintfLogger.cxx:85\n#6  0x00007f5d8bbaef4c in I3Tray::Execute (this=0x22eab00, maxCount=4294967295)\n    at ../../src/icetray/private/icetray/I3Tray.cxx:473\n#7  0x00007f5d8bbae939 in I3Tray::Execute (this=0x22eab00) at ../../src/icetray/private/icetray/I3Tray.cxx:439\n#8  0x00007f5d8bcdde86 in boost::python::detail::invoke<int, void (I3Tray::*)(), boost::python::arg_from_python<I3Tray&> > (f=@0x19a6e28: (void (I3Tray::*)(I3Tray * const)) 0x7f5d8bbae918 <I3Tray::Execute()>, tc=...)\n    at /usr/include/boost/python/detail/invoke.hpp:94\n#9  0x00007f5d8bcdc0a4 in boost::python::detail::caller_arity<1u>::impl<void (I3Tray::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, I3Tray&> >::operator() (this=0x19a6e28, \n    args_=(<I3Tray(segments_in_order=[], last_added='<function test at 0x7f5d8143f398>_0000') at remote 0x7f5d7d7e4418>,)) at /usr/include/boost/python/detail/caller.hpp:223\n#10 0x00007f5d8bcda1d3 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (I3Tray::*)(), boost::python::default_call_policies, boost::mpl::vector2<void, I3Tray&> > >::operator() (\n    this=0x19a6e20, \n    args=(<I3Tray(segments_in_order=[], last_added='<function test at 0x7f5d8143f398>_0000') at remote 0x7f5d7d7e4418>,), kw=0x0) at /usr/include/boost/python/object/py_function.hpp:38\n#11 0x00007f5d8ae9078d in boost::python::objects::function::call(_object*, _object*) const ()\n   from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0\n#12 0x00007f5d8ae909a8 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0\n#13 0x00007f5d8ae9a653 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0\n#14 0x00007f5d665e87d8 in boost::python::detail::translate_exception<not_found_exception, void (*)(not_found_exc---Type <return> to continue, or q <return> to quit---\neption const&)>::operator() (this=0x1d1a2a8, handler=..., f=..., \n    translate=0x7f5d665c1baf <translate(not_found_exception const&)>)\n    at /usr/include/boost/python/detail/translate_exception.hpp:48\n#15 0x00007f5d665e5c67 in boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(not_found_exception const&)> >::operator()<bool, boost::python::detail::translate_exception<not_found_exception, void (*)(not_found_exception const&)>, boost::_bi::list2<boost::python::detail::exception_handler const&, boost::function0<void> const&> > (this=0x1d1a2b0, f=..., a=...) at /usr/include/boost/bind/bind.hpp:382\n#16 0x00007f5d665e0f41 in boost::_bi::bind_t<bool, boost::python::detail::translate_exception<not_found_exception, void (*)(not_found_exception const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(not_found_exception const&)> > >::operator()<boost::python::detail::exception_handler, boost::function0<void> > (this=0x1d1a2a8, a1=..., a2=...) at /usr/include/boost/bind/bind_template.hpp:102\n#17 0x00007f5d665dbd5f in boost::detail::function::function_obj_invoker2<boost::_bi::bind_t<bool, boost::python::detail::translate_exception<not_found_exception, void (*)(not_found_exception const&)>, boost::_bi::list3<boost::arg<1>, boost::arg<2>, boost::_bi::value<void (*)(not_found_exception const&)> > >, bool, boost::python::detail::exception_handler const&, boost::function0<void> const&>::invoke (function_obj_ptr=..., a0=..., a1=...)\n    at /usr/include/boost/function/function_template.hpp:132\n#18 0x00007f5d8ae9a3fd in boost::python::handle_exception_impl(boost::function0<void>) ()\n   from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0\n#19 0x00007f5d8ae8f189 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0\n#20 0x00000000004cd9ab in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>)\n    at ../Objects/abstract.c:2529\n#21 do_call (nk=<optimized out>, na=<optimized out>, pp_stack=<optimized out>, func=<optimized out>)\n    at ../Python/ceval.c:4253\n#22 call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4058\n#23 PyEval_EvalFrameEx () at ../Python/ceval.c:2681\n#24 0x00000000004cb6b1 in PyEval_EvalCodeEx () at ../Python/ceval.c:3267\n#25 0x00000000004ce7d3 in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, \n    pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4131\n#26 call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4056\n#27 PyEval_EvalFrameEx () at ../Python/ceval.c:2681\n#28 0x00000000004cb6b1 in PyEval_EvalCodeEx () at ../Python/ceval.c:3267\n#29 0x000000000050481f in PyEval_EvalCode (\n    locals={'load': <function at remote 0x7f5d80461500>, 'dataio': <module at remote 0x7f5d8db47440>, 'bayesian_priors': <module at remote 0x7f5d80474ec0>, 'icetray': <module at remote 0x7f5d8c8df590>, 'NaN': <float at remot---Type <return> to continue, or q <return> to quit---\ne 0x1a590a0>, '__package__': None, 'platform': <module at remote 0x7f5d8c8d1b40>, 'I3Tray': <Boost.Python.class at remote 0x19f7e00>, 'test': <function at remote 0x7f5d8143f398>, '__doc__': '\\nUnit test for Bayesian Priors. This runs bayes on a Level3 nugen\\nfile with identical parameters as the original result in the file, \\nand compares the two. Future Improvements to bayes may cause \\nthis test to fail.\\n', 'files': ['GeoCalibDetectorStatus_IC86.55697_corrected_V2.i3.gz', 'Level3_nugen_numu_IC86.2012.011069.000000_20events.i3.bz2'], 'UpgoingEvents': <function at remote 0x7f5d8143f2a8>, '__builtins__': <module at remote 0x7f5d8dcabb08>, '__file__': '/home/nega/i3/combo/src/bayesian-priors/resources/tests/test_bayesian.py', 'inspect': <module at remote 0x7f5d8db3c130>, 'sys': <module at remote 0x7f5...(truncated), \n    globals={'load': <function at remote 0x7f5d80461500>, 'dataio': <module at remote 0x7f5d8db47440>, 'bayesian_priors': <module at remote 0x7f5d80474ec0>, 'icetray': <module at remote 0x7f5d8c8df590>, 'NaN': <float at remote 0x1a590a0>, '__package__': None, 'platform': <module at remote 0x7f5d8c8d1b40>, 'I3Tray': <Boost.Python.class at remote 0x19f7e00>, 'test': <function at remote 0x7f5d8143f398>, '__doc__': '\\nUnit test for Bayesian Priors. This runs bayes on a Level3 nugen\\nfile with identical parameters as the original result in the file, \\nand compares the two. Future Improvements to bayes may cause \\nthis test to fail.\\n', 'files': ['GeoCalibDetectorStatus_IC86.55697_corrected_V2.i3.gz', 'Level3_nugen_numu_IC86.2012.011069.000000_20events.i3.bz2'], 'UpgoingEvents': <function at remote 0x7f5d8143f2a8>, '__builtins__': <module at remote 0x7f5d8dcabb08>, '__file__': '/home/nega/i3/combo/src/bayesian-priors/resources/tests/test_bayesian.py', 'inspect': <module at remote 0x7f5d8db3c130>, 'sys': <module at remote 0x7f5...(truncated), co=0x7f5d8dbe6db0) at ../Python/ceval.c:669\n#30 run_mod.lto_priv () at ../Python/pythonrun.c:1371\n#31 0x00000000004fc182 in PyRun_FileExFlags () at ../Python/pythonrun.c:1357\n#32 0x00000000004fb247 in PyRun_SimpleFileExFlags () at ../Python/pythonrun.c:949\n#33 0x000000000049aa6e in Py_Main () at ../Modules/main.c:640\n#34 0x00007f5d8d514a40 in __libc_start_main (main=0x49a500 <main>, argc=2, argv=0x7fffeed144c8, \n    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffeed144b8)\n    at libc-start.c:289\n#35 0x000000000049a429 in _start ()\n}}}", 
    "reporter": "nega", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1461860929325856", 
    "component": "combo reconstruction", 
    "summary": "[bayesian-priors] tests gone wild!", 
    "priority": "normal", 
    "keywords": "bayesian-priors, tests, SIGPIPE, signal-handler, root", 
    "time": "2016-02-23T04:51:26", 
    "milestone": "", 
    "owner": "kjmeagher", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160223T17:04:04: 
* nega changed owner from "" to "kjmeagher"
* nega changed keywords from "" to "bayesian-priors, tests, SIGPIPE, signal-handler, root"
* nega changed status from "new" to "assigned"

**Comment by icecube-trac** [comment]
Trac update at 20160224T12:33:45: 
* kjmeagher commented:

> I don't see anything ROOT specific or bayesian-priors specific for that matter. It is failing on `fputs(log_message, stderr);` This looks like an IO issue with the machine. 


* kjmeagher changed _comment0 from "I don't see anything ROOT specific or bayesian-priors specific for that matter. This looks like an IO issue with the machine." to "1456317719284617"

**Comment by icecube-trac** [comment]
Trac update at 20160224T17:05:00: 
* nega commented:

> Maybe. Maybe an ssh session died in the middle of the `fputs()`. The point is our software is handling that poorly. It should **not** get stuck in an infinite loop.


* nega changed _comment0 from "Maybe. Maybe an ssh session died in the middle of the fputs. The point is our software is handling that poorly. It should **not** get stuck in an infinite loop." to "1456333516085730"

**Comment by icecube-trac** [comment]
Trac update at 20160425T18:01:46: olivas commented:

> Please set a milestone.

**Comment by icecube-trac** [comment]
Trac update at 20160428T12:28:15: 
* kjmeagher changed resolution from "" to "invalid"
* kjmeagher commented:

> If icetray needs better error handling for failed logging calls, then assign it to the logging maintainer, not the maintainer of the test where the logging call failed 


* kjmeagher changed status from "assigned" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20160428T12:45:36: 
* nega changed resolution from "invalid" to ""
* nega commented:

> so, don't close it. reassign it. 


* nega changed status from "closed" to "reopened"

**Comment by icecube-trac** [comment]
Trac update at 20160428T16:28:49: 
* nega commented:

> fixed in r2466/IceTray


* nega changed resolution from "" to "fixed"
* nega changed status from "reopened" to "closed"
