### ISSUE TITLE
[IceHive] tests gone wild! (Trac #1562)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1554]
See #1553

``` 21230 ?        Rl   26416:47 python /home/nega/i3/combo/src/IceHive/resources/test/i3hiveclusterTest.py```

```text
(gdb) bt
https://code.icecube.wisc.edu/ticket/0  0x00007f80e00414fd in write () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f80dffc3bff in _IO_new_file_write (f=0x7f80e030f640 <_IO_2_1_stderr_>, data=0x7ffd9bf81300, n=121) at fileops.c:1251
#2  0x00007f80dffc439f in new_do_write (to_do=121, data=0x7ffd9bf81300 "INFO (HiveSplitter): DistanceMap built (HiveSplitter.cxx:759 in void HiveSplitter::BuildLookUpTables(const I3Geometry&))\n", fp=0x7f80e030f640 <_IO_2_1_stderr_>)
    at fileops.c:506
#3  _IO_new_file_xsputn (f=0x7f80e030f640 <_IO_2_1_stderr_>, data=<optimized out>, n=121) at fileops.c:1330
#4  0x00007f80dffb9488 in __GI__IO_fputs (str=0x7ffd9bf81300 "INFO (HiveSplitter): DistanceMap built (HiveSplitter.cxx:759 in void HiveSplitter::BuildLookUpTables(const I3Geometry&))\n", fp=0x7f80e030f640 <_IO_2_1_stderr_>)
    at iofputs.c:40
#5  0x00007f80de67d127 in boost::serialization::serialize<boost::archive::portable_binary_oarchive, boost::serialization::nvp<I3PODHolder<bool> > > (ar=..., t=..., file_version=32640)
    at /usr/include/boost/serialization/serialization.hpp:66
#6  0x00007f80cab9cec6 in HiveSplitter::BuildLookUpTables (this=0x7f80de9257d3, geo=...) at ../../src/IceHive/private/IceHive/HiveSplitter.cxx:759
#7  0x00007f80cac01a88 in I3HiveCluster<I3RecoPulse>::PerformCleaning (this=0x16b2c60, frame=...) at ../../src/IceHive/private/IceHive/I3HiveCluster.h:232
#8  0x00007f80cac001a0 in I3HiveCluster<I3RecoPulse>::Configure (this=0x7ffd9bf82698) at ../../src/IceHive/private/IceHive/I3HiveCluster.h:169
#9  0x00007f80de64c610 in std::__find_if<__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, __gnu_cxx::__ops::_Iter_equals_val<std::string const> > (
    __first="P+\370\233\375\177\000\000\206\247dހ\177\000\000&\260dހ\177\000\000\000\000\000\000\000\000\000\000 ,k\001\000\000\000\000\260D\230\001\000\000\000\000 ,k\001\000\000\000\000\200*\370\233\375\177\000\000\220*\370\233\375\177\000\000\nU_ހ\177\000\000\000\000\000\000\000\000\000\000\030,k\001\000\000\000\000 ,k\001\000\000\000\000\000\037m\375\272\064\252\250\340*\370\233\375\177\000\000\250T_ހ\177\000\000 ,k\001\000\000\000\000\320*\370\233\375\177\000\000\340*\370\233\375\177\000\000\000,k\001\000\000\000\000\200,\370\233\375\177\000\000\001\000\000\000\000\000\000\000P1\370\233\377\377\377\377h,k\001", '\000' <repeats 12 times>..., 
    __last="P\354\324ހ\177\000\000\004\000\000\000\001\000\000\000\240\366\242\001\000\000\000\000q\000\000\000\000\000\000\000A\000\000\000\000\000\000\000A\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000/home/nega/i3/ports/test-data/IceHive/hivecluster_testcase.i3.bz2", '\000' <repeats 15 times>, "Q\000\000\000\000\000\000\000\220+iˀ\177\000\000 \340\232\001\000\000\000\000\060\301\232\001", '\000' <repeats 28 times>, "@\340\232\001\000\000\000\000"..., 
    __pred=...) at /usr/include/c++/4.9/bits/stl_algo.h:132
#10 0x00007f80de64b981 in std::_Rb_tree<std::string, std::pair<std::string const, boost::shared_ptr<I3Module> >, std::_Select1st<std::pair<std::string const, boost::shared_ptr<I3Module> > >, std::less<std::string>, std::allocator<std::pair<std::string const, boost::shared_ptr<I3Module> > > >::_M_lower_bound (this=0x16b2c00, __x=0x21, __y=0xa8aa34bafd6d1f00, __k="") at /usr/include/c++/4.9/bits/stl_tree.h:1262
#11 0x00007f80de64a786 in ?? () from /home/nega/i3/combo/build/lib/libicetray.so
#12 0x00007f80de64b026 in std::_Rb_tree<double, std::pair<double const, std::string>, std::_Select1st<std::pair<double const, std::string> >, std::less<double>, std::allocator<std::pair<double const, std::string> > >::_M_destroy_node (
    this=0x16b2c00, __p=0x1983fb0) at /usr/include/c++/4.9/bits/stl_tree.h:410
#13 0x00007f80de64aad4 in __gnu_cxx::hashtable<std::pair<std::string const, boost::any>, std::string, __gnu_cxx::hash<std::string>, std::_Select1st<std::pair<std::string const, boost::any> >, std::equal_to<std::string>, std::allocator<boost::any> >::resize (this=0x1, __num_elements_hint=140727220186528) at /usr/include/c++/4.9/backward/hashtable.h:1055
#14 0x00007f80de6376b8 in boost::archive::detail::save_pointer_type<boost::archive::xml_oarchive>::polymorphic::save<OMKey> (ar=..., t=...) at /usr/include/boost/archive/detail/oserializer.hpp:387
#15 0x00007f80de637235 in boost::serialization::nvp<int const>::save<boost::archive::portable_binary_oarchive> (this=0x1958360, ar=...) at /usr/include/boost/serialization/nvp.hpp:74
#16 0x00007f80de7692d0 in boost::python::detail::make_function_aux<bool (I3Tray::*)(std::string const&, std::string const&, std::string const&), boost::python::default_call_policies, boost::mpl::vector5<bool, I3Tray&, std::string const&, std::string const&, std::string const&>, mpl_::int_<0> > (f=
    (bool (I3Tray::*)(I3Tray * const, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > &, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > &, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > &)) 0x7f80cb302950, p=..., kw=...) at /usr/include/boost/python/make_function.hpp:46
#17 0x00007f80de7674ee in boost::python::class_<I3Tray, boost::noncopyable_::noncopyable, boost::python::detail::not_specified, boost::python::detail::not_specified>::def_impl<I3Tray, I3Tray::param_setter (I3Tray::*)(std::string const&, std::string), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> > (this=0x7ffd9bf83150, name=0x16b9e88 "\024rcހ\177", 
    fn=NULL, helper=...) at /usr/include/boost/python/class.hpp:529
#18 0x00007f80de76561d in I3Tray::SetParameter<std::vector<int, std::allocator<int> > > (
    this=0x7f80de76561d <I3Tray::SetParameter<std::vector<int, std::allocator<int> > >(std::string const&, std::string const&, std::vector<int, std::allocator<int> > const&)+67>, 
    module=<error reading variable: Cannot access memory at address 0xffffffffffffffe9>, parameter=<error reading variable: Cannot access memory at address 0x1>, value=std::vector of length 35047862944671, capacity 5957535 = {...})
    at ../../src/icetray/public/icetray/I3Tray.h:230
#19 0x00007f80dd8cd78d in boost::python::objects::function::call(_object*, _object*) const () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0
#20 0x00007f80dd8cd9a8 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0
#21 0x00007f80dd8d7653 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0
#22 0x00007f80cf6d430e in boost::serialization::make_nvp<I3Particle> (name=0x7ffd9bf82fc0 "\020\060\370\233\375\177", t=...) at /usr/include/boost/serialization/nvp.hpp:97
#23 0x00007ffd9bf83150 in ?? ()
#24 0x00000000013e0860 in ?? ()
#25 0x00000000013e0868 in ?? ()
#26 0x00007ffd9bf82fc0 in ?? ()
#27 0x00007f80cf6d42e0 in std::stack<unsigned int, std::deque<unsigned int, std::allocator<unsigned int> > >::push (this=0xc3c900000000b8ff, __x=@0xffff40b58948f07d: <error reading variable>) at /usr/include/c++/4.9/bits/stl_stack.h:190
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

```

Migrated from https://code.icecube.wisc.edu/ticket/1562
```json
{
    "status": "closed", 
    "changetime": "2016-04-28T16:29:13", 
    "description": "See #1561\n\n{{{ 21230 ?        Rl   26416:47 python /home/nega/i3/combo/src/IceHive/resources/test/i3hiveclusterTest.py}}}\n\n{{{\n(gdb) bt\n#0  0x00007f80e00414fd in write () at ../sysdeps/unix/syscall-template.S:81\n#1  0x00007f80dffc3bff in _IO_new_file_write (f=0x7f80e030f640 <_IO_2_1_stderr_>, data=0x7ffd9bf81300, n=121) at fileops.c:1251\n#2  0x00007f80dffc439f in new_do_write (to_do=121, data=0x7ffd9bf81300 \"INFO (HiveSplitter): DistanceMap built (HiveSplitter.cxx:759 in void HiveSplitter::BuildLookUpTables(const I3Geometry&))\\n\", fp=0x7f80e030f640 <_IO_2_1_stderr_>)\n    at fileops.c:506\n#3  _IO_new_file_xsputn (f=0x7f80e030f640 <_IO_2_1_stderr_>, data=<optimized out>, n=121) at fileops.c:1330\n#4  0x00007f80dffb9488 in __GI__IO_fputs (str=0x7ffd9bf81300 \"INFO (HiveSplitter): DistanceMap built (HiveSplitter.cxx:759 in void HiveSplitter::BuildLookUpTables(const I3Geometry&))\\n\", fp=0x7f80e030f640 <_IO_2_1_stderr_>)\n    at iofputs.c:40\n#5  0x00007f80de67d127 in boost::serialization::serialize<boost::archive::portable_binary_oarchive, boost::serialization::nvp<I3PODHolder<bool> > > (ar=..., t=..., file_version=32640)\n    at /usr/include/boost/serialization/serialization.hpp:66\n#6  0x00007f80cab9cec6 in HiveSplitter::BuildLookUpTables (this=0x7f80de9257d3, geo=...) at ../../src/IceHive/private/IceHive/HiveSplitter.cxx:759\n#7  0x00007f80cac01a88 in I3HiveCluster<I3RecoPulse>::PerformCleaning (this=0x16b2c60, frame=...) at ../../src/IceHive/private/IceHive/I3HiveCluster.h:232\n#8  0x00007f80cac001a0 in I3HiveCluster<I3RecoPulse>::Configure (this=0x7ffd9bf82698) at ../../src/IceHive/private/IceHive/I3HiveCluster.h:169\n#9  0x00007f80de64c610 in std::__find_if<__gnu_cxx::__normal_iterator<std::string*, std::vector<std::string, std::allocator<std::string> > >, __gnu_cxx::__ops::_Iter_equals_val<std::string const> > (\n    __first=\"P+\\370\\233\\375\\177\\000\\000\\206\\247d\u0780\\177\\000\\000&\\260d\u0780\\177\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000 ,k\\001\\000\\000\\000\\000\\260D\\230\\001\\000\\000\\000\\000 ,k\\001\\000\\000\\000\\000\\200*\\370\\233\\375\\177\\000\\000\\220*\\370\\233\\375\\177\\000\\000\\nU_\u0780\\177\\000\\000\\000\\000\\000\\000\\000\\000\\000\\000\\030,k\\001\\000\\000\\000\\000 ,k\\001\\000\\000\\000\\000\\000\\037m\\375\\272\\064\\252\\250\\340*\\370\\233\\375\\177\\000\\000\\250T_\u0780\\177\\000\\000 ,k\\001\\000\\000\\000\\000\\320*\\370\\233\\375\\177\\000\\000\\340*\\370\\233\\375\\177\\000\\000\\000,k\\001\\000\\000\\000\\000\\200,\\370\\233\\375\\177\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000P1\\370\\233\\377\\377\\377\\377h,k\\001\", '\\000' <repeats 12 times>..., \n    __last=\"P\\354\\324\u0780\\177\\000\\000\\004\\000\\000\\000\\001\\000\\000\\000\\240\\366\\242\\001\\000\\000\\000\\000q\\000\\000\\000\\000\\000\\000\\000A\\000\\000\\000\\000\\000\\000\\000A\\000\\000\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\\000/home/nega/i3/ports/test-data/IceHive/hivecluster_testcase.i3.bz2\", '\\000' <repeats 15 times>, \"Q\\000\\000\\000\\000\\000\\000\\000\\220+i\u02c0\\177\\000\\000 \\340\\232\\001\\000\\000\\000\\000\\060\\301\\232\\001\", '\\000' <repeats 28 times>, \"@\\340\\232\\001\\000\\000\\000\\000\"..., \n    __pred=...) at /usr/include/c++/4.9/bits/stl_algo.h:132\n#10 0x00007f80de64b981 in std::_Rb_tree<std::string, std::pair<std::string const, boost::shared_ptr<I3Module> >, std::_Select1st<std::pair<std::string const, boost::shared_ptr<I3Module> > >, std::less<std::string>, std::allocator<std::pair<std::string const, boost::shared_ptr<I3Module> > > >::_M_lower_bound (this=0x16b2c00, __x=0x21, __y=0xa8aa34bafd6d1f00, __k=\"\") at /usr/include/c++/4.9/bits/stl_tree.h:1262\n#11 0x00007f80de64a786 in ?? () from /home/nega/i3/combo/build/lib/libicetray.so\n#12 0x00007f80de64b026 in std::_Rb_tree<double, std::pair<double const, std::string>, std::_Select1st<std::pair<double const, std::string> >, std::less<double>, std::allocator<std::pair<double const, std::string> > >::_M_destroy_node (\n    this=0x16b2c00, __p=0x1983fb0) at /usr/include/c++/4.9/bits/stl_tree.h:410\n#13 0x00007f80de64aad4 in __gnu_cxx::hashtable<std::pair<std::string const, boost::any>, std::string, __gnu_cxx::hash<std::string>, std::_Select1st<std::pair<std::string const, boost::any> >, std::equal_to<std::string>, std::allocator<boost::any> >::resize (this=0x1, __num_elements_hint=140727220186528) at /usr/include/c++/4.9/backward/hashtable.h:1055\n#14 0x00007f80de6376b8 in boost::archive::detail::save_pointer_type<boost::archive::xml_oarchive>::polymorphic::save<OMKey> (ar=..., t=...) at /usr/include/boost/archive/detail/oserializer.hpp:387\n#15 0x00007f80de637235 in boost::serialization::nvp<int const>::save<boost::archive::portable_binary_oarchive> (this=0x1958360, ar=...) at /usr/include/boost/serialization/nvp.hpp:74\n#16 0x00007f80de7692d0 in boost::python::detail::make_function_aux<bool (I3Tray::*)(std::string const&, std::string const&, std::string const&), boost::python::default_call_policies, boost::mpl::vector5<bool, I3Tray&, std::string const&, std::string const&, std::string const&>, mpl_::int_<0> > (f=\n    (bool (I3Tray::*)(I3Tray * const, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > &, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > &, const std::basic_string<char, std::char_traits<char>, std::allocator<char> > &)) 0x7f80cb302950, p=..., kw=...) at /usr/include/boost/python/make_function.hpp:46\n#17 0x00007f80de7674ee in boost::python::class_<I3Tray, boost::noncopyable_::noncopyable, boost::python::detail::not_specified, boost::python::detail::not_specified>::def_impl<I3Tray, I3Tray::param_setter (I3Tray::*)(std::string const&, std::string), boost::python::detail::def_helper<char const*, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified> > (this=0x7ffd9bf83150, name=0x16b9e88 \"\\024rc\u0780\\177\", \n    fn=NULL, helper=...) at /usr/include/boost/python/class.hpp:529\n#18 0x00007f80de76561d in I3Tray::SetParameter<std::vector<int, std::allocator<int> > > (\n    this=0x7f80de76561d <I3Tray::SetParameter<std::vector<int, std::allocator<int> > >(std::string const&, std::string const&, std::vector<int, std::allocator<int> > const&)+67>, \n    module=<error reading variable: Cannot access memory at address 0xffffffffffffffe9>, parameter=<error reading variable: Cannot access memory at address 0x1>, value=std::vector of length 35047862944671, capacity 5957535 = {...})\n    at ../../src/icetray/public/icetray/I3Tray.h:230\n#19 0x00007f80dd8cd78d in boost::python::objects::function::call(_object*, _object*) const () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0\n#20 0x00007f80dd8cd9a8 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0\n#21 0x00007f80dd8d7653 in boost::python::detail::exception_handler::operator()(boost::function0<void> const&) const () from /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.55.0\n#22 0x00007f80cf6d430e in boost::serialization::make_nvp<I3Particle> (name=0x7ffd9bf82fc0 \"\\020\\060\\370\\233\\375\\177\", t=...) at /usr/include/boost/serialization/nvp.hpp:97\n#23 0x00007ffd9bf83150 in ?? ()\n#24 0x00000000013e0860 in ?? ()\n#25 0x00000000013e0868 in ?? ()\n#26 0x00007ffd9bf82fc0 in ?? ()\n#27 0x00007f80cf6d42e0 in std::stack<unsigned int, std::deque<unsigned int, std::allocator<unsigned int> > >::push (this=0xc3c900000000b8ff, __x=@0xffff40b58948f07d: <error reading variable>) at /usr/include/c++/4.9/bits/stl_stack.h:190\nBacktrace stopped: previous frame inner to this frame (corrupt stack?)\n\n}}}", 
    "reporter": "nega", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1461860953266426", 
    "component": "combo reconstruction", 
    "summary": "[IceHive] tests gone wild!", 
    "priority": "normal", 
    "keywords": "icehive, tests, SIGPIPE, signal-handler, root", 
    "time": "2016-02-23T04:56:31", 
    "milestone": "Long-Term Future", 
    "owner": "mzoll", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160223T17:03:10: 
* nega changed owner from "" to "mzoll"
* nega changed status from "new" to "assigned"
* nega changed keywords from "" to "hivesplitter, tests, SIGPIPE, signal-handler, root"

**Comment by icecube-trac** [comment]
Trac update at 20160425T18:01:46: olivas commented:

> Please set a milestone.

**Comment by icecube-trac** [comment]
Trac update at 20160426T15:16:55: olivas changed milestone from "" to "Long-Term Future"

**Comment by icecube-trac** [comment]
Trac update at 20160428T13:51:21: 
* mzoll changed summary from "[HiveSplitter] tests gone wild!" to "[IceHive] tests gone wild!"
* mzoll commented:

> let's look into this

**Comment by icecube-trac** [comment]
Trac update at 20160428T14:19:05: 
* mzoll commented:

> Cannot reproduce this with the current trunk; disk IO issues?


* mzoll changed resolution from "" to "invalid"
* mzoll changed status from "assigned" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20160428T14:23:05: 
* nega changed status from "closed" to "reopened"
* nega changed resolution from "invalid" to ""
* nega commented:

> issue happens intermittently. might be able to reproduce by killing ctest and closing the terminal, allowing the test to run in the background w/o being attached to a terminal. or maybe by backgrounding the test, disowning it, and closing the terminal.

**Comment by icecube-trac** [comment]
Trac update at 20160428T14:27:31: mzoll commented:

> Sounds like a system issue to me then. I am not interacting with the system in any way except to read in a small txt-file from disc at the construction of the internal lookuptables and streaming an I3File (testdata) to compare to.

**Comment by icecube-trac** [comment]
Trac update at 20160428T14:29:22: mzoll commented:

> Despite, the test is currently enabled, and the bots do not show any trouble on this project or this test specifically :/

**Comment by icecube-trac** [comment]
Trac update at 20160428T15:16:33: 
* nega commented:

> Replying to [comment:7 mzoll]:
> > Sounds like a system issue to me then.
> 1) not a system issue. issue occurs on multiple OS X machines, and multiple Linux machines; including the bots
> 2) the bots wouldn't show this behavior as it requires running ps or top to find, and you don't have that kind of access on the bots
> 
> > I am not interacting with the system in any way except to read in a small txt-file from disc at the construction of the internal lookuptables and streaming an I3File (testdata) to compare to.
> I would suggest reading the backtrace again. Especially steps 0-4.


* nega changed _comment0 from:

> 1) not a system issue. issue occurs on multiple OS X machines, and multiple Linux machines; including the bots
> 2) the bots wouldn't show this behavior as it requires running ps or top to find, and you don't have that kind of access on the bots

to:

> 1461857222287349

**Comment by icecube-trac** [comment]
Trac update at 20160428T16:10:15: mzoll commented:

> I am sorry, the trace does not help me there: #1-#4 suggests file write access, which I do not do in my code

**Comment by icecube-trac** [comment]
Trac update at 20160428T16:28:18: 
* nega changed resolution from "" to "fixed"
* nega changed status from "reopened" to "closed"
* nega commented:

> fixed in r2466/IceTray

**Comment by icecube-trac** [comment]
Trac update at 20160428T16:29:13: nega changed keywords from "hivesplitter, tests, SIGPIPE, signal-handler, root" to "icehive, tests, SIGPIPE, signal-handler, root"
