### ISSUE TITLE
[DOMLauncher] tests gone wild! (Trac #1563)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1555]
see #1553 and #1554

```text
21246 ?        Rl   26420:41 python /home/nega/i3/combo/src/DOMLauncher/resources/test/LC-logicTest.py
```

```text
(gdb) bt
https://code.icecube.wisc.edu/ticket/0  0x00007f1f485ba4fd in write () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f1f4853cbff in _IO_new_file_write (f=0x7f1f48888640 <_IO_2_1_stderr_>, data=0x3f57140, n=55) at fileops.c:1251
#2  0x00007f1f4853d39f in new_do_write (to_do=55, data=0x3f57140 "\n *** Break *** write on a pipe with no one to read it\n", fp=0x7f1f48888640 <_IO_2_1_stderr_>) at fileops.c:506
#3  _IO_new_file_xsputn (f=0x7f1f48888640 <_IO_2_1_stderr_>, data=<optimized out>, n=55) at fileops.c:1330
#4  0x00007f1f48532488 in __GI__IO_fputs (str=0x3f57140 "\n *** Break *** write on a pipe with no one to read it\n", fp=0x7f1f48888640 <_IO_2_1_stderr_>) at iofputs.c:40
#5  0x00007f1f43c3a436 in DebugPrint(char const*, ...) () from /home/nega/i3/ports/root-v5.34.18/lib/libCore.so
#6  0x00007f1f43c3ad04 in DefaultErrorHandler(int, bool, char const*, char const*) () from /home/nega/i3/ports/root-v5.34.18/lib/libCore.so
#7  0x00007f1f43c3a66a in ErrorHandler () from /home/nega/i3/ports/root-v5.34.18/lib/libCore.so
#8  0x00007f1f43c3a97f in Break(char const*, char const*, ...) () from /home/nega/i3/ports/root-v5.34.18/lib/libCore.so
#9  0x00007f1f43cc9e2f in TUnixSystem::DispatchSignals(ESignals) () from /home/nega/i3/ports/root-v5.34.18/lib/libCore.so
#10 <signal handler called>
#11 0x00007f1f485ba4fd in write () at ../sysdeps/unix/syscall-template.S:81
#12 0x00007f1f4853cbff in _IO_new_file_write (f=0x7f1f48888640 <_IO_2_1_stderr_>, data=0x7f1f48c694dc, n=1) at fileops.c:1251
#13 0x00007f1f4853d39f in new_do_write (to_do=1, data=0x7f1f48c694dc ".", fp=0x7f1f48888640 <_IO_2_1_stderr_>) at fileops.c:506
#14 _IO_new_file_xsputn (f=0x7f1f48888640 <_IO_2_1_stderr_>, data=<optimized out>, n=1) at fileops.c:1330
#15 0x00007f1f48532b69 in __GI__IO_fwrite (buf=0x7f1f48c694dc, size=size@entry=1, count=1, fp=0x7f1f48888640 <_IO_2_1_stderr_>) at iofwrite.c:43
#16 0x0000000000551c02 in file_write.lto_priv () at ../Objects/fileobject.c:1852
#17 0x00000000004ccd05 in call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4035
#18 PyEval_EvalFrameEx () at ../Python/ceval.c:2681
#19 0x00000000004cd4e2 in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4121
#20 call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4056
#21 PyEval_EvalFrameEx () at ../Python/ceval.c:2681
#22 0x00000000004e7cc8 in PyEval_EvalCodeEx (closure=<optimized out>, defcount=<optimized out>, defs=<optimized out>, kwcount=<optimized out>, kws=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, 
    globals=<optimized out>, co=<optimized out>) at ../Python/ceval.c:3267
#23 function_call.lto_priv () at ../Objects/funcobject.c:526
#24 0x00000000004cf239 in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529
#25 ext_do_call (nk=<optimized out>, na=<optimized out>, flags=<optimized out>, pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4348
#26 PyEval_EvalFrameEx () at ../Python/ceval.c:2720
#27 0x00000000004e7cc8 in PyEval_EvalCodeEx (closure=<optimized out>, defcount=<optimized out>, defs=<optimized out>, kwcount=<optimized out>, kws=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, 
    globals=<optimized out>, co=<optimized out>) at ../Python/ceval.c:3267
#28 function_call.lto_priv () at ../Objects/funcobject.c:526
#29 0x000000000050b968 in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529
#30 instancemethod_call.lto_priv () at ../Objects/classobject.c:2602
#31 0x0000000000573bfd in PyObject_Call (kw=0x0, arg=
    (<TextTestResult(_original_stdout=<file at remote 0x7f1f48c9c150>, dots=True, skipped=[], _mirrorOutput=False, stream=<_WritelnDecorator(stream=<file at remote 0x7f1f48c9c1e0>) at remote 0x7f1f3954dad0>, testsRun=1, buffer=False, _original_stderr=<file at remote 0x7f1f48c9c1e0>, showAll=False, _stdout_buffer=None, _stderr_buffer=None, _moduleSetUpFailed=False, expectedFailures=[], errors=[], descriptions=True, _previousTestClass=<type at remote 0x10a0dc0>, unexpectedSuccesses=[], failures=[], _testRunEntered=True, shouldStop=False, failfast=False) at remote 0x7f1f3954de90>,), func=<instancemethod at remote 0x7f1f3bba9190>) at ../Objects/abstract.c:2529
#32 slot_tp_call.lto_priv () at ../Objects/typeobject.c:5449
#33 0x00000000004cd9ab in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529
#34 do_call (nk=<optimized out>, na=<optimized out>, pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4253
#35 call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4058
#36 PyEval_EvalFrameEx () at ../Python/ceval.c:2681
#37 0x00000000004e7cc8 in PyEval_EvalCodeEx (closure=<optimized out>, defcount=<optimized out>, defs=<optimized out>, kwcount=<optimized out>, kws=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, 
    globals=<optimized out>, co=<optimized out>) at ../Python/ceval.c:3267
#38 function_call.lto_priv () at ../Objects/funcobject.c:526
#39 0x00000000004cf239 in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529
#40 ext_do_call (nk=<optimized out>, na=<optimized out>, flags=<optimized out>, pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4348
#41 PyEval_EvalFrameEx () at ../Python/ceval.c:2720
#42 0x00000000004e7cc8 in PyEval_EvalCodeEx (closure=<optimized out>, defcount=<optimized out>, defs=<optimized out>, kwcount=<optimized out>, kws=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, 
    globals=<optimized out>, co=<optimized out>) at ../Python/ceval.c:3267
#43 function_call.lto_priv () at ../Objects/funcobject.c:526
#44 0x000000000050b968 in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529
#45 instancemethod_call.lto_priv () at ../Objects/classobject.c:2602
#46 0x0000000000573bfd in PyObject_Call (kw=0x0, 
    arg=(<TextTestResult(_original_stdout=<file at remote 0x7f1f48c9c150>, dots=True, skipped=[], _mirrorOutput=False, stream=<_WritelnDecorator(stream=<file at remote 0x7f1f48c9c1e0>) at remote 0x7f1f3954dad0>, testsRun=1, buffer=False, _original_stderr=<file at remote 0x7f1f48c9c1e0>, showAll=False, _stdout_buffer=None, _stderr_buffer=None, _moduleSetUpFailed=False, expectedFailures=[], errors=[], descriptions=True, _previousTestClass=<type at remote 0x10a0dc0>, unexpectedSuccesses=[], failures=[], _testRunEntered=True, shouldStop=False, failfast=False) at remote 0x7f1f3954de90>,), func=<instancemethod at remote 0x7f1f3bba9230>) at ../Objects/abstract.c:2529
#47 slot_tp_call.lto_priv () at ../Objects/typeobject.c:5449
#48 0x00000000004cd9ab in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529
#49 do_call (nk=<optimized out>, na=<optimized out>, pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4253
#50 call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4058
#51 PyEval_EvalFrameEx () at ../Python/ceval.c:2681
#52 0x00000000004cd4e2 in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4121
#53 call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4056
#54 PyEval_EvalFrameEx () at ../Python/ceval.c:2681
#55 0x00000000004e7cc8 in PyEval_EvalCodeEx (closure=<optimized out>, defcount=<optimized out>, defs=<optimized out>, kwcount=<optimized out>, kws=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, 
    globals=<optimized out>, co=<optimized out>) at ../Python/ceval.c:3267
#56 function_call.lto_priv () at ../Objects/funcobject.c:526
#57 0x000000000050b968 in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529
#58 instancemethod_call.lto_priv () at ../Objects/classobject.c:2602
#59 0x00000000004d437b in PyObject_Call (kw=<optimized out>, arg=(<I3Frame at remote 0x7f1f3954c398>,), func=<instancemethod at remote 0x7f1f3bba9140>) at ../Objects/abstract.c:2529
#60 PyEval_CallObjectWithKeywords () at ../Python/ceval.c:3904
#61 0x0000000000495b80 in PyEval_CallFunction (obj=<instancemethod at remote 0x7f1f3bba9140>, format=<optimized out>) at ../Python/modsupport.c:557
#62 0x00007f1f46b9bcd0 in boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast> >::clone_impl (this=0x6a8711e3b3cd6900, x=..., __in_chrg=<optimized out>, __vtt_parm=<optimized out>)
    at /usr/include/boost/exception/exception.hpp:446
#63 0x00007f1f46b99877 in std::_Deque_base<boost::shared_ptr<I3Frame>, std::allocator<boost::shared_ptr<I3Frame> > >::_M_destroy_nodes (this=0x7ffd571daa60, __nstart=0x1730df0, __nfinish=0x7ffd571daaa0)
    at /usr/include/c++/4.9/bits/stl_deque.h:647
#64 0x00007f1f46c0187b in PythonModule<I3Module>::Physics (this=0x6a8711e3b3cd6900, frame=...) at ../../src/icetray/private/icetray/PythonModule.cxx:249
#65 0x00007f1f46b8bcdf in boost::python::objects::make_ptr_instance<I3Context, boost::python::objects::pointer_holder<I3Context*, I3Context> >::get_class_object_impl<I3Context> (p=0x7ffd571daa80)
    at /usr/include/boost/python/object/make_ptr_instance.hpp:51
#66 0x00007ffd571dab80 in ?? ()
#67 0x0000000001730de8 in ?? ()
#68 0x0000000001730f80 in ?? ()
#69 0x0000000001730da0 in ?? ()
#70 0x00007ffd571daad0 in ?? ()
#71 0x6a8711e3b3cd6900 in ?? ()
#72 0x00007ffd571dab10 in ?? ()
#73 0x0000000001401000 in ?? ()
#74 0x00007ffd571dace0 in ?? ()
#75 0x00007f1f46b8537b in boost::function1<boost::shared_ptr<I3ServiceFactory>, I3Context const&>::function1 (this=0xd3ffd78948c68948, f=...) at /usr/include/boost/function/function_template.hpp:749
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

Migrated from https://code.icecube.wisc.edu/ticket/1563
```json
{
    "status": "closed", 
    "changetime": "2016-04-28T16:27:59", 
    "description": "see #1561 and #1562\n\n{{{\n21246 ?        Rl   26420:41 python /home/nega/i3/combo/src/DOMLauncher/resources/test/LC-logicTest.py\n}}}\n\n{{{\n(gdb) bt\n#0  0x00007f1f485ba4fd in write () at ../sysdeps/unix/syscall-template.S:81\n#1  0x00007f1f4853cbff in _IO_new_file_write (f=0x7f1f48888640 <_IO_2_1_stderr_>, data=0x3f57140, n=55) at fileops.c:1251\n#2  0x00007f1f4853d39f in new_do_write (to_do=55, data=0x3f57140 \"\\n *** Break *** write on a pipe with no one to read it\\n\", fp=0x7f1f48888640 <_IO_2_1_stderr_>) at fileops.c:506\n#3  _IO_new_file_xsputn (f=0x7f1f48888640 <_IO_2_1_stderr_>, data=<optimized out>, n=55) at fileops.c:1330\n#4  0x00007f1f48532488 in __GI__IO_fputs (str=0x3f57140 \"\\n *** Break *** write on a pipe with no one to read it\\n\", fp=0x7f1f48888640 <_IO_2_1_stderr_>) at iofputs.c:40\n#5  0x00007f1f43c3a436 in DebugPrint(char const*, ...) () from /home/nega/i3/ports/root-v5.34.18/lib/libCore.so\n#6  0x00007f1f43c3ad04 in DefaultErrorHandler(int, bool, char const*, char const*) () from /home/nega/i3/ports/root-v5.34.18/lib/libCore.so\n#7  0x00007f1f43c3a66a in ErrorHandler () from /home/nega/i3/ports/root-v5.34.18/lib/libCore.so\n#8  0x00007f1f43c3a97f in Break(char const*, char const*, ...) () from /home/nega/i3/ports/root-v5.34.18/lib/libCore.so\n#9  0x00007f1f43cc9e2f in TUnixSystem::DispatchSignals(ESignals) () from /home/nega/i3/ports/root-v5.34.18/lib/libCore.so\n#10 <signal handler called>\n#11 0x00007f1f485ba4fd in write () at ../sysdeps/unix/syscall-template.S:81\n#12 0x00007f1f4853cbff in _IO_new_file_write (f=0x7f1f48888640 <_IO_2_1_stderr_>, data=0x7f1f48c694dc, n=1) at fileops.c:1251\n#13 0x00007f1f4853d39f in new_do_write (to_do=1, data=0x7f1f48c694dc \".\", fp=0x7f1f48888640 <_IO_2_1_stderr_>) at fileops.c:506\n#14 _IO_new_file_xsputn (f=0x7f1f48888640 <_IO_2_1_stderr_>, data=<optimized out>, n=1) at fileops.c:1330\n#15 0x00007f1f48532b69 in __GI__IO_fwrite (buf=0x7f1f48c694dc, size=size@entry=1, count=1, fp=0x7f1f48888640 <_IO_2_1_stderr_>) at iofwrite.c:43\n#16 0x0000000000551c02 in file_write.lto_priv () at ../Objects/fileobject.c:1852\n#17 0x00000000004ccd05 in call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4035\n#18 PyEval_EvalFrameEx () at ../Python/ceval.c:2681\n#19 0x00000000004cd4e2 in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4121\n#20 call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4056\n#21 PyEval_EvalFrameEx () at ../Python/ceval.c:2681\n#22 0x00000000004e7cc8 in PyEval_EvalCodeEx (closure=<optimized out>, defcount=<optimized out>, defs=<optimized out>, kwcount=<optimized out>, kws=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, \n    globals=<optimized out>, co=<optimized out>) at ../Python/ceval.c:3267\n#23 function_call.lto_priv () at ../Objects/funcobject.c:526\n#24 0x00000000004cf239 in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529\n#25 ext_do_call (nk=<optimized out>, na=<optimized out>, flags=<optimized out>, pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4348\n#26 PyEval_EvalFrameEx () at ../Python/ceval.c:2720\n#27 0x00000000004e7cc8 in PyEval_EvalCodeEx (closure=<optimized out>, defcount=<optimized out>, defs=<optimized out>, kwcount=<optimized out>, kws=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, \n    globals=<optimized out>, co=<optimized out>) at ../Python/ceval.c:3267\n#28 function_call.lto_priv () at ../Objects/funcobject.c:526\n#29 0x000000000050b968 in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529\n#30 instancemethod_call.lto_priv () at ../Objects/classobject.c:2602\n#31 0x0000000000573bfd in PyObject_Call (kw=0x0, arg=\n    (<TextTestResult(_original_stdout=<file at remote 0x7f1f48c9c150>, dots=True, skipped=[], _mirrorOutput=False, stream=<_WritelnDecorator(stream=<file at remote 0x7f1f48c9c1e0>) at remote 0x7f1f3954dad0>, testsRun=1, buffer=False, _original_stderr=<file at remote 0x7f1f48c9c1e0>, showAll=False, _stdout_buffer=None, _stderr_buffer=None, _moduleSetUpFailed=False, expectedFailures=[], errors=[], descriptions=True, _previousTestClass=<type at remote 0x10a0dc0>, unexpectedSuccesses=[], failures=[], _testRunEntered=True, shouldStop=False, failfast=False) at remote 0x7f1f3954de90>,), func=<instancemethod at remote 0x7f1f3bba9190>) at ../Objects/abstract.c:2529\n#32 slot_tp_call.lto_priv () at ../Objects/typeobject.c:5449\n#33 0x00000000004cd9ab in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529\n#34 do_call (nk=<optimized out>, na=<optimized out>, pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4253\n#35 call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4058\n#36 PyEval_EvalFrameEx () at ../Python/ceval.c:2681\n#37 0x00000000004e7cc8 in PyEval_EvalCodeEx (closure=<optimized out>, defcount=<optimized out>, defs=<optimized out>, kwcount=<optimized out>, kws=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, \n    globals=<optimized out>, co=<optimized out>) at ../Python/ceval.c:3267\n#38 function_call.lto_priv () at ../Objects/funcobject.c:526\n#39 0x00000000004cf239 in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529\n#40 ext_do_call (nk=<optimized out>, na=<optimized out>, flags=<optimized out>, pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4348\n#41 PyEval_EvalFrameEx () at ../Python/ceval.c:2720\n#42 0x00000000004e7cc8 in PyEval_EvalCodeEx (closure=<optimized out>, defcount=<optimized out>, defs=<optimized out>, kwcount=<optimized out>, kws=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, \n    globals=<optimized out>, co=<optimized out>) at ../Python/ceval.c:3267\n#43 function_call.lto_priv () at ../Objects/funcobject.c:526\n#44 0x000000000050b968 in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529\n#45 instancemethod_call.lto_priv () at ../Objects/classobject.c:2602\n#46 0x0000000000573bfd in PyObject_Call (kw=0x0, \n    arg=(<TextTestResult(_original_stdout=<file at remote 0x7f1f48c9c150>, dots=True, skipped=[], _mirrorOutput=False, stream=<_WritelnDecorator(stream=<file at remote 0x7f1f48c9c1e0>) at remote 0x7f1f3954dad0>, testsRun=1, buffer=False, _original_stderr=<file at remote 0x7f1f48c9c1e0>, showAll=False, _stdout_buffer=None, _stderr_buffer=None, _moduleSetUpFailed=False, expectedFailures=[], errors=[], descriptions=True, _previousTestClass=<type at remote 0x10a0dc0>, unexpectedSuccesses=[], failures=[], _testRunEntered=True, shouldStop=False, failfast=False) at remote 0x7f1f3954de90>,), func=<instancemethod at remote 0x7f1f3bba9230>) at ../Objects/abstract.c:2529\n#47 slot_tp_call.lto_priv () at ../Objects/typeobject.c:5449\n#48 0x00000000004cd9ab in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529\n#49 do_call (nk=<optimized out>, na=<optimized out>, pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4253\n#50 call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4058\n#51 PyEval_EvalFrameEx () at ../Python/ceval.c:2681\n#52 0x00000000004cd4e2 in fast_function (nk=<optimized out>, na=<optimized out>, n=<optimized out>, pp_stack=<optimized out>, func=<optimized out>) at ../Python/ceval.c:4121\n#53 call_function (oparg=<optimized out>, pp_stack=<optimized out>) at ../Python/ceval.c:4056\n#54 PyEval_EvalFrameEx () at ../Python/ceval.c:2681\n#55 0x00000000004e7cc8 in PyEval_EvalCodeEx (closure=<optimized out>, defcount=<optimized out>, defs=<optimized out>, kwcount=<optimized out>, kws=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=<optimized out>, \n    globals=<optimized out>, co=<optimized out>) at ../Python/ceval.c:3267\n#56 function_call.lto_priv () at ../Objects/funcobject.c:526\n#57 0x000000000050b968 in PyObject_Call (kw=<optimized out>, arg=<optimized out>, func=<optimized out>) at ../Objects/abstract.c:2529\n#58 instancemethod_call.lto_priv () at ../Objects/classobject.c:2602\n#59 0x00000000004d437b in PyObject_Call (kw=<optimized out>, arg=(<I3Frame at remote 0x7f1f3954c398>,), func=<instancemethod at remote 0x7f1f3bba9140>) at ../Objects/abstract.c:2529\n#60 PyEval_CallObjectWithKeywords () at ../Python/ceval.c:3904\n#61 0x0000000000495b80 in PyEval_CallFunction (obj=<instancemethod at remote 0x7f1f3bba9140>, format=<optimized out>) at ../Python/modsupport.c:557\n#62 0x00007f1f46b9bcd0 in boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast> >::clone_impl (this=0x6a8711e3b3cd6900, x=..., __in_chrg=<optimized out>, __vtt_parm=<optimized out>)\n    at /usr/include/boost/exception/exception.hpp:446\n#63 0x00007f1f46b99877 in std::_Deque_base<boost::shared_ptr<I3Frame>, std::allocator<boost::shared_ptr<I3Frame> > >::_M_destroy_nodes (this=0x7ffd571daa60, __nstart=0x1730df0, __nfinish=0x7ffd571daaa0)\n    at /usr/include/c++/4.9/bits/stl_deque.h:647\n#64 0x00007f1f46c0187b in PythonModule<I3Module>::Physics (this=0x6a8711e3b3cd6900, frame=...) at ../../src/icetray/private/icetray/PythonModule.cxx:249\n#65 0x00007f1f46b8bcdf in boost::python::objects::make_ptr_instance<I3Context, boost::python::objects::pointer_holder<I3Context*, I3Context> >::get_class_object_impl<I3Context> (p=0x7ffd571daa80)\n    at /usr/include/boost/python/object/make_ptr_instance.hpp:51\n#66 0x00007ffd571dab80 in ?? ()\n#67 0x0000000001730de8 in ?? ()\n#68 0x0000000001730f80 in ?? ()\n#69 0x0000000001730da0 in ?? ()\n#70 0x00007ffd571daad0 in ?? ()\n#71 0x6a8711e3b3cd6900 in ?? ()\n#72 0x00007ffd571dab10 in ?? ()\n#73 0x0000000001401000 in ?? ()\n#74 0x00007ffd571dace0 in ?? ()\n#75 0x00007f1f46b8537b in boost::function1<boost::shared_ptr<I3ServiceFactory>, I3Context const&>::function1 (this=0xd3ffd78948c68948, f=...) at /usr/include/boost/function/function_template.hpp:749\nBacktrace stopped: previous frame inner to this frame (corrupt stack?)\n}}}", 
    "reporter": "nega", 
    "cc": "sflis", 
    "resolution": "fixed", 
    "_ts": "1461860879759677", 
    "component": "combo simulation", 
    "summary": "[DOMLauncher] tests gone wild!", 
    "priority": "normal", 
    "keywords": "domlauncher, tests, SIGPIPE, signal-handler, root", 
    "time": "2016-02-23T05:00:46", 
    "milestone": "", 
    "owner": "cweaver", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160223T05:47:06: nega commented:

> The test works w/ a root-less build
> 
> 
> ```text
> [zinc:~/i3/combo/build] ./env-shell.sh python /home/nega/i3/combo/src/DOMLauncher/resources/test/LC-logicTest.py
> DEBUG (I3Tray): setting testy (Streams => [icetray.I3Frame.DAQ]) in config record (I3Tray.cxx:554 in bool I3Tray::SetParameter(const string&, const string&, boost::python::api::object))
> INFO (I3Module): Prefixing with filename/url /home/nega/i3/ports/test-data/sim/GeoCalibDetectorStatus_IC86.55697_corrected_V2.i3.gz (I3InfiniteSource.cxx:55 in virtual void I3InfiniteSource::Configure())
> DEBUG (icetray): Opened file /home/nega/i3/ports/test-data/sim/GeoCalibDetectorStatus_IC86.55697_corrected_V2.i3.gz (open.cxx:611 in void I3::dataio::open(boost::iostreams::filtering_istream&, const string&))
> DEBUG (I3Module): Opened file /home/nega/i3/ports/test-data/sim/GeoCalibDetectorStatus_IC86.55697_corrected_V2.i3.gz (I3InfiniteSource.cxx:66 in virtual void I3InfiniteSource::Configure())
> DEBUG (I3Tray): connecting outbox "OutBox" on module "FrameMaker" to module "testy" (I3Tray.cxx:306 in bool I3Tray::ConnectBoxes(const string&, const string&, const string&))
> DEBUG (I3Tray): connecting outbox "OutBox" on module "testy" to module "end" (I3Tray.cxx:306 in bool I3Tray::ConnectBoxes(const string&, const string&, const string&))
> DEBUG (I3Tray): Driving module is FrameMaker (I3Tray.cxx:412 in void I3Tray::Configure())
> ..
> ----------------------------------------------------------------------
> Ran 2 tests in 12.837s
> 
> OK
> NOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:473 in void I3Tray::Execute(unsigned int))
> [zinc:~/i3/combo/build]
> ```

**Comment by icecube-trac** [comment]
Trac update at 20160223T17:02:35: 
* nega changed cc from "" to "sflis"
* nega changed status from "new" to "assigned"
* nega changed keywords from "" to "domlauncher, tests, SIGPIPE, signal-handler, root"
* nega changed owner from "" to "cweaver"

**Comment by icecube-trac** [comment]
Trac update at 20160223T19:14:55: cweaver commented:

> I cannot reproduce this crash with the current trunk in a build on cobalt linked against py2-v1 in CVMFS and using ROOT.

**Comment by icecube-trac** [comment]
Trac update at 20160425T18:01:46: olivas commented:

> Please set a milestone.

**Comment by icecube-trac** [comment]
Trac update at 20160426T15:16:17: 
* olivas changed resolution from "" to "worksforme"
* olivas changed status from "assigned" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20160428T15:37:56: 
* nega changed status from "closed" to "reopened"
* nega changed resolution from "worksforme" to ""
* nega commented:

> 1) not a crash. read the first block again, which is output from `ps xa`. tests should not run for 18 days.

**Comment by icecube-trac** [comment]
Trac update at 20160428T15:48:39: cweaver commented:

> Like the rest of the tickets in this family, it is highly unclear that this has anything to do with the code in DOMLauncher or its tests. (Particularly since apparently the presence of ROOT controls the problem, and DOMLauncher does not intentionally use ROOT.) Also, since no one else seems to be able to reproduce the issue, there isn't much we can do without more investigation from the reporter.

**Comment by icecube-trac** [comment]
Trac update at 20160428T16:27:59: 
* nega changed resolution from "" to "fixed"
* nega changed status from "reopened" to "closed"
* nega commented:

> fixed in r2466/IceTray
