### ISSUE TITLE
[CoincSuite] tests gone wild! (Trac #1565)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1557]
See #1553, #1554, #1555.

```text
  580 ?        R    221865:25 python /build/buildslave/yaoguai_cvmfs/coverage/source/CoincSuite/resources/test/AfterpulseTest.py
```

Backtrace isn't helpful

```text
(gdb) bt
https://code.icecube.wisc.edu/ticket/0  0x00002abc8274cfd0 in write () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00002abc826df813 in _IO_file_write () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00002abc826df6da in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00002abc826e018e in _IO_file_xsputn () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00002abc826d557d in fputs () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00002abc87908f16 in DebugPrint(char const*, ...) () from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_12_x86_64/i3ports/root-v5.34.18/lib/libCore.so
#6  0x00002abc879090bc in DefaultErrorHandler(int, bool, char const*, char const*) () from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_12_x86_64/i3ports/root-v5.34.18/lib/libCore.so
#7  0x00002abc879095da in ErrorHandler () from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_12_x86_64/i3ports/root-v5.34.18/lib/libCore.so
#8  0x00002abc87909892 in Break(char const*, char const*, ...) () from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_12_x86_64/i3ports/root-v5.34.18/lib/libCore.so
#9  0x00002abc879c77bf in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_12_x86_64/i3ports/root-v5.34.18/lib/libCore.so
#10 <signal handler called>
#11 0x00002abc8274cfd0 in write () from /lib/x86_64-linux-gnu/libc.so.6
#12 0x00002abc826df813 in _IO_file_write () from /lib/x86_64-linux-gnu/libc.so.6
#13 0x00002abc826df6da in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#14 0x00002abc826e018e in _IO_file_xsputn () from /lib/x86_64-linux-gnu/libc.so.6
#15 0x00002abc826d557d in fputs () from /lib/x86_64-linux-gnu/libc.so.6
#16 0x00002abc820cc08e in PyFile_WriteString (s=0x2abc821c1d00 "Traceback (most recent call last):\n", f=0x2abc8314d1e0) at Objects/fileobject.c:2638
#17 0x00002abc8217cac0 in PyTraceBack_Print (v=0x2abc8d4d28c0, f=0x2abc8314d1e0) at Python/traceback.c:279
#18 0x00002abc82172aa3 in PyErr_Display (exception=0x2abc823f7de0, value=0x2abc8d4d2908, tb=0x2abc8d4d28c0) at Python/pythonrun.c:1240
#19 0x00002abc8217a40c in sys_excepthook (self=<optimized out>, args=<optimized out>) at Python/sysmodule.c:138
#20 0x00002abc820ab503 in PyObject_Call (func=0x2abc831680e0, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2529
#21 0x00002abc821498c7 in PyEval_CallObjectWithKeywords (func=0x2abc831680e0, arg=0x2abc83a2c370, kw=<optimized out>) at Python/ceval.c:3902
#22 0x00002abc82173dee in PyErr_PrintEx (set_sys_last_vars=<optimized out>) at Python/pythonrun.c:1186
#23 0x00002abc821743be in PyRun_SimpleFileExFlags (fp=<optimized out>, filename=<optimized out>, closeit=1, flags=0x7ffd712ef250) at Python/pythonrun.c:959
#24 0x00002abc821877ec in Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:640
#25 0x00002abc8268876d in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#26 0x0000000000400661 in _start ()
```

Migrated from https://code.icecube.wisc.edu/ticket/1565
```json
{
    "status": "closed", 
    "changetime": "2016-05-04T18:38:11", 
    "description": "See #1561, #1562, #1563.\n\n{{{\n  580 ?        R    221865:25 python /build/buildslave/yaoguai_cvmfs/coverage/source/CoincSuite/resources/test/AfterpulseTest.py\n}}}\n\nBacktrace isn't helpful\n\n{{{\n(gdb) bt\n#0  0x00002abc8274cfd0 in write () from /lib/x86_64-linux-gnu/libc.so.6\n#1  0x00002abc826df813 in _IO_file_write () from /lib/x86_64-linux-gnu/libc.so.6\n#2  0x00002abc826df6da in ?? () from /lib/x86_64-linux-gnu/libc.so.6\n#3  0x00002abc826e018e in _IO_file_xsputn () from /lib/x86_64-linux-gnu/libc.so.6\n#4  0x00002abc826d557d in fputs () from /lib/x86_64-linux-gnu/libc.so.6\n#5  0x00002abc87908f16 in DebugPrint(char const*, ...) () from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_12_x86_64/i3ports/root-v5.34.18/lib/libCore.so\n#6  0x00002abc879090bc in DefaultErrorHandler(int, bool, char const*, char const*) () from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_12_x86_64/i3ports/root-v5.34.18/lib/libCore.so\n#7  0x00002abc879095da in ErrorHandler () from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_12_x86_64/i3ports/root-v5.34.18/lib/libCore.so\n#8  0x00002abc87909892 in Break(char const*, char const*, ...) () from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_12_x86_64/i3ports/root-v5.34.18/lib/libCore.so\n#9  0x00002abc879c77bf in TUnixSystem::DispatchSignals(ESignals) () from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_12_x86_64/i3ports/root-v5.34.18/lib/libCore.so\n#10 <signal handler called>\n#11 0x00002abc8274cfd0 in write () from /lib/x86_64-linux-gnu/libc.so.6\n#12 0x00002abc826df813 in _IO_file_write () from /lib/x86_64-linux-gnu/libc.so.6\n#13 0x00002abc826df6da in ?? () from /lib/x86_64-linux-gnu/libc.so.6\n#14 0x00002abc826e018e in _IO_file_xsputn () from /lib/x86_64-linux-gnu/libc.so.6\n#15 0x00002abc826d557d in fputs () from /lib/x86_64-linux-gnu/libc.so.6\n#16 0x00002abc820cc08e in PyFile_WriteString (s=0x2abc821c1d00 \"Traceback (most recent call last):\\n\", f=0x2abc8314d1e0) at Objects/fileobject.c:2638\n#17 0x00002abc8217cac0 in PyTraceBack_Print (v=0x2abc8d4d28c0, f=0x2abc8314d1e0) at Python/traceback.c:279\n#18 0x00002abc82172aa3 in PyErr_Display (exception=0x2abc823f7de0, value=0x2abc8d4d2908, tb=0x2abc8d4d28c0) at Python/pythonrun.c:1240\n#19 0x00002abc8217a40c in sys_excepthook (self=<optimized out>, args=<optimized out>) at Python/sysmodule.c:138\n#20 0x00002abc820ab503 in PyObject_Call (func=0x2abc831680e0, arg=<optimized out>, kw=<optimized out>) at Objects/abstract.c:2529\n#21 0x00002abc821498c7 in PyEval_CallObjectWithKeywords (func=0x2abc831680e0, arg=0x2abc83a2c370, kw=<optimized out>) at Python/ceval.c:3902\n#22 0x00002abc82173dee in PyErr_PrintEx (set_sys_last_vars=<optimized out>) at Python/pythonrun.c:1186\n#23 0x00002abc821743be in PyRun_SimpleFileExFlags (fp=<optimized out>, filename=<optimized out>, closeit=1, flags=0x7ffd712ef250) at Python/pythonrun.c:959\n#24 0x00002abc821877ec in Py_Main (argc=<optimized out>, argv=<optimized out>) at Modules/main.c:640\n#25 0x00002abc8268876d in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6\n#26 0x0000000000400661 in _start ()\n}}}", 
    "reporter": "nega", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1462387091357477", 
    "component": "combo reconstruction", 
    "summary": "[CoincSuite] tests gone wild!", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2016-02-24T16:58:54", 
    "milestone": "Long-Term Future", 
    "owner": "mzoll", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160425T18:01:46: olivas commented:

> Please set a milestone.

**Comment by icecube-trac** [comment]
Trac update at 20160426T15:16:41: olivas changed milestone from "" to "Long-Term Future"

**Comment by icecube-trac** [comment]
Trac update at 20160504T18:38:11: 
* nega commented:

> fixed in r2466/IceTray


* nega changed status from "new" to "closed"
* nega changed resolution from "" to "fixed"
