### ISSUE TITLE
I3Db: all test/scripts failing (Trac #161)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#161]
Since the I3Db update for noiseRate/relativeDomEff, I3Db is now going log_fatal on older dates than IC59 times:

./I3Db/resources/scripts/dump_db_nofile.py

FATAL: I3DbCalibrationService: Calibration Start Date (Tue May 19 23:38:00 2009
) later than End Date (Tue May 19 23:38:00 2009
)- ?!?
Traceback (most recent call last):
  File "./I3Db/resources/scripts/dump_db_nofile.py", line 77, in <module>
    tray.Execute(4)
  File "/data/i3home/blaufuss/icework/offline-software/trunk/build_release/lib/I3Tray.py", line 72, in Execute
    args[0].the_tray.Execute(args[1])
RuntimeError: I3DbCalibrationService: Calibration Start Date (Tue May 19 23:38:00 2009
) later than End Date (Tue May 19 23:38:00 2009
)- ?!?

This GCD file should be from 2007.  It seems the date is getting set by the new tables when the these values don't exist. 

For earlier years than IC59, can the std noise rate for "std" doms of 480 Hz

Migrated from https://code.icecube.wisc.edu/ticket/161
```json
{
    "status": "closed", 
    "changetime": "2014-11-23T03:37:56", 
    "description": "Since the I3Db update for noiseRate/relativeDomEff, I3Db is now going log_fatal on older dates than IC59 times:\n\n./I3Db/resources/scripts/dump_db_nofile.py\n\nFATAL: I3DbCalibrationService: Calibration Start Date (Tue May 19 23:38:00 2009\n) later than End Date (Tue May 19 23:38:00 2009\n)- ?!?\nTraceback (most recent call last):\n  File \"./I3Db/resources/scripts/dump_db_nofile.py\", line 77, in <module>\n    tray.Execute(4)\n  File \"/data/i3home/blaufuss/icework/offline-software/trunk/build_release/lib/I3Tray.py\", line 72, in Execute\n    args[0].the_tray.Execute(args[1])\nRuntimeError: I3DbCalibrationService: Calibration Start Date (Tue May 19 23:38:00 2009\n) later than End Date (Tue May 19 23:38:00 2009\n)- ?!?\n\nThis GCD file should be from 2007.  It seems the date is getting set by the new tables when the these values don't exist. \n\nFor earlier years than IC59, can the std noise rate for \"std\" doms of 480 Hz", 
    "reporter": "blaufuss", 
    "cc": "kohnen@umh.ac.be", 
    "resolution": "fixed", 
    "_ts": "1416713876862109", 
    "component": "combo core", 
    "summary": "I3Db: all test/scripts failing", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2009-06-12T20:10:07", 
    "milestone": "", 
    "owner": "kohnen", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20090612T20:39:46: blaufuss changed milestone from "offline-v3" to "v3-bugsquash"

**Comment by icecube-trac** [comment]
Trac update at 20090618T11:08:06: 
* kohnen changed cc from "" to "kohnen@umh.ac.be"
* kohnen changed resolution from "" to "fixed"
* kohnen changed status from "new" to "closed"
* kohnen commented:

> Fixed at Rev. 55941

**Comment by icecube-trac** [comment]
Trac update at 20141123T03:37:56: 
* olivas commented:

> Milestone v3-bugsquash deleted


* olivas changed milestone from "v3-bugsquash" to ""
