### ISSUE TITLE
[dst] Tests fail (Trac #1619)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1611]
Likely forgot to check-in dsttest.

        Start 177: dst::dst13.py
177/422 Test #177: dst::dst13.py ..................................................***Failed    1.16 sec
Traceback (most recent call last):
  File "/build/buildslave/avnas/Fedora_20/source/dst/resources/test/dst13.py", line 14, in <module>
    from icecube.dst.dsttest import CheckFrameIndex
ImportError: No module named dsttest

        Start 178: dst::dst16.py
178/422 Test #178: dst::dst16.py ..................................................***Failed    1.17 sec
Traceback (most recent call last):
  File "/build/buildslave/avnas/Fedora_20/source/dst/resources/test/dst16.py", line 13, in <module>
    from icecube.dst.dsttest import CheckFrameIndex
ImportError: No module named dsttest

Migrated from https://code.icecube.wisc.edu/ticket/1619
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:11:57", 
    "description": "Likely forgot to check-in dsttest.\n\n        Start 177: dst::dst13.py\n177/422 Test #177: dst::dst13.py ..................................................***Failed    1.16 sec\nTraceback (most recent call last):\n  File \"/build/buildslave/avnas/Fedora_20/source/dst/resources/test/dst13.py\", line 14, in <module>\n    from icecube.dst.dsttest import CheckFrameIndex\nImportError: No module named dsttest\n\n        Start 178: dst::dst16.py\n178/422 Test #178: dst::dst16.py ..................................................***Failed    1.17 sec\nTraceback (most recent call last):\n  File \"/build/buildslave/avnas/Fedora_20/source/dst/resources/test/dst16.py\", line 13, in <module>\n    from icecube.dst.dsttest import CheckFrameIndex\nImportError: No module named dsttest", 
    "reporter": "olivas", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1550067117911749", 
    "component": "combo reconstruction", 
    "summary": "[dst] Tests fail", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2016-04-02T14:35:16", 
    "milestone": "", 
    "owner": "juancarlos", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160402T14:45:36: 
* juancarlos commented:

> commit 144189 fixes this. Module was not imported to svn.


* juancarlos changed status from "new" to "closed"
* juancarlos changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:11:57: 
* olivas changed milestone from "IceRec V5" to ""
* olivas commented:

> Milestone IceRec V5 deleted
