### ISSUE TITLE
[steamshovel] Test failure (Trac #1718)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1710]
```text
    Start 353: steamshovel::test_shovelscripts.py
6/6 Test #352: steamshovel::test_shovelscripts.py ...............***Failed   12.77 sec
...F.
======================================================================
FAIL: test_particles_artist_draws_tracks (__main__.TestShovelScripts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/olivas/icecube/combo/src/steamshovel/resources/test/test_shovelscripts.py", line 79, in test_particles_artist_draws_tracks
    self.assertImage( name + ".png", 35 )
  File "/home/olivas/icecube/combo/src/steamshovel/resources/test/test_shovelscripts.py", line 46, in assertImage
    self.assertGreater(psnr, threshold)
AssertionError: 29.780892595095874 not greater than 35

----------------------------------------------------------------------
```

Migrated from https://code.icecube.wisc.edu/ticket/1718
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:13:10", 
    "description": "{{{\n    Start 353: steamshovel::test_shovelscripts.py\n6/6 Test #353: steamshovel::test_shovelscripts.py ...............***Failed   12.77 sec\n...F.\n======================================================================\nFAIL: test_particles_artist_draws_tracks (__main__.TestShovelScripts)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/home/olivas/icecube/combo/src/steamshovel/resources/test/test_shovelscripts.py\", line 79, in test_particles_artist_draws_tracks\n    self.assertImage( name + \".png\", 35 )\n  File \"/home/olivas/icecube/combo/src/steamshovel/resources/test/test_shovelscripts.py\", line 46, in assertImage\n    self.assertGreater(psnr, threshold)\nAssertionError: 29.780892595095874 not greater than 35\n\n----------------------------------------------------------------------\n}}}", 
    "reporter": "olivas", 
    "cc": "david.schultz", 
    "resolution": "fixed", 
    "_ts": "1550067190995086", 
    "component": "combo core", 
    "summary": "[steamshovel] Test failure", 
    "priority": "major", 
    "keywords": "steamshovel X11", 
    "time": "2016-05-31T17:49:41", 
    "milestone": "", 
    "owner": "hdembinski", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160608T19:20:59: 
* hdembinski commented:

> testcase


* hdembinski changed attachment from "" to "particles_artist_draws_tracks.png"

**Comment by icecube-trac** [comment]
Trac update at 20160608T19:21:56: 
* hdembinski changed attachment from "" to "particles_artist_draws_tracks.2.png"
* hdembinski commented:

> reference

**Comment by icecube-trac** [comment]
Trac update at 20160608T19:24:00: hdembinski commented:

> the test fails, because the image tested is produced with different "sharpness" on different systems, see attachments. we need to find a measure of distance which is robust against such smoothing artifacts.

**Comment by icecube-trac** [comment]
Trac update at 20160608T19:27:02: hdembinski changed type from "rumor / allegation" to "defect"

**Comment by icecube-trac** [comment]
Trac update at 20160608T19:28:12: 
* david.schultz changed type from "defect" to "rumor / allegation"
* david.schultz changed cc from "" to "david.schultz"

**Comment by icecube-trac** [comment]
Trac update at 20160608T19:28:36: david.schultz changed type from "rumor / allegation" to "defect"

**Comment by icecube-trac** [comment]
Trac update at 20160608T19:30:34: hdembinski commented:

> possibly relevant:
> http://stackoverflow.com/questions/843972/image-comparison-fast-algorithmhttps://code.icecube.wisc.edu/ticket/844113

**Comment by icecube-trac** [comment]
Trac update at 20160608T19:46:13: david.schultz changed description from:

>     Start 353: steamshovel::test_shovelscripts.py
> 6/6 Test #353: steamshovel::test_shovelscripts.py ...............***Failed   12.77 sec
> ...F.
> ======================================================================
> FAIL: test_particles_artist_draws_tracks (__main__.TestShovelScripts)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/olivas/icecube/combo/src/steamshovel/resources/test/test_shovelscripts.py", line 79, in test_particles_artist_draws_tracks
>     self.assertImage( name + ".png", 35 )
>   File "/home/olivas/icecube/combo/src/steamshovel/resources/test/test_shovelscripts.py", line 46, in assertImage
>     self.assertGreater(psnr, threshold)
> AssertionError: 29.780892595095874 not greater than 35
> 
> ----------------------------------------------------------------------
> 

to:

> {{{
>     Start 353: steamshovel::test_shovelscripts.py
> 6/6 Test #353: steamshovel::test_shovelscripts.py ...............***Failed   12.77 sec
> ...F.
> ======================================================================
> FAIL: test_particles_artist_draws_tracks (__main__.TestShovelScripts)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/olivas/icecube/combo/src/steamshovel/resources/test/test_shovelscripts.py", line 79, in test_particles_artist_draws_tracks
>     self.assertImage( name + ".png", 35 )
>   File "/home/olivas/icecube/combo/src/steamshovel/resources/test/test_shovelscripts.py", line 46, in assertImage
>     self.assertGreater(psnr, threshold)
> AssertionError: 29.780892595095874 not greater than 35
> 
> ----------------------------------------------------------------------
> }}}

**Comment by icecube-trac** [comment]
Trac update at 20160608T19:48:08: hdembinski commented:

> also possibly relevant:
> http://pdiff.sourceforge.net/

**Comment by icecube-trac** [comment]
Trac update at 20160608T19:48:26: david.schultz commented:

> if we're only generating a very simple shape, we can probably use object recognition to detect it. that should be much more robust than comparing pixels, and should work even with different size images. it also doesn't rely on a reference image.

**Comment by icecube-trac** [comment]
Trac update at 20160609T14:29:46: olivas commented:

> Looks like a new failure : http://builds.icecube.wisc.edu/builders/Ubuntu%2016.04/builds/93/steps/test_2/logs/stdio

**Comment by icecube-trac** [comment]
Trac update at 20160609T14:46:44: 
* olivas changed priority from "normal" to "major"
* olivas changed milestone from "" to "June 2016"

**Comment by icecube-trac** [comment]
Trac update at 20160609T15:11:52: 
* nega changed priority from "major" to "normal"
* nega changed milestone from "June 2016" to "July 2016"
* nega commented:

> It's a new test. It's going to fail a lot.


* nega changed keywords from "" to "steamshovel X11"

**Comment by icecube-trac** [comment]
Trac update at 20160609T15:32:52: 
* olivas changed priority from "normal" to "major"
* olivas commented:

> Replying to [comment:11 nega]:
> > It's a new test. It's going to fail a lot.
> It makes absolutely no sense that because a test is new that it will therefore fail a lot.
> 
> Tests that cause bots to fail are not "normal" priority.

**Comment by icecube-trac** [comment]
Trac update at 20160610T13:39:04: 
* hdembinski changed status from "new" to "closed"
* hdembinski changed resolution from "" to "fixed"
* hdembinski commented:

> it turns out that mimicking human visual perception is hard. check thresholds have been hand-tuned to not cause failures.

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:13:10: 
* olivas changed milestone from "July 2016" to ""
* olivas commented:

> Milestone July 2016 deleted
