### ISSUE TITLE
[tableio] named argument in class declaration (Trac #1733)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1725]
The sphinx build gives the following error:

```text
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/tableio/enum3.py", line 43
    class enum(baseEnum, metaclass=metaEnum):
                                  ^
SyntaxError: invalid syntax
```

Migrated from https://code.icecube.wisc.edu/ticket/1733
```json
{
    "status": "closed", 
    "changetime": "2016-06-10T16:08:49", 
    "description": "The sphinx build gives the following error:\n{{{\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/tableio/enum3.py\", line 43\n    class enum(baseEnum, metaclass=metaEnum):\n                                  ^\nSyntaxError: invalid syntax\n}}}\n", 
    "reporter": "kjmeagher", 
    "cc": "", 
    "resolution": "duplicate", 
    "_ts": "1465574929009082", 
    "component": "cmake", 
    "summary": "[tableio] named argument in class declaration", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2016-06-10T07:25:28", 
    "milestone": "Long-Term Future", 
    "owner": "jvansanten", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160610T16:08:49: 
* kjmeagher changed resolution from "" to "duplicate"
* kjmeagher commented:

> duplicate of #1726


* kjmeagher changed status from "new" to "closed"
