### ISSUE TITLE
[tableio] named argument in class declaration (Trac #1734)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1726]
The sphinx build gives the following error:

```text
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/tableio/enum3.py", line 43
    class enum(baseEnum, metaclass=metaEnum):
                                  ^
SyntaxError: invalid syntax
```

Migrated from https://code.icecube.wisc.edu/ticket/1734
```json
{
    "status": "closed", 
    "changetime": "2016-06-10T08:01:03", 
    "description": "The sphinx build gives the following error:\n{{{\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/tableio/enum3.py\", line 43\n    class enum(baseEnum, metaclass=metaEnum):\n                                  ^\nSyntaxError: invalid syntax\n}}}\n", 
    "reporter": "kjmeagher", 
    "cc": "", 
    "resolution": "wontfix", 
    "_ts": "1465545663829039", 
    "component": "cmake", 
    "summary": "[tableio] named argument in class declaration", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2016-06-10T07:25:29", 
    "milestone": "Long-Term Future", 
    "owner": "jvansanten", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160610T08:01:03: 
* jvansanten commented:

> This is sphinx-apidoc trying to load a py3 compatibility shim. Unless there's a way to make sphinx-apidoc ignore specific submodules, there's no way to fix this and still maintain py2/py3 compatibility.


* jvansanten changed status from "new" to "closed"
* jvansanten changed resolution from "" to "wontfix"
