### ISSUE TITLE
[Steamshovel] artists python files don't like being called on their own which confuses the documentation (Trac #1736)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1728]
It is not clear to me exactly how steamshovel loads these artist files but it causes problems with sphinx documentation. These can be tested by running the file directly for example calling `python ${I3_SRC}/CommonVariables/python/artists/direct_hits.py` instead of calling sphinx and it gets the same result.

* common_variables/artists/direct_hits.py
* common_variables/artists/hit_multiplicity.py
* common_variables/artists/hit_statistics.py
* common_variables/artists/track_characteristics.py
* millipede/artists.py
* steamshovel/artists/LEDPowerHouse.py
* steamshovel/artists/ParticleUncertainty.py
* steamshovel/sessions/IT73.py
* steamshovel/sessions/Minimum.py

Full error messages below

```text
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.common_variables.artists.rst:15: WARNING: autodoc: failed to import module u'icecube.common_variables.artists.direct_hits'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/direct_hits.py", line 5, in <module>
    class I3DirectHitsValues(PyArtist):
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/direct_hits.py", line 10, in I3DirectHitsValues
    requiredTypes = [ direct_hits.I3DirectHitsValues ]
AttributeError: 'module' object has no attribute 'I3DirectHitsValues'
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.common_variables.artists.rst:23: WARNING: autodoc: failed to import module u'icecube.common_variables.artists.hit_multiplicity'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/hit_multiplicity.py", line 4, in <module>
    class I3HitMultiplicityValues(PyArtist):
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/hit_multiplicity.py", line 9, in I3HitMultiplicityValues
    requiredTypes = [ hit_multiplicity.I3HitMultiplicityValues ]
AttributeError: 'module' object has no attribute 'I3HitMultiplicityValues'
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.common_variables.artists.rst:31: WARNING: autodoc: failed to import module u'icecube.common_variables.artists.hit_statistics'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/hit_statistics.py", line 5, in <module>
    class I3HitStatisticsValues(PyArtist):
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/hit_statistics.py", line 10, in I3HitStatisticsValues
    requiredTypes = [ hit_statistics.I3HitStatisticsValues ]
AttributeError: 'module' object has no attribute 'I3HitStatisticsValues'
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.common_variables.artists.rst:39: WARNING: autodoc: failed to import module u'icecube.common_variables.artists.track_characteristics'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/track_characteristics.py", line 5, in <module>
    class I3TrackCharacteristicsValues(PyArtist):
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/track_characteristics.py", line 10, in I3TrackCharacteristicsValues
    requiredTypes = [ track_characteristics.I3TrackCharacteristicsValues ]
AttributeError: 'module' object has no attribute 'I3TrackCharacteristicsValues'
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.ipdf.rst:23: WARNING: autodoc: failed to import module u'icecube.ipdf.test_bug'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/ipdf/test_bug.py", line 3, in <module>
    scenario = window.gl.scenario
NameError: name 'window' is not defined
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.millipede.rst:15: WARNING: autodoc: failed to import module u'icecube.millipede.artists'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/millipede/artists.py", line 7, in <module>
    from icecube.steamshovel.artists.MPLArtist import MPLArtist
ImportError: No module named MPLArtist
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.steamshovel.artists.rst:70: WARNING: autodoc: failed to import module u'icecube.steamshovel.artists.LEDPowerHouse'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/steamshovel/artists/LEDPowerHouse.py", line 9, in <module>
    import serial
ImportError: No module named serial
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.steamshovel.artists.rst:78: WARNING: autodoc: failed to import module u'icecube.steamshovel.artists.ParticleUncertainty'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/steamshovel/artists/ParticleUncertainty.py", line 6, in <module>
    from .AnimatedParticle import PosAtTime
ImportError: No module named AnimatedParticle
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.steamshovel.sessions.rst:15: WARNING: autodoc: failed to import module u'icecube.steamshovel.sessions.IT73'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/steamshovel/sessions/IT73.py", line 124, in <module>
    _dumpScenario()
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/steamshovel/sessions/IT73.py", line 6, in _dumpScenario
    scenario = window.gl.scenario
NameError: global name 'window' is not defined
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.steamshovel.sessions.rst:23: WARNING: autodoc: failed to import module u'icecube.steamshovel.sessions.Minimum'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/steamshovel/sessions/Minimum.py", line 47, in <module>
    _dumpScenario()
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/steamshovel/sessions/Minimum.py", line 6, in _dumpScenario
    scenario = window.gl.scenario
NameError: global name 'window' is not defined
```

Migrated from https://code.icecube.wisc.edu/ticket/1736
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:12:38", 
    "description": "It is not clear to me exactly how steamshovel loads these artist files but it causes problems with sphinx documentation. These can be tested by running the file directly for example calling `python ${I3_SRC}/CommonVariables/python/artists/direct_hits.py` instead of calling sphinx and it gets the same result.\n\n* common_variables/artists/direct_hits.py\n* common_variables/artists/hit_multiplicity.py\n* common_variables/artists/hit_statistics.py\n* common_variables/artists/track_characteristics.py\n* millipede/artists.py\n* steamshovel/artists/LEDPowerHouse.py\n* steamshovel/artists/ParticleUncertainty.py\n* steamshovel/sessions/IT73.py\n* steamshovel/sessions/Minimum.py\n\nFull error messages below\n{{{\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.common_variables.artists.rst:15: WARNING: autodoc: failed to import module u'icecube.common_variables.artists.direct_hits'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/direct_hits.py\", line 5, in <module>\n    class I3DirectHitsValues(PyArtist):\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/direct_hits.py\", line 10, in I3DirectHitsValues\n    requiredTypes = [ direct_hits.I3DirectHitsValues ]\nAttributeError: 'module' object has no attribute 'I3DirectHitsValues'\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.common_variables.artists.rst:23: WARNING: autodoc: failed to import module u'icecube.common_variables.artists.hit_multiplicity'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/hit_multiplicity.py\", line 4, in <module>\n    class I3HitMultiplicityValues(PyArtist):\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/hit_multiplicity.py\", line 9, in I3HitMultiplicityValues\n    requiredTypes = [ hit_multiplicity.I3HitMultiplicityValues ]\nAttributeError: 'module' object has no attribute 'I3HitMultiplicityValues'\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.common_variables.artists.rst:31: WARNING: autodoc: failed to import module u'icecube.common_variables.artists.hit_statistics'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/hit_statistics.py\", line 5, in <module>\n    class I3HitStatisticsValues(PyArtist):\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/hit_statistics.py\", line 10, in I3HitStatisticsValues\n    requiredTypes = [ hit_statistics.I3HitStatisticsValues ]\nAttributeError: 'module' object has no attribute 'I3HitStatisticsValues'\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.common_variables.artists.rst:39: WARNING: autodoc: failed to import module u'icecube.common_variables.artists.track_characteristics'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/track_characteristics.py\", line 5, in <module>\n    class I3TrackCharacteristicsValues(PyArtist):\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/common_variables/artists/track_characteristics.py\", line 10, in I3TrackCharacteristicsValues\n    requiredTypes = [ track_characteristics.I3TrackCharacteristicsValues ]\nAttributeError: 'module' object has no attribute 'I3TrackCharacteristicsValues'\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.ipdf.rst:23: WARNING: autodoc: failed to import module u'icecube.ipdf.test_bug'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/ipdf/test_bug.py\", line 3, in <module>\n    scenario = window.gl.scenario\nNameError: name 'window' is not defined\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.millipede.rst:15: WARNING: autodoc: failed to import module u'icecube.millipede.artists'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/millipede/artists.py\", line 7, in <module>\n    from icecube.steamshovel.artists.MPLArtist import MPLArtist\nImportError: No module named MPLArtist\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.steamshovel.artists.rst:70: WARNING: autodoc: failed to import module u'icecube.steamshovel.artists.LEDPowerHouse'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/steamshovel/artists/LEDPowerHouse.py\", line 9, in <module>\n    import serial\nImportError: No module named serial\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.steamshovel.artists.rst:78: WARNING: autodoc: failed to import module u'icecube.steamshovel.artists.ParticleUncertainty'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/steamshovel/artists/ParticleUncertainty.py\", line 6, in <module>\n    from .AnimatedParticle import PosAtTime\nImportError: No module named AnimatedParticle\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.steamshovel.sessions.rst:15: WARNING: autodoc: failed to import module u'icecube.steamshovel.sessions.IT73'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/steamshovel/sessions/IT73.py\", line 124, in <module>\n    _dumpScenario()\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/steamshovel/sessions/IT73.py\", line 6, in _dumpScenario\n    scenario = window.gl.scenario\nNameError: global name 'window' is not defined\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.steamshovel.sessions.rst:23: WARNING: autodoc: failed to import module u'icecube.steamshovel.sessions.Minimum'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/steamshovel/sessions/Minimum.py\", line 47, in <module>\n    _dumpScenario()\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/steamshovel/sessions/Minimum.py\", line 6, in _dumpScenario\n    scenario = window.gl.scenario\nNameError: global name 'window' is not defined\n}}}", 
    "reporter": "kjmeagher", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1550067158057333", 
    "component": "combo core", 
    "summary": "[Steamshovel] artists python files don't like being called on their own which confuses the documentation", 
    "priority": "normal", 
    "keywords": "documentation", 
    "time": "2016-06-10T07:42:38", 
    "milestone": "", 
    "owner": "hdembinski", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160615T18:40:21: olivas changed component from "cmake" to "icecube offline"

**Comment by icecube-trac** [comment]
Trac update at 20160621T12:38:56: hdembinski commented:

> Please assign this ticket to the maintainers of millipede and common_variables, too. I will take care of the artists inside steamshovel.

**Comment by icecube-trac** [comment]
Trac update at 20160621T12:43:55: hdembinski commented:

> You need to exclude the files in steamshovel/sessions/ from Sphinx
> 
> Sessions are not normal Python scripts. They are configuration files written in Python code. They require a special environment set up by Steamshovel, they cannot be executed standalone.

**Comment by icecube-trac** [comment]
Trac update at 20160621T13:03:26: 
* hdembinski commented:

> In changeset 147639:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="147639"
> attempt to fix #1728
> ```


* hdembinski changed status from "new" to "closed"
* hdembinski changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20160621T13:04:29: hdembinski commented:

> no need to contact millipede and common_variables maintainers, my commit should fix those issues.

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:12:38: 
* olivas changed milestone from "August 2016" to ""
* olivas commented:

> Milestone August 2016 deleted
