### ISSUE TITLE
filter scripts refer to extinct projects in many places (Trac #1742)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1734]
it is causing warnings in sphinx

```text
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.dst.rst:15: WARNING: autodoc: failed to import module u'icecube.dst.dstfilter'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/dst/dstfilter.py", line 5, in <module>
    import filter_globals
ImportError: No module named filter_globals
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.examples_simulation.rst:15: WARNING: autodoc: failed to import module u'icecube.examples_simulation.configure_simulation'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/examples_simulation/configure_simulation.py", line 14, in <module>
    from icecube.sim_services.sanity_checker import SimulationSanityChecker
ImportError: No module named sanity_checker
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.filterscripts.offlineL2.rst:47lders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/filterscripts/offlineL2/level2_Reconstruction_Cascade.py", line 2, in <module>
    from icecube import linefit, improvedLinefit, dipolefit, clast, cscd_llh, fill_ratio, tensor_of_inertia,CascadeVariables, AtmCscdEnergyReco
ImportError: cannot import name AtmCscdEnergyReco
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.finiteReco.rst:15: WARNING: autodoc: failed to import module u'icecube.finiteReco.converters'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/finiteReco/converters.py", line 1, in <module>
    from icecube.finiteReco import I3FiniteCuts
ImportError: cannot import name I3FiniteCuts
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.level3_filter_lowen.rst:15: WARNING: autodoc: failed to import module u'icecube.level3_filter_lowen.LowEnergyL3TraySegment'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/level3_filter_lowen/LowEnergyL3TraySegment.py", line 17, in <module>
    from icecube.STTools.seededRT.configuration_services import I3ClassicSeededRTConfigurationService
ImportError: cannot import name I3ClassicSeededRTConfigurationService
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.level3_filter_lowen.rst:23: WARNING: autodoc: failed to import module u'icecube.level3_filter_lowen.level3_Master_2012'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/level3_filter_lowen/level3_Master_2012.py", line 17, in <module>
    from icecube.level3_filter_lowen import LowEnergyL3TraySegment
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/level3_filter_lowen/LowEnergyL3TraySegment.py", line 17, in <module>
    from icecube.STTools.seededRT.configuration_services import I3ClassicSeededRTConfigurationService
ImportError: cannot import name I3ClassicSeededRTConfigurationService
/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.level3_filter_lowen.rst:31: WARNING: autodoc: failed to import module u'icecube.level3_filter_lowen.level3_segments'; the following exception was raised:
Traceback (most recent call last):
  File "/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py", line 385, in import_object
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/level3_filter_lowen/level3_segments.py", line 17, in <module>
    from icecube.STTools.seededRT.configuration_services import I3ClassicSeededRTConfigurationService
ImportError: cannot import name I3ClassicSeededRTConfigurationService
```

Migrated from https://code.icecube.wisc.edu/ticket/1742
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:12:38", 
    "description": "it is causing warnings in sphinx\n{{{\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.dst.rst:15: WARNING: autodoc: failed to import module u'icecube.dst.dstfilter'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/dst/dstfilter.py\", line 5, in <module>\n    import filter_globals\nImportError: No module named filter_globals\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.examples_simulation.rst:15: WARNING: autodoc: failed to import module u'icecube.examples_simulation.configure_simulation'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/examples_simulation/configure_simulation.py\", line 14, in <module>\n    from icecube.sim_services.sanity_checker import SimulationSanityChecker\nImportError: No module named sanity_checker\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.filterscripts.offlineL2.rst:47lders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/filterscripts/offlineL2/level2_Reconstruction_Cascade.py\", line 2, in <module>\n    from icecube import linefit, improvedLinefit, dipolefit, clast, cscd_llh, fill_ratio, tensor_of_inertia,CascadeVariables, AtmCscdEnergyReco\nImportError: cannot import name AtmCscdEnergyReco\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.finiteReco.rst:15: WARNING: autodoc: failed to import module u'icecube.finiteReco.converters'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/finiteReco/converters.py\", line 1, in <module>\n    from icecube.finiteReco import I3FiniteCuts\nImportError: cannot import name I3FiniteCuts\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.level3_filter_lowen.rst:15: WARNING: autodoc: failed to import module u'icecube.level3_filter_lowen.LowEnergyL3TraySegment'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/level3_filter_lowen/LowEnergyL3TraySegment.py\", line 17, in <module>\n    from icecube.STTools.seededRT.configuration_services import I3ClassicSeededRTConfigurationService\nImportError: cannot import name I3ClassicSeededRTConfigurationService\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.level3_filter_lowen.rst:23: WARNING: autodoc: failed to import module u'icecube.level3_filter_lowen.level3_Master_2012'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/level3_filter_lowen/level3_Master_2012.py\", line 17, in <module>\n    from icecube.level3_filter_lowen import LowEnergyL3TraySegment\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/level3_filter_lowen/LowEnergyL3TraySegment.py\", line 17, in <module>\n    from icecube.STTools.seededRT.configuration_services import I3ClassicSeededRTConfigurationService\nImportError: cannot import name I3ClassicSeededRTConfigurationService\n/Users/kmeagher/icecube/combo/release/sphinx_build/source/python/icecube.level3_filter_lowen.rst:31: WARNING: autodoc: failed to import module u'icecube.level3_filter_lowen.level3_segments'; the following exception was raised:\nTraceback (most recent call last):\n  File \"/private/var/folders/rc/g_4_lyp9039cj1586zzg88f40000gn/T/pip-build-A327aa/sphinx/sphinx/ext/autodoc.py\", line 385, in import_object\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/level3_filter_lowen/level3_segments.py\", line 17, in <module>\n    from icecube.STTools.seededRT.configuration_services import I3ClassicSeededRTConfigurationService\nImportError: cannot import name I3ClassicSeededRTConfigurationService\n}}}\n", 
    "reporter": "kjmeagher", 
    "cc": "", 
    "resolution": "invalid", 
    "_ts": "1550067158057333", 
    "component": "combo reconstruction", 
    "summary": "filter scripts refer to extinct projects in many places", 
    "priority": "minor", 
    "keywords": "documentation", 
    "time": "2016-06-10T11:50:34", 
    "milestone": "", 
    "owner": "blaufuss", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160610T14:45:48: 
* olivas changed owner from "" to "blaufuss"
* olivas changed status from "new" to "assigned"

**Comment by icecube-trac** [comment]
Trac update at 20160610T14:52:38: blaufuss commented:

> short of nuking old scripts in filterscripts, I don't know a good solution to this.  
> 
> Someone might want to see the 2012 level3 scripts...
>

**Comment by icecube-trac** [comment]
Trac update at 20161115T12:57:22: 
* kjmeagher changed resolution from "" to "invalid"
* kjmeagher changed status from "assigned" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:12:38: 
* olivas changed milestone from "August 2016" to ""
* olivas commented:

> Milestone August 2016 deleted
