### ISSUE TITLE
clsim example script fails (Trac #1757)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1749]
py2-v2, ubuntu 16.04; script code listing is [http://software.icecube.wisc.edu/documentation/projects/clsim/usage.html#example-script here]

Output when run:

```text
$ python example_script.py 
FATAL (I3Tray): Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /home/icecube/build/simulation/releases/V05-00-00/lib/libc2j-icetray.so: cannot open shared object file: No such file or directory (I3Tray.py:36 in load)
Traceback (most recent call last):
  File "example_script.py", line 21, in <module>
    load("libc2j-icetray")
  File "/home/icecube/build/simulation/releases/V05-00-00/lib/I3Tray.py", line 36, in load
    % (sys.exc_info()[0], sys.exc_info()[1]), "I3Tray")
  File "/home/icecube/build/simulation/releases/V05-00-00/lib/icecube/icetray/i3logging.py", line 150, in log_fatal
    raise RuntimeError(message + " (in " + tb[2] + ")")
RuntimeError: Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /home/icecube/build/simulation/releases/V05-00-00/lib/libc2j-icetray.so: cannot open shared object file: No such file or directory (in load)
```

Migrated from https://code.icecube.wisc.edu/ticket/1757
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:13:10", 
    "description": "py2-v2, ubuntu 16.04; script code listing is [http://software.icecube.wisc.edu/documentation/projects/clsim/usage.html#example-script here]\n\nOutput when run:\n{{{\n$ python example_script.py \nFATAL (I3Tray): Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /home/icecube/build/simulation/releases/V05-00-00/lib/libc2j-icetray.so: cannot open shared object file: No such file or directory (I3Tray.py:36 in load)\nTraceback (most recent call last):\n  File \"example_script.py\", line 21, in <module>\n    load(\"libc2j-icetray\")\n  File \"/home/icecube/build/simulation/releases/V05-00-00/lib/I3Tray.py\", line 36, in load\n    % (sys.exc_info()[0], sys.exc_info()[1]), \"I3Tray\")\n  File \"/home/icecube/build/simulation/releases/V05-00-00/lib/icecube/icetray/i3logging.py\", line 150, in log_fatal\n    raise RuntimeError(message + \" (in \" + tb[2] + \")\")\nRuntimeError: Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /home/icecube/build/simulation/releases/V05-00-00/lib/libc2j-icetray.so: cannot open shared object file: No such file or directory (in load)\n}}}", 
    "reporter": "jlanfranchi", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1550067190995086", 
    "component": "combo simulation", 
    "summary": "clsim example script fails", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2016-06-23T04:30:15", 
    "milestone": "", 
    "owner": "claudio.kopper", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160623T14:05:46: 
* olivas changed owner from "" to "claudio.kopper"
* olivas changed status from "new" to "assigned"
* olivas changed milestone from "" to "July 2016"
* olivas changed priority from "normal" to "blocker"
* olivas commented:

> libc2j-icetray was retired a looooong time ago.

**Comment by icecube-trac** [comment]
Trac update at 20161111T18:24:43: 
* claudio.kopper changed resolution from "" to "fixed"
* claudio.kopper changed status from "assigned" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20161111T18:24:57: claudio.kopper commented:

> (fixed in r151435)

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:13:10: 
* olivas changed milestone from "July 2016" to ""
* olivas commented:

> Milestone July 2016 deleted
