### ISSUE TITLE
Bug in timeshifter (Trac #1778)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1770]
We have a custom key in our simulation called Generation Spec, I receive the following error:

```text
ERROR (I3Module): <class 'icecube.trigger_sim.modules.time_shifter.I3TimeShifter'>_0000: Exception thrown (I3Module.cxx:116 in void I3Module::Do(void (I3Module::*)()))
Traceback (most recent call last):
  File "corsika.py", line 24, in <module>
    detsim.ExecuteOpts(stats)
  File "/cvmfs/icecube.opensciencegrid.org/py2-v2/RHEL_6_x86_64/metaprojects/simulation/V05-00-00/lib/icecube/simprod/ipmodule.py", line 219, in ExecuteOpts
    retval = self.Execute(stats)
  File "/cvmfs/icecube.opensciencegrid.org/py2-v2/RHEL_6_x86_64/metaprojects/simulation/V05-00-00/lib/icecube/simprod/modules/detectors.py", line 54, in Execute
    tray.Execute()
  File "/cvmfs/icecube.opensciencegrid.org/py2-v2/RHEL_6_x86_64/metaprojects/simulation/V05-00-00/lib/I3Tray.py", line 234, in Execute
    super(I3Tray, self).Execute()
  File "/cvmfs/icecube.opensciencegrid.org/py2-v2/RHEL_6_x86_64/metaprojects/simulation/V05-00-00/lib/icecube/trigger_sim/modules/time_shifter.py", line 55, in DAQ
    for trigger_hierarchy in [f for key,f in frame.items() \
RuntimeError: Frame caught exception "unregistered class" for key "GenerationSpec" of type MuonInjectionConfiguration
```

Migrated from https://code.icecube.wisc.edu/ticket/1778
```json
{
    "status": "closed", 
    "changetime": "2016-07-15T16:06:04", 
    "description": "We have a custom key in our simulation called Generation Spec, I receive the following error:\n\n{{{\nERROR (I3Module): <class 'icecube.trigger_sim.modules.time_shifter.I3TimeShifter'>_0000: Exception thrown (I3Module.cxx:116 in void I3Module::Do(void (I3Module::*)()))\nTraceback (most recent call last):\n  File \"corsika.py\", line 24, in <module>\n    detsim.ExecuteOpts(stats)\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v2/RHEL_6_x86_64/metaprojects/simulation/V05-00-00/lib/icecube/simprod/ipmodule.py\", line 219, in ExecuteOpts\n    retval = self.Execute(stats)\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v2/RHEL_6_x86_64/metaprojects/simulation/V05-00-00/lib/icecube/simprod/modules/detectors.py\", line 54, in Execute\n    tray.Execute()\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v2/RHEL_6_x86_64/metaprojects/simulation/V05-00-00/lib/I3Tray.py\", line 234, in Execute\n    super(I3Tray, self).Execute()\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v2/RHEL_6_x86_64/metaprojects/simulation/V05-00-00/lib/icecube/trigger_sim/modules/time_shifter.py\", line 55, in DAQ\n    for trigger_hierarchy in [f for key,f in frame.items() \\\nRuntimeError: Frame caught exception \"unregistered class\" for key \"GenerationSpec\" of type MuonInjectionConfiguration\n}}}", 
    "reporter": "saxani", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1468598764273384", 
    "component": "cmake", 
    "summary": "Bug in timeshifter", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2016-07-15T15:00:25", 
    "milestone": "", 
    "owner": "olivas", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160715T15:02:39: 
* david.schultz changed priority from "normal" to "critical"
* david.schultz commented:

> The issue is that we try to deserialize the contents of the entire frame before checking the skip keys.


* david.schultz changed milestone from "" to "IceSim 5.1"
* david.schultz changed owner from "" to "olivas"
* david.schultz changed component from "cmake" to "simulation"
* david.schultz changed status from "new" to "assigned"

**Comment by icecube-trac** [comment]
Trac update at 20160715T15:09:19: 
* cweaver changed milestone from "IceSim 5.1" to ""
* cweaver commented:

> This is a known issue in the new Time Shifter code. Does applying this patch and adding "GenerationSpec" to the TimeShifter's `SkipKeys` parameter solve the problem?
> 
> 
> ```text
> Index: python/modules/time_shifter.py
> ===================================================================
> --- python/modules/time_shifter.py	(revision 148201)
> +++ python/modules/time_shifter.py	(working copy)
> @@ -53,6 +53,8 @@
>          # or trigger times.  The earliest time will be DELTA_T.
>          ttimes = list()
>          for frame_key in frame.keys():
> +            if frame_key in self.skip_keys:
> +                continue
>              try:
>                  frame_object = frame[frame_key]
>              except RuntimeError:
> @@ -64,6 +66,8 @@
>          if len(ttimes) == 0 :
>              # These are untriggered events, so look for the earliest I3MCHit or I3MCPE.
>              for frame_key in frame.keys():
> +                if frame_key in self.skip_keys:
> +                    continue
>                  try:
>                      frame_object = frame[frame_key]
>                  except RuntimeError:
> @@ -78,6 +82,8 @@
>                  # check for DOMLaunches.
>                  # this is for trigger hitspool data
>                  for frame_key in frame.keys():
> +                    if frame_key in self.skip_keys:
> +                        continue
>                      try:
>                          frame_object = frame[frame_key]
>                      except RuntimeError:
> ```


* cweaver changed component from "simulation" to "cmake"
* cweaver changed priority from "critical" to "normal"

**Comment by icecube-trac** [comment]
Trac update at 20160715T15:42:26: david.schultz commented:

> Actually, the trunk looks sufficiently different from the V5 release that it may work fine.  The RuntimeError checks may catch this.

**Comment by icecube-trac** [comment]
Trac update at 20160715T16:06:04: 
* olivas changed resolution from "" to "fixed"
* olivas commented:

> Yup...
> http://code.icecube.wisc.edu/projects/icecube/changeset/145572/IceCube/projects/trigger-sim/trunk
> 
> Closing this as 'fixed' since this is a duplicate and already fixed on the trunk.


* olivas changed status from "assigned" to "closed"
