### ISSUE TITLE
homebrew formula need to upgrade from SHA1 hashes (Trac #1841)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1833]
```text
[avnas:~] brew tap icecube-spno/icecube
==> Tapping icecube-spno/icecube
Cloning into '/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16 (delta 1), reused 8 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.
Checking connectivity... done.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/boostnumpy.rb:7:in `<class:Boostnumpy>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/boostnumpy.rb:7:in `<class:Boostnumpy>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/boostnumpy.rb:7:in `<class:Boostnumpy>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/cvmfs.rb:6:in `<class:Cvmfs>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/cvmfs.rb:6:in `<class:Cvmfs>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/cvmfs.rb:6:in `<class:Cvmfs>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/pythia6.rb:6:in `<class:Pythia6>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/pythia6.rb:6:in `<class:Pythia6>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/pythia6.rb:6:in `<class:Pythia6>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/rdmc.rb:6:in `<class:Rdmc>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/rdmc.rb:6:in `<class:Rdmc>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/rdmc.rb:6:in `<class:Rdmc>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/root.rb:7:in `<class:Root>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/root.rb:7:in `<class:Root>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/root.rb:7:in `<class:Root>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/root.rb:11:in `block in <class:Root>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/root.rb:12:in `block in <class:Root>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling BottleSpecification#sha1 is deprecated!
Use BottleSpecification#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/root.rb:13:in `block in <class:Root>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/slalib-c.rb:6:in `<class:SlalibC>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/slalib-c.rb:6:in `<class:SlalibC>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/slalib-c.rb:6:in `<class:SlalibC>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/sprng2.rb:6:in `<class:Sprng2>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/sprng2.rb:6:in `<class:Sprng2>'
Please report this to the icecube-spno/icecube tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/sprng2.rb:6:in `<class:Sprng2>'
Please report this to the icecube-spno/icecube tap!

Tapped 13 formulae (51 files, 86K)
[avnas:~] 
```

Migrated from https://code.icecube.wisc.edu/ticket/1841
```json
{
    "status": "closed", 
    "changetime": "2016-09-06T19:30:44", 
    "description": "{{{\n[avnas:~] brew tap icecube-spno/icecube\n==> Tapping icecube-spno/icecube\nCloning into '/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube'...\nremote: Counting objects: 16, done.\nremote: Compressing objects: 100% (16/16), done.\nremote: Total 16 (delta 1), reused 8 (delta 0), pack-reused 0\nUnpacking objects: 100% (16/16), done.\nChecking connectivity... done.\nWarning: Calling Formula.sha1 is deprecated!\nUse Formula.sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/boostnumpy.rb:7:in `<class:Boostnumpy>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling SoftwareSpec#sha1 is deprecated!\nUse SoftwareSpec#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/boostnumpy.rb:7:in `<class:Boostnumpy>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling Resource#sha1 is deprecated!\nUse Resource#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/boostnumpy.rb:7:in `<class:Boostnumpy>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling Formula.sha1 is deprecated!\nUse Formula.sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/cvmfs.rb:6:in `<class:Cvmfs>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling SoftwareSpec#sha1 is deprecated!\nUse SoftwareSpec#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/cvmfs.rb:6:in `<class:Cvmfs>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling Resource#sha1 is deprecated!\nUse Resource#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/cvmfs.rb:6:in `<class:Cvmfs>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling Formula.sha1 is deprecated!\nUse Formula.sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/pythia6.rb:6:in `<class:Pythia6>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling SoftwareSpec#sha1 is deprecated!\nUse SoftwareSpec#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/pythia6.rb:6:in `<class:Pythia6>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling Resource#sha1 is deprecated!\nUse Resource#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/pythia6.rb:6:in `<class:Pythia6>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling Formula.sha1 is deprecated!\nUse Formula.sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/rdmc.rb:6:in `<class:Rdmc>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling SoftwareSpec#sha1 is deprecated!\nUse SoftwareSpec#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/rdmc.rb:6:in `<class:Rdmc>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling Resource#sha1 is deprecated!\nUse Resource#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/rdmc.rb:6:in `<class:Rdmc>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling Formula.sha1 is deprecated!\nUse Formula.sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/root.rb:7:in `<class:Root>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling SoftwareSpec#sha1 is deprecated!\nUse SoftwareSpec#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/root.rb:7:in `<class:Root>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling Resource#sha1 is deprecated!\nUse Resource#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/root.rb:7:in `<class:Root>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling BottleSpecification#sha1 is deprecated!\nUse BottleSpecification#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/root.rb:11:in `block in <class:Root>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling BottleSpecification#sha1 is deprecated!\nUse BottleSpecification#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/root.rb:12:in `block in <class:Root>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling BottleSpecification#sha1 is deprecated!\nUse BottleSpecification#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/root.rb:13:in `block in <class:Root>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling Formula.sha1 is deprecated!\nUse Formula.sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/slalib-c.rb:6:in `<class:SlalibC>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling SoftwareSpec#sha1 is deprecated!\nUse SoftwareSpec#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/slalib-c.rb:6:in `<class:SlalibC>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling Resource#sha1 is deprecated!\nUse Resource#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/slalib-c.rb:6:in `<class:SlalibC>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling Formula.sha1 is deprecated!\nUse Formula.sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/sprng2.rb:6:in `<class:Sprng2>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling SoftwareSpec#sha1 is deprecated!\nUse SoftwareSpec#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/sprng2.rb:6:in `<class:Sprng2>'\nPlease report this to the icecube-spno/icecube tap!\n\nWarning: Calling Resource#sha1 is deprecated!\nUse Resource#sha256 instead.\n/build/linuxbrew/Library/Taps/icecube-spno/homebrew-icecube/sprng2.rb:6:in `<class:Sprng2>'\nPlease report this to the icecube-spno/icecube tap!\n\nTapped 13 formulae (51 files, 86K)\n[avnas:~] \n}}}\n", 
    "reporter": "nega", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1473190244600506", 
    "component": "tools/ports", 
    "summary": "homebrew formula need to upgrade from SHA1 hashes", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2016-08-30T18:45:33", 
    "milestone": "", 
    "owner": "nega", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160906T19:30:44: 
* nega changed resolution from "" to "fixed"
* nega changed status from "new" to "closed"
