### ISSUE TITLE
dst - test dst::dst16.py is failing across the board (Trac #1847)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1839]
```text
187/425 Test #187: dst::dst16.py ..................................................***Failed    6.66 sec
INFO (I3Tray): qify-dst: WritePFrame = True (I3Tray.py:226 in __call__)
INFO (I3Tray): Adding Anonymous Module of type '<class 'icecube.dst.dsttest.CheckFrameIndex'>' with name 'CheckFrameIndex_0000' (I3Tray.py:75 in _create_name)
INFO (I3Tray): Adding Anonymous Module of type 'CountFrames' with name 'CountFrames_0000' (I3Tray.py:75 in _create_name)
INFO (I3Tray): Adding Anonymous Module of type 'Dump' with name 'Dump_0000' (I3Tray.py:75 in _create_name)
INFO (I3Tray): Adding Anonymous Module of type 'CountFrames' with name 'CountFrames_0001' (I3Tray.py:75 in _create_name)
INFO (I3Tray): Adding Anonymous Module of type '<class 'icecube.dst.dsttest.CheckFrameIndex'>' with name 'CheckFrameIndex_0001' (I3Tray.py:75 in _create_name)
INFO (I3Module): Prefixing with filename/url /build/ports/test-data/sim/GeoCalibDetectorStatus_IC80_DC6.54655.i3.gz (I3InfiniteSource.cxx:55 in virtual void I3InfiniteSource::Configure())
WARN (I3DSTModule16): I3DirectHitsValues 'PoleMuonLlhFitDirectHitsBaseC' will be ignored as per user request. (I3DSTModule16.cxx:117 in virtual void I3DSTModule16::Configure())
INFO (dst): dst pixel size: 0.0337076 deg (HealPixCoordinates.cxx:68 in void HealPixCoordinate::ComputeBins(int))
INFO (I3DSTExtractor16): Skipping frame (I3DSTExtractor16.cxx:116 in virtual void I3DSTExtractor16::Process())
INFO (I3DSTExtractor16): Skipping frame (I3DSTExtractor16.cxx:116 in virtual void I3DSTExtractor16::Process())
INFO (I3DSTExtractor16): Skipping frame (I3DSTExtractor16.cxx:116 in virtual void I3DSTExtractor16::Process())
INFO (I3DSTExtractor16): Skipping frame (I3DSTExtractor16.cxx:116 in virtual void I3DSTExtractor16::Process())
INFO (I3DSTExtractor16): header not writtten.. buffering (I3DSTExtractor16.cxx:124 in virtual void I3DSTExtractor16::Process())
INFO (I3DSTExtractor16): header not writtten.. buffering (I3DSTExtractor16.cxx:124 in virtual void I3DSTExtractor16::Process())
INFO (dst): dst pixel size: 0.0337076 deg (HealPixCoordinates.cxx:68 in void HealPixCoordinate::ComputeBins(int))
FATAL (phys-services): Physics frames cannot be split (I3Splitter.cxx:36 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))
ERROR (I3Module): UnpackDST: Exception thrown (I3Module.cxx:118 in void I3Module::Do(void (I3Module::*)()))
------------------------- This is frame number 1 -------------------------
[ I3Frame  (TrayInfo):
  '2008-09-29T20:07:59.914225' [TrayInfo] ==> I3TrayInfo (13528)
]
------------------------- This is frame number 2 -------------------------
[ I3Frame  (Geometry):
  'Gindex' [Geometry] ==> I3PODHolder<int> (unk)
  'I3Geometry' [Geometry] ==> I3Geometry (436738)
]
------------------------- This is frame number 3 -------------------------
[ I3Frame  (Calibration):
  'Cindex' [Calibration] ==> I3PODHolder<int> (unk)
  'Gindex' [Geometry] ==> I3PODHolder<int> (unk)
  'I3Calibration' [Calibration] ==> I3Calibration (120071635)
  'I3Geometry' [Geometry] ==> I3Geometry (436738)
]
------------------------- This is frame number 4 -------------------------
[ I3Frame  (DetectorStatus):
  'Cindex' [Calibration] ==> I3PODHolder<int> (unk)
  'Dindex' [DetectorStatus] ==> I3PODHolder<int> (unk)
  'Gindex' [Geometry] ==> I3PODHolder<int> (unk)
  'I3Calibration' [Calibration] ==> I3Calibration (120071635)
  'I3DetectorStatus' [DetectorStatus] ==> I3DetectorStatus (995670)
  'I3Geometry' [Geometry] ==> I3Geometry (436738)
]
Traceback (most recent call last):
  File "/Volumes/Macintosh_HD2/build/buildslave/barbas/OS_X_Yosemite/source/dst/resources/test/dst16.py", line 64, in <module>
    tray.Execute(14)
  File "/Volumes/Macintosh_HD2/build/buildslave/barbas/OS_X_Yosemite/build/lib/I3Tray.py", line 238, in Execute
    super(I3Tray, self).Execute(args[0])
RuntimeError: Physics frames cannot be split (in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))
```

Migrated from https://code.icecube.wisc.edu/ticket/1847
```json
{
    "status": "closed", 
    "changetime": "2016-09-01T14:56:02", 
    "description": "{{{\n187/425 Test #187: dst::dst16.py ..................................................***Failed    6.66 sec\nINFO (I3Tray): qify-dst: WritePFrame = True (I3Tray.py:226 in __call__)\nINFO (I3Tray): Adding Anonymous Module of type '<class 'icecube.dst.dsttest.CheckFrameIndex'>' with name 'CheckFrameIndex_0000' (I3Tray.py:75 in _create_name)\nINFO (I3Tray): Adding Anonymous Module of type 'CountFrames' with name 'CountFrames_0000' (I3Tray.py:75 in _create_name)\nINFO (I3Tray): Adding Anonymous Module of type 'Dump' with name 'Dump_0000' (I3Tray.py:75 in _create_name)\nINFO (I3Tray): Adding Anonymous Module of type 'CountFrames' with name 'CountFrames_0001' (I3Tray.py:75 in _create_name)\nINFO (I3Tray): Adding Anonymous Module of type '<class 'icecube.dst.dsttest.CheckFrameIndex'>' with name 'CheckFrameIndex_0001' (I3Tray.py:75 in _create_name)\nINFO (I3Module): Prefixing with filename/url /build/ports/test-data/sim/GeoCalibDetectorStatus_IC80_DC6.54655.i3.gz (I3InfiniteSource.cxx:55 in virtual void I3InfiniteSource::Configure())\nWARN (I3DSTModule16): I3DirectHitsValues 'PoleMuonLlhFitDirectHitsBaseC' will be ignored as per user request. (I3DSTModule16.cxx:117 in virtual void I3DSTModule16::Configure())\nINFO (dst): dst pixel size: 0.0337076 deg (HealPixCoordinates.cxx:68 in void HealPixCoordinate::ComputeBins(int))\nINFO (I3DSTExtractor16): Skipping frame (I3DSTExtractor16.cxx:116 in virtual void I3DSTExtractor16::Process())\nINFO (I3DSTExtractor16): Skipping frame (I3DSTExtractor16.cxx:116 in virtual void I3DSTExtractor16::Process())\nINFO (I3DSTExtractor16): Skipping frame (I3DSTExtractor16.cxx:116 in virtual void I3DSTExtractor16::Process())\nINFO (I3DSTExtractor16): Skipping frame (I3DSTExtractor16.cxx:116 in virtual void I3DSTExtractor16::Process())\nINFO (I3DSTExtractor16): header not writtten.. buffering (I3DSTExtractor16.cxx:124 in virtual void I3DSTExtractor16::Process())\nINFO (I3DSTExtractor16): header not writtten.. buffering (I3DSTExtractor16.cxx:124 in virtual void I3DSTExtractor16::Process())\nINFO (dst): dst pixel size: 0.0337076 deg (HealPixCoordinates.cxx:68 in void HealPixCoordinate::ComputeBins(int))\nFATAL (phys-services): Physics frames cannot be split (I3Splitter.cxx:36 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))\nERROR (I3Module): UnpackDST: Exception thrown (I3Module.cxx:118 in void I3Module::Do(void (I3Module::*)()))\n------------------------- This is frame number 1 -------------------------\n[ I3Frame  (TrayInfo):\n  '2008-09-29T20:07:59.914225' [TrayInfo] ==> I3TrayInfo (13528)\n]\n------------------------- This is frame number 2 -------------------------\n[ I3Frame  (Geometry):\n  'Gindex' [Geometry] ==> I3PODHolder<int> (unk)\n  'I3Geometry' [Geometry] ==> I3Geometry (436738)\n]\n------------------------- This is frame number 3 -------------------------\n[ I3Frame  (Calibration):\n  'Cindex' [Calibration] ==> I3PODHolder<int> (unk)\n  'Gindex' [Geometry] ==> I3PODHolder<int> (unk)\n  'I3Calibration' [Calibration] ==> I3Calibration (120071635)\n  'I3Geometry' [Geometry] ==> I3Geometry (436738)\n]\n------------------------- This is frame number 4 -------------------------\n[ I3Frame  (DetectorStatus):\n  'Cindex' [Calibration] ==> I3PODHolder<int> (unk)\n  'Dindex' [DetectorStatus] ==> I3PODHolder<int> (unk)\n  'Gindex' [Geometry] ==> I3PODHolder<int> (unk)\n  'I3Calibration' [Calibration] ==> I3Calibration (120071635)\n  'I3DetectorStatus' [DetectorStatus] ==> I3DetectorStatus (995670)\n  'I3Geometry' [Geometry] ==> I3Geometry (436738)\n]\nTraceback (most recent call last):\n  File \"/Volumes/Macintosh_HD2/build/buildslave/barbas/OS_X_Yosemite/source/dst/resources/test/dst16.py\", line 64, in <module>\n    tray.Execute(14)\n  File \"/Volumes/Macintosh_HD2/build/buildslave/barbas/OS_X_Yosemite/build/lib/I3Tray.py\", line 238, in Execute\n    super(I3Tray, self).Execute(args[0])\nRuntimeError: Physics frames cannot be split (in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))\n}}}", 
    "reporter": "nega", 
    "cc": "", 
    "resolution": "duplicate", 
    "_ts": "1472741762631521", 
    "component": "combo reconstruction", 
    "summary": "dst - test dst::dst16.py is failing across the board", 
    "priority": "normal", 
    "keywords": "dst tests", 
    "time": "2016-09-01T14:51:34", 
    "milestone": "", 
    "owner": "juancarlos", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160901T14:56:02: 
* jvansanten changed resolution from "" to "duplicate"
* jvansanten commented:

> Duplicate of #1835


* jvansanten changed status from "new" to "closed"
