### ISSUE TITLE
[truncated-energy] test failing (Trac #1848)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1840]
```text
        Start 408: truncated_energy::test_truncated.py
408/423 Test #407: truncated_energy::test_truncated.py ............................***Failed   11.07 sec
INFO (I3Tray): Adding Anonymous Module of type 'I3TruncatedEnergy' with name 'I3TruncatedEnergy_0000' (I3Tray.py:75 in _create_name)
INFO (I3Tray): Adding Anonymous Module of type '<function test at 0x7ff3d6219c80>' with name 'test_0000' (I3Tray.py:75 in _create_name)
INFO (I3PhotonicsL2Reader): Photonics Level2: Version 'I3PhotonicsReader $Rev: 142977 $' (I3PhotonicsL2Reader.cxx:433 in int I3PhotonicsL2Reader::load_level2_tables(const char *))
INFO (I3PhotonicsL2Reader): Photonics Level2: Using 'Photorec' mode. (I3PhotonicsL2Reader.cxx:565 in int I3PhotonicsL2Reader::load_level2_tables(const char *))
INFO (I3PhotonicsL2Reader): Photonics Level2: loaded 1539 starting tables, setid   0 photorec mode (I3PhotonicsL2Reader.cxx:728 in int I3PhotonicsL2Reader::load_level2_tables(const char *))
INFO (I3PhotonicsL2Reader): Photonics Level2: Active interval: (setid: 0)    0<=th<= 180  -800<=z<= 800 (I3PhotonicsL2Reader.cxx:840 in int I3PhotonicsL2Reader::load_level2_tables(const char *))
INFO (I3Module): Opened file /build/ports/test-data/sim/GeoCalibDetectorStatus_2012.56063_V0.i3.gz (I3Reader.cxx:180 in void I3Reader::OpenNextFile())
INFO (I3Module): Opened file /build/ports/test-data/sim/Level3_nugen_numu_IC86.2012.011069.000000_20events.i3.bz2 (I3Reader.cxx:180 in void I3Reader::OpenNextFile())
ERROR (PythonFunction): Error running python function as module: (PythonFunction.cxx:173 in virtual void PythonFunction::Process())
ERROR (I3Module): test_0000: Exception thrown (I3Module.cxx:118 in void I3Module::Do(void (I3Module::*)()))
SplineMPETruncatedEnergy_SPICEMie_AllDOMS_MuEres 0.0
SplineMPETruncatedEnergy_SPICEMie_DOMS_Neutrino 0.342341098934
Traceback (most recent call last):
  File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/source/truncated_energy/resources/test/test_truncated.py", line 59, in <module>
    tray.Execute()
  File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/I3Tray.py", line 240, in Execute
    super(I3Tray, self).Execute()
  File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/source/truncated_energy/resources/test/test_truncated.py", line 55, in test
    assert d < 1e-4
AssertionError
INFO (I3PhotonicsService): Destructor called for I3PhotonicsTableService 
 (I3PhotonicsTableService.cxx:100 in virtual I3PhotonicsTableService::~I3PhotonicsTableService())
```

Migrated from https://code.icecube.wisc.edu/ticket/1848
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:13:18", 
    "description": "{{{\n        Start 408: truncated_energy::test_truncated.py\n408/423 Test #408: truncated_energy::test_truncated.py ............................***Failed   11.07 sec\nINFO (I3Tray): Adding Anonymous Module of type 'I3TruncatedEnergy' with name 'I3TruncatedEnergy_0000' (I3Tray.py:75 in _create_name)\nINFO (I3Tray): Adding Anonymous Module of type '<function test at 0x7ff3d6219c80>' with name 'test_0000' (I3Tray.py:75 in _create_name)\nINFO (I3PhotonicsL2Reader): Photonics Level2: Version 'I3PhotonicsReader $Rev: 142977 $' (I3PhotonicsL2Reader.cxx:433 in int I3PhotonicsL2Reader::load_level2_tables(const char *))\nINFO (I3PhotonicsL2Reader): Photonics Level2: Using 'Photorec' mode. (I3PhotonicsL2Reader.cxx:565 in int I3PhotonicsL2Reader::load_level2_tables(const char *))\nINFO (I3PhotonicsL2Reader): Photonics Level2: loaded 1539 starting tables, setid   0 photorec mode (I3PhotonicsL2Reader.cxx:728 in int I3PhotonicsL2Reader::load_level2_tables(const char *))\nINFO (I3PhotonicsL2Reader): Photonics Level2: Active interval: (setid: 0)    0<=th<= 180  -800<=z<= 800 (I3PhotonicsL2Reader.cxx:840 in int I3PhotonicsL2Reader::load_level2_tables(const char *))\nINFO (I3Module): Opened file /build/ports/test-data/sim/GeoCalibDetectorStatus_2012.56063_V0.i3.gz (I3Reader.cxx:180 in void I3Reader::OpenNextFile())\nINFO (I3Module): Opened file /build/ports/test-data/sim/Level3_nugen_numu_IC86.2012.011069.000000_20events.i3.bz2 (I3Reader.cxx:180 in void I3Reader::OpenNextFile())\nERROR (PythonFunction): Error running python function as module: (PythonFunction.cxx:173 in virtual void PythonFunction::Process())\nERROR (I3Module): test_0000: Exception thrown (I3Module.cxx:118 in void I3Module::Do(void (I3Module::*)()))\nSplineMPETruncatedEnergy_SPICEMie_AllDOMS_MuEres 0.0\nSplineMPETruncatedEnergy_SPICEMie_DOMS_Neutrino 0.342341098934\nTraceback (most recent call last):\n  File \"/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/source/truncated_energy/resources/test/test_truncated.py\", line 59, in <module>\n    tray.Execute()\n  File \"/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/I3Tray.py\", line 240, in Execute\n    super(I3Tray, self).Execute()\n  File \"/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/source/truncated_energy/resources/test/test_truncated.py\", line 55, in test\n    assert d < 1e-4\nAssertionError\nINFO (I3PhotonicsService): Destructor called for I3PhotonicsTableService \n (I3PhotonicsTableService.cxx:100 in virtual I3PhotonicsTableService::~I3PhotonicsTableService())\n}}}\n", 
    "reporter": "nega", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1550067198646291", 
    "component": "combo reconstruction", 
    "summary": "[truncated-energy] test failing", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2016-09-01T14:54:17", 
    "milestone": "", 
    "owner": "tpalczewski", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160909T17:50:29: 
* olivas changed milestone from "" to "September 2016"
* olivas changed status from "new" to "assigned"
* olivas changed priority from "normal" to "critical"
* olivas changed owner from "mjl5147" to "tpalczewski"
* olivas changed summary from "vuvuzela - test - generateNoiseOnly.py failing" to "[truncated-energy] test failing"
* olivas commented:

> I'm not seeing anything in that error message that points to vuvuzela.  This test is still failing on the SL6 bot though.

**Comment by icecube-trac** [comment]
Trac update at 20161025T19:16:15: 
* olivas commented:

> This is currently blocking a stable combo update.  Up'ed the severity to blocker.


* olivas changed priority from "critical" to "blocker"

**Comment by icecube-trac** [comment]
Trac update at 20170405T16:49:25: 
* tpalczewski changed resolution from "" to "fixed"
* tpalczewski changed status from "assigned" to "closed"
* tpalczewski commented:

> It was just a problem on the bot. In addition, differences were really small, for example: 
> I3Particle
> 2371351.6450250553898513317108154296875
> 2371351.9873661543242633342742919921875
> 0.3423410989344120025634765625
> I3Particle
> 247353.43138378617004491388797760009765625
> 247353.47043552013929001986980438232421875
> 0.03905173396924510598182678223
> I3Particle
> 1611666.1303677461110055446624755859375
> 1611666.3537254831753671169281005859375
> 0.2233577370643615722656250000
> I3Double
> 17.962945793
> 17.9629485834
> 2.79048071405e-06
> I3Particle
> 10808096.8095473684370517730712890625
> 10808098.92268607206642627716064453125
> 2.113138703629374504089355469
> I3Double
> 143.597167252
> 143.597194458
> 2.72066615707e-05
> (energy from the file, energy2 calculated inside the test scrip and difference between them)
>

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:13:18: 
* olivas changed milestone from "September 2016" to ""
* olivas commented:

> Milestone September 2016 deleted
