### ISSUE TITLE
[tableio] Test failure (Trac #1854)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1846]
On the SL6 bot:

```text
370/424 Test #369: tableio::test_converters.py ....................................***Failed   18.16 sec
INFO (I3Tray): Adding Anonymous Module of type 'I3InfiniteSource' with name 'I3InfiniteSource_0000' (I3Tray.py:75 in _create_name)
INFO (I3Tray): Adding Anonymous Module of type '<function fake_event_header at 0x7fc82b699aa0>' with name 'fake_event_header_0000' (I3Tray.py:75 in _create_name)
INFO (I3Tray): Adding Anonymous Module of type '<function fill_frame at 0x7fc82b699b18>' with name 'fill_frame_0000' (I3Tray.py:75 in _create_name)
INFO (I3Tray): Adding Anonymous Module of type '<class 'icecube.tableio.I3TableWriterModule.I3TableWriter'>' with name 'I3TableWriter_0000' (I3Tray.py:75 in _create_name)
/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/icecube/tableio/I3TableWriterModule.py:158: UserWarning: 
I3TableWriter is now going to book everything it can find in the frame. This has the tendency to produce very, very large files, and is almost certainly not what you want to do.

To book only the frame objects you're interested in, pass a list of keys as the `keys' parameter, or a list of types as the `types' parameter when configuring I3TableWriter. You can find a tutorial in $I3_BUILD/doc/projects/tableio/howto.html .

  """)
WARN (phys-services): Using the I3Configuration instance name for the subevent stream name is deprecated. (I3Splitter.cxx:46 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))
WARN (phys-services): Derived modules should set sub_event_stream_name_ explicitly. (I3Splitter.cxx:47 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))
WARN (phys-services): Users should set SubEventStreamName in the splitting module nullsplit. (I3Splitter.cxx:49 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))
FATAL (I3TableWriter): No converter found for 'I3CLastFitParams' of type 'I3CLastFitParams' (I3TableWriter.cxx:115 in bool I3TableWriter::AddObject(std::string, std::string, I3ConverterPtr, I3FrameObjectConstPtr))
ERROR (I3Module): I3TableWriter_0000: Exception thrown (I3Module.cxx:118 in void I3Module::Do(void (I3Module::*)()))
Traceback (most recent call last):
  File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/source/tableio/resources/test/test_converters.py", line 105, in <module>
    tray.Execute(1)
  File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/I3Tray.py", line 238, in Execute
    super(I3Tray, self).Execute(args[0])
  File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/icecube/tableio/I3TableWriterModule.py", line 209, in Physics
    return self.handle_frame(frame)
  File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/icecube/tableio/I3TableWriterModule.py", line 205, in handle_frame
    self.writer.convert(frame)
RuntimeError: No converter found for 'I3CLastFitParams' of type 'I3CLastFitParams' (in bool I3TableWriter::AddObject(std::string, std::string, I3ConverterPtr, I3FrameObjectConstPtr))
ERROR (I3TableService): Table 'BootstrapParams' is still connected, which means that the output file was never properly closed. This is a BUG!
 (I3TableService.cxx:219 in virtual I3TableService::~I3TableService())
```

Migrated from https://code.icecube.wisc.edu/ticket/1854
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:13:18", 
    "description": "On the SL6 bot:\n\n\n{{{\n370/424 Test #370: tableio::test_converters.py ....................................***Failed   18.16 sec\nINFO (I3Tray): Adding Anonymous Module of type 'I3InfiniteSource' with name 'I3InfiniteSource_0000' (I3Tray.py:75 in _create_name)\nINFO (I3Tray): Adding Anonymous Module of type '<function fake_event_header at 0x7fc82b699aa0>' with name 'fake_event_header_0000' (I3Tray.py:75 in _create_name)\nINFO (I3Tray): Adding Anonymous Module of type '<function fill_frame at 0x7fc82b699b18>' with name 'fill_frame_0000' (I3Tray.py:75 in _create_name)\nINFO (I3Tray): Adding Anonymous Module of type '<class 'icecube.tableio.I3TableWriterModule.I3TableWriter'>' with name 'I3TableWriter_0000' (I3Tray.py:75 in _create_name)\n/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/icecube/tableio/I3TableWriterModule.py:158: UserWarning: \nI3TableWriter is now going to book everything it can find in the frame. This has the tendency to produce very, very large files, and is almost certainly not what you want to do.\n\nTo book only the frame objects you're interested in, pass a list of keys as the `keys' parameter, or a list of types as the `types' parameter when configuring I3TableWriter. You can find a tutorial in $I3_BUILD/doc/projects/tableio/howto.html .\n\n  \"\"\")\nWARN (phys-services): Using the I3Configuration instance name for the subevent stream name is deprecated. (I3Splitter.cxx:46 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))\nWARN (phys-services): Derived modules should set sub_event_stream_name_ explicitly. (I3Splitter.cxx:47 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))\nWARN (phys-services): Users should set SubEventStreamName in the splitting module nullsplit. (I3Splitter.cxx:49 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))\nFATAL (I3TableWriter): No converter found for 'I3CLastFitParams' of type 'I3CLastFitParams' (I3TableWriter.cxx:115 in bool I3TableWriter::AddObject(std::string, std::string, I3ConverterPtr, I3FrameObjectConstPtr))\nERROR (I3Module): I3TableWriter_0000: Exception thrown (I3Module.cxx:118 in void I3Module::Do(void (I3Module::*)()))\nTraceback (most recent call last):\n  File \"/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/source/tableio/resources/test/test_converters.py\", line 105, in <module>\n    tray.Execute(1)\n  File \"/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/I3Tray.py\", line 238, in Execute\n    super(I3Tray, self).Execute(args[0])\n  File \"/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/icecube/tableio/I3TableWriterModule.py\", line 209, in Physics\n    return self.handle_frame(frame)\n  File \"/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/icecube/tableio/I3TableWriterModule.py\", line 205, in handle_frame\n    self.writer.convert(frame)\nRuntimeError: No converter found for 'I3CLastFitParams' of type 'I3CLastFitParams' (in bool I3TableWriter::AddObject(std::string, std::string, I3ConverterPtr, I3FrameObjectConstPtr))\nERROR (I3TableService): Table 'BootstrapParams' is still connected, which means that the output file was never properly closed. This is a BUG!\n (I3TableService.cxx:219 in virtual I3TableService::~I3TableService())\n}}}\n", 
    "reporter": "olivas", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1550067198646291", 
    "component": "combo core", 
    "summary": "[tableio] Test failure", 
    "priority": "critical", 
    "keywords": "", 
    "time": "2016-09-09T18:28:07", 
    "milestone": "", 
    "owner": "jvansanten", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160909T18:33:19: david.schultz changed description from:

> On the SL6 bot:
> 
> 370/424 Test #370: tableio::test_converters.py ....................................***Failed   18.16 sec
> INFO (I3Tray): Adding Anonymous Module of type 'I3InfiniteSource' with name 'I3InfiniteSource_0000' (I3Tray.py:75 in _create_name)
> INFO (I3Tray): Adding Anonymous Module of type '<function fake_event_header at 0x7fc82b699aa0>' with name 'fake_event_header_0000' (I3Tray.py:75 in _create_name)
> INFO (I3Tray): Adding Anonymous Module of type '<function fill_frame at 0x7fc82b699b18>' with name 'fill_frame_0000' (I3Tray.py:75 in _create_name)
> INFO (I3Tray): Adding Anonymous Module of type '<class 'icecube.tableio.I3TableWriterModule.I3TableWriter'>' with name 'I3TableWriter_0000' (I3Tray.py:75 in _create_name)
> /build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/icecube/tableio/I3TableWriterModule.py:158: UserWarning: 
> I3TableWriter is now going to book everything it can find in the frame. This has the tendency to produce very, very large files, and is almost certainly not what you want to do.
> 
> To book only the frame objects you're interested in, pass a list of keys as the `keys' parameter, or a list of types as the `types' parameter when configuring I3TableWriter. You can find a tutorial in $I3_BUILD/doc/projects/tableio/howto.html .
> 
>   """)
> WARN (phys-services): Using the I3Configuration instance name for the subevent stream name is deprecated. (I3Splitter.cxx:46 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))
> WARN (phys-services): Derived modules should set sub_event_stream_name_ explicitly. (I3Splitter.cxx:47 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))
> WARN (phys-services): Users should set SubEventStreamName in the splitting module nullsplit. (I3Splitter.cxx:49 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))
> FATAL (I3TableWriter): No converter found for 'I3CLastFitParams' of type 'I3CLastFitParams' (I3TableWriter.cxx:115 in bool I3TableWriter::AddObject(std::string, std::string, I3ConverterPtr, I3FrameObjectConstPtr))
> ERROR (I3Module): I3TableWriter_0000: Exception thrown (I3Module.cxx:118 in void I3Module::Do(void (I3Module::*)()))
> Traceback (most recent call last):
>   File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/source/tableio/resources/test/test_converters.py", line 105, in <module>
>     tray.Execute(1)
>   File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/I3Tray.py", line 238, in Execute
>     super(I3Tray, self).Execute(args[0])
>   File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/icecube/tableio/I3TableWriterModule.py", line 209, in Physics
>     return self.handle_frame(frame)
>   File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/icecube/tableio/I3TableWriterModule.py", line 205, in handle_frame
>     self.writer.convert(frame)
> RuntimeError: No converter found for 'I3CLastFitParams' of type 'I3CLastFitParams' (in bool I3TableWriter::AddObject(std::string, std::string, I3ConverterPtr, I3FrameObjectConstPtr))
> ERROR (I3TableService): Table 'BootstrapParams' is still connected, which means that the output file was never properly closed. This is a BUG!
>  (I3TableService.cxx:219 in virtual I3TableService::~I3TableService())

to:

> On the SL6 bot:
> 
> 
> {{{
> 370/424 Test #370: tableio::test_converters.py ....................................***Failed   18.16 sec
> INFO (I3Tray): Adding Anonymous Module of type 'I3InfiniteSource' with name 'I3InfiniteSource_0000' (I3Tray.py:75 in _create_name)
> INFO (I3Tray): Adding Anonymous Module of type '<function fake_event_header at 0x7fc82b699aa0>' with name 'fake_event_header_0000' (I3Tray.py:75 in _create_name)
> INFO (I3Tray): Adding Anonymous Module of type '<function fill_frame at 0x7fc82b699b18>' with name 'fill_frame_0000' (I3Tray.py:75 in _create_name)
> INFO (I3Tray): Adding Anonymous Module of type '<class 'icecube.tableio.I3TableWriterModule.I3TableWriter'>' with name 'I3TableWriter_0000' (I3Tray.py:75 in _create_name)
> /build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/icecube/tableio/I3TableWriterModule.py:158: UserWarning: 
> I3TableWriter is now going to book everything it can find in the frame. This has the tendency to produce very, very large files, and is almost certainly not what you want to do.
> 
> To book only the frame objects you're interested in, pass a list of keys as the `keys' parameter, or a list of types as the `types' parameter when configuring I3TableWriter. You can find a tutorial in $I3_BUILD/doc/projects/tableio/howto.html .
> 
>   """)
> WARN (phys-services): Using the I3Configuration instance name for the subevent stream name is deprecated. (I3Splitter.cxx:46 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))
> WARN (phys-services): Derived modules should set sub_event_stream_name_ explicitly. (I3Splitter.cxx:47 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))
> WARN (phys-services): Users should set SubEventStreamName in the splitting module nullsplit. (I3Splitter.cxx:49 in I3FramePtr I3Splitter::GetNextSubEvent(I3FramePtr))
> FATAL (I3TableWriter): No converter found for 'I3CLastFitParams' of type 'I3CLastFitParams' (I3TableWriter.cxx:115 in bool I3TableWriter::AddObject(std::string, std::string, I3ConverterPtr, I3FrameObjectConstPtr))
> ERROR (I3Module): I3TableWriter_0000: Exception thrown (I3Module.cxx:118 in void I3Module::Do(void (I3Module::*)()))
> Traceback (most recent call last):
>   File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/source/tableio/resources/test/test_converters.py", line 105, in <module>
>     tray.Execute(1)
>   File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/I3Tray.py", line 238, in Execute
>     super(I3Tray, self).Execute(args[0])
>   File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/icecube/tableio/I3TableWriterModule.py", line 209, in Physics
>     return self.handle_frame(frame)
>   File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/icecube/tableio/I3TableWriterModule.py", line 205, in handle_frame
>     self.writer.convert(frame)
> RuntimeError: No converter found for 'I3CLastFitParams' of type 'I3CLastFitParams' (in bool I3TableWriter::AddObject(std::string, std::string, I3ConverterPtr, I3FrameObjectConstPtr))
> ERROR (I3TableService): Table 'BootstrapParams' is still connected, which means that the output file was never properly closed. This is a BUG!
>  (I3TableService.cxx:219 in virtual I3TableService::~I3TableService())
> }}}
>

**Comment by icecube-trac** [comment]
Trac update at 20160909T21:31:16: jvansanten commented:

> I can't reproduce this on cobalt with py2-v3_early_access.

**Comment by icecube-trac** [comment]
Trac update at 20160910T22:53:30: jvansanten commented:

> Edit: reproducible on kipple.
> 
> The issue is that I3CLastFitParams has its virtual destructor (which is there only to force a vtable for RTTI) defined inline, allowing the implementation to plunk the vtable into any translation unit it pleases. As a result, the recclasses library and recclasses pybindings have ''different'' vtables for I3CLastFitParams, and the `typeid`-based comparison used inside of tableio fails for objects created from Python. There are at least 15 instances of this in recclasses:
> 
> 
> ```text
> [jvansanten@kipple]/build/jvs/icerec/debug% grep '~' ../src/recclasses/public/recclasses/*.h
> ../src/recclasses/public/recclasses/CramerRaoParams.h:  virtual ~CramerRaoParams();
> ../src/recclasses/public/recclasses/I3CLastFitParams.h:    virtual ~I3CLastFitParams() {};
> ../src/recclasses/public/recclasses/I3CscdLlhFitParams.h:    ~I3CscdLlhFitParams() {};
> ../src/recclasses/public/recclasses/I3DipoleFitParams.h:  virtual ~I3DipoleFitParams() {};
> ../src/recclasses/public/recclasses/I3DirectHitsValues.h:    ~I3DirectHitsValues()
> ../src/recclasses/public/recclasses/I3FillRatioInfo.h:    ~I3FillRatioInfo(){}
> ../src/recclasses/public/recclasses/I3FiniteCuts.h:  ~I3FiniteCuts(){}
> ../src/recclasses/public/recclasses/I3HitMultiplicityValues.h:    ~I3HitMultiplicityValues()
> ../src/recclasses/public/recclasses/I3LaputopParams.h:  virtual ~I3LaputopParams() {}
> ../src/recclasses/public/recclasses/I3LineFitParams.h:    virtual ~I3LineFitParams() {}
> ../src/recclasses/public/recclasses/I3OpheliaFirstGuessTrack.h:     virtual ~I3OpheliaFirstGuessTrack() {}
> ../src/recclasses/public/recclasses/I3OpheliaParticle.h:     virtual ~I3OpheliaParticle() {}
> ../src/recclasses/public/recclasses/I3OpheliaRecoResult.h:   virtual ~I3OpheliaRecoResult() {}
> ../src/recclasses/public/recclasses/I3ParticleIntersections.h:  virtual ~I3ParticleIntersections() {}
> ../src/recclasses/public/recclasses/I3StartStopParams.h:  virtual ~I3StartStopParams(){}
> ../src/recclasses/public/recclasses/I3STConfiguration.h:    ~I3STConfiguration();
> ../src/recclasses/public/recclasses/I3TensorOfInertiaFitParams.h:    virtual ~I3TensorOfInertiaFitParams() {};
> ../src/recclasses/public/recclasses/I3TopLateralFitParams.h:  virtual ~I3TopLateralFitParams() {};
> ../src/recclasses/public/recclasses/I3TopRecoPlaneFitParams.h:  virtual ~I3TopRecoPlaneFitParams() {};
> ../src/recclasses/public/recclasses/I3Veto.h:  virtual ~I3Veto();
> ../src/recclasses/public/recclasses/I3Veto.h:  virtual ~I3VetoShort();
> ../src/recclasses/public/recclasses/OMKeyLink.h:    ~OMKeyLink();
> ../src/recclasses/public/recclasses/OMKeyLinkSet.h:    ~OMKeyLinkSet();
> ../src/recclasses/public/recclasses/OMKeyPair.h:    ~OMKeyPair();
> ../src/recclasses/public/recclasses/OMKeySet.h:    ~OMKeySet();
> ```
> 
> I'm not entirely sure why this ''ever'' worked.

**Comment by icecube-trac** [comment]
Trac update at 20160913T14:12:46: jvansanten commented:

> Fixed in r150001

**Comment by icecube-trac** [comment]
Trac update at 20170117T18:43:42: 
* olivas changed status from "new" to "closed"
* olivas changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:13:18: 
* olivas changed milestone from "September 2016" to ""
* olivas commented:

> Milestone September 2016 deleted
