### ISSUE TITLE
[fill-ratio] Test failure (Trac #1855)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1847]
```text
        Start 189: fill-ratio::FillRatioTest.py
189/424 Test #189: fill-ratio::FillRatioTest.py ...................................***Failed    5.17 sec
INFO (I3Module): Opened file /build/ports/test-data/event-viewer/Level3aGCD_IC79_EEData_Run00115990.i3 (I3Reader.cxx:180 in void I3Reader::OpenNextFile())
INFO (I3FillRatioModule): Configuring the I3FillRatio (I3FillRatioModule.cxx:97 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): VertexName              : clast (I3FillRatioModule.cxx:112 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): ResultName              : FillRatioTest (I3FillRatioModule.cxx:113 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): RecoPulseName           : MaskedOfflinePulses (I3FillRatioModule.cxx:114 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): SphericalRadiusRMS      : 3.500000 (I3FillRatioModule.cxx:115 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): SphericalRadiusMean     : 2.000000 (I3FillRatioModule.cxx:116 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): AmplitudeWeightingPower : 0.000000 => no weighting (I3FillRatioModule.cxx:120 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): BadOms [size of list]   : 0 (I3FillRatioModule.cxx:132 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): Configuring the I3FillRatio (I3FillRatioModule.cxx:97 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): VertexName              : clast (I3FillRatioModule.cxx:112 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): ResultName              : FillRatioInfo (I3FillRatioModule.cxx:113 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): RecoPulseName           : MaskedOfflinePulses (I3FillRatioModule.cxx:114 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): SphericalRadiusRMS      : 3.000000 (I3FillRatioModule.cxx:115 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): SphericalRadiusMean     : 2.000000 (I3FillRatioModule.cxx:116 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): AmplitudeWeightingPower : 0.000000 => no weighting (I3FillRatioModule.cxx:120 in virtual void I3FillRatioModule::Configure())
INFO (I3FillRatioModule): BadOms [size of list]   : 0 (I3FillRatioModule.cxx:132 in virtual void I3FillRatioModule::Configure())
FATAL (I3FillRatio2StringDoubleMap): FillRatioInfo DOES NOT EXIST (I3FillRatio2StringDoubleMap.cxx:93 in virtual void I3FillRatio2StringDoubleMap::Physics(I3FramePtr))
ERROR (I3Module): FR_to_Map_segment: Exception thrown (I3Module.cxx:118 in void I3Module::Do(void (I3Module::*)()))
Traceback (most recent call last):
  File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/source/fill-ratio/resources/tests/FillRatioTest.py", line 48, in <module>
    tray.Execute()
  File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/I3Tray.py", line 240, in Execute
    super(I3Tray, self).Execute()
RuntimeError: FillRatioInfo DOES NOT EXIST (in virtual void I3FillRatio2StringDoubleMap::Physics(I3FramePtr))
```

Migrated from https://code.icecube.wisc.edu/ticket/1855
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:13:18", 
    "description": "{{{\n        Start 189: fill-ratio::FillRatioTest.py\n189/424 Test #189: fill-ratio::FillRatioTest.py ...................................***Failed    5.17 sec\nINFO (I3Module): Opened file /build/ports/test-data/event-viewer/Level3aGCD_IC79_EEData_Run00115990.i3 (I3Reader.cxx:180 in void I3Reader::OpenNextFile())\nINFO (I3FillRatioModule): Configuring the I3FillRatio (I3FillRatioModule.cxx:97 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): VertexName              : clast (I3FillRatioModule.cxx:112 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): ResultName              : FillRatioTest (I3FillRatioModule.cxx:113 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): RecoPulseName           : MaskedOfflinePulses (I3FillRatioModule.cxx:114 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): SphericalRadiusRMS      : 3.500000 (I3FillRatioModule.cxx:115 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): SphericalRadiusMean     : 2.000000 (I3FillRatioModule.cxx:116 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): AmplitudeWeightingPower : 0.000000 => no weighting (I3FillRatioModule.cxx:120 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): BadOms [size of list]   : 0 (I3FillRatioModule.cxx:132 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): Configuring the I3FillRatio (I3FillRatioModule.cxx:97 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): VertexName              : clast (I3FillRatioModule.cxx:112 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): ResultName              : FillRatioInfo (I3FillRatioModule.cxx:113 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): RecoPulseName           : MaskedOfflinePulses (I3FillRatioModule.cxx:114 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): SphericalRadiusRMS      : 3.000000 (I3FillRatioModule.cxx:115 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): SphericalRadiusMean     : 2.000000 (I3FillRatioModule.cxx:116 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): AmplitudeWeightingPower : 0.000000 => no weighting (I3FillRatioModule.cxx:120 in virtual void I3FillRatioModule::Configure())\nINFO (I3FillRatioModule): BadOms [size of list]   : 0 (I3FillRatioModule.cxx:132 in virtual void I3FillRatioModule::Configure())\nFATAL (I3FillRatio2StringDoubleMap): FillRatioInfo DOES NOT EXIST (I3FillRatio2StringDoubleMap.cxx:93 in virtual void I3FillRatio2StringDoubleMap::Physics(I3FramePtr))\nERROR (I3Module): FR_to_Map_segment: Exception thrown (I3Module.cxx:118 in void I3Module::Do(void (I3Module::*)()))\nTraceback (most recent call last):\n  File \"/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/source/fill-ratio/resources/tests/FillRatioTest.py\", line 48, in <module>\n    tray.Execute()\n  File \"/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/I3Tray.py\", line 240, in Execute\n    super(I3Tray, self).Execute()\nRuntimeError: FillRatioInfo DOES NOT EXIST (in virtual void I3FillRatio2StringDoubleMap::Physics(I3FramePtr))\n}}}", 
    "reporter": "olivas", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1550067198646291", 
    "component": "combo reconstruction", 
    "summary": "[fill-ratio] Test failure", 
    "priority": "critical", 
    "keywords": "", 
    "time": "2016-09-09T18:29:13", 
    "milestone": "", 
    "owner": "mjl5147", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20160909T18:33:53: david.schultz changed description from:

>         Start 189: fill-ratio::FillRatioTest.py
> 189/424 Test #189: fill-ratio::FillRatioTest.py ...................................***Failed    5.17 sec
> INFO (I3Module): Opened file /build/ports/test-data/event-viewer/Level3aGCD_IC79_EEData_Run00115990.i3 (I3Reader.cxx:180 in void I3Reader::OpenNextFile())
> INFO (I3FillRatioModule): Configuring the I3FillRatio (I3FillRatioModule.cxx:97 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): VertexName              : clast (I3FillRatioModule.cxx:112 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): ResultName              : FillRatioTest (I3FillRatioModule.cxx:113 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): RecoPulseName           : MaskedOfflinePulses (I3FillRatioModule.cxx:114 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): SphericalRadiusRMS      : 3.500000 (I3FillRatioModule.cxx:115 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): SphericalRadiusMean     : 2.000000 (I3FillRatioModule.cxx:116 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): AmplitudeWeightingPower : 0.000000 => no weighting (I3FillRatioModule.cxx:120 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): BadOms [size of list]   : 0 (I3FillRatioModule.cxx:132 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): Configuring the I3FillRatio (I3FillRatioModule.cxx:97 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): VertexName              : clast (I3FillRatioModule.cxx:112 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): ResultName              : FillRatioInfo (I3FillRatioModule.cxx:113 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): RecoPulseName           : MaskedOfflinePulses (I3FillRatioModule.cxx:114 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): SphericalRadiusRMS      : 3.000000 (I3FillRatioModule.cxx:115 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): SphericalRadiusMean     : 2.000000 (I3FillRatioModule.cxx:116 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): AmplitudeWeightingPower : 0.000000 => no weighting (I3FillRatioModule.cxx:120 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): BadOms [size of list]   : 0 (I3FillRatioModule.cxx:132 in virtual void I3FillRatioModule::Configure())
> FATAL (I3FillRatio2StringDoubleMap): FillRatioInfo DOES NOT EXIST (I3FillRatio2StringDoubleMap.cxx:93 in virtual void I3FillRatio2StringDoubleMap::Physics(I3FramePtr))
> ERROR (I3Module): FR_to_Map_segment: Exception thrown (I3Module.cxx:118 in void I3Module::Do(void (I3Module::*)()))
> Traceback (most recent call last):
>   File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/source/fill-ratio/resources/tests/FillRatioTest.py", line 48, in <module>
>     tray.Execute()
>   File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/I3Tray.py", line 240, in Execute
>     super(I3Tray, self).Execute()
> RuntimeError: FillRatioInfo DOES NOT EXIST (in virtual void I3FillRatio2StringDoubleMap::Physics(I3FramePtr))
> 

to:

> {{{
>         Start 189: fill-ratio::FillRatioTest.py
> 189/424 Test #189: fill-ratio::FillRatioTest.py ...................................***Failed    5.17 sec
> INFO (I3Module): Opened file /build/ports/test-data/event-viewer/Level3aGCD_IC79_EEData_Run00115990.i3 (I3Reader.cxx:180 in void I3Reader::OpenNextFile())
> INFO (I3FillRatioModule): Configuring the I3FillRatio (I3FillRatioModule.cxx:97 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): VertexName              : clast (I3FillRatioModule.cxx:112 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): ResultName              : FillRatioTest (I3FillRatioModule.cxx:113 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): RecoPulseName           : MaskedOfflinePulses (I3FillRatioModule.cxx:114 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): SphericalRadiusRMS      : 3.500000 (I3FillRatioModule.cxx:115 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): SphericalRadiusMean     : 2.000000 (I3FillRatioModule.cxx:116 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): AmplitudeWeightingPower : 0.000000 => no weighting (I3FillRatioModule.cxx:120 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): BadOms [size of list]   : 0 (I3FillRatioModule.cxx:132 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): Configuring the I3FillRatio (I3FillRatioModule.cxx:97 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): VertexName              : clast (I3FillRatioModule.cxx:112 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): ResultName              : FillRatioInfo (I3FillRatioModule.cxx:113 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): RecoPulseName           : MaskedOfflinePulses (I3FillRatioModule.cxx:114 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): SphericalRadiusRMS      : 3.000000 (I3FillRatioModule.cxx:115 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): SphericalRadiusMean     : 2.000000 (I3FillRatioModule.cxx:116 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): AmplitudeWeightingPower : 0.000000 => no weighting (I3FillRatioModule.cxx:120 in virtual void I3FillRatioModule::Configure())
> INFO (I3FillRatioModule): BadOms [size of list]   : 0 (I3FillRatioModule.cxx:132 in virtual void I3FillRatioModule::Configure())
> FATAL (I3FillRatio2StringDoubleMap): FillRatioInfo DOES NOT EXIST (I3FillRatio2StringDoubleMap.cxx:93 in virtual void I3FillRatio2StringDoubleMap::Physics(I3FramePtr))
> ERROR (I3Module): FR_to_Map_segment: Exception thrown (I3Module.cxx:118 in void I3Module::Do(void (I3Module::*)()))
> Traceback (most recent call last):
>   File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/source/fill-ratio/resources/tests/FillRatioTest.py", line 48, in <module>
>     tray.Execute()
>   File "/build/buildslave/kipple_cvmfs/Scientific_Linux_6__new___cvmfs_/build/lib/I3Tray.py", line 240, in Execute
>     super(I3Tray, self).Execute()
> RuntimeError: FillRatioInfo DOES NOT EXIST (in virtual void I3FillRatio2StringDoubleMap::Physics(I3FramePtr))
> }}}

**Comment by icecube-trac** [comment]
Trac update at 20170330T18:59:41: 
* olivas changed resolution from "" to "fixed"
* olivas commented:

> Assuming this is fixed since we don't see the failure anymore.


* olivas changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:13:18: 
* olivas commented:

> Milestone September 2016 deleted


* olivas changed milestone from "September 2016" to ""
