### ISSUE TITLE
[icetray] Adding object to frame twice with same key gives bus error rather than exception (Trac #1869)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1861]
Migrated from https://code.icecube.wisc.edu/ticket/1869
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:13:24", 
    "description": "", 
    "reporter": "markw04", 
    "cc": "", 
    "resolution": "worksforme", 
    "_ts": "1550067204154158", 
    "component": "combo core", 
    "summary": "[icetray] Adding object to frame twice with same key gives bus error rather than exception", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2016-10-01T10:00:56", 
    "milestone": "", 
    "owner": "olivas", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20161001T10:01:46: markw04 changed component from "cmake" to "simulation"

**Comment by icecube-trac** [comment]
Trac update at 20161017T17:18:06: 
* olivas changed summary from "[Bootcamp] Adding object to frame twice with same key gives bus error rather than exception" to "[icetray] Adding object to frame twice with same key gives bus error rather than exception"
* olivas changed owner from "" to "olivas"
* olivas changed component from "simulation" to "icecube offline"
* olivas changed status from "new" to "accepted"
* olivas changed milestone from "" to "October 2016"

**Comment by icecube-trac** [comment]
Trac update at 20161116T08:25:24: kjmeagher commented:

> I cannot reproduce this, can you provide an example script?
> 
> 
> ```text
> from I3Tray import *
> from icecube import icetray
> 
> def f(frame):
>     frame["asdf"]=icetray.I3Bool(True)
>     frame["asdf"]=icetray.I3Bool(False)
> 
> tray = I3Tray()
> tray.Add("BottomlessSource", stream = icetray.I3Frame.Physics)
> tray.Add(f)
> tray.Execute()
> tray.Finish()
> ```
> 
> Provides the following informative error message 
> 
> 
> ```text
> INFO (I3Tray): Adding Anonymous Module of type 'BottomlessSource' with name 'BottomlessSource_0000' (I3Tray.py:75 in _create_name)
> INFO (I3Tray): Adding Anonymous Module of type '<function f at 0x10d864aa0>' with name 'f_0000' (I3Tray.py:75 in _create_name)
> FATAL (icetray): frame already contains "asdf", of type "I3PODHolder<bool>" (I3Frame.cxx:282 in void I3Frame::Put(const string &, I3FrameObjectConstPtr, const I3Frame::Stream &))
> ERROR (PythonFunction): Error running python function as module: (PythonFunction.cxx:173 in virtual void PythonFunction::Process())
> ERROR (I3Module): f_0000: Exception thrown (I3Module.cxx:118 in void I3Module::Do(void (I3Module::*)()))
> Traceback (most recent call last):
>   File "t.py", line 11, in <module>
>     tray.Execute()
>   File "/Users/kmeagher/icecube/combo/release/lib/I3Tray.py", line 240, in Execute
>     super(I3Tray, self).Execute()
>   File "t.py", line 6, in f
>     frame["asdf"]=icetray.I3Bool(False)
> RuntimeError: frame already contains "asdf", of type "I3PODHolder<bool>" (in void I3Frame::Put(const string &, I3FrameObjectConstPtr, const I3Frame::Stream &))
> ```
>

**Comment by icecube-trac** [comment]
Trac update at 20161116T16:25:34: olivas commented:

> If I remember correctly this on a Mac.  Might need an OSX box to reproduce.

**Comment by icecube-trac** [comment]
Trac update at 20161116T16:41:14: kjmeagher commented:

> That was from my macbook running El Cap

**Comment by icecube-trac** [comment]
Trac update at 20161116T17:54:30: 
* olivas changed resolution from "" to "worksforme"
* olivas commented:

> Hmm...ok...I think we have to close this as 'worksforme' then.


* olivas changed status from "accepted" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:13:24: 
* olivas changed milestone from "October 2016" to ""
* olivas commented:

> Milestone October 2016 deleted
