### ISSUE TITLE
Sn2ms page updater trying to write to read-only file system (Trac #1908)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1900]
Traceback (most recent call last):
  File "/home/hitspool/Sn2msHTML/Sn2msPageUpdater.py", line 62, in <module>
    process_wrapper()
  File "/home/hitspool/Sn2msHTML/Sn2msPageUpdater.py", line 41, in process_wrapper
    plot_sn2ms.make_panel_plots(sf)
  File "/home/hitspool/Sn2msHTML/plot_sn2ms.py", line 83, in make_panel_plots
    fig.savefig(plotname)
  File "/cvmfs/icecube.opensciencegrid.org/py2-v1/RHEL_6_x86_64/lib/python2.7/site-packages/matplotlib/figure.py", line 1421, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/cvmfs/icecube.opensciencegrid.org/py2-v1/RHEL_6_x86_64/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2220, in print_figure
    **kwargs)
  File "/cvmfs/icecube.opensciencegrid.org/py2-v1/RHEL_6_x86_64/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 510, in print_png
    filename_or_obj = open(filename_or_obj, 'wb')
IOError: [Errno 30] Read-only file system: '/data/ana/Supernova/sn2ms/2016/1007/cand2ms12858615_panelplot.png'

Migrated from https://code.icecube.wisc.edu/ticket/1908
```json
{
    "status": "closed", 
    "changetime": "2016-11-06T21:15:53", 
    "description": "Traceback (most recent call last):\n  File \"/home/hitspool/Sn2msHTML/Sn2msPageUpdater.py\", line 62, in <module>\n    process_wrapper()\n  File \"/home/hitspool/Sn2msHTML/Sn2msPageUpdater.py\", line 41, in process_wrapper\n    plot_sn2ms.make_panel_plots(sf)\n  File \"/home/hitspool/Sn2msHTML/plot_sn2ms.py\", line 83, in make_panel_plots\n    fig.savefig(plotname)\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v1/RHEL_6_x86_64/lib/python2.7/site-packages/matplotlib/figure.py\", line 1421, in savefig\n    self.canvas.print_figure(*args, **kwargs)\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v1/RHEL_6_x86_64/lib/python2.7/site-packages/matplotlib/backend_bases.py\", line 2220, in print_figure\n    **kwargs)\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v1/RHEL_6_x86_64/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py\", line 510, in print_png\n    filename_or_obj = open(filename_or_obj, 'wb')\nIOError: [Errno 30] Read-only file system: '/data/ana/Supernova/sn2ms/2016/1007/cand2ms12858615_panelplot.png'", 
    "reporter": "dheereman", 
    "cc": "gmoment, dheereman", 
    "resolution": "fixed", 
    "_ts": "1478466953660485", 
    "component": "other", 
    "summary": "Sn2ms page updater trying to write to read-only file system", 
    "priority": "normal", 
    "keywords": "hitspool processing", 
    "time": "2016-11-06T20:12:51", 
    "milestone": "", 
    "owner": "dheereman", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20161106T21:15:53: 
* dheereman changed resolution from "" to "fixed"
* dheereman changed status from "new" to "closed"
* dheereman commented:

> Solved by manually deleting product and reprocessing via:
> hitspool@cobalt05 ~/Sn2msHTML $ python Sn2msPageUpdater.py 
>
