### ISSUE TITLE
[simclasses] should contain `I3PhotonSeriesMap` (Trac #1910)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1902]
In `steamshovel` I cannot display photon paths. I get the following warning:

**`WARN (steamshovel): PyArtist PhotonPaths cannot be used for the following reason: AttributeError: 'module' object has no attribute 'I3PhotonSeriesMap'`**

== Details ==

- Version: icecube-simulation V05-00-06 (I did a fresh checkout and build).
- Steamshovel output:

```text
➜  steamshovel $ICESIM_ROOT/src/clsim/resources/scripts/flasher/StandardCandle/test_flashesSC_clsim.i3
/Users/fiedl/Library/Python/2.7/lib/python/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
WARN (steamshovel): PyArtist PhotonPaths cannot be used for the following reason:
Traceback (most recent call last):
  File "/Users/fiedl/icecube/software/icecube-simulation-V05-00-06/debug_build/lib/icecube/steamshovel/artists/PhotonPaths.py", line 7, in <module>
    class PhotonPaths( PyArtist ):
  File "/Users/fiedl/icecube/software/icecube-simulation-V05-00-06/debug_build/lib/icecube/steamshovel/artists/PhotonPaths.py", line 21, in PhotonPaths
    requiredTypes = [ simclasses.I3PhotonSeriesMap, dataclasses.I3MCTree ]
AttributeError: 'module' object has no attribute 'I3PhotonSeriesMap' (ArtistRegistry.cpp:85 in void ArtistRegistry::registerPythonArtists())
```

- The `I3PhotonSeriesMap` headers are missing in `simclasses`:

```text
[17:11:08] fiedl@fiedl-mbp: ~/icecube/software/icecube-simulation-V05-00-06/src/simclasses/public/simclasses
➜  ls
CorsikaLongStep.h     I3MCNKGInfo.h         I3MCPulse.h           I3ParticleIDMap.hpp
I3CorsikaShowerInfo.h I3MCPE.h              I3MMCTrack.h          I3WimpParams.h
```

- svn info:

```text
[17:11:09] fiedl@fiedl-mbp: ~/icecube/software/icecube-simulation-V05-00-06/src/simclasses/public/simclasses
➜  svn info $I3_SRC/simclasses/
Path: /Users/fiedl/icecube/software/icecube-simulation-V05-00-06/src/simclasses
Working Copy Root Path: /Users/fiedl/icecube/software/icecube-simulation-V05-00-06/src/simclasses
URL: http://code.icecube.wisc.edu/svn/projects/simclasses/releases/V02-00-00
Relative URL: ^/projects/simclasses/releases/V02-00-00
Repository Root: http://code.icecube.wisc.edu/svn
Repository UUID: 16731396-06f5-0310-8873-f7f720988828
Revision: 144450
Node Kind: directory
Schedule: normal
Last Changed Author: olivas
Last Changed Rev: 144450
Last Changed Date: 2016-04-09 04:23:43 +0200 (Sa, 09 Apr 2016)
```

== Further references ==

- https://icecube-spno.slack.com/archives/software/p1479225700002987
- https://icecube-spno.slack.com/archives/software/p1479226410003013
- https://icecube-spno.slack.com/archives/software/p1479226736003034

Migrated from https://code.icecube.wisc.edu/ticket/1910
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:13:32", 
    "description": "In `steamshovel` I cannot display photon paths. I get the following warning:\n\n**`WARN (steamshovel): PyArtist PhotonPaths cannot be used for the following reason: AttributeError: 'module' object has no attribute 'I3PhotonSeriesMap'`**\n\n== Details ==\n\n- Version: icecube-simulation V05-00-06 (I did a fresh checkout and build).\n- Steamshovel output:\n\n{{{\n\u279c  steamshovel $ICESIM_ROOT/src/clsim/resources/scripts/flasher/StandardCandle/test_flashesSC_clsim.i3\n/Users/fiedl/Library/Python/2.7/lib/python/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.\n  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')\nWARN (steamshovel): PyArtist PhotonPaths cannot be used for the following reason:\nTraceback (most recent call last):\n  File \"/Users/fiedl/icecube/software/icecube-simulation-V05-00-06/debug_build/lib/icecube/steamshovel/artists/PhotonPaths.py\", line 7, in <module>\n    class PhotonPaths( PyArtist ):\n  File \"/Users/fiedl/icecube/software/icecube-simulation-V05-00-06/debug_build/lib/icecube/steamshovel/artists/PhotonPaths.py\", line 21, in PhotonPaths\n    requiredTypes = [ simclasses.I3PhotonSeriesMap, dataclasses.I3MCTree ]\nAttributeError: 'module' object has no attribute 'I3PhotonSeriesMap' (ArtistRegistry.cpp:85 in void ArtistRegistry::registerPythonArtists())\n}}}\n\n- The `I3PhotonSeriesMap` headers are missing in `simclasses`:\n\n{{{\n[17:11:08] fiedl@fiedl-mbp: ~/icecube/software/icecube-simulation-V05-00-06/src/simclasses/public/simclasses\n\u279c  ls\nCorsikaLongStep.h     I3MCNKGInfo.h         I3MCPulse.h           I3ParticleIDMap.hpp\nI3CorsikaShowerInfo.h I3MCPE.h              I3MMCTrack.h          I3WimpParams.h\n}}}\n\n- svn info:\n\n{{{\n[17:11:09] fiedl@fiedl-mbp: ~/icecube/software/icecube-simulation-V05-00-06/src/simclasses/public/simclasses\n\u279c  svn info $I3_SRC/simclasses/\nPath: /Users/fiedl/icecube/software/icecube-simulation-V05-00-06/src/simclasses\nWorking Copy Root Path: /Users/fiedl/icecube/software/icecube-simulation-V05-00-06/src/simclasses\nURL: http://code.icecube.wisc.edu/svn/projects/simclasses/releases/V02-00-00\nRelative URL: ^/projects/simclasses/releases/V02-00-00\nRepository Root: http://code.icecube.wisc.edu/svn\nRepository UUID: 16731396-06f5-0310-8873-f7f720988828\nRevision: 144450\nNode Kind: directory\nSchedule: normal\nLast Changed Author: olivas\nLast Changed Rev: 144450\nLast Changed Date: 2016-04-09 04:23:43 +0200 (Sa, 09 Apr 2016)\n}}}\n\n== Further references ==\n\n- https://icecube-spno.slack.com/archives/software/p1479225700002987\n- https://icecube-spno.slack.com/archives/software/p1479226410003013\n- https://icecube-spno.slack.com/archives/software/p1479226736003034", 
    "reporter": "fiedl", 
    "cc": "", 
    "resolution": "wontfix", 
    "_ts": "1550067212810271", 
    "component": "combo simulation", 
    "summary": "[simclasses] should contain `I3PhotonSeriesMap`", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2016-11-15T18:01:58", 
    "milestone": "", 
    "owner": "olivas", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20161115T22:03:00: 
* olivas changed owner from "" to "olivas"
* olivas changed milestone from "" to "November 2016"
* olivas changed status from "new" to "accepted"

**Comment by icecube-trac** [comment]
Trac update at 20161216T16:41:47: fiedl commented:

> Same issue in V05-00-07. I just did a fresh build.
> Cheers, Sebastian

**Comment by icecube-trac** [comment]
Trac update at 20170118T19:19:44: 
* olivas changed milestone from "November 2016" to "January 2017"
* olivas changed summary from "`simclasses` should contain `I3PhotonSeriesMap`" to "[simclasses] should contain `I3PhotonSeriesMap`"

**Comment by icecube-trac** [comment]
Trac update at 20170330T19:06:14: olivas changed milestone from "January 2017" to "March 2017"

**Comment by icecube-trac** [comment]
Trac update at 20170420T16:58:14: 
* olivas changed status from "accepted" to "closed"
* olivas changed resolution from "" to "wontfix"
* olivas commented:

> IceSim 5.1 is about to be released and won't have this issue.  I'm assuming switching to the new release isn't going to be a problem.  If we actually need to get an incremental 5.0 release out with this fixed, feel free to reopen this ticket.

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:13:32: 
* olivas changed milestone from "March 2017" to ""
* olivas commented:

> Milestone March 2017 deleted
