### ISSUE TITLE
Steamshovel runs into a segmentation fault (Trac #1944)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1936]
I'm trying to use steamshovel but it runs immediately into a segmentation fault after I start it. I'm using Ubuntu 16.04 with the offline-software (trunk) metaproject. 
This is what I got from GDB:

```text
lrrr@laptop:~/files.ln/icetray/offline-software/trunk/build/bin $ gdb steamshovel
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from steamshovel...(no debugging symbols found)...done.
(gdb) run
Starting program: /media/lrrr/linuxData/files/icetray/offline-software/trunk/build/bin/steamshovel 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
You have PySide installed, which creates a conflict with Steamshovel's use of IPython and PyQt4/PyQt5. The embedded Python shell in Steamshovel will be disabled. Remove PySide to correct this issue.
WARN (steamshovel): Cannot embed IPython Qt widget, falling back to tty-based console (embed.cpp:95 in scripting::PyConsole::PyConsole(const scripting::PyInterpreter&, scripting::PyConsole::Type))

Program received signal SIGSEGV, Segmentation fault.
__memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:865
865	../sysdeps/x86_64/multiarch/memcmp-sse4.S: No such file or directory.
(gdb) backtrace
https://code.icecube.wisc.edu/ticket/0  __memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:865
#1  0x00007fffe1cd3498 in QMetaType::registerNormalizedType(QByteArray const&, void (*)(void*), void* (*)(void*, void const*), int, QFlags<QMetaType::TypeFlag>, QMetaObject const*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007fffe2076964 in ?? () from /usr/lib/python2.7/dist-packages/PyQt5/QtCore.x86_64-linux-gnu.so
#3  0x00007fffe2076a00 in ?? () from /usr/lib/python2.7/dist-packages/PyQt5/QtCore.x86_64-linux-gnu.so
#4  0x00007fffe20765f1 in ?? () from /usr/lib/python2.7/dist-packages/PyQt5/QtCore.x86_64-linux-gnu.so
#5  0x00007ffff5a6d4e7 in _PyImport_LoadDynamicModule () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#6  0x00007ffff5a6e300 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#7  0x00007ffff5a6e5c8 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#8  0x00007ffff5a6f6db in PyImport_ImportModuleLevel () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#9  0x00007ffff59e6698 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#10 0x00007ffff5a321e3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#11 0x00007ffff5b08447 in PyEval_CallObjectWithKeywords () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#12 0x00007ffff59db5c6 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#13 0x00007ffff5b0901c in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#14 0x00007ffff59decfd in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#15 0x00007ffff5b0901c in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#16 0x00007ffff5a5f2e0 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#17 0x00007ffff5a321e3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#18 0x00007ffff5b08447 in PyEval_CallObjectWithKeywords () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#19 0x00007ffff5a66f17 in PyEval_CallFunction () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#20 0x000000000051b21a in scripting::PyConsole::init_python_shell(bool) ()
#21 0x000000000051badd in scripting::PyConsole::PyConsole(scripting::PyInterpreter const&, scripting::PyConsole::Type) ()
#22 0x0000000000496271 in main ()
(gdb) quit
```

Thank you in advance!

Migrated from https://code.icecube.wisc.edu/ticket/1944
```json
{
    "status": "closed", 
    "changetime": "2017-02-02T10:19:38", 
    "description": "I'm trying to use steamshovel but it runs immediately into a segmentation fault after I start it. I'm using Ubuntu 16.04 with the offline-software (trunk) metaproject. \nThis is what I got from GDB:\n{{{\nlrrr@laptop:~/files.ln/icetray/offline-software/trunk/build/bin $ gdb steamshovel\nGNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1\nCopyright (C) 2016 Free Software Foundation, Inc.\nLicense GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.  Type \"show copying\"\nand \"show warranty\" for details.\nThis GDB was configured as \"x86_64-linux-gnu\".\nType \"show configuration\" for configuration details.\nFor bug reporting instructions, please see:\n<http://www.gnu.org/software/gdb/bugs/>.\nFind the GDB manual and other documentation resources online at:\n<http://www.gnu.org/software/gdb/documentation/>.\nFor help, type \"help\".\nType \"apropos word\" to search for commands related to \"word\"...\nReading symbols from steamshovel...(no debugging symbols found)...done.\n(gdb) run\nStarting program: /media/lrrr/linuxData/files/icetray/offline-software/trunk/build/bin/steamshovel \n[Thread debugging using libthread_db enabled]\nUsing host libthread_db library \"/lib/x86_64-linux-gnu/libthread_db.so.1\".\nYou have PySide installed, which creates a conflict with Steamshovel's use of IPython and PyQt4/PyQt5. The embedded Python shell in Steamshovel will be disabled. Remove PySide to correct this issue.\nWARN (steamshovel): Cannot embed IPython Qt widget, falling back to tty-based console (embed.cpp:95 in scripting::PyConsole::PyConsole(const scripting::PyInterpreter&, scripting::PyConsole::Type))\n\nProgram received signal SIGSEGV, Segmentation fault.\n__memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:865\n865\t../sysdeps/x86_64/multiarch/memcmp-sse4.S: No such file or directory.\n(gdb) backtrace\n#0  __memcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:865\n#1  0x00007fffe1cd3498 in QMetaType::registerNormalizedType(QByteArray const&, void (*)(void*), void* (*)(void*, void const*), int, QFlags<QMetaType::TypeFlag>, QMetaObject const*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5\n#2  0x00007fffe2076964 in ?? () from /usr/lib/python2.7/dist-packages/PyQt5/QtCore.x86_64-linux-gnu.so\n#3  0x00007fffe2076a00 in ?? () from /usr/lib/python2.7/dist-packages/PyQt5/QtCore.x86_64-linux-gnu.so\n#4  0x00007fffe20765f1 in ?? () from /usr/lib/python2.7/dist-packages/PyQt5/QtCore.x86_64-linux-gnu.so\n#5  0x00007ffff5a6d4e7 in _PyImport_LoadDynamicModule () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#6  0x00007ffff5a6e300 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#7  0x00007ffff5a6e5c8 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#8  0x00007ffff5a6f6db in PyImport_ImportModuleLevel () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#9  0x00007ffff59e6698 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#10 0x00007ffff5a321e3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#11 0x00007ffff5b08447 in PyEval_CallObjectWithKeywords () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#12 0x00007ffff59db5c6 in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#13 0x00007ffff5b0901c in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#14 0x00007ffff59decfd in PyEval_EvalFrameEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#15 0x00007ffff5b0901c in PyEval_EvalCodeEx () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#16 0x00007ffff5a5f2e0 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#17 0x00007ffff5a321e3 in PyObject_Call () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#18 0x00007ffff5b08447 in PyEval_CallObjectWithKeywords () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#19 0x00007ffff5a66f17 in PyEval_CallFunction () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0\n#20 0x000000000051b21a in scripting::PyConsole::init_python_shell(bool) ()\n#21 0x000000000051badd in scripting::PyConsole::PyConsole(scripting::PyInterpreter const&, scripting::PyConsole::Type) ()\n#22 0x0000000000496271 in main ()\n(gdb) quit\n}}}\n\nThank you in advance!", 
    "reporter": "thomas.kittler", 
    "cc": "nega", 
    "resolution": "fixed", 
    "_ts": "1486030778189213", 
    "component": "combo core", 
    "summary": "Steamshovel runs into a segmentation fault", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2017-01-31T11:10:47", 
    "milestone": "", 
    "owner": "sander.vanheule", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20170131T17:44:15: 
* olivas changed cc from "" to "nega"
* olivas changed owner from "" to "sander.vanheule"
* olivas changed status from "new" to "assigned"

**Comment by icecube-trac** [comment]
Trac update at 20170201T16:53:52: sander.vanheule commented:

> Since Thomas' build was performed with the default value for the USE_QT5 CMake flag (USE_QT5=OFF) steamshovel itself was linked to Qt4.
> 
> However, the console embedding code ''always'' refers to PyQt5, irrespective of the linked Qt version:
> source:/IceCube/projects/steamshovel/trunk/python/embed/console_widget.py.in
> source:/IceCube/projects/steamshovel/trunk/python/embed/console.py.in

**Comment by icecube-trac** [comment]
Trac update at 20170201T17:11:07: nega commented:

> This is more or less intentional, and USE_QT5 should go away as an option. Support for Qt4 ended over a year ago, and Qt5 has been out even longer. Flipping the switch to Qt5 only though, should have a co-ordinated release among the three major meta-projects.
> 
> Dual version support is doable, but will take more work than solely supporting Qt5

**Comment by icecube-trac** [comment]
Trac update at 20170201T17:15:39: thomas.kittler commented:

> if I use:
> ```  
> $ QT_API=pyqt4 steamshovel --noconsole
> ```
> I don't run into the segmentation fault and I can use steamshovel (without any interactive python of course).

**Comment by icecube-trac** [comment]
Trac update at 20170201T17:31:14: 
* nega changed status from "assigned" to "closed"
* nega commented:

> In changeset 153095:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="153095"
> fix Qt versioning in steamshovel
> 
> Changeset r152138/IceCube was incomplete and didn't do variable
> subistitution on all the files it should have.
> 
> see r152138/IceCube
> 
> closes #1936
> ```


* nega changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20170201T17:31:36: nega commented:

> I take that back about  it being intentional. I dorked up the commit.
> 
> Looking back at r152138/IceCube, I can see that I only added CMake variable substitution for one file. Not all of them. Easy enough to fix.

**Comment by icecube-trac** [comment]
Trac update at 20170202T10:19:38: sander.vanheule commented:

> r153108/IceCube makes sure QWidget is properly imported depending on the PyQt version. QWidget has moved from the QtGui to the (new) QtWidgets module in Qt5.
> 
> Caveats for using steamshovel at this point:
> 1. The system default for PyQt might conflict with steamshovel's Qt version. If it segfaults on the PyConsole when calling a Qt library, try setting the QT_API environment variable to the same version as steamshovel's.
>   * steamshovel compiled with Qt4 (the default):
>     
> ```text
>     $ QT_API=pyqt steamshovel
>     ```
>   * steamshovel compiled with Qt5:
>     
> ```text
>     $ QT_API=pyqt5 steamshovel
>     ```
> 2. We tell CMake to configure python files in-place in the source tree and then symlink everything in the build directory. As a consequence, you cannot simultaneously have one build directory that uses Qt4 and a second that uses Qt5, because the python source code will be configured for whichever build was performed last.
>
