### ISSUE TITLE
[filterscripts] Exception if no best Fit was found (Trac #1950)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1942]
Hello,

I am encountering this:

```text
ERROR (PythonFunction): Error running python function as module: (PythonFunction.cxx:173 in virtual void PythonFunction::Process())
ERROR (I3Module): OnlineL2_findBestSucceededFit: Exception thrown (I3Module.cxx:116 in void I3Module::Do(void (I3Module::*)()))
Traceback (most recent call last):
  File "/data/user/flauber/scripts/executables/SimulationFiltering.py", line 412, in <module>
    main(opts)
  File "/data/user/flauber/scripts/executables/SimulationFiltering.py", line 371, in main
    tray.Execute()
  File "/mnt/lfs3/user/flauber/software/icerec_V05-00-05/build/lib/I3Tray.py", line 234, in Execute
    super(I3Tray, self).Execute()
  File "/mnt/lfs3/user/flauber/software/icerec_V05-00-05/build/lib/icecube/filterscripts/onlinel2filter.py", line 570, in findBestSucceededFit
    frame.Put(name+"_BestFitName", "None")
Boost.Python.ArgumentError: Python argument types in
    I3Frame.Put(I3Frame, str, str)
did not match C++ signature:
    Put(I3Frame {lvalue}, std::string, boost::shared_ptr<I3FrameObject const>, I3Frame::Stream)
    Put(I3Frame {lvalue}, std::string, boost::shared_ptr<I3FrameObject const>)
```

while running SimulationFiltering.py from filterscripts/resources/scripts

I guess, the "None" needs to be wrapped to become an dataclasses.I3String or similar.

Migrated from https://code.icecube.wisc.edu/ticket/1950
```json
{
    "status": "closed", 
    "changetime": "2017-02-20T09:08:11", 
    "description": "Hello,\n\nI am encountering this:\n{{{\nERROR (PythonFunction): Error running python function as module: (PythonFunction.cxx:173 in virtual void PythonFunction::Process())\nERROR (I3Module): OnlineL2_findBestSucceededFit: Exception thrown (I3Module.cxx:116 in void I3Module::Do(void (I3Module::*)()))\nTraceback (most recent call last):\n  File \"/data/user/flauber/scripts/executables/SimulationFiltering.py\", line 412, in <module>\n    main(opts)\n  File \"/data/user/flauber/scripts/executables/SimulationFiltering.py\", line 371, in main\n    tray.Execute()\n  File \"/mnt/lfs3/user/flauber/software/icerec_V05-00-05/build/lib/I3Tray.py\", line 234, in Execute\n    super(I3Tray, self).Execute()\n  File \"/mnt/lfs3/user/flauber/software/icerec_V05-00-05/build/lib/icecube/filterscripts/onlinel2filter.py\", line 570, in findBestSucceededFit\n    frame.Put(name+\"_BestFitName\", \"None\")\nBoost.Python.ArgumentError: Python argument types in\n    I3Frame.Put(I3Frame, str, str)\ndid not match C++ signature:\n    Put(I3Frame {lvalue}, std::string, boost::shared_ptr<I3FrameObject const>, I3Frame::Stream)\n    Put(I3Frame {lvalue}, std::string, boost::shared_ptr<I3FrameObject const>)\n}}}\n\nwhile running SimulationFiltering.py from filterscripts/resources/scripts\n\nI guess, the \"None\" needs to be wrapped to become an dataclasses.I3String or similar.\n", 
    "reporter": "flauber", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1487581691387840", 
    "component": "combo reconstruction", 
    "summary": "[filterscripts] Exception if no best Fit was found", 
    "priority": "normal", 
    "keywords": "filterscripts", 
    "time": "2017-02-20T08:51:22", 
    "milestone": "", 
    "owner": "thomas.kintscher", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20170220T09:08:11: 
* thomas.kintscher changed owner from "" to "thomas.kintscher"
* thomas.kintscher changed resolution from "" to "fixed"
* thomas.kintscher changed status from "new" to "closed"
* thomas.kintscher commented:

> In changeset 153415:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="153415"
> In the rare case of a HESE event with no successful likelihood fit at all,
> convert the absence of a best fit into a proper I3String (fixes #1942).
> ```
