### ISSUE TITLE
[icetray] Memory tracking blows the stack on exit (Trac #1973)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#1965]
If I run this script with memory tracking enabled on SL6 with devtoolset-2:

```text
from icecube import icetray, dataclasses, dataio
from I3Tray import I3Tray

tray = I3Tray()

tray.Add("I3InfiniteSource")

t = icetray.memory.MemoryTimeline()
t.start(10000)
tray.Execute(1)
t.stop

tray.Finish()

```

it runs to completion, and I can do things like plot the memory timeline. Then, after the interpreter exits, it segfaults:

```text
https://code.icecube.wisc.edu/ticket/0  0x00007ffff6e38b80 in _int_malloc () from /lib64/libc.so.6
#1  0x00007ffff6e39b1c in malloc () from /lib64/libc.so.6
#2  0x00007ffff048d3c4 in memory::malloc_override(unsigned long) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so
#3  0x00007ffff048d509 in operator new(unsigned long) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so
#4  0x00007fffee5303c9 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) ()
   from /usr/lib64/libstdc++.so.6
#5  0x00007fffee530de5 in ?? () from /usr/lib64/libstdc++.so.6
#6  0x00007fffee530f33 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) () from /usr/lib64/libstdc++.so.6
#7  0x00007ffff048bcc2 in boost::thread_exception::thread_exception(int, char const*) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so
#8  0x00007ffff048d4b5 in memory::malloc_override(unsigned long) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so
#9  0x00007ffff048d509 in operator new(unsigned long) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so
#10 0x00007fffee5303c9 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) ()
   from /usr/lib64/libstdc++.so.6
#11 0x00007fffee530de5 in ?? () from /usr/lib64/libstdc++.so.6
#12 0x00007fffee530f33 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) () from /usr/lib64/libstdc++.so.6
#13 0x00007ffff048bcc2 in boost::thread_exception::thread_exception(int, char const*) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so
#14 0x00007ffff048d4b5 in memory::malloc_override(unsigned long) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so
#15 0x00007ffff048d509 in operator new(unsigned long) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so
#16 0x00007fffee5303c9 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) ()
   from /usr/lib64/libstdc++.so.6
```
and so on for 248174 frames.

I suspect that global objects may be getting destroyed in an unexpected order.

Migrated from https://code.icecube.wisc.edu/ticket/1973
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:14:44", 
    "description": "If I run this script with memory tracking enabled on SL6 with devtoolset-2:\n{{{\nfrom icecube import icetray, dataclasses, dataio\nfrom I3Tray import I3Tray\n\ntray = I3Tray()\n\ntray.Add(\"I3InfiniteSource\")\n\nt = icetray.memory.MemoryTimeline()\nt.start(10000)\ntray.Execute(1)\nt.stop\n\ntray.Finish()\n\n}}}\n\nit runs to completion, and I can do things like plot the memory timeline. Then, after the interpreter exits, it segfaults:\n\n{{{\n#0  0x00007ffff6e38b80 in _int_malloc () from /lib64/libc.so.6\n#1  0x00007ffff6e39b1c in malloc () from /lib64/libc.so.6\n#2  0x00007ffff048d3c4 in memory::malloc_override(unsigned long) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so\n#3  0x00007ffff048d509 in operator new(unsigned long) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so\n#4  0x00007fffee5303c9 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) ()\n   from /usr/lib64/libstdc++.so.6\n#5  0x00007fffee530de5 in ?? () from /usr/lib64/libstdc++.so.6\n#6  0x00007fffee530f33 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) () from /usr/lib64/libstdc++.so.6\n#7  0x00007ffff048bcc2 in boost::thread_exception::thread_exception(int, char const*) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so\n#8  0x00007ffff048d4b5 in memory::malloc_override(unsigned long) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so\n#9  0x00007ffff048d509 in operator new(unsigned long) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so\n#10 0x00007fffee5303c9 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) ()\n   from /usr/lib64/libstdc++.so.6\n#11 0x00007fffee530de5 in ?? () from /usr/lib64/libstdc++.so.6\n#12 0x00007fffee530f33 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) () from /usr/lib64/libstdc++.so.6\n#13 0x00007ffff048bcc2 in boost::thread_exception::thread_exception(int, char const*) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so\n#14 0x00007ffff048d4b5 in memory::malloc_override(unsigned long) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so\n#15 0x00007ffff048d509 in operator new(unsigned long) () from /scratch/jvs/metaprojects/simulation/build/lib/libicetray.so\n#16 0x00007fffee5303c9 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_S_create(unsigned long, unsigned long, std::allocator<char> const&) ()\n   from /usr/lib64/libstdc++.so.6\n}}}\nand so on for 248174 frames.\n\nI suspect that global objects may be getting destroyed in an unexpected order.", 
    "reporter": "jvansanten", 
    "cc": "cweaver, david.schultz", 
    "resolution": "fixed", 
    "_ts": "1550067284370534", 
    "component": "combo core", 
    "summary": "[icetray] Memory tracking blows the stack on exit", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2017-03-23T10:04:27", 
    "milestone": "", 
    "owner": "nega", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20170323T10:16:26: jvansanten commented:

> Also, if I never harvest the tracking info, I end up with
> 
> ```text
> python -c "from icecube import icetray"
> terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
> terminate called recursively
> ```

**Comment by icecube-trac** [comment]
Trac update at 20170323T13:36:59: 
* david.schultz changed milestone from "April 2017" to "July 2017"
* david.schultz changed status from "new" to "accepted"

**Comment by icecube-trac** [comment]
Trac update at 20170515T15:11:59: david.schultz commented:

> Looking at just the `python -c 'from icecube import icetray'` line right now.
> 
> I think this started failing when we took over serialization.  A hint to that is this stack trace part:
> 
> 
> ```text
> #21 0x00007fffedb56a2a in __gnu_cxx::new_allocator<std::_Rb_tree_node<icecube::serialization::typeid_system::extended_type_info_typeid_0 const*> >::deallocate (
>     this=0x7fffeddbb7a0 <icecube::serialization::singleton<std::multiset<icecube::serialization::typeid_system::extended_type_info_typeid_0 const*, 
>     icecube::serialization::typeid_system::type_compare, std::allocator<icecube::serialization::typeid_system::extended_type_info_typeid_0 const*> > >::get_instance()::t>, __p=0x6cb810)
> ```
> 
> It looks like something with our usage of the `icecube::serialization::singleton` for `icetray/public/icetray/i3_extended_type_info.h`.
> 
>

**Comment by icecube-trac** [comment]
Trac update at 20170515T15:24:05: nega commented:

> In changeset 2891:
> 
> ```text
> #!CommitTicketReference repository="IceTray" revision="2891"
> disable memory tracking for now
> 
> this should be disabled until it's confirmed to build, and work
> locally.  see #1965
> ```

**Comment by icecube-trac** [comment]
Trac update at 20170515T16:34:21: 
* david.schultz changed cc from "" to "cweaver"
* david.schultz commented:

> I've confirmed that when I initially merged memory tracking in r2605/IceTray it didn't segfault.  That was just after cweaver added the initial serialization code.
> 
> I guess time to start the bisection process.

**Comment by icecube-trac** [comment]
Trac update at 20170515T17:35:33: 
* david.schultz commented:

> Here's the commit: r2660/IceTray
> 
> Apparently the linker isn't smart enough to link libstdc++ correctly.
> 
> When I revert that commit to trunk, it magically works again.


* david.schultz changed cc from "cweaver" to "cweaver, nega"

**Comment by icecube-trac** [comment]
Trac update at 20170515T17:54:30: nega commented:

> interesting. it should be smart enough. i guess it depends on how the linker is being called in icetray. what if libstdc++ is added only to icetray? does everything still crap out? forcing libstdc++ is going to cause problems with clang's libc++ in the future
>

**Comment by icecube-trac** [comment]
Trac update at 20170515T18:48:31: 
* david.schultz commented:

> If I only add it to icetray, it works fine.  But I had to manually link it to get the library ordering right.  When linking `lib/icecube/icetray.so`, it needs to come before `lib/libicetray.so`.
> 
> My guess is that if I built with clang and libc++, it wouldn't need libstdc++.  So maybe so sort of conditional in cmake based on which compiler/library is in use?


* david.schultz changed _comment0 from:

> If I only add it to icetray, it works fine.  But I had to manually link it to get the library ordering right.  When linking `lib/icecube/icetray.so`, it needs to come before `lib/libicetray.so`.
> 
> My guess is that if I built with clang and libc++, it wouldn't need libstc++.  So maybe so sort of conditional in cmake based on which compiler/library is in use?

to:

> 1494877177298751

**Comment by icecube-trac** [comment]
Trac update at 20170515T19:40:17: 
* david.schultz changed cc from "cweaver, nega" to "cweaver, david.schultz"
* david.schultz changed status from "accepted" to "assigned"
* david.schultz changed owner from "david.schultz" to "nega"

**Comment by icecube-trac** [comment]
Trac update at 20170516T14:11:26: nega commented:

> reverting r2660/IceTray, I still get segfaults

**Comment by icecube-trac** [comment]
Trac update at 20170516T22:01:16: david.schultz commented:

> Which OS are you testing on?  There might be another error for non-SL6.

**Comment by icecube-trac** [comment]
Trac update at 20170914T15:02:16: 
* david.schultz changed status from "assigned" to "closed"
* david.schultz changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20190111T20:58:55: nwhitehorn commented:

> In changeset 168816:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="168816"
> disable memory tracking for now
> 
> this should be disabled until it's confirmed to build, and work
> locally.  see #1965
> ```

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:14:44: 
* olivas commented:

> Milestone July 2017 deleted


* olivas changed milestone from "July 2017" to ""
