### ISSUE TITLE
[filterscripts] bug in gfu filter? (Trac #2031)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2023]
When running simulationFiltering.py, this was found.

```text
ERROR (I3Module): GammaFollowUp_BDT_Up: Exception thrown (I3Module.cxx:120 in void I3Module::Do(void (I3Module::*)()))
Traceback (most recent call last):
  File "/data/user/ssarkar/IceRec/build-trunk/filterscripts/resources/scripts/SimulationFiltering.py", line 357, in <module>
    main(opts)
  File "/data/user/ssarkar/IceRec/build-trunk/filterscripts/resources/scripts/SimulationFiltering.py", line 314, in main
    tray.Execute()
  File "/data/user/ssarkar/IceRec/build-trunk/lib/I3Tray.py", line 256, in Execute
    super(I3Tray, self).Execute()
  File "/data/user/ssarkar/IceRec/build-trunk/lib/icecube/filterscripts/gfufilter.py", line 668, in <lambda>
    If          = lambda f: If(f) and EventHasBasicReco(f) and (not EventIsDowngoing(f)) and EventPassesUpgoingPrecuts(f)
  File "/data/user/ssarkar/IceRec/build-trunk/lib/icecube/filterscripts/gfufilter.py", line 616, in EventPassesUpgoingPrecuts
    var = get_bdt_vars_up(frame)
  File "/data/user/ssarkar/IceRec/build-trunk/lib/icecube/filterscripts/gfufilter.py", line 559, in get_bdt_vars_up
    BayesLlhDiff          = replace_nan(clip(frame['OnlineL2_BayesianFitFitParams'].logl - frame['OnlineL2_SPE2itFitFitParams'].logl, -100.), -100.),
KeyError: 'OnlineL2_BayesianFitFitParams'
```

Migrated from https://code.icecube.wisc.edu/ticket/2031
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:13:53", 
    "description": "When running simulationFiltering.py, this was found.\n\n{{{\nERROR (I3Module): GammaFollowUp_BDT_Up: Exception thrown (I3Module.cxx:120 in void I3Module::Do(void (I3Module::*)()))\nTraceback (most recent call last):\n  File \"/data/user/ssarkar/IceRec/build-trunk/filterscripts/resources/scripts/SimulationFiltering.py\", line 357, in <module>\n    main(opts)\n  File \"/data/user/ssarkar/IceRec/build-trunk/filterscripts/resources/scripts/SimulationFiltering.py\", line 314, in main\n    tray.Execute()\n  File \"/data/user/ssarkar/IceRec/build-trunk/lib/I3Tray.py\", line 256, in Execute\n    super(I3Tray, self).Execute()\n  File \"/data/user/ssarkar/IceRec/build-trunk/lib/icecube/filterscripts/gfufilter.py\", line 668, in <lambda>\n    If          = lambda f: If(f) and EventHasBasicReco(f) and (not EventIsDowngoing(f)) and EventPassesUpgoingPrecuts(f)\n  File \"/data/user/ssarkar/IceRec/build-trunk/lib/icecube/filterscripts/gfufilter.py\", line 616, in EventPassesUpgoingPrecuts\n    var = get_bdt_vars_up(frame)\n  File \"/data/user/ssarkar/IceRec/build-trunk/lib/icecube/filterscripts/gfufilter.py\", line 559, in get_bdt_vars_up\n    BayesLlhDiff          = replace_nan(clip(frame['OnlineL2_BayesianFitFitParams'].logl - frame['OnlineL2_SPE2itFitFitParams'].logl, -100.), -100.),\nKeyError: 'OnlineL2_BayesianFitFitParams'\n}}}", 
    "reporter": "david.schultz", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1550067233566919", 
    "component": "combo reconstruction", 
    "summary": "[filterscripts] bug in gfu filter?", 
    "priority": "major", 
    "keywords": "", 
    "time": "2017-05-23T21:20:14", 
    "milestone": "", 
    "owner": "thomas.kintscher", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20170524T11:53:56: 
* thomas.kintscher commented:

> This is fixed in the V17-05-00 release of filterscripts, or in the trunk as of revision 155658.


* thomas.kintscher changed resolution from "" to "fixed"
* thomas.kintscher changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:13:53: 
* olivas changed milestone from "May 2017" to ""
* olivas commented:

> Milestone May 2017 deleted
