### ISSUE TITLE
[hdfwriter] gets fatal RunTimeError, file not properly closed, message: "This is a BUG" (Trac #2104)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2096]
I'm not sure if this is problem of the hdfwriter of the processing before. I didn't get any errors when I produced the i3 files. I can open them without problem and use them as i3 files without issues, but when I try to convert them to hdf5 I get this error.

Here is the complete traceback:

Traceback (most recent call last):
  File "s0040-m_divide_data_years_in_LE_HE_low_high_samples_i3_to_hdf5_s0233.py", line 128, in <module>
    tray.Execute()
  File "/home/lunger/data/meta-projects/processing/release/V05-00-00/trunk/build/lib/I3Tray.py", line 234, in Execute
    super(I3Tray, self).Execute()
  File "/home/lunger/data/meta-projects/processing/release/V05-00-00/trunk/build/lib/icecube/tableio/I3TableWriterModule.py", line 209, in Physics
    return self.handle_frame(frame)
  File "/home/lunger/data/meta-projects/processing/release/V05-00-00/trunk/build/lib/icecube/tableio/I3TableWriterModule.py", line 205, in handle_frame
    self.writer.convert(frame)
RuntimeError: trying to get the address of unknown field OFUFilter_14 (in T* I3TableRow::GetPointer(const std::string&, size_t) [with T = bool])
FATAL (I3TableService): Table 'AtmCscdEnergyReco_L2' is still connected, which means that the output file was never properly closed. This is a BUG!
 (I3TableService.cxx:219 in virtual I3TableService::~I3TableService())
terminate called after throwing an instance of 'std::runtime_error'
  what():  Table 'AtmCscdEnergyReco_L2' is still connected, which means that the output file was never properly closed. This is a BUG!
 (in virtual I3TableService::~I3TableService())

Migrated from https://code.icecube.wisc.edu/ticket/2104
```json
{
    "status": "closed", 
    "changetime": "2019-03-27T16:30:49", 
    "description": "I'm not sure if this is problem of the hdfwriter of the processing before. I didn't get any errors when I produced the i3 files. I can open them without problem and use them as i3 files without issues, but when I try to convert them to hdf5 I get this error.\n\nHere is the complete traceback:\n\nTraceback (most recent call last):\n  File \"s0040-m_divide_data_years_in_LE_HE_low_high_samples_i3_to_hdf5_s0233.py\", line 128, in <module>\n    tray.Execute()\n  File \"/home/lunger/data/meta-projects/processing/release/V05-00-00/trunk/build/lib/I3Tray.py\", line 234, in Execute\n    super(I3Tray, self).Execute()\n  File \"/home/lunger/data/meta-projects/processing/release/V05-00-00/trunk/build/lib/icecube/tableio/I3TableWriterModule.py\", line 209, in Physics\n    return self.handle_frame(frame)\n  File \"/home/lunger/data/meta-projects/processing/release/V05-00-00/trunk/build/lib/icecube/tableio/I3TableWriterModule.py\", line 205, in handle_frame\n    self.writer.convert(frame)\nRuntimeError: trying to get the address of unknown field OFUFilter_14 (in T* I3TableRow::GetPointer(const std::string&, size_t) [with T = bool])\nFATAL (I3TableService): Table 'AtmCscdEnergyReco_L2' is still connected, which means that the output file was never properly closed. This is a BUG!\n (I3TableService.cxx:219 in virtual I3TableService::~I3TableService())\nterminate called after throwing an instance of 'std::runtime_error'\n  what():  Table 'AtmCscdEnergyReco_L2' is still connected, which means that the output file was never properly closed. This is a BUG!\n (in virtual I3TableService::~I3TableService())\n", 
    "reporter": "lisa", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1553704249811581", 
    "component": "combo reconstruction", 
    "summary": "[hdfwriter] gets fatal RunTimeError, file not properly closed, message: \"This is a BUG\"", 
    "priority": "critical", 
    "keywords": "", 
    "time": "2017-10-22T10:57:04", 
    "milestone": "Vernal Equinox 2019", 
    "owner": "jvansanten", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20180515T17:54:48: 
* olivas changed status from "new" to "assigned"
* olivas changed owner from "" to "jvansanten"

**Comment by icecube-trac** [comment]
Trac update at 20180515T18:03:05: 
* jvansanten commented:

> This happens when FilterMask changes definitions in the middle of an I3Tray run, usually because different years of processing have been merged together. Is this still a problem?


* jvansanten changed _comment0 from "This happens when FilterMask changes definitions mid-file, usually because different years of processing have been merged together. Is this still a problem?" to "1526407412379756"

**Comment by icecube-trac** [comment]
Trac update at 20180515T18:35:04: kjmeagher commented:

> It sounds like it needs a better error message at the very least

**Comment by icecube-trac** [comment]
Trac update at 20180922T09:14:41: olivas changed milestone from "" to "Autumnal Equinox 2018"

**Comment by icecube-trac** [comment]
Trac update at 20180922T10:47:50: olivas changed summary from "hdfwriter gets fatal RunTimeError, file not properly closed, message: "This is a BUG"" to "[hdfwriter] gets fatal RunTimeError, file not properly closed, message: "This is a BUG""

**Comment by icecube-trac** [comment]
Trac update at 20181001T21:53:02: 
* olivas changed resolution from "" to "duplicate"
* olivas changed status from "assigned" to "closed"
* olivas commented:

> This is actually a duplicate of #1653, which was closed two years ago.  This can still happen when using old releases, however.  The error message now includes a few more hints.

**Comment by icecube-trac** [comment]
Trac update at 20181119T15:53:03: 
* olivas changed resolution from "duplicate" to ""
* olivas changed status from "closed" to "reopened"
* olivas commented:

> The error message lead me to think (mistakenly) that this was a duplicate.  It's not and it's still a problem.

**Comment by icecube-trac** [comment]
Trac update at 20181127T02:29:30: olivas changed milestone from "Autumnal Equinox 2018" to "Winter Solstice 2018"

**Comment by icecube-trac** [comment]
Trac update at 20190327T16:30:49: 
* olivas changed resolution from "" to "fixed"
* olivas commented:

> This is fixed...-ish.


* olivas changed status from "reopened" to "closed"
