### ISSUE TITLE
steamshovel - "headless' tests dump core (Trac #2112)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2104]
Several of the tests in `resources/test/shovelscripts/` (which are run by `resources/test/test_shovelscripts.py`) throw a segmentation fault when run. Initially I thought this was a semi-known bug in the Intel GPU drivers, but further testing confirms the segfaults on Radeon and recent NVIDIA GPUS. 

The backtrace looks like:

```text
(gdb) bt 
https://code.icecube.wisc.edu/ticket/0  0x00007ffff3e89470 in QOpenGLContext::shareGroup() const () from /usr/lib/libQt5Gui.so.5
#1  0x00007ffff417de4c in QOpenGLFunctions::initializeOpenGLFunctions() () from /usr/lib/libQt5Gui.so.5
#2  0x00007ffff4d39d97 in ?? () from /usr/lib/libQt5OpenGL.so.5
#3  0x00007ffff4d3ae4e in QGLFramebufferObject::QGLFramebufferObject(int, int, QGLFramebufferObjectFormat const&) () from /usr/lib/libQt5OpenGL.so.5
#4  0x00005555557c3647 in I3GLWidget::ScreenshotContext::ScreenshotContext (this=0x7fffffffd340, w=0x555556ce1b20, width=200, height=200, scaling_factor=1) at ../../src/steamshovel/private/steamshovel/I3GLWidget.cpp:493
#5  0x00005555557c4646 in I3GLWidget::screenshotData (this=0x555556ce1b20, xdim=200, ydim=200, scaling_factor=1) at ../../src/steamshovel/private/steamshovel/I3GLWidget.cpp:556
#6  0x00005555557c288e in I3GLWidget::screenshot_engine (this=0x555556ce1b20, xdim=200, ydim=200, filename="cylinder.png", dpi=0, scaling_factor=1, gamma_factor=1) at ../../src/steamshovel/private/steamshovel/I3GLWidget.cpp:432
#7  0x00005555557c69ce in I3GLWidget::screenshot (this=0x555556ce1b20, xdim=200, ydim=200, name="cylinder.png", gamma_factor=1) at ../../src/steamshovel/private/steamshovel/I3GLWidget.h:124
#8  0x00005555557bd22d in I3GLWidget::qt_static_metacall (_o=0x555556ce1b20, _c=QMetaObject::InvokeMetaMethod, _id=21, _a=0x7fffd7fcd710) at steamshovel_autogen/include/moc_I3GLWidget.cpp:228
#9  0x00007ffff391f662 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#10 0x00007ffff464d13c in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
```

Given that: 
  1) The code in question is rather old
  1) The docs for the related Qt functions (for Qt4 and Qt5) state we will get a crash if we do what we're doing

I suspect that we may have been getting away with something in Qt4, that has since been "tightened up"  in Qt5. 

Migrated from https://code.icecube.wisc.edu/ticket/2112
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:49:18", 
    "description": "Several of the tests in `resources/test/shovelscripts/` (which are run by `resources/test/test_shovelscripts.py`) throw a segmentation fault when run. Initially I thought this was a semi-known bug in the Intel GPU drivers, but further testing confirms the segfaults on Radeon and recent NVIDIA GPUS. \n\nThe backtrace looks like:\n{{{\n(gdb) bt \n#0  0x00007ffff3e89470 in QOpenGLContext::shareGroup() const () from /usr/lib/libQt5Gui.so.5\n#1  0x00007ffff417de4c in QOpenGLFunctions::initializeOpenGLFunctions() () from /usr/lib/libQt5Gui.so.5\n#2  0x00007ffff4d39d97 in ?? () from /usr/lib/libQt5OpenGL.so.5\n#3  0x00007ffff4d3ae4e in QGLFramebufferObject::QGLFramebufferObject(int, int, QGLFramebufferObjectFormat const&) () from /usr/lib/libQt5OpenGL.so.5\n#4  0x00005555557c3647 in I3GLWidget::ScreenshotContext::ScreenshotContext (this=0x7fffffffd340, w=0x555556ce1b20, width=200, height=200, scaling_factor=1) at ../../src/steamshovel/private/steamshovel/I3GLWidget.cpp:493\n#5  0x00005555557c4646 in I3GLWidget::screenshotData (this=0x555556ce1b20, xdim=200, ydim=200, scaling_factor=1) at ../../src/steamshovel/private/steamshovel/I3GLWidget.cpp:556\n#6  0x00005555557c288e in I3GLWidget::screenshot_engine (this=0x555556ce1b20, xdim=200, ydim=200, filename=\"cylinder.png\", dpi=0, scaling_factor=1, gamma_factor=1) at ../../src/steamshovel/private/steamshovel/I3GLWidget.cpp:432\n#7  0x00005555557c69ce in I3GLWidget::screenshot (this=0x555556ce1b20, xdim=200, ydim=200, name=\"cylinder.png\", gamma_factor=1) at ../../src/steamshovel/private/steamshovel/I3GLWidget.h:124\n#8  0x00005555557bd22d in I3GLWidget::qt_static_metacall (_o=0x555556ce1b20, _c=QMetaObject::InvokeMetaMethod, _id=21, _a=0x7fffd7fcd710) at steamshovel_autogen/include/moc_I3GLWidget.cpp:228\n#9  0x00007ffff391f662 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5\n#10 0x00007ffff464d13c in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5\n}}}\n\nGiven that: \n  1) The code in question is rather old\n  1) The docs for the related Qt functions (for Qt4 and Qt5) state we will get a crash if we do what we're doing\n\nI suspect that we may have been getting away with something in Qt4, that has since been \"tightened up\"  in Qt5. \n", 
    "reporter": "nega", 
    "cc": "nega", 
    "resolution": "insufficient resources", 
    "_ts": "1550069358694099", 
    "component": "analysis", 
    "summary": "steamshovel - \"headless' tests dump core", 
    "priority": "minor", 
    "keywords": "steamshovel, Qt, opengl, segrault", 
    "time": "2017-11-15T16:32:42", 
    "milestone": "Long-Term Future", 
    "owner": "olivas", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20171115T16:33:22: nega commented:

> Since the whole "headless steamshovel testing" never worked super great anyway, I'm fine with kicking this can down the road.

**Comment by icecube-trac** [comment]
Trac update at 20171115T16:53:38: nega commented:

> Some thoughts...
> 
> So segfaulting in `QOpenGLContext::shareGroup()` seems to be fairly "common" on Intel GPUS, and seems to be Intel's fault. At least according to the Googles. 
> 
> Our problem is the step !#3 of the bt, the call constructor for [source:IceCube/projects/steamshovel/trunk/private/steamshovel/I3GLWidget.cpp@151930:488#L488 QGLFramebufferObject]. The [https://doc.qt.io/qt-5/qglframebufferobject.html#details docs state]:
> 
>   '''It is important to have a current GL context when creating a QGLFramebufferObject, otherwise initialization will fail.''' 
> Which is what we're doing. They also state that `GLFrameBufferObject` is deprecated, but swapping it out for its replacement class doesn't seem to do anything.
> 
> What I don't understand right now is: why this is only failing in tests? Assumedly anyone taking a screenshot or making a movie should see this same crash. It would probably make sense to look at the failing tests first, before digging deeper into the screenshot/movie code or doing any Qt4 vs Qt5 comparisons.

**Comment by icecube-trac** [comment]
Trac update at 20180922T12:23:54: 
* olivas changed status from "new" to "assigned"
* olivas changed owner from "sander.vanheule" to "olivas"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:49:18: 
* olivas changed status from "assigned" to "closed"
* olivas changed resolution from "" to "insufficient resources"
