### ISSUE TITLE
[toprec] update examples (Trac #2116)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2108]
Some of the example scripts are using things that don't exist anymore, like flat-ntuple.

```text
amedina@cobalt02 ~/combo/build/toprec/resources/examples $ python try_gulliverized_fourstep_fitter.py
FATAL (I3Tray): Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /home/amedina/combo/build/lib/libflat-ntuple.so: cannot open shared object file: No such file or directory (I3Tray.py:36 in load)
Traceback (most recent call last):
 File "try_gulliverized_fourstep_fitter.py", line 20, in <module>
   load("libflat-ntuple")
 File "/home/amedina/combo/build/lib/I3Tray.py", line 36, in load
   % (sys.exc_info()[0], sys.exc_info()[1]), "I3Tray")
 File "/home/amedina/combo/build/lib/icecube/icetray/i3logging.py", line 152, in log_fatal
   raise RuntimeError(message + " (in " + tb[2] + ")")
RuntimeError: Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /home/amedina/combo/build/lib/libflat-ntuple.so: cannot open shared object file: No such file or directory (in load)
```

One easy way to make sure these stay current is to call them from tests, so we see the breakage. 

Migrated from https://code.icecube.wisc.edu/ticket/2116
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T14:14:51", 
    "description": "Some of the example scripts are using things that don't exist anymore, like flat-ntuple.\n\n{{{\namedina@cobalt02 ~/combo/build/toprec/resources/examples $ python try_gulliverized_fourstep_fitter.py\nFATAL (I3Tray): Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /home/amedina/combo/build/lib/libflat-ntuple.so: cannot open shared object file: No such file or directory (I3Tray.py:36 in load)\nTraceback (most recent call last):\n File \"try_gulliverized_fourstep_fitter.py\", line 20, in <module>\n   load(\"libflat-ntuple\")\n File \"/home/amedina/combo/build/lib/I3Tray.py\", line 36, in load\n   % (sys.exc_info()[0], sys.exc_info()[1]), \"I3Tray\")\n File \"/home/amedina/combo/build/lib/icecube/icetray/i3logging.py\", line 152, in log_fatal\n   raise RuntimeError(message + \" (in \" + tb[2] + \")\")\nRuntimeError: Failed to load library (<type 'exceptions.RuntimeError'>): dlopen() dynamic loading error: /home/amedina/combo/build/lib/libflat-ntuple.so: cannot open shared object file: No such file or directory (in load)\n}}}\n\nOne easy way to make sure these stay current is to call them from tests, so we see the breakage. ", 
    "reporter": "david.schultz", 
    "cc": "kjmeagher", 
    "resolution": "wontfix", 
    "_ts": "1550067291068818", 
    "component": "combo reconstruction", 
    "summary": "[toprec] update examples", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2017-11-21T17:24:02", 
    "milestone": "", 
    "owner": "kath", 
    "type": "cleanup"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20180607T16:26:20: 
* olivas changed resolution from "" to "wontfix"
* olivas changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:14:51: 
* olivas changed milestone from "December 2017" to ""
* olivas commented:

> Milestone December 2017 deleted
