### ISSUE TITLE
Services cannot be accessed if the simclasses python module is loaded before load("libdataio") (Trac #211)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#211]
If in a python script 

```text
  from icecube import simclasses
```
is done before

```text
  load("libdataio")
```
modules/services in an I3Tray will not be able to Get any services from the context. The attached script "doesnotwork.py" demonstrates this. It will fail with the output:

```text
Loading libicetray........................................ok
Loading libdataio.........................................ok
Loading libsim-services...................................ok
Logging configured from file /mnt/sda7/home/fabian/Physik/software/icetray/simulation/build-release/log4cplus.conf
/mnt/sda7/home/fabian/Physik/software/icetray/simulation/src/icetray/public/icetray/I3Context.h:127: FATAL: bad any cast getting object "I3EventService" out of context as "I3EventService"
Traceback (most recent call last):
  File "./doesnotwork.py", line 32, in <module>
    tray.Execute(4)
  File "/mnt/sda7/home/fabian/Physik/software/icetray/simulation/build-release/lib/I3Tray.py", line 116, in Execute
    args[0].the_tray.Execute(args[1])
RuntimeError: bad any cast getting object "I3EventService" out of context as "I3EventService"
```
While "works.py" where the order of these two calls is reversed works just fine. Variations of this test suggest that this problem is not limited to I3EventService. The current official IC59 GCD file is needed to run the scripts.

Migrated from https://code.icecube.wisc.edu/ticket/211
```json
{
    "status": "closed", 
    "changetime": "2011-04-15T09:41:21", 
    "description": "If in a python script \n{{{\n  from icecube import simclasses\n}}}\nis done before\n{{{\n  load(\"libdataio\")\n}}}\nmodules/services in an I3Tray will not be able to Get any services from the context. The attached script \"doesnotwork.py\" demonstrates this. It will fail with the output:\n{{{\nLoading libicetray........................................ok\nLoading libdataio.........................................ok\nLoading libsim-services...................................ok\nLogging configured from file /mnt/sda7/home/fabian/Physik/software/icetray/simulation/build-release/log4cplus.conf\n/mnt/sda7/home/fabian/Physik/software/icetray/simulation/src/icetray/public/icetray/I3Context.h:127: FATAL: bad any cast getting object \"I3EventService\" out of context as \"I3EventService\"\nTraceback (most recent call last):\n  File \"./doesnotwork.py\", line 32, in <module>\n    tray.Execute(4)\n  File \"/mnt/sda7/home/fabian/Physik/software/icetray/simulation/build-release/lib/I3Tray.py\", line 116, in Execute\n    args[0].the_tray.Execute(args[1])\nRuntimeError: bad any cast getting object \"I3EventService\" out of context as \"I3EventService\"\n}}}\nWhile \"works.py\" where the order of these two calls is reversed works just fine. Variations of this test suggest that this problem is not limited to I3EventService. The current official IC59 GCD file is needed to run the scripts.", 
    "reporter": "kislat", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1302860481000000", 
    "component": "combo simulation", 
    "summary": "Services cannot be accessed if the simclasses python module is loaded before load(\"libdataio\")", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2010-09-08T13:47:33", 
    "milestone": "", 
    "owner": "olivas", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20110414T19:07:23: blaufuss changed owner from "kislat" to "olivas"

**Comment by icecube-trac** [comment]
Trac update at 20110415T09:41:21: 
* kislat commented:

> Fixed on trunk in r69351.


* kislat changed resolution from "" to "fixed"
* kislat changed component from "icerec" to "simulation"
* kislat changed status from "new" to "closed"
