### ISSUE TITLE
weighting - crashes with AttributeError under Python3 (Trac #2120)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2112]
```text
463/470 Test #462: weighting::compare_oneweight.py ................................***Failed    1.25 sec
Traceback (most recent call last):
  File "/build/buildslave/paimon/Arch_Linux/source/weighting/resources/test/compare_oneweight.py", line 84, in <module>
    check_oneweight(dataset)
  File "/build/buildslave/paimon/Arch_Linux/source/weighting/resources/test/compare_oneweight.py", line 43, in check_oneweight
    generator = weighting.from_simprod(dataset)
  File "/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py", line 774, in from_simprod
    **nugen_kwargs)
  File "/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py", line 593, in NeutrinoGenerator
    return GenerationProbabilityCollection(probs).to_PDG()
  File "/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py", line 195, in to_PDG
    spectra += [s.to_PDG() for s in v]
  File "/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py", line 195, in <listcomp>
    spectra += [s.to_PDG() for s in v]
  File "/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py", line 68, in to_PDG
    if self.particle_type is not None and getattr(PDGCode, self.particle_type.name) == self.particle_type:
AttributeError: 'int' object has no attribute 'name'

        Start 464: weighting::corsika_weight_calculator.py
464/470 Test #463: weighting::corsika_weight_calculator.py ........................***Failed    1.65 sec
INFO (Python): Got a file for dataset 10285: http://icecube:skua@convey.icecube.wisc.edu/data/sim/IceCube/2011/generated/CORSIKA-in-ice/10285/00000-00999/IC86.2011_corsika.010285.000025.i3.bz2 (compare_oneweight.py:38 in get_random_filename)
Traceback (most recent call last):
  File "/build/buildslave/paimon/Arch_Linux/source/weighting/resources/test/corsika_weight_calculator.py", line 37, in <module>
    opts.dataset = weighting.from_simprod(opts.dataset)
  File "/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py", line 832, in from_simprod
    height=length, radius=radius)
  File "/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py", line 478, in FiveComponent
    return GenerationProbabilityCollection([PowerLaw(g, emin*mlo, emax*mhi, nevents=n, area=area, particle_type=p) for mlo, mhi, g, n, p in zip(lower_energy_scale, upper_energy_scale, gamma, nshower, pt)]).to_PDG()
  File "/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py", line 195, in to_PDG
    spectra += [s.to_PDG() for s in v]
  File "/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py", line 195, in <listcomp>
    spectra += [s.to_PDG() for s in v]
  File "/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py", line 68, in to_PDG
    if self.particle_type is not None and getattr(PDGCode, self.particle_type.name) == self.particle_type:
AttributeError: 'int' object has no attribute 'name'
```

Migrated from https://code.icecube.wisc.edu/ticket/2120
```json
{
    "status": "closed", 
    "changetime": "2019-04-17T08:15:12", 
    "description": "{{{\n463/470 Test #463: weighting::compare_oneweight.py ................................***Failed    1.25 sec\nTraceback (most recent call last):\n  File \"/build/buildslave/paimon/Arch_Linux/source/weighting/resources/test/compare_oneweight.py\", line 84, in <module>\n    check_oneweight(dataset)\n  File \"/build/buildslave/paimon/Arch_Linux/source/weighting/resources/test/compare_oneweight.py\", line 43, in check_oneweight\n    generator = weighting.from_simprod(dataset)\n  File \"/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py\", line 774, in from_simprod\n    **nugen_kwargs)\n  File \"/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py\", line 593, in NeutrinoGenerator\n    return GenerationProbabilityCollection(probs).to_PDG()\n  File \"/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py\", line 195, in to_PDG\n    spectra += [s.to_PDG() for s in v]\n  File \"/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py\", line 195, in <listcomp>\n    spectra += [s.to_PDG() for s in v]\n  File \"/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py\", line 68, in to_PDG\n    if self.particle_type is not None and getattr(PDGCode, self.particle_type.name) == self.particle_type:\nAttributeError: 'int' object has no attribute 'name'\n\n        Start 464: weighting::corsika_weight_calculator.py\n464/470 Test #464: weighting::corsika_weight_calculator.py ........................***Failed    1.65 sec\nINFO (Python): Got a file for dataset 10285: http://icecube:skua@convey.icecube.wisc.edu/data/sim/IceCube/2011/generated/CORSIKA-in-ice/10285/00000-00999/IC86.2011_corsika.010285.000025.i3.bz2 (compare_oneweight.py:38 in get_random_filename)\nTraceback (most recent call last):\n  File \"/build/buildslave/paimon/Arch_Linux/source/weighting/resources/test/corsika_weight_calculator.py\", line 37, in <module>\n    opts.dataset = weighting.from_simprod(opts.dataset)\n  File \"/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py\", line 832, in from_simprod\n    height=length, radius=radius)\n  File \"/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py\", line 478, in FiveComponent\n    return GenerationProbabilityCollection([PowerLaw(g, emin*mlo, emax*mhi, nevents=n, area=area, particle_type=p) for mlo, mhi, g, n, p in zip(lower_energy_scale, upper_energy_scale, gamma, nshower, pt)]).to_PDG()\n  File \"/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py\", line 195, in to_PDG\n    spectra += [s.to_PDG() for s in v]\n  File \"/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py\", line 195, in <listcomp>\n    spectra += [s.to_PDG() for s in v]\n  File \"/build/buildslave/paimon/Arch_Linux/build/lib/icecube/weighting/weighting.py\", line 68, in to_PDG\n    if self.particle_type is not None and getattr(PDGCode, self.particle_type.name) == self.particle_type:\nAttributeError: 'int' object has no attribute 'name'\n}}}\n", 
    "reporter": "nega", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1555488912998122", 
    "component": "combo simulation", 
    "summary": "weighting - crashes with AttributeError under Python3", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2017-12-04T20:09:47", 
    "milestone": "Long-Term Future", 
    "owner": "jvansanten", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20180613T17:42:35: olivas changed milestone from "December 2017" to "Long-Term Future"

**Comment by icecube-trac** [comment]
Trac update at 20190417T08:15:12: 
* jvansanten changed resolution from "" to "fixed"
* jvansanten changed status from "new" to "closed"
* jvansanten commented:

> Was fixed in [159962/IceCube]
