### ISSUE TITLE
steamshovel - icetopviewer widget broken with matplotlib version >= 2.1.0 (Trac #2169)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2161]
The icetop widget is broken if the matplotlib version is greater than 2.1 and produces the following error message:

```text
ERROR (steamshovel): Uncaught python exception in event loop:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 533, in print_to_buffer
    FigureCanvasAgg.draw(self)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/collections.py", line 845, in draw
    Collection.draw(self, renderer)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/collections.py", line 256, in draw
    transform, transOffset, offsets, paths = self._prepare_points()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/collections.py", line 237, in _prepare_points
    offsets = transOffset.transform_non_affine(offsets)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/transforms.py", line 2457, in transform_non_affine
    return self._a.transform_non_affine(points)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/transforms.py", line 2243, in transform_non_affine
    y_points = y.transform_non_affine(points[:, 1])
IndexError: index 1 is out of bounds for axis 1 with size 0 (SteamshovelApp.cpp:149 in virtual bool SteamshovelApp::notify(QObject*, QEvent*))
```
Tested older versions and the work fine. The ldf-plot seems to be responsible as it is crashing during the transformation to a log y axis.

Migrated from https://code.icecube.wisc.edu/ticket/2169
```json
{
    "status": "closed", 
    "changetime": "2019-03-15T20:57:31", 
    "description": "The icetop widget is broken if the matplotlib version is greater than 2.1 and produces the following error message:\n{{{\nERROR (steamshovel): Uncaught python exception in event loop:\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py\", line 533, in print_to_buffer\n    FigureCanvasAgg.draw(self)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_agg.py\", line 430, in draw\n    self.figure.draw(self.renderer)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py\", line 55, in draw_wrapper\n    return draw(artist, renderer, *args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/figure.py\", line 1295, in draw\n    renderer, self, artists, self.suppressComposite)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/image.py\", line 138, in _draw_list_compositing_images\n    a.draw(renderer)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py\", line 55, in draw_wrapper\n    return draw(artist, renderer, *args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.py\", line 2399, in draw\n    mimage._draw_list_compositing_images(renderer, self, artists)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/image.py\", line 138, in _draw_list_compositing_images\n    a.draw(renderer)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py\", line 55, in draw_wrapper\n    return draw(artist, renderer, *args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/collections.py\", line 845, in draw\n    Collection.draw(self, renderer)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/artist.py\", line 55, in draw_wrapper\n    return draw(artist, renderer, *args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/collections.py\", line 256, in draw\n    transform, transOffset, offsets, paths = self._prepare_points()\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/collections.py\", line 237, in _prepare_points\n    offsets = transOffset.transform_non_affine(offsets)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/transforms.py\", line 2457, in transform_non_affine\n    return self._a.transform_non_affine(points)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/transforms.py\", line 2243, in transform_non_affine\n    y_points = y.transform_non_affine(points[:, 1])\nIndexError: index 1 is out of bounds for axis 1 with size 0 (SteamshovelApp.cpp:149 in virtual bool SteamshovelApp::notify(QObject*, QEvent*))\n}}}\nTested older versions and the work fine. The ldf-plot seems to be responsible as it is crashing during the transformation to a log y axis.", 
    "reporter": "mplum", 
    "cc": "mplum", 
    "resolution": "fixed", 
    "_ts": "1552683451598779", 
    "component": "analysis", 
    "summary": "steamshovel - icetopviewer widget broken with matplotlib version >= 2.1.0", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2018-07-06T20:19:48", 
    "milestone": "Vernal Equinox 2019", 
    "owner": "mplum", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20180706T20:20:28: mplum changed summary from "steamshovel - icetopviewer widget broken with matplotlib version > 2.1.0" to "steamshovel - icetopviewer widget broken with matplotlib version >= 2.1.0"

**Comment by icecube-trac** [comment]
Trac update at 20180922T09:38:28: 
* olivas commented:

> Need to find an owner for steamshovel.


* olivas changed owner from "" to "olivas"
* olivas changed milestone from "" to "Winter Solstice 2018"
* olivas changed status from "new" to "assigned"

**Comment by icecube-trac** [comment]
Trac update at 20181114T14:47:00: olivas changed owner from "olivas" to ""

**Comment by icecube-trac** [comment]
Trac update at 20181211T16:35:33: 
* olivas changed owner from "" to "mplum"
* olivas changed milestone from "Winter Solstice 2018" to "Vernal Equinox 2019"

**Comment by icecube-trac** [comment]
Trac update at 20190315T15:50:57: mplum commented:

> Due to API change in matplotlib. Contacted developer for help. Added warning to widget if matplotlib is newer than 2.0.2 .

**Comment by icecube-trac** [comment]
Trac update at 20190315T20:57:31: 
* mplum commented:

> Bug fixed of widget for matplotlib versions above 2.0.2 implemented and will raise error if version is lower than 1.5.0


* mplum changed resolution from "" to "fixed"
* mplum changed status from "assigned" to "closed"
