### ISSUE TITLE
matching trigger config in trigger-sim (Trac #2175)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2167]
First, I am Elim... I know I am terrible for signing in as icecube..
but I lost my password and wasn't able to reset it.. please don't hate me...

I am trying to run
$ python /data/user/elims/strike/clsim_jessie/applytoL2.py --outfile /data/user/elims/strike/clsim_jessie/outputs/events10_toL2_test.i3.gz --infile /data/user/elims/strike/clsim_jessie/outputs/events10_clsim_lea_over1.i3 --holeice 0

The GCD file is
/data/sim/sim-new/downloadssz6dx/GCD/GeoCalibDetectorStatus_2013.56429_V1.i3.gz

The error occurs at Line 204 of /data/user/elims/strike/clsim_jessie/applytoL2.py:
> tray.AddSegment(trigger_sim.TriggerSim, 'trig',
>                gcd_file = gcd_file,
>                run_id = 1,
>                time_shift_args = time_shift_args)

The version of trigger sim used here is 163127. And the software built is the current combo/trunk.

The error message is:
> FATAL (SimpleMajorityTrigger): Failed to configure this module from the DetectorStatus.(SimpleMajorityTrigger.cxx:268 in virtual void SimpleMajorityTrigger::DetectorStatus(I3FramePtr))
> ERROR (I3Module): SimpleMajorityTrigger_0001: Exception thrown (I3Module.cxx:123 in void I3Module::Do(void (I3Module::*)()))
> Traceback (most recent call last):
>   File "applytoL2.py", line 224, in <module>
>     tray.Execute()
>   File "/data/user/elims/software/gpu_combo/debug/lib/I3Tray.py", line 256, in Execute
>    super(I3Tray, self).Execute()
> RuntimeError: Failed to configure this module from the DetectorStatus. (in virtual void SimpleMajorityTrigger::DetectorStatus(I3FramePtr))

Here is more printout from before the fatal error:
> ERROR (trigger-sim): Here's the user specified input : 
>  TypeID = 0
>  ConfigID = 1011
> (DetectorStatusUtils.h:176 in ResultType DetectorStatusUtils::boost_param_default_139GetTriggerStatus(ResultType (*)(), const Args&, int, detS
tat_type&, sourceID_type&, typeID_type&, configID_type&, subtypeID_type&) [with ResultType = boost::optional<std::pair<TriggerKey, I3TriggerSta
tus> >; Args = boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::configID, boost::optional
<int> >, boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::typeID, const TriggerKey::TypeI
D>, boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::sourceID, TriggerKey::SourceID>, boo
st::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::detStat, const boost::shared_ptr<const I3Detector
Status> >, boost::parameter::aux::empty_arg_list> > > >; detStat_type = boost::shared_ptr<const I3DetectorStatus>; sourceID_type = TriggerKey::
SourceID; typeID_type = TriggerKey::TypeID; configID_type = boost::optional<int>; subtypeID_type = TriggerKey::SubtypeID])
> ERROR (trigger-sim): Here are the keys in the I3TriggerStatus: 
> key_matches.size() == 0
>  (DetectorStatusUtils.h:186 in ResultType DetectorStatusUtils::boost_param_default_139GetTriggerStatus(ResultType (*)(), const Args&, int, detS
tat_type&, sourceID_type&, typeID_type&, configID_type&, subtypeID_type&) [with ResultType = boost::optional<std::pair<TriggerKey, I3TriggerSta
tus> >; Args = boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::configID, boost::optional
<int> >, boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::typeID, const TriggerKey::TypeI
D>, boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::sourceID, TriggerKey::SourceID>, boo
st::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::detStat, const boost::shared_ptr<const I3Detector
Status> >, boost::parameter::aux::empty_arg_list> > > >; detStat_type = boost::shared_ptr<const I3DetectorStatus>; sourceID_type = TriggerKey::
SourceID; typeID_type = TriggerKey::TypeID; configID_type = boost::optional<int>; subtypeID_type = TriggerKey::SubtypeID])
> ERROR (trigger-sim): No match found (DetectorStatusUtils.h:188 in ResultType DetectorStatusUtils::boost_param_default_139GetTriggerStatus(ResultType (*)(), const Args&, int, detStat_type&, sourceID_type&, typeID_type&, configID_type&, subtypeID_type&) [with ResultType = boost::optiona$<std::pair<TriggerKey, I3TriggerStatus> >; Args = boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusU$ils::tag::configID, boost::optional<int> >, boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::$ag::typeID, const TriggerKey::TypeID>, boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::$ourceID, TriggerKey::SourceID>, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::detStat, cons$ boost::shared_ptr<const I3DetectorStatus> >, boost::parameter::aux::empty_arg_list> > > >; detStat_type = boost::shared_ptr<const I3DetectorS$atus>; sourceID_type = TriggerKey::SourceID; typeID_type = TriggerKey::TypeID; configID_type = boost::optional<int>; subtypeID_type = TriggerK$y::SubtypeID])

Migrated from https://code.icecube.wisc.edu/ticket/2175
```json
{
    "status": "closed", 
    "changetime": "2018-07-20T16:28:05", 
    "description": "First, I am Elim... I know I am terrible for signing in as icecube..\nbut I lost my password and wasn't able to reset it.. please don't hate me...\n\nI am trying to run\n$ python /data/user/elims/strike/clsim_jessie/applytoL2.py --outfile /data/user/elims/strike/clsim_jessie/outputs/events10_toL2_test.i3.gz --infile /data/user/elims/strike/clsim_jessie/outputs/events10_clsim_lea_over1.i3 --holeice 0\n\nThe GCD file is\n/data/sim/sim-new/downloadssz6dx/GCD/GeoCalibDetectorStatus_2013.56429_V1.i3.gz\n\nThe error occurs at Line 204 of /data/user/elims/strike/clsim_jessie/applytoL2.py:\n> tray.AddSegment(trigger_sim.TriggerSim, 'trig',\n>                gcd_file = gcd_file,\n>                run_id = 1,\n>                time_shift_args = time_shift_args)\n\nThe version of trigger sim used here is 163127. And the software built is the current combo/trunk.\n\nThe error message is:\n> FATAL (SimpleMajorityTrigger): Failed to configure this module from the DetectorStatus.(SimpleMajorityTrigger.cxx:268 in virtual void SimpleMajorityTrigger::DetectorStatus(I3FramePtr))\n> ERROR (I3Module): SimpleMajorityTrigger_0001: Exception thrown (I3Module.cxx:123 in void I3Module::Do(void (I3Module::*)()))\n> Traceback (most recent call last):\n>   File \"applytoL2.py\", line 224, in <module>\n>     tray.Execute()\n>   File \"/data/user/elims/software/gpu_combo/debug/lib/I3Tray.py\", line 256, in Execute\n>    super(I3Tray, self).Execute()\n> RuntimeError: Failed to configure this module from the DetectorStatus. (in virtual void SimpleMajorityTrigger::DetectorStatus(I3FramePtr))\n\nHere is more printout from before the fatal error:\n> ERROR (trigger-sim): Here's the user specified input : \n>  TypeID = 0\n>  ConfigID = 1011\n> (DetectorStatusUtils.h:176 in ResultType DetectorStatusUtils::boost_param_default_139GetTriggerStatus(ResultType (*)(), const Args&, int, detS\ntat_type&, sourceID_type&, typeID_type&, configID_type&, subtypeID_type&) [with ResultType = boost::optional<std::pair<TriggerKey, I3TriggerSta\ntus> >; Args = boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::configID, boost::optional\n<int> >, boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::typeID, const TriggerKey::TypeI\nD>, boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::sourceID, TriggerKey::SourceID>, boo\nst::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::detStat, const boost::shared_ptr<const I3Detector\nStatus> >, boost::parameter::aux::empty_arg_list> > > >; detStat_type = boost::shared_ptr<const I3DetectorStatus>; sourceID_type = TriggerKey::\nSourceID; typeID_type = TriggerKey::TypeID; configID_type = boost::optional<int>; subtypeID_type = TriggerKey::SubtypeID])\n> ERROR (trigger-sim): Here are the keys in the I3TriggerStatus: \n> key_matches.size() == 0\n>  (DetectorStatusUtils.h:186 in ResultType DetectorStatusUtils::boost_param_default_139GetTriggerStatus(ResultType (*)(), const Args&, int, detS\ntat_type&, sourceID_type&, typeID_type&, configID_type&, subtypeID_type&) [with ResultType = boost::optional<std::pair<TriggerKey, I3TriggerSta\ntus> >; Args = boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::configID, boost::optional\n<int> >, boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::typeID, const TriggerKey::TypeI\nD>, boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::sourceID, TriggerKey::SourceID>, boo\nst::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::detStat, const boost::shared_ptr<const I3Detector\nStatus> >, boost::parameter::aux::empty_arg_list> > > >; detStat_type = boost::shared_ptr<const I3DetectorStatus>; sourceID_type = TriggerKey::\nSourceID; typeID_type = TriggerKey::TypeID; configID_type = boost::optional<int>; subtypeID_type = TriggerKey::SubtypeID])\n> ERROR (trigger-sim): No match found (DetectorStatusUtils.h:188 in ResultType DetectorStatusUtils::boost_param_default_139GetTriggerStatus(ResultType (*)(), const Args&, int, detStat_type&, sourceID_type&, typeID_type&, configID_type&, subtypeID_type&) [with ResultType = boost::optiona$<std::pair<TriggerKey, I3TriggerStatus> >; Args = boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusU$ils::tag::configID, boost::optional<int> >, boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::$ag::typeID, const TriggerKey::TypeID>, boost::parameter::aux::arg_list<const boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::$ourceID, TriggerKey::SourceID>, boost::parameter::aux::arg_list<boost::parameter::aux::tagged_argument<DetectorStatusUtils::tag::detStat, cons$ boost::shared_ptr<const I3DetectorStatus> >, boost::parameter::aux::empty_arg_list> > > >; detStat_type = boost::shared_ptr<const I3DetectorS$atus>; sourceID_type = TriggerKey::SourceID; typeID_type = TriggerKey::TypeID; configID_type = boost::optional<int>; subtypeID_type = TriggerK$y::SubtypeID])", 
    "reporter": "icecube", 
    "cc": "", 
    "resolution": "invalid", 
    "_ts": "1532104085473604", 
    "component": "analysis", 
    "summary": "matching trigger config in trigger-sim", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2018-07-20T01:47:13", 
    "milestone": "", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20180720T16:28:05: 
* olivas changed resolution from "" to "invalid"
* olivas changed status from "new" to "closed"
* olivas commented:

> This turned out to be a combination of user error and design flaw (see #1925).  The input file had a leftover D frame from an IC79 GCD file, which contained the SMT3 configuration for ID 1010, instead of 1011, which is effectively what the user was asking for.
> 
> Something to keep in mind for the trigger-sim overhaul (likely to happen this winter).
