### ISSUE TITLE
[simprod] weighting.from_simprod doesn't work with dataset 20215 (Trac #2231)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2223]
It looks for key 'composition' in the simprod steering parameters which seems to be absent for newer CORSIKA datasets. Not sure if this is an issue with simprod or the weighting module

```text
Traceback (most recent call last):
  File "plot_hdf.py", line 39, in <module>
    generator= weighting.from_simprod(20215)
  File "/Users/kmeagher/icecube/simulation/trunk_kjm/release/lib/icecube/weighting/weighting.py", line 872, in from_simprod
    if steering['composition'].startswith('5-component') or steering['composition'] == 'jcorsika':
KeyError: 'composition'

```

Migrated from https://code.icecube.wisc.edu/ticket/2231
```json
{
    "status": "closed", 
    "changetime": "2019-02-04T19:38:43", 
    "description": "It looks for key 'composition' in the simprod steering parameters which seems to be absent for newer CORSIKA datasets. Not sure if this is an issue with simprod or the weighting module\n\n\n{{{\nTraceback (most recent call last):\n  File \"plot_hdf.py\", line 39, in <module>\n    generator= weighting.from_simprod(20215)\n  File \"/Users/kmeagher/icecube/simulation/trunk_kjm/release/lib/icecube/weighting/weighting.py\", line 872, in from_simprod\n    if steering['composition'].startswith('5-component') or steering['composition'] == 'jcorsika':\nKeyError: 'composition'\n\n}}}\n", 
    "reporter": "kjmeagher", 
    "cc": "juancarlos, jvansanten, olivas", 
    "resolution": "fixed", 
    "_ts": "1549309123853017", 
    "component": "analysis", 
    "summary": "[simprod] weighting.from_simprod doesn't work with dataset 20215", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2019-01-15T20:36:41", 
    "milestone": "Vernal Equinox 2019", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20190204T18:35:10: olivas changed cc from "" to "juancarlos, jvansanten, olivas"

**Comment by icecube-trac** [comment]
Trac update at 20190204T19:38:43: 
* juancarlos commented:

> Database was missing "composition" steering parameter. This is now fixed. Also fixed the same problem on dataset 20212.


* juancarlos changed resolution from "" to "fixed"
* juancarlos changed status from "new" to "closed"
