### ISSUE TITLE
[filterscripts] MESE filter has wrong configuration (Trac #2238)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2230]
mese filter.py line 115. „Output“ is not configured in the "LayerVeto" module.

The TFT is currently requesting filter checks, thus this bug is an issue to hold the deadline set by TFT for ppl who have to simulate their own signal.

Migrated from https://code.icecube.wisc.edu/ticket/2238
```json
{
    "status": "closed", 
    "changetime": "2019-02-13T16:29:28", 
    "description": "mese filter.py line 115. \u201eOutput\u201c is not configured in the \"LayerVeto\" module.\n\nThe TFT is currently requesting filter checks, thus this bug is an issue to hold the deadline set by TFT for ppl who have to simulate their own signal.", 
    "reporter": "anna.obertacke", 
    "cc": "", 
    "resolution": "invalid", 
    "_ts": "1550075368511910", 
    "component": "analysis", 
    "summary": "[filterscripts] MESE filter has wrong configuration", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2019-02-13T11:53:03", 
    "milestone": "", 
    "owner": "olivas", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20190213T13:53:50: 
* olivas commented:

> What version of filterscripts are you using?  It looks fine on the trunk and fixed 5 months ago in revision 165404.
> https://code.icecube.wisc.edu/projects/icecube/changeset/165404/IceCube
> 
> 


* olivas changed owner from "" to "olivas"
* olivas changed status from "new" to "accepted"

**Comment by icecube-trac** [comment]
Trac update at 20190213T15:25:13: anna.obertacke commented:

> I am using IceRec V05_02_02-RC1 and updated the filterscripts project to the current trunk today in order to get the SPE update to get simulation to L1 and L2.

**Comment by icecube-trac** [comment]
Trac update at 20190213T15:33:04: 
* olivas changed resolution from "" to "invalid"
* olivas changed status from "accepted" to "closed"
* olivas commented:

> Great!  I'm going to close this, but feel free to reopen or create a new ticket if you continue to run into problems.

**Comment by icecube-trac** [comment]
Trac update at 20190213T16:14:53: anna.obertacke commented:

> Sorry, it seems I didn't make it clear: The issue started when I switched to the filterscript trunk!

**Comment by icecube-trac** [comment]
Trac update at 20190213T16:17:36: olivas commented:

> Maybe we need more debugging info?  It does look configured on the trunk to me.  Maybe the name changed and a downstream module is complaining?

**Comment by icecube-trac** [comment]
Trac update at 20190213T16:29:28: anna.obertacke commented:

> This is the error message:
> 
> 
> WARN (Python): Module iceprod.modules not found. Will not define IceProd Class (SimulationFiltering_SPE.py:403 in <module>)
> FATAL (icetray): Attempt to set parameter Output that doesn't exist (I3ConfigurationImpl.cxx:65 in void I3ConfigurationImpl::Set(const string&, const boost::python::api::object&$
> Traceback (most recent call last):
>   File "/data/user/aobertacke/31_Filter2019/L1/scripts_newWavedeform//SimulationFiltering_SPE.py", line 420, in <module>
>     main(opts)
>   File "/data/user/aobertacke/31_Filter2019/L1/scripts_newWavedeform//SimulationFiltering_SPE.py", line 153, in main
>     **online_kwargs
>   File "/data/user/aobertacke/software/icerec_IC2019_V05_02_02-RC1/build/lib/I3Tray.py", line 224, in AddSegment
>     return _segment(self, _name, **kwargs)
>   File "/data/user/aobertacke/software/icerec_IC2019_V05_02_02-RC1/build/lib/icecube/filterscripts/all_filters.py", line 165, in OnlineFilter
>     If =  (which_split(split_name= filter_globals.InIceSplitter))
>   File "/data/user/aobertacke/software/icerec_IC2019_V05_02_02-RC1/build/lib/I3Tray.py", line 224, in AddSegment
>     return _segment(self, _name, **kwargs)
>   File "/data/user/aobertacke/software/icerec_IC2019_V05_02_02-RC1/build/lib/icecube/filterscripts/mesefilter.py", line 117, in MeseFilter
>     If=If_with_triggers)
>   File "/data/user/aobertacke/software/icerec_IC2019_V05_02_02-RC1/build/lib/I3Tray.py", line 224, in AddSegment
>     return _segment(self, _name, **kwargs)
>   File "/data/user/aobertacke/software/icerec_IC2019_V05_02_02-RC1/build/lib/icecube/filterscripts/mesefilter.py", line 113, in DefineLayers
>     tray.AddModule("LayerVeto", name, **kwargs)
>   File "/data/user/aobertacke/software/icerec_IC2019_V05_02_02-RC1/build/lib/I3Tray.py", line 147, in AddModule
>     super(I3Tray, self).SetParameter(_name, k, v)
> RuntimeError: Attempt to set parameter Output that doesn't exist (in void I3ConfigurationImpl::Set(const string&, const boost::python::api::object&))
