### ISSUE TITLE
[filterscripts] spe fit injector -> key error (Trac #2239)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2231]
When using the new SimulationFiltering_SPE and the --spe-file option the follwoing error occurs: 

WARN (Python): Module iceprod.modules not found. Will not define IceProd Class (SimulationFiltering_SPE.py:403 in <module>)
WARN (I3PhotoSplineTable): No nGroup in table, using default! This is probably not what you want (I3PhotoSplineTable.cxx:81 in bool I3PhotoSplineTable::SetupTable(co$
WARN (I3PhotoSplineTable): No nGroup in table, using default! This is probably not what you want (I3PhotoSplineTable.cxx:81 in bool I3PhotoSplineTable::SetupTable(co$
ERROR (I3Tray): Exception thrown while configuring module "fixspe". (I3Tray.cxx:385 in void I3Tray::Configure())
fixspe (icecube.phys_services.spe_fit_injector.I3SPEFitInjector)
  Filename
    Description :  JSON (may bz2 compressed) file with SPE fit data
    Default     :  ''
    Configured  :  '/cvmfs/icecube.opensciencegrid.org/py2-v3.0.1/metaprojects/icerec/V05-02-02-RC2/filterscripts/resources/data/pass3/IC86.2016_923_NewWaveDeform_liorm_lite.json'

Traceback (most recent call last):
  File "/data/user/aobertacke/31_Filter2019/L1/scripts_newWavedeform//SimulationFiltering_SPE.py", line 420, in <module>
    main(opts)
  File "/data/user/aobertacke/31_Filter2019/L1/scripts_newWavedeform//SimulationFiltering_SPE.py", line 377, in main
    tray.Execute()
  File "/data/user/aobertacke/software/icerec_IC2019_V05_02_02-RC1/build/lib/I3Tray.py", line 256, in Execute
    super(I3Tray, self).Execute()
  File "/data/user/aobertacke/software/icerec_IC2019_V05_02_02-RC1/build/lib/icecube/phys_services/spe_fit_injector.py", line 41, in Configure
    if bool(data['JOINT_fit']['valid']) == False and \
KeyError: 'JOINT_fit'

The TFT is currently requesting filter checks, thus this bug is an issue to hold the deadline set by TFT for ppl who have to simulate their own signal.

Migrated from https://code.icecube.wisc.edu/ticket/2239
```json
{
    "status": "closed", 
    "changetime": "2019-06-21T17:09:41", 
    "description": "When using the new SimulationFiltering_SPE and the --spe-file option the follwoing error occurs: \n\n\nWARN (Python): Module iceprod.modules not found. Will not define IceProd Class (SimulationFiltering_SPE.py:403 in <module>)\nWARN (I3PhotoSplineTable): No nGroup in table, using default! This is probably not what you want (I3PhotoSplineTable.cxx:81 in bool I3PhotoSplineTable::SetupTable(co$\nWARN (I3PhotoSplineTable): No nGroup in table, using default! This is probably not what you want (I3PhotoSplineTable.cxx:81 in bool I3PhotoSplineTable::SetupTable(co$\nERROR (I3Tray): Exception thrown while configuring module \"fixspe\". (I3Tray.cxx:385 in void I3Tray::Configure())\nfixspe (icecube.phys_services.spe_fit_injector.I3SPEFitInjector)\n  Filename\n    Description :  JSON (may bz2 compressed) file with SPE fit data\n    Default     :  ''\n    Configured  :  '/cvmfs/icecube.opensciencegrid.org/py2-v3.0.1/metaprojects/icerec/V05-02-02-RC2/filterscripts/resources/data/pass3/IC86.2016_923_NewWaveDeform_liorm_lite.json'\n\nTraceback (most recent call last):\n  File \"/data/user/aobertacke/31_Filter2019/L1/scripts_newWavedeform//SimulationFiltering_SPE.py\", line 420, in <module>\n    main(opts)\n  File \"/data/user/aobertacke/31_Filter2019/L1/scripts_newWavedeform//SimulationFiltering_SPE.py\", line 377, in main\n    tray.Execute()\n  File \"/data/user/aobertacke/software/icerec_IC2019_V05_02_02-RC1/build/lib/I3Tray.py\", line 256, in Execute\n    super(I3Tray, self).Execute()\n  File \"/data/user/aobertacke/software/icerec_IC2019_V05_02_02-RC1/build/lib/icecube/phys_services/spe_fit_injector.py\", line 41, in Configure\n    if bool(data['JOINT_fit']['valid']) == False and \\\nKeyError: 'JOINT_fit'\n\n\n\nThe TFT is currently requesting filter checks, thus this bug is an issue to hold the deadline set by TFT for ppl who have to simulate their own signal.", 
    "reporter": "anna.obertacke", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1561136981975028", 
    "component": "analysis", 
    "summary": "[filterscripts] spe fit injector -> key error", 
    "priority": "major", 
    "keywords": "", 
    "time": "2019-02-13T11:55:25", 
    "milestone": "", 
    "owner": "olivas", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20190213T13:44:00: olivas commented:

> Where does this file come from?
> /cvmfs/icecube.opensciencegrid.org/py2-v3.0.1/metaprojects/icerec/V05-02-02-RC2/filterscripts/resources/data/pass3/IC86.2016_923_NewWaveDeform_liorm_lite.json
> 
> pass3 in an old release of cvmfs and an IceRec candidate?  What's 'liorm' and what's 'lite' about this file?

**Comment by icecube-trac** [comment]
Trac update at 20190213T13:44:14: 
* olivas changed owner from "" to "olivas"
* olivas changed status from "new" to "accepted"

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:25:28: david.schultz commented:

> That's a file I put in there from Spencer, for the new pass3 fits.  Not sure exactly how it got here, but Juan Carlos has been making a bunch of RCs for testing.

**Comment by icecube-trac** [comment]
Trac update at 20190213T14:26:35: david.schultz commented:

> My guess - combining different project releases resulted in unstable code. Don't use this RC unless you're Juan Carlos.

**Comment by icecube-trac** [comment]
Trac update at 20190621T17:09:41: 
* olivas changed status from "accepted" to "closed"
* olivas commented:

> The current SPE injector works with standard JSON fit files.  No guarantees about non-standard JSON files.


* olivas changed resolution from "" to "fixed"
