### ISSUE TITLE
[steamshovel] doesn't work on macos with python3 (Trac #2250)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2242]
Steamshovel works fine with python2.7 but fails with python3.7.2. On macOS Mojave Version 10.14.3. Qt version 5.12.1.

The exception that is thrown is `boost::python::error_already_set` which is boost::python catching an error and not telling you which one, see #2213.

Note that the interactive console does not run as well (which is not causing the crash), even though that works fine in python2 as well.

The exception involving 'DOMLabel' also appears to be unrelated and not present in python2. 

```text
$ steamshovel
No module named 'IPython'
WARN (steamshovel): Cannot embed IPython Qt widget, falling back to tty-based console (embed.cpp:95 in scripting::PyConsole::PyConsole(const scripting::PyInterpreter &, scripting::PyConsole::Type))
WARN (steamshovel): Could not use IPython, falling back to vanilla python console (embed.cpp:103 in scripting::PyConsole::PyConsole(const scripting::PyInterpreter &, scripting::PyConsole::Type))
Python 3.7.2 (default, Feb 12 2019, 08:15:36) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> ERROR (ShovelMainWindow): Problem executing scenario code:
Traceback (most recent call last):
  File "<string>", line 25, in _dumpScenario
RuntimeError: No such factory name: 'DOMLabel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 113, in <module>
  File "<string>", line 30, in _dumpScenario
NameError: name 'StandardError' is not defined
String was:
def _dumpScenario():
    from icecube.shovelart import ActivePixmapOverlay, Arrow, ArtistHandle, ArtistHandleList, ArtistKeylist, BaseLineObject, ChoiceSetting, ColorMap, ColoredObject, ConstantColorMap, ConstantFloat, ConstantQColor, ConstantTime, ConstantVec3d, Cylinder, DynamicLines, FileSetting, I3TimeColorMap, KeySetting, LinterpFunctionFloat, LinterpFunctionQColor, LinterpFunctionVec3d, OMKeySet, OverlayLine, OverlaySizeHint, OverlaySizeHints, ParticlePath, ParticlePoint, Phantom, PixmapOverlay, PyArtist, PyQColor, PyQFont, PyVariantFloat, PyVariantQColor, PyVariantTime, PyVariantVec3d, RangeSetting, Scenario, SceneGroup, SceneObject, SceneOverlay, SolidObject, Sphere, StaticLines, StepFunctionFloat, StepFunctionQColor, StepFunctionTime, StepFunctionVec3d, Text, TextOverlay, TimePoint, TimeWindow, TimeWindowColor, VariantFloat, VariantQColor, VariantTime, VariantVec3d, VariantVec3dList, Vec3dList, ZPlane, vec3d
    from icecube.icetray import OMKey
    from icecube.icetray import logging
    scenario = window.gl.scenario
    scenario.clear()
    try:
        artist = scenario.add( 'Detector', ['I3Geometry', ] )
        scenario.setIsActive( artist, False )
        scenario.changeSetting( artist, 'DOM color', PyQColor(255,255,255,255) )
        scenario.changeSetting( artist, 'DOM radius', 1 )
        scenario.changeSetting( artist, 'outline width', 0 )
        scenario.changeSetting( artist, 'high quality DOMs', True )
        scenario.changeSetting( artist, 'string cross', False )
        scenario.changeSetting( artist, 'string color', PyQColor(255,255,255,76) )
        scenario.changeSetting( artist, 'string width', 1 )
        scenario.changeSetting( artist, 'hide', 0 )
        scenario.changeSetting( artist, 'DOM labels', False )
        scenario.setIsActive( artist, True )
    except StandardError as e:
        logging.log_error( e.__class__.__name__ + " occured while loading saved state of Detector: " + str(e) )
    except:
        logging.log_error( "Unknown error occured while loading saved state of Detector: " + str(e) )
    try:
        artist = scenario.add( 'DOMLabel', ['I3Geometry', ] )
        scenario.setIsActive( artist, False )
        scenario.changeSetting( artist, 'font', PyQFont.fromString('Arial,13,-1,5,50,0,0,0,0,0') )
        scenario.changeSetting( artist, 'selection', [] )
        scenario.changeSetting( artist, 'fontsize', 13 )
    except StandardError as e:
        logging.log_error( e.__class__.__name__ + " occured while loading saved state of DOMLabel: " + str(e) )
    except:
        logging.log_error( "Unknown error occured while loading saved state of DOMLabel: " + str(e) )
    try:
        artist = scenario.add( 'DOMOrientation', ['I3Geometry', ] )
        scenario.setIsActive( artist, False )
        scenario.changeSetting( artist, 'opacity', 1 )
        scenario.changeSetting( artist, 'Label Axes', False )
        scenario.changeSetting( artist, 'Draw Orthogonal Direction', True )
        scenario.changeSetting( artist, 'ortho length', '10m' )
        scenario.changeSetting( artist, 'Draw DOM Direction', True )
        scenario.changeSetting( artist, 'Draw Flasher Direction', True )
        scenario.changeSetting( artist, 'dom length', '10m' )
        scenario.changeSetting( artist, 'flasher length', '10m' )
        scenario.changeSetting( artist, 'line width', 10 )
        scenario.changeSetting( artist, 'head angle', 20 )
        scenario.changeSetting( artist, 'Draw Default Orientation', False )
        scenario.changeSetting( artist, 'head length', 1 )
    except StandardError as e:
        logging.log_error( e.__class__.__name__ + " occured while loading saved state of DOMOrientation: " + str(e) )
    except:
        logging.log_error( "Unknown error occured while loading saved state of DOMOrientation: " + str(e) )
    try:
        artist = scenario.add( 'Particles', ['I3MCTree', ] )
        scenario.setIsActive( artist, False )
        scenario.changeSetting( artist, 'min. energy [track]', '' )
        scenario.changeSetting( artist, 'scale', 10 )
        scenario.changeSetting( artist, 'show light fronts', False )
        scenario.changeSetting( artist, 'colormap', I3TimeColorMap() )
        scenario.changeSetting( artist, 'power', 0.15 )
        scenario.changeSetting( artist, 'color', PyQColor(243,51,51,153) )
        scenario.changeSetting( artist, 'vertex size', 0 )
        scenario.changeSetting( artist, 'labels', True )
        scenario.changeSetting( artist, 'Cherenkov cone size', 0 )
        scenario.changeSetting( artist, 'blue light fronts', True )
        scenario.changeSetting( artist, 'incoming/outgoing', True )
        scenario.changeSetting( artist, 'color by type', True )
        scenario.changeSetting( artist, 'arrow head size', 120 )
        scenario.changeSetting( artist, 'linewidth', 3 )
        scenario.changeSetting( artist, 'min. energy [cascade]', '' )
        scenario.setIsActive( artist, True )
    except StandardError as e:
        logging.log_error( e.__class__.__name__ + " occured while loading saved state of Particles: " + str(e) )
    except:
        logging.log_error( "Unknown error occured while loading saved state of Particles: " + str(e) )
    try:
        artist = scenario.add( 'Bubbles', ['I3Geometry', 'IceTopRawData', ] )
        scenario.setIsActive( artist, False )
        scenario.changeSetting( artist, 'scale', 10 )
        scenario.changeSetting( artist, 'colormap', I3TimeColorMap() )
        scenario.changeSetting( artist, 'power', 0.15 )
        scenario.changeSetting( artist, 'custom color window', '' )
        scenario.changeSetting( artist, 'log10(delay/ns)', 5 )
        scenario.changeSetting( artist, 'static', PyQColor(255,0,255,255) )
        scenario.setIsActive( artist, True )
    except StandardError as e:
        logging.log_error( e.__class__.__name__ + " occured while loading saved state of Bubbles: " + str(e) )
    except:
        logging.log_error( "Unknown error occured while loading saved state of Bubbles: " + str(e) )
    try:
        artist = scenario.add( 'Bubbles', ['I3Geometry', 'InIceRawData', ] )
        scenario.setIsActive( artist, False )
        scenario.changeSetting( artist, 'scale', 10 )
        scenario.changeSetting( artist, 'colormap', I3TimeColorMap() )
        scenario.changeSetting( artist, 'power', 0.15 )
        scenario.changeSetting( artist, 'custom color window', '' )
        scenario.changeSetting( artist, 'log10(delay/ns)', 5 )
        scenario.changeSetting( artist, 'static', PyQColor(255,0,255,255) )
        scenario.setIsActive( artist, True )
    except StandardError as e:
        logging.log_error( e.__class__.__name__ + " occured while loading saved state of Bubbles: " + str(e) )
    except:
        logging.log_error( "Unknown error occured while loading saved state of Bubbles: " + str(e) )
    window.gl.setCameraPivot(0.0, 0.0, 0.0)
    window.gl.setCameraLoc(-1864.75549316, -362.478149414, 590.385009766)
    window.gl.setCameraOrientation(0.190808907151, -0.981627702713, 3.51667404175e-06)
    window.gl.cameraLock = False
    window.gl.perspectiveView = True
    window.gl.backgroundColor = PyQColor(38,38,38,255)
    window.timeline.rangeFinder = "Default"
    window.frame_filter.code = ""
    window.activeView = 0
_dumpScenario()
del _dumpScenario (ShovelMainWindow.cpp:333 in bool ShovelMainWindow::loadScenarioCode(const QString &))
objc[43690]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff99c38210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x12c0eadc8). One of the two will be used. Which one is undefined.
libc++abi.dylib: terminating with uncaught exception of type boost::python::error_already_set
Abort trap: 6

```

Migrated from https://code.icecube.wisc.edu/ticket/2250
```json
{
    "status": "closed", 
    "changetime": "2020-06-24T12:31:42", 
    "description": "Steamshovel works fine with python2.7 but fails with python3.7.2. On macOS Mojave Version 10.14.3. Qt version 5.12.1.\n\nThe exception that is thrown is `boost::python::error_already_set` which is boost::python catching an error and not telling you which one, see #2221.\n\nNote that the interactive console does not run as well (which is not causing the crash), even though that works fine in python2 as well.\n\nThe exception involving 'DOMLabel' also appears to be unrelated and not present in python2. \n\n{{{\n$ steamshovel\nNo module named 'IPython'\nWARN (steamshovel): Cannot embed IPython Qt widget, falling back to tty-based console (embed.cpp:95 in scripting::PyConsole::PyConsole(const scripting::PyInterpreter &, scripting::PyConsole::Type))\nWARN (steamshovel): Could not use IPython, falling back to vanilla python console (embed.cpp:103 in scripting::PyConsole::PyConsole(const scripting::PyInterpreter &, scripting::PyConsole::Type))\nPython 3.7.2 (default, Feb 12 2019, 08:15:36) \n[Clang 10.0.0 (clang-1000.11.45.5)] on darwin\nType \"help\", \"copyright\", \"credits\" or \"license\" for more information.\n(InteractiveConsole)\n>>> ERROR (ShovelMainWindow): Problem executing scenario code:\nTraceback (most recent call last):\n  File \"<string>\", line 25, in _dumpScenario\nRuntimeError: No such factory name: 'DOMLabel'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"<string>\", line 113, in <module>\n  File \"<string>\", line 30, in _dumpScenario\nNameError: name 'StandardError' is not defined\nString was:\ndef _dumpScenario():\n    from icecube.shovelart import ActivePixmapOverlay, Arrow, ArtistHandle, ArtistHandleList, ArtistKeylist, BaseLineObject, ChoiceSetting, ColorMap, ColoredObject, ConstantColorMap, ConstantFloat, ConstantQColor, ConstantTime, ConstantVec3d, Cylinder, DynamicLines, FileSetting, I3TimeColorMap, KeySetting, LinterpFunctionFloat, LinterpFunctionQColor, LinterpFunctionVec3d, OMKeySet, OverlayLine, OverlaySizeHint, OverlaySizeHints, ParticlePath, ParticlePoint, Phantom, PixmapOverlay, PyArtist, PyQColor, PyQFont, PyVariantFloat, PyVariantQColor, PyVariantTime, PyVariantVec3d, RangeSetting, Scenario, SceneGroup, SceneObject, SceneOverlay, SolidObject, Sphere, StaticLines, StepFunctionFloat, StepFunctionQColor, StepFunctionTime, StepFunctionVec3d, Text, TextOverlay, TimePoint, TimeWindow, TimeWindowColor, VariantFloat, VariantQColor, VariantTime, VariantVec3d, VariantVec3dList, Vec3dList, ZPlane, vec3d\n    from icecube.icetray import OMKey\n    from icecube.icetray import logging\n    scenario = window.gl.scenario\n    scenario.clear()\n    try:\n        artist = scenario.add( 'Detector', ['I3Geometry', ] )\n        scenario.setIsActive( artist, False )\n        scenario.changeSetting( artist, 'DOM color', PyQColor(255,255,255,255) )\n        scenario.changeSetting( artist, 'DOM radius', 1 )\n        scenario.changeSetting( artist, 'outline width', 0 )\n        scenario.changeSetting( artist, 'high quality DOMs', True )\n        scenario.changeSetting( artist, 'string cross', False )\n        scenario.changeSetting( artist, 'string color', PyQColor(255,255,255,76) )\n        scenario.changeSetting( artist, 'string width', 1 )\n        scenario.changeSetting( artist, 'hide', 0 )\n        scenario.changeSetting( artist, 'DOM labels', False )\n        scenario.setIsActive( artist, True )\n    except StandardError as e:\n        logging.log_error( e.__class__.__name__ + \" occured while loading saved state of Detector: \" + str(e) )\n    except:\n        logging.log_error( \"Unknown error occured while loading saved state of Detector: \" + str(e) )\n    try:\n        artist = scenario.add( 'DOMLabel', ['I3Geometry', ] )\n        scenario.setIsActive( artist, False )\n        scenario.changeSetting( artist, 'font', PyQFont.fromString('Arial,13,-1,5,50,0,0,0,0,0') )\n        scenario.changeSetting( artist, 'selection', [] )\n        scenario.changeSetting( artist, 'fontsize', 13 )\n    except StandardError as e:\n        logging.log_error( e.__class__.__name__ + \" occured while loading saved state of DOMLabel: \" + str(e) )\n    except:\n        logging.log_error( \"Unknown error occured while loading saved state of DOMLabel: \" + str(e) )\n    try:\n        artist = scenario.add( 'DOMOrientation', ['I3Geometry', ] )\n        scenario.setIsActive( artist, False )\n        scenario.changeSetting( artist, 'opacity', 1 )\n        scenario.changeSetting( artist, 'Label Axes', False )\n        scenario.changeSetting( artist, 'Draw Orthogonal Direction', True )\n        scenario.changeSetting( artist, 'ortho length', '10m' )\n        scenario.changeSetting( artist, 'Draw DOM Direction', True )\n        scenario.changeSetting( artist, 'Draw Flasher Direction', True )\n        scenario.changeSetting( artist, 'dom length', '10m' )\n        scenario.changeSetting( artist, 'flasher length', '10m' )\n        scenario.changeSetting( artist, 'line width', 10 )\n        scenario.changeSetting( artist, 'head angle', 20 )\n        scenario.changeSetting( artist, 'Draw Default Orientation', False )\n        scenario.changeSetting( artist, 'head length', 1 )\n    except StandardError as e:\n        logging.log_error( e.__class__.__name__ + \" occured while loading saved state of DOMOrientation: \" + str(e) )\n    except:\n        logging.log_error( \"Unknown error occured while loading saved state of DOMOrientation: \" + str(e) )\n    try:\n        artist = scenario.add( 'Particles', ['I3MCTree', ] )\n        scenario.setIsActive( artist, False )\n        scenario.changeSetting( artist, 'min. energy [track]', '' )\n        scenario.changeSetting( artist, 'scale', 10 )\n        scenario.changeSetting( artist, 'show light fronts', False )\n        scenario.changeSetting( artist, 'colormap', I3TimeColorMap() )\n        scenario.changeSetting( artist, 'power', 0.15 )\n        scenario.changeSetting( artist, 'color', PyQColor(243,51,51,153) )\n        scenario.changeSetting( artist, 'vertex size', 0 )\n        scenario.changeSetting( artist, 'labels', True )\n        scenario.changeSetting( artist, 'Cherenkov cone size', 0 )\n        scenario.changeSetting( artist, 'blue light fronts', True )\n        scenario.changeSetting( artist, 'incoming/outgoing', True )\n        scenario.changeSetting( artist, 'color by type', True )\n        scenario.changeSetting( artist, 'arrow head size', 120 )\n        scenario.changeSetting( artist, 'linewidth', 3 )\n        scenario.changeSetting( artist, 'min. energy [cascade]', '' )\n        scenario.setIsActive( artist, True )\n    except StandardError as e:\n        logging.log_error( e.__class__.__name__ + \" occured while loading saved state of Particles: \" + str(e) )\n    except:\n        logging.log_error( \"Unknown error occured while loading saved state of Particles: \" + str(e) )\n    try:\n        artist = scenario.add( 'Bubbles', ['I3Geometry', 'IceTopRawData', ] )\n        scenario.setIsActive( artist, False )\n        scenario.changeSetting( artist, 'scale', 10 )\n        scenario.changeSetting( artist, 'colormap', I3TimeColorMap() )\n        scenario.changeSetting( artist, 'power', 0.15 )\n        scenario.changeSetting( artist, 'custom color window', '' )\n        scenario.changeSetting( artist, 'log10(delay/ns)', 5 )\n        scenario.changeSetting( artist, 'static', PyQColor(255,0,255,255) )\n        scenario.setIsActive( artist, True )\n    except StandardError as e:\n        logging.log_error( e.__class__.__name__ + \" occured while loading saved state of Bubbles: \" + str(e) )\n    except:\n        logging.log_error( \"Unknown error occured while loading saved state of Bubbles: \" + str(e) )\n    try:\n        artist = scenario.add( 'Bubbles', ['I3Geometry', 'InIceRawData', ] )\n        scenario.setIsActive( artist, False )\n        scenario.changeSetting( artist, 'scale', 10 )\n        scenario.changeSetting( artist, 'colormap', I3TimeColorMap() )\n        scenario.changeSetting( artist, 'power', 0.15 )\n        scenario.changeSetting( artist, 'custom color window', '' )\n        scenario.changeSetting( artist, 'log10(delay/ns)', 5 )\n        scenario.changeSetting( artist, 'static', PyQColor(255,0,255,255) )\n        scenario.setIsActive( artist, True )\n    except StandardError as e:\n        logging.log_error( e.__class__.__name__ + \" occured while loading saved state of Bubbles: \" + str(e) )\n    except:\n        logging.log_error( \"Unknown error occured while loading saved state of Bubbles: \" + str(e) )\n    window.gl.setCameraPivot(0.0, 0.0, 0.0)\n    window.gl.setCameraLoc(-1864.75549316, -362.478149414, 590.385009766)\n    window.gl.setCameraOrientation(0.190808907151, -0.981627702713, 3.51667404175e-06)\n    window.gl.cameraLock = False\n    window.gl.perspectiveView = True\n    window.gl.backgroundColor = PyQColor(38,38,38,255)\n    window.timeline.rangeFinder = \"Default\"\n    window.frame_filter.code = \"\"\n    window.activeView = 0\n_dumpScenario()\ndel _dumpScenario (ShovelMainWindow.cpp:333 in bool ShovelMainWindow::loadScenarioCode(const QString &))\nobjc[43690]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff99c38210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x12c0eadc8). One of the two will be used. Which one is undefined.\nlibc++abi.dylib: terminating with uncaught exception of type boost::python::error_already_set\nAbort trap: 6\n\n}}}\n", 
    "reporter": "kjmeagher", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1593001902142004", 
    "component": "combo core", 
    "summary": "[steamshovel] doesn't work on macos with python3", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2019-03-14T16:46:49", 
    "milestone": "Autumnal Equinox 2020", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20190604T16:55:05: olivas changed milestone from "Summer Solstice 2019" to "Vernal Equinox 2020"

**Comment by icecube-trac** [comment]
Trac update at 20191022T23:35:14: 
* nwhitehorn commented:

> Fixed in r176348.


* nwhitehorn changed status from "new" to "closed"
* nwhitehorn changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20200624T12:31:42: 
* olivas commented:

> Milestone Vernal Equinox 2020 deleted


* olivas changed milestone from "Vernal Equinox 2020" to "Autumnal Equinox 2020"
