### ISSUE TITLE
steamshovel - not python3  friendly (Trac #2251)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2243]
i think this is from the mini-test during packaging. dunno why it cant find numpy

```text
ERROR (RangeFinder): TimelineWidget.cpp:64 in timeline::RangeFinder::RangeFinder()
Traceback (most recent call last):
  File "/Users/nega/i3/combo/build/lib/icecube/steamshovel/util/rangefinder.py", line 6, in 
    import numpy
ModuleNotFoundError: No module named 'numpy'

ERROR (steamshovel): SteamshovelApp.cpp:149 in virtual bool SteamshovelApp::notify(QObject *, QEvent *)
Uncaught python exception in event loop:
Traceback (most recent call last):
  File "/Users/nega/i3/combo/build/lib/icecube/steamshovel/embed/__init__.py", line 10, in 
    execfile(activate_script, {'__file__': activate_script})
NameError: name 'execfile' is not defined

ERROR (ShovelMainWindow): ShovelMainWindow.cpp:315 in QString ShovelMainWindow::getScenarioCode() const
Problem generating scenario code:
Traceback (most recent call last):
  File "", line 978, in _find_and_load
NoneType: None
```

Migrated from https://code.icecube.wisc.edu/ticket/2251
```json
{
    "status": "closed", 
    "changetime": "2019-03-15T03:22:56", 
    "description": "i think this is from the mini-test during packaging. dunno why it cant find numpy\n\n{{{\nERROR (RangeFinder): TimelineWidget.cpp:64 in timeline::RangeFinder::RangeFinder()\nTraceback (most recent call last):\n  File \"/Users/nega/i3/combo/build/lib/icecube/steamshovel/util/rangefinder.py\", line 6, in \n    import numpy\nModuleNotFoundError: No module named 'numpy'\n\nERROR (steamshovel): SteamshovelApp.cpp:149 in virtual bool SteamshovelApp::notify(QObject *, QEvent *)\nUncaught python exception in event loop:\nTraceback (most recent call last):\n  File \"/Users/nega/i3/combo/build/lib/icecube/steamshovel/embed/__init__.py\", line 10, in \n    execfile(activate_script, {'__file__': activate_script})\nNameError: name 'execfile' is not defined\n\nERROR (ShovelMainWindow): ShovelMainWindow.cpp:315 in QString ShovelMainWindow::getScenarioCode() const\nProblem generating scenario code:\nTraceback (most recent call last):\n  File \"\", line 978, in _find_and_load\nNoneType: None\n}}}", 
    "reporter": "nega", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1552620176973419", 
    "component": "other", 
    "summary": "steamshovel - not python3  friendly", 
    "priority": "major", 
    "keywords": "steamshovel python3", 
    "time": "2019-03-15T02:43:46", 
    "milestone": "", 
    "owner": "nega", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20190315T03:22:56: 
* nega changed status from "new" to "closed"
* nega changed resolution from "" to "fixed"
* nega commented:

> In changeset 172046:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="172046"
> fix crash on startup with python3
> 
> closes: #2243
> ```
