### ISSUE TITLE
[icetray] I3TestModuleFactory doesn't work in python3 (Trac #2256)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2248]
It looks like the `unittest` works differently in python 2 and 3. In 2 you can keep running the same unit test over and over again, but in 3 after you run it once it gets deleted and becomes a `None`

```text
$ python CoincSuite/resources/test/AfterpulseTest.py 
NOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:497 in void I3Tray::Execute(unsigned int))
NOTICE (TesterModule): 
Recombination Decisions by AfterpulseTester:
  YES       : 1
  NO        : 0
  UNDECIDED : 0
 (TesterModule.cxx:45 in virtual void TesterModule::Finish())
CoincSuite/resources/test/AfterpulseTest.py:142: DeprecationWarning: Please use assertTrue instead.
  self.assert_(self.frame.Has(SplitName+"RecombAttempts"))
CoincSuite/resources/test/AfterpulseTest.py:144: DeprecationWarning: Please use assertTrue instead.
  self.assert_(ra[0] == "AfterpulseTester")
.
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
CoincSuite/resources/test/AfterpulseTest.py:156: DeprecationWarning: Please use assertTrue instead.
  self.assert_(eh.sub_event_stream=="split" and eh.sub_event_id==0)
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
ERROR (I3Module): TestPhysicsSequence: Exception thrown (I3Module.cxx:127 in void I3Module::Do(void (I3Module::*)()))
Traceback (most recent call last):
  File "CoincSuite/resources/test/AfterpulseTest.py", line 194, in <module>
    tray.Execute()
  File "/Users/kmeagher/icecube/combo/release/lib/I3Tray.py", line 256, in Execute
    super(I3Tray, self).Execute()
  File "/Users/kmeagher/icecube/combo/release/lib/icecube/icetray/test_module.py", line 83, in RunTests
    test_result = self.test_runner.run(self.test_suites)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/runner.py", line 176, in run
    test(result)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
TypeError: 'NoneType' object is not callable

```

Migrated from https://code.icecube.wisc.edu/ticket/2256
```json
{
    "status": "closed", 
    "changetime": "2020-06-24T12:31:42", 
    "description": "It looks like the `unittest` works differently in python 2 and 3. In 2 you can keep running the same unit test over and over again, but in 3 after you run it once it gets deleted and becomes a `None`\n{{{\n$ python CoincSuite/resources/test/AfterpulseTest.py \nNOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:497 in void I3Tray::Execute(unsigned int))\nNOTICE (TesterModule): \nRecombination Decisions by AfterpulseTester:\n  YES       : 1\n  NO        : 0\n  UNDECIDED : 0\n (TesterModule.cxx:45 in virtual void TesterModule::Finish())\nCoincSuite/resources/test/AfterpulseTest.py:142: DeprecationWarning: Please use assertTrue instead.\n  self.assert_(self.frame.Has(SplitName+\"RecombAttempts\"))\nCoincSuite/resources/test/AfterpulseTest.py:144: DeprecationWarning: Please use assertTrue instead.\n  self.assert_(ra[0] == \"AfterpulseTester\")\n.\n----------------------------------------------------------------------\nRan 1 test in 0.001s\n\nOK\nCoincSuite/resources/test/AfterpulseTest.py:156: DeprecationWarning: Please use assertTrue instead.\n  self.assert_(eh.sub_event_stream==\"split\" and eh.sub_event_id==0)\n.\n----------------------------------------------------------------------\nRan 1 test in 0.000s\n\nOK\nERROR (I3Module): TestPhysicsSequence: Exception thrown (I3Module.cxx:127 in void I3Module::Do(void (I3Module::*)()))\nTraceback (most recent call last):\n  File \"CoincSuite/resources/test/AfterpulseTest.py\", line 194, in <module>\n    tray.Execute()\n  File \"/Users/kmeagher/icecube/combo/release/lib/I3Tray.py\", line 256, in Execute\n    super(I3Tray, self).Execute()\n  File \"/Users/kmeagher/icecube/combo/release/lib/icecube/icetray/test_module.py\", line 83, in RunTests\n    test_result = self.test_runner.run(self.test_suites)\n  File \"/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/runner.py\", line 176, in run\n    test(result)\n  File \"/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/suite.py\", line 84, in __call__\n    return self.run(*args, **kwds)\n  File \"/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/suite.py\", line 122, in run\n    test(result)\nTypeError: 'NoneType' object is not callable\n\n}}}\n", 
    "reporter": "kjmeagher", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1593001902142004", 
    "component": "combo core", 
    "summary": "[icetray] I3TestModuleFactory doesn't work in python3", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2019-03-18T19:19:29", 
    "milestone": "Autumnal Equinox 2020", 
    "owner": "olivas", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20190318T20:53:36: david.schultz commented:

> yeah, I'm pretty sure unittest was never designed to be used like it is in the I3TestModule.  You might be able to recreate `unittest.TestSuite` for each frame, instead of doing that in the init.

**Comment by icecube-trac** [comment]
Trac update at 20190318T21:02:36: kjmeagher commented:

> I attempted to do just that but, it wasn't straightforward

**Comment by icecube-trac** [comment]
Trac update at 20190604T16:55:30: olivas changed milestone from "Summer Solstice 2019" to "Vernal Equinox 2020"

**Comment by icecube-trac** [comment]
Trac update at 20190621T18:41:00: 
* olivas changed owner from "" to "olivas"
* olivas changed status from "new" to "accepted"

**Comment by icecube-trac** [comment]
Trac update at 20200121T18:19:28: olivas changed priority from "normal" to "blocker"

**Comment by icecube-trac** [comment]
Trac update at 20200121T19:46:46: kjmeagher commented:

> I think that this was fixed in r177624/IceCube

**Comment by icecube-trac** [comment]
Trac update at 20200224T17:49:53: 
* olivas changed resolution from "" to "fixed"
* olivas changed status from "accepted" to "closed"
* olivas commented:

> Most tests pass for me with py3, so it looks like this is in fact fixed.

**Comment by icecube-trac** [comment]
Trac update at 20200624T12:31:42: 
* olivas changed milestone from "Vernal Equinox 2020" to "Autumnal Equinox 2020"
* olivas commented:

> Milestone Vernal Equinox 2020 deleted
