### ISSUE TITLE
[MuonGun] import fails if imported after certain modules (Trac #2258)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2250]
In a release build of combo/trunk against py2-v3.1.1 on SL7, the following sequence fails:

```text
./env-shell.sh python -c "from icecube import spline_reco, stochastics, MuonGun"
Error in <TUnixSystem::FindDynamicLibrary>: GX11[.so | .dll | .dylib | .sl | .dl | .a] does not exist in /scratch/jvansanten/metaprojects/combo/build/lib:/scratch/jvansanten/metaprojects/combo/build/lib/tools:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/lib:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/lib64:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/../distrib/jdk1.6.0_24_RHEL_7_x86_64/lib:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/../distrib/jdk1.6.0_24_RHEL_7_x86_64/jre/lib:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/../distrib/jdk1.6.0_24_RHEL_7_x86_64/jre/lib/amd64:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/../distrib/jdk1.6.0_24_RHEL_7_x86_64/jre/lib/amd64/server:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/lib:.:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/lib:/lib64/tls/x86_64:/lib64/tls:/lib64/x86_64:/lib64:/usr/lib64/tls/x86_64:/usr/lib64/tls:/usr/lib64/x86_64:/usr/lib64
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/scratch/jvansanten/metaprojects/combo/build/lib/icecube/MuonGun/__init__.py", line 3, in <module>
    load_pybindings(__name__,__path__)
  File "/scratch/jvansanten/metaprojects/combo/build/lib/icecube/load_pybindings.py", line 67, in load_pybindings
    m = imp.load_dynamic(name, path[0] + ".so")
TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<I3MuonGun::Cylinder>
```

Importing `spline_reco`, `stochastics`, and `MuonGun` in any other order works just fine. `stochastics` appears to unconditionally import pyROOT, which may or may not be related.

Migrated from https://code.icecube.wisc.edu/ticket/2258
```json
{
    "status": "closed", 
    "changetime": "2020-06-24T12:31:42", 
    "description": "In a release build of combo/trunk against py2-v3.1.1 on SL7, the following sequence fails:\n\n{{{\n./env-shell.sh python -c \"from icecube import spline_reco, stochastics, MuonGun\"\nError in <TUnixSystem::FindDynamicLibrary>: GX11[.so | .dll | .dylib | .sl | .dl | .a] does not exist in /scratch/jvansanten/metaprojects/combo/build/lib:/scratch/jvansanten/metaprojects/combo/build/lib/tools:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/lib:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/lib64:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/../distrib/jdk1.6.0_24_RHEL_7_x86_64/lib:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/../distrib/jdk1.6.0_24_RHEL_7_x86_64/jre/lib:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/../distrib/jdk1.6.0_24_RHEL_7_x86_64/jre/lib/amd64:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/../distrib/jdk1.6.0_24_RHEL_7_x86_64/jre/lib/amd64/server:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/lib:.:/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/lib:/lib64/tls/x86_64:/lib64/tls:/lib64/x86_64:/lib64:/usr/lib64/tls/x86_64:/usr/lib64/tls:/usr/lib64/x86_64:/usr/lib64\nTraceback (most recent call last):\n  File \"<string>\", line 1, in <module>\n  File \"/scratch/jvansanten/metaprojects/combo/build/lib/icecube/MuonGun/__init__.py\", line 3, in <module>\n    load_pybindings(__name__,__path__)\n  File \"/scratch/jvansanten/metaprojects/combo/build/lib/icecube/load_pybindings.py\", line 67, in load_pybindings\n    m = imp.load_dynamic(name, path[0] + \".so\")\nTypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<I3MuonGun::Cylinder>\n}}}\n\nImporting `spline_reco`, `stochastics`, and `MuonGun` in any other order works just fine. `stochastics` appears to unconditionally import pyROOT, which may or may not be related.", 
    "reporter": "jvansanten", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1593001902142004", 
    "component": "combo simulation", 
    "summary": "[MuonGun] import fails if imported after certain modules", 
    "priority": "major", 
    "keywords": "", 
    "time": "2019-03-20T08:41:17", 
    "milestone": "Autumnal Equinox 2020", 
    "owner": "jvansanten", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20190621T17:45:06: 
* olivas changed priority from "normal" to "major"
* olivas commented:

> Seems like something we might want to fix before we get a release out.


* olivas changed milestone from "" to "Summer Solstice 2019"

**Comment by icecube-trac** [comment]
Trac update at 20190621T22:22:37: olivas commented:

> It's time to start thinking about the next milestone.  Going to try something new, since waiting until the code sprints to attack tickets hasn't provided the results we were hoping for.
> 
> If you're the owner of this ticket, please acknowledge you're at least receiving email updates by 'accept'ing this ticket in 3 easy steps.  
> 
> 1) Click "Modify Ticket"
> 2) Click "accept"
> 3) Click "Submit changes"

**Comment by icecube-trac** [comment]
Trac update at 20190624T15:38:19: olivas commented:

> To the owner of this ticket.  Signal you're aware if this ticket, by 'accept'ing it.

**Comment by icecube-trac** [comment]
Trac update at 20190904T13:03:24: 
* olivas changed owner from "" to "jvansanten"
* olivas changed status from "new" to "assigned"
* olivas changed summary from "MuonGun import fails if imported after certain modules" to "[MuonGun] import fails if imported after certain modules"

**Comment by icecube-trac** [comment]
Trac update at 20191209T10:16:33: 
* jvansanten changed resolution from "" to "fixed"
* jvansanten commented:

> In changeset 177773:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="177773"
> Defer ROOT import until tray execution time
> 
> Closes #2250, without actually figuring out why it broke in the first
> place
> ```


* jvansanten changed status from "assigned" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20191220T18:43:06: 
* olivas commented:

> Milestone Winter Solstice 2019 deleted


* olivas changed milestone from "Winter Solstice 2019" to "Vernal Equinox 2020"

**Comment by icecube-trac** [comment]
Trac update at 20200624T12:31:42: 
* olivas commented:

> Milestone Vernal Equinox 2020 deleted


* olivas changed milestone from "Vernal Equinox 2020" to "Autumnal Equinox 2020"
