### ISSUE TITLE
[phys-services] I3SPEFitInjector and pass3 JSON (Trac #2260)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2252]
Getting this message when passing a new pass3 JSON file to SPEFitInjector.  If this doesn't fail later it almost certainly won't get us the results we want and they'll be subtle systematics.  Not good.

The provided JSON file appears to be a older version.
 - Older versions were used for Pass2 charge scaling: 
 - The shape of the charge distribution should come from TA0003.
 - The mean ATWD and FADC charge values are the shifts performed in data.
 - We will set the charge distribution to TA0003 and have the gaussian mean at 1.0.

Migrated from https://code.icecube.wisc.edu/ticket/2260
```json
{
    "status": "closed", 
    "changetime": "2019-04-02T15:02:38", 
    "description": "Getting this message when passing a new pass3 JSON file to SPEFitInjector.  If this doesn't fail later it almost certainly won't get us the results we want and they'll be subtle systematics.  Not good.\n\nThe provided JSON file appears to be a older version.\n - Older versions were used for Pass2 charge scaling: \n - The shape of the charge distribution should come from TA0003.\n - The mean ATWD and FADC charge values are the shifts performed in data.\n - We will set the charge distribution to TA0003 and have the gaussian mean at 1.0.\n", 
    "reporter": "olivas", 
    "cc": "rsnihur, david.schultz, saxani", 
    "resolution": "fixed", 
    "_ts": "1554217358326110", 
    "component": "combo core", 
    "summary": "[phys-services] I3SPEFitInjector and pass3 JSON", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2019-03-21T01:59:11", 
    "milestone": "Vernal Equinox 2019", 
    "owner": "olivas", 
    "type": "rumor / allegation"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20190321T21:08:27: rsnihur commented:

> David Schultz just now changed filterscripts/resources/pass3/prepare_spe_corrected_gcd.py in combo trunk so that it gets spe_fit_injector from phys_services instead of sim_services .
> 
> When I made this change myself and executed prepare_spe_corrected_gcd.py on a run from late 2017 (run 130475) an exception is thrown:
> 
> WARN (Python): I3Calibration: Skipping device TP7P2509: has OMKey 9-16 but insufficient calibration data: Missing: Front End Impedance (I3CalibrationBuilder.py:262 in buildI3Calibration)
> ERROR (I3Module): I3SPEFitInjector_0000: Exception thrown (I3Module.cxx:123 in void I3Module::Do(void (I3Module::*)()))
> The provided JSON file appears to be a newer version.
>  - Newer versions include: 
>  - A description of the individual charge distributions with two exponentials and a gaussian. After the charge shift.
>  - A compensation factor such that the DOM efficiency does not need to be scaled.
>  - A mean ATWD and FADC charge, corresponding to the charge shift performed in data.
> Traceback (most recent call last):
>   File "/data/user/i3filter/IC86_OfflineProcessing/combo/TrunkCobalt-sl6NewWavedeform8/filterscripts/resources/pass3/prepare_spe_corrected_gcd.py", line 44, in <module>
>     main()
>   File "/data/user/i3filter/IC86_OfflineProcessing/combo/TrunkCobalt-sl6NewWavedeform8/filterscripts/resources/pass3/prepare_spe_corrected_gcd.py", line 41, in main
>     run(**vars(args))
>   File "/data/user/i3filter/IC86_OfflineProcessing/combo/TrunkCobalt-sl6NewWavedeform8/filterscripts/resources/pass3/prepare_spe_corrected_gcd.py", line 24, in run
>     tray.Execute()
>   File "/data/user/i3filter/IC86_OfflineProcessing/combo/RHEL_6_TrunkCobalt-sl6NewWavedeform8/lib/I3Tray.py", line 256, in Execute
>     super(I3Tray, self).Execute()
>   File "/data/user/i3filter/IC86_OfflineProcessing/combo/RHEL_6_TrunkCobalt-sl6NewWavedeform8/lib/icecube/phys_services/spe_fit_injector.py", line 146, in Calibration
>     self.spe_fit_injector(frame)
>   File "/data/user/i3filter/IC86_OfflineProcessing/combo/RHEL_6_TrunkCobalt-sl6NewWavedeform8/lib/icecube/phys_services/spe_fit_injector.py", line 135, in __call__
>     self.__load_from_new_json(frame)
>   File "/data/user/i3filter/IC86_OfflineProcessing/combo/RHEL_6_TrunkCobalt-sl6NewWavedeform8/lib/icecube/phys_services/spe_fit_injector.py", line 63, in __load_from_new_json
>     setattr(spe_distribution, attr, fits['ATWD_fit'][attr])
> KeyError: 'compensation_factor'
> 
> 
> NB: For new Wavedeform , I believe the correct JSON file to use is /data/ana/SterileNeutrino/IC86/HighEnergy/SPE_Templates/SPE_harvesting/SPE_fits/923_NewWaveDeform/IC86.2017_923_NewWaveDeform.json and for 2016 data, it would be IC86.2016_923_NewWaveDeform.json (in the same directory) -- NOT IC86.2016_923_NewWaveDeform_Pass3.json
> 
> Perhaps Spencer can confirm.
> 
> Thx,
> -Rob
>

**Comment by icecube-trac** [comment]
Trac update at 20190322T13:42:01: olivas changed status from "new" to "accepted"

**Comment by icecube-trac** [comment]
Trac update at 20190326T02:39:41: olivas commented:

> Ok.  I get the same thing when I try the injector test on that file.
> 
>  $ ./phys-services/resources/test/test_spe_fit_injector.py --json-file=./IC86.2017_923_NewWaveDeform.json
> INFO (I3Tray): Adding Anonymous Module of type 'I3InfiniteSource' with name 'I3InfiniteSource_0000' (I3Tray.py:76 in _create_name)
> INFO (I3Tray): Adding Anonymous Module of type '<class 'icecube.phys_services.spe_fit_injector.I3SPEFitInjector'>' with name 'I3SPEFitInjector_0000' (I3Tray.py:76 in _create_name)
> INFO (I3Tray): Adding Anonymous Module of type '<class '__main__.SPEFitTestModule'>' with name 'SPEFitTestModule_0000' (I3Tray.py:76 in _create_name)
> INFO (I3InfiniteSource): Prefixing with filename/url /home/olivas/icecube/test-data/releases/V00-00-01/sim/GeoCalibDetectorStatus_2013.56429_V1.i3.gz (I3InfiniteSource.cxx:56 in virtual void I3InfiniteSource::Configure())
> The provided JSON file appears to be a newer version.
>  - Newer versions include: 
>  - A description of the individual charge distributions with two exponentials and a gaussian. After the charge shift.
>  - A compensation factor such that the DOM efficiency does not need to be scaled.
>  - A mean ATWD and FADC charge, corresponding to the charge shift performed in data.
> ERROR (I3Module): I3SPEFitInjector_0000: Exception thrown (I3Module.cxx:123 in void I3Module::Do(void (I3Module::*)()))
> Traceback (most recent call last):
>   File "./phys-services/resources/test/test_spe_fit_injector.py", line 97, in <module>
>     tray.Execute(4)
>   File "/home/olivas/icecube/combo/trunk/build/lib/I3Tray.py", line 254, in Execute
>     super(I3Tray, self).Execute(args[0])
>   File "/home/olivas/icecube/combo/trunk/build/lib/icecube/phys_services/spe_fit_injector.py", line 146, in Calibration
>     self.spe_fit_injector(frame)
>   File "/home/olivas/icecube/combo/trunk/build/lib/icecube/phys_services/spe_fit_injector.py", line 135, in __call__
>     self.__load_from_new_json(frame)
>   File "/home/olivas/icecube/combo/trunk/build/lib/icecube/phys_services/spe_fit_injector.py", line 63, in __load_from_new_json
>     setattr(spe_distribution, attr, fits['ATWD_fit'][attr])
> KeyError: 'compensation_factor'
> 
> 
> Apparently we can't grab just any old JSON file and we'll need to wait for official files. In the meantime Spencer says this might work: /data/ana/SterileNeutrino/IC86/HighEnergy/SPE_Templates/SPE_harvesting/SPE_fits/923_OWD_50ns/IC86.2014_Pass3.json
> 
> The new JSON files will eventually live (at the end of this week) in production data section that will have a sync target, just like test-data.
> 
> The test doesn't choke at least.

**Comment by icecube-trac** [comment]
Trac update at 20190402T15:02:38: 
* olivas changed status from "accepted" to "closed"
* olivas commented:

> This works if you give it the right JSON file and is no longer a code issue.


* olivas changed resolution from "" to "fixed"
