### ISSUE TITLE
[IceHive] ...is not working anymore (Trac #2290)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2282]
The code below is working with less recent combo versions, not anymore with the newest ones

```text
    from icecube import IceHive

    singleRings = IceHive.RingLimits()
    singleRings.AddLimitPair(IceHive.LimitPair(-255., 255.))
    singleRings.AddLimitPair(IceHive.LimitPair(-272.7, 272.7))
    singleRings.AddLimitPair(IceHive.LimitPair(-165.8, 165.8))
    doubleRings = IceHive.RingLimits()
    doubleRings.AddLimitPair(IceHive.LimitPair(-70., 70.))
    doubleRings.AddLimitPair(IceHive.LimitPair(-131.5, 131.5))
    doubleRings.AddLimitPair(IceHive.LimitPair(-40.8, 40.8))
    tripleRings = IceHive.RingLimits()
    tripleRings.AddLimitPair(IceHive.LimitPair(-70., 70.))
    tripleRings.AddLimitPair(IceHive.LimitPair(-144.1, 144.1))
    tripleRings.AddLimitPair(IceHive.LimitPair(-124.7, 124.7))
    tripleRings.AddLimitPair(IceHive.LimitPair(-82.8, 82.8))
    singleVicinity = IceHive.RingLimits()
    singleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))
    singleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))
    doubleVicinity = IceHive.RingLimits()
    doubleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))
    doubleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))
    doubleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))
    tripleVicinity = IceHive.RingLimits()
    tripleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))
    tripleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))
    tripleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))
    tripleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))

    tray.AddModule("I3IceHive<I3RecoPulse>","IceHiveSplit",
      InputName="InIcePulses",#"OfflinePulses",
      OutputName="MaskedInIcePulses",#"MaskedOfflinePulses",
      SubEventStreamName="IceHiveSplit",
      Multiplicity=4,
      TimeWindow=2000.*I3Units.ns,
      TimeCVMinus=300.*I3Units.ns,
      TimeCVPlus=300.*I3Units.ns,
      TimeCNMinus=200.*I3Units.ns,
      TimeCNPlus=200.*I3Units.ns,
      TimeStatic=200.*I3Units.ns,
      SingleDenseRingLimits=singleRings,
      DoubleDenseRingLimits=doubleRings,
      TripleDenseRingLimits=tripleRings,
      SingleDenseRingVicinity=singleVicinity,
      DoubleDenseRingVicinity=doubleVicinity,
      TripleDenseRingVicinity=tripleVicinity,
      ReadoutWindowMinus = 4000.*I3Units.ns,
      ReadoutWindowPlus = 6000.*I3Units.ns,
      SaveSplitCount=True)

    cleanVicinity = IceHive.RingLimits()
    cleanVicinity.AddLimitPair(IceHive.LimitPair(-70., 70.))
    cleanVicinity.AddLimitPair(IceHive.LimitPair(-70., 70.))
    
    #clean the output pulses in the P-frame
    tray.AddModule("I3HiveCleaning<I3RecoPulse>","HiveClean",
      InputName = "MaskedInIcePulses",#"MaskedOfflinePulses",
      OutputName = "HC"+"MaskedInIcePulses",#+"MaskedOfflinePulses",
      TimeStaticMinus= 600.*I3Units.ns,
      TimeStaticPlus= 600.*I3Units.ns,
      SingleDenseRingVicinity=cleanVicinity,
      DoubleDenseRingVicinity=cleanVicinity,
      TripleDenseRingVicinity=cleanVicinity,
      Stream = icetray.I3Frame.Physics,
      If = lambda f: True)
```

The error I get in running this is 

```text
FATAL (IceHive): File '/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/metaprojects/combo/V00-00-00-RC2/IceHive/resources/data/IC86Topology.dat' seems not to have the correct format; please review the IceHive documentation (Hive-lib.cxx:451 in builder::Topology builder::ReadTopologyFromFile(const string&))
ERROR (I3Tray): Exception thrown while configuring module "IceHiveSplit". (I3Tray.cxx:384 in void I3Tray::Configure())
IceHiveSplit (I3IceHive<I3RecoPulse>)
...
Traceback (most recent call last):
 File "/home/grenzi/L3b/level3_Master.py", line 259, in <module>
   tray.Execute()
 File "/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/metaprojects/combo/V00-00-00-RC2/lib/I3Tray.py", line 256, in Execute
   super(I3Tray, self).Execute()
RuntimeError: File '/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/metaprojects/combo/V00-00-00-RC2/IceHive/resources/data/IC86Topology.dat' seems not to have the correct format; please review the IceHive documentation (in builder::Topology builder::ReadTopologyFromFile(const string&))
```

The file IC86Topology.dat seems to have been the same for 5 years

Migrated from https://code.icecube.wisc.edu/ticket/2290
```json
{
    "status": "closed", 
    "changetime": "2020-06-24T12:31:42", 
    "description": "The code below is working with less recent combo versions, not anymore with the newest ones\n\n\n{{{\n    from icecube import IceHive\n\n    singleRings = IceHive.RingLimits()\n    singleRings.AddLimitPair(IceHive.LimitPair(-255., 255.))\n    singleRings.AddLimitPair(IceHive.LimitPair(-272.7, 272.7))\n    singleRings.AddLimitPair(IceHive.LimitPair(-165.8, 165.8))\n    doubleRings = IceHive.RingLimits()\n    doubleRings.AddLimitPair(IceHive.LimitPair(-70., 70.))\n    doubleRings.AddLimitPair(IceHive.LimitPair(-131.5, 131.5))\n    doubleRings.AddLimitPair(IceHive.LimitPair(-40.8, 40.8))\n    tripleRings = IceHive.RingLimits()\n    tripleRings.AddLimitPair(IceHive.LimitPair(-70., 70.))\n    tripleRings.AddLimitPair(IceHive.LimitPair(-144.1, 144.1))\n    tripleRings.AddLimitPair(IceHive.LimitPair(-124.7, 124.7))\n    tripleRings.AddLimitPair(IceHive.LimitPair(-82.8, 82.8))\n    singleVicinity = IceHive.RingLimits()\n    singleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))\n    singleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))\n    doubleVicinity = IceHive.RingLimits()\n    doubleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))\n    doubleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))\n    doubleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))\n    tripleVicinity = IceHive.RingLimits()\n    tripleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))\n    tripleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))\n    tripleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))\n    tripleVicinity.AddLimitPair(IceHive.LimitPair(-100.,100.))\n\n    tray.AddModule(\"I3IceHive<I3RecoPulse>\",\"IceHiveSplit\",\n      InputName=\"InIcePulses\",#\"OfflinePulses\",\n      OutputName=\"MaskedInIcePulses\",#\"MaskedOfflinePulses\",\n      SubEventStreamName=\"IceHiveSplit\",\n      Multiplicity=4,\n      TimeWindow=2000.*I3Units.ns,\n      TimeCVMinus=300.*I3Units.ns,\n      TimeCVPlus=300.*I3Units.ns,\n      TimeCNMinus=200.*I3Units.ns,\n      TimeCNPlus=200.*I3Units.ns,\n      TimeStatic=200.*I3Units.ns,\n      SingleDenseRingLimits=singleRings,\n      DoubleDenseRingLimits=doubleRings,\n      TripleDenseRingLimits=tripleRings,\n      SingleDenseRingVicinity=singleVicinity,\n      DoubleDenseRingVicinity=doubleVicinity,\n      TripleDenseRingVicinity=tripleVicinity,\n      ReadoutWindowMinus = 4000.*I3Units.ns,\n      ReadoutWindowPlus = 6000.*I3Units.ns,\n      SaveSplitCount=True)\n\n    cleanVicinity = IceHive.RingLimits()\n    cleanVicinity.AddLimitPair(IceHive.LimitPair(-70., 70.))\n    cleanVicinity.AddLimitPair(IceHive.LimitPair(-70., 70.))\n    \n    #clean the output pulses in the P-frame\n    tray.AddModule(\"I3HiveCleaning<I3RecoPulse>\",\"HiveClean\",\n      InputName = \"MaskedInIcePulses\",#\"MaskedOfflinePulses\",\n      OutputName = \"HC\"+\"MaskedInIcePulses\",#+\"MaskedOfflinePulses\",\n      TimeStaticMinus= 600.*I3Units.ns,\n      TimeStaticPlus= 600.*I3Units.ns,\n      SingleDenseRingVicinity=cleanVicinity,\n      DoubleDenseRingVicinity=cleanVicinity,\n      TripleDenseRingVicinity=cleanVicinity,\n      Stream = icetray.I3Frame.Physics,\n      If = lambda f: True)\n}}}\n\nThe error I get in running this is \n\n\n{{{\nFATAL (IceHive): File '/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/metaprojects/combo/V00-00-00-RC2/IceHive/resources/data/IC86Topology.dat' seems not to have the correct format; please review the IceHive documentation (Hive-lib.cxx:451 in builder::Topology builder::ReadTopologyFromFile(const string&))\nERROR (I3Tray): Exception thrown while configuring module \"IceHiveSplit\". (I3Tray.cxx:384 in void I3Tray::Configure())\nIceHiveSplit (I3IceHive<I3RecoPulse>)\n...\nTraceback (most recent call last):\n File \"/home/grenzi/L3b/level3_Master.py\", line 259, in <module>\n   tray.Execute()\n File \"/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/metaprojects/combo/V00-00-00-RC2/lib/I3Tray.py\", line 256, in Execute\n   super(I3Tray, self).Execute()\nRuntimeError: File '/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/metaprojects/combo/V00-00-00-RC2/IceHive/resources/data/IC86Topology.dat' seems not to have the correct format; please review the IceHive documentation (in builder::Topology builder::ReadTopologyFromFile(const string&))\n}}}\n\nThe file IC86Topology.dat seems to have been the same for 5 years", 
    "reporter": "grenzi", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1593001902142004", 
    "component": "combo reconstruction", 
    "summary": "[IceHive] ...is not working anymore", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2019-05-21T13:55:50", 
    "milestone": "Autumnal Equinox 2020", 
    "owner": "jvansanten", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20190621T17:40:38: 
* olivas changed component from "analysis" to "icerec"
* olivas commented:

> We don't release broken code.


* olivas changed milestone from "" to "Summer Solstice 2019"
* olivas changed priority from "normal" to "blocker"

**Comment by icecube-trac** [comment]
Trac update at 20190621T18:44:34: olivas changed summary from "IceHive not working anymore" to "[IceHive] ...is not working anymore"

**Comment by icecube-trac** [comment]
Trac update at 20190621T22:22:37: olivas commented:

> It's time to start thinking about the next milestone.  Going to try something new, since waiting until the code sprints to attack tickets hasn't provided the results we were hoping for.
> 
> If you're the owner of this ticket, please acknowledge you're at least receiving email updates by 'accept'ing this ticket in 3 easy steps.  
> 
> 1) Click "Modify Ticket"
> 2) Click "accept"
> 3) Click "Submit changes"

**Comment by icecube-trac** [comment]
Trac update at 20190624T15:38:19: olivas commented:

> To the owner of this ticket.  Signal you're aware if this ticket, by 'accept'ing it.

**Comment by icecube-trac** [comment]
Trac update at 20190904T13:05:09: 
* olivas commented:

> Tickets for projects with no owners get assigned to the Tech Lead.


* olivas changed owner from "" to "carguelles"
* olivas changed status from "new" to "assigned"

**Comment by icecube-trac** [comment]
Trac update at 20191207T13:09:52: 
* olivas commented:

> We just learned this week that the hives are not used only by the BSM, but are used in Muon L3, so a much wider group.  It's not really fair to assign this to the BSM WG Tech Lead.  Carlos, you're off the hook. :)


* olivas changed owner from "carguelles" to ""

**Comment by icecube-trac** [comment]
Trac update at 20191207T13:30:20: 
* jvansanten commented:

> This looks like a permissions issue that only appears on CVMFS, but not on local builds. The function in question uses `std::fstream`, which implies write permission it doesn't have on read-only CVMFS. Instead, it should use `std::ifstream` to read files. It looks like happens a lot on IceHive; Chris Weaver cleaned up some of it, but not all.


* jvansanten changed _comment1 from "This looks like a permissions issue that only appears on CVMFS, but not on local builds. The function in question uses `std::fstream`, which implies write permission it doesn't have on read-only CVMFS. Instead, it should use `std::ifstream` to read files." to "1575725541541774"
* jvansanten changed _comment0 from "This looks like a permissions issue that only appears on CVMFS, but not on local builds. The code opens uses `std::fstream`, which implies write permission it doesn't have on read-only CVMFS." to "1575725497298673"

**Comment by icecube-trac** [comment]
Trac update at 20191209T10:25:36: 
* jvansanten changed status from "assigned" to "closed"
* jvansanten changed owner from "" to "jvansanten"
* jvansanten commented:

> In changeset 177774:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="177774"
> Open files without demanding write permission
> 
> Also, check whether the file actually opened. Fixes #2282.
> ```


* jvansanten changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20191220T18:43:06: 
* olivas changed milestone from "Winter Solstice 2019" to "Vernal Equinox 2020"
* olivas commented:

> Milestone Winter Solstice 2019 deleted

**Comment by icecube-trac** [comment]
Trac update at 20200624T12:31:42: 
* olivas changed milestone from "Vernal Equinox 2020" to "Autumnal Equinox 2020"
* olivas commented:

> Milestone Vernal Equinox 2020 deleted
