### ISSUE TITLE
[weighting] problem reading simulation steering files (Trac #2292)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2284]
Some CORSIKA datasets steering files have some values in an inconvenient format (ex: eprimarymax in string, instead of float/int)

This causes weighting.weighting.from_simprod(dataset_number) to fail, being it unable to multiply strings and numbers.

Problem appeared at line 929 of [https://code.icecube.wisc.edu/projects/icecube/browser/IceCube/meta-projects/combo/stable/weighting/python/weighting.py here]

example error belowis produced with old version (just not the same line of the code)

```text
FATAL (IceHive): File '/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/metaprojects/combo/V00-00-00-RC2/IceHive/resources/data/IC86Topology.dat' seems not to have the correct format; please review the IceHive documentation (Hive-lib.cxx:451 in builder::Topology builder::ReadTopologyFromFile(const string&))
ERROR (I3Tray): Exception thrown while configuring module "IceHiveSplit". (I3Tray.cxx:384 in void I3Tray::Configure())
IceHiveSplit (I3IceHive<I3RecoPulse>)
...
Traceback (most recent call last):
 File "/home/grenzi/L3b/level3_Master.py", line 259, in <module>
   tray.Execute()
 File "/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/metaprojects/combo/V00-00-00-RC2/lib/I3Tray.py", line 256, in Execute
   super(I3Tray, self).Execute()
RuntimeError: File '/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/metaprojects/combo/V00-00-00-RC2/IceHive/resources/data/IC86Topology.dat' seems not to have the correct format; please review the IceHive documentation (in builder::Topology builder::ReadTopologyFromFile(const string&))
```

An easy solution could be just wrapping possible affected values in float() functions all along the code

Migrated from https://code.icecube.wisc.edu/ticket/2292
```json
{
    "status": "closed", 
    "changetime": "2020-06-24T12:31:42", 
    "description": "Some CORSIKA datasets steering files have some values in an inconvenient format (ex: eprimarymax in string, instead of float/int)\n\nThis causes weighting.weighting.from_simprod(dataset_number) to fail, being it unable to multiply strings and numbers.\n\nProblem appeared at line 929 of [https://code.icecube.wisc.edu/projects/icecube/browser/IceCube/meta-projects/combo/stable/weighting/python/weighting.py here]\n\nexample error belowis produced with old version (just not the same line of the code)\n\n{{{\nFATAL (IceHive): File '/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/metaprojects/combo/V00-00-00-RC2/IceHive/resources/data/IC86Topology.dat' seems not to have the correct format; please review the IceHive documentation (Hive-lib.cxx:451 in builder::Topology builder::ReadTopologyFromFile(const string&))\nERROR (I3Tray): Exception thrown while configuring module \"IceHiveSplit\". (I3Tray.cxx:384 in void I3Tray::Configure())\nIceHiveSplit (I3IceHive<I3RecoPulse>)\n...\nTraceback (most recent call last):\n File \"/home/grenzi/L3b/level3_Master.py\", line 259, in <module>\n   tray.Execute()\n File \"/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/metaprojects/combo/V00-00-00-RC2/lib/I3Tray.py\", line 256, in Execute\n   super(I3Tray, self).Execute()\nRuntimeError: File '/cvmfs/icecube.opensciencegrid.org/py2-v3.1.1/RHEL_7_x86_64/metaprojects/combo/V00-00-00-RC2/IceHive/resources/data/IC86Topology.dat' seems not to have the correct format; please review the IceHive documentation (in builder::Topology builder::ReadTopologyFromFile(const string&))\n}}}\n\nAn easy solution could be just wrapping possible affected values in float() functions all along the code", 
    "reporter": "grenzi", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1593001902142004", 
    "component": "combo simulation", 
    "summary": "[weighting] problem reading simulation steering files", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2019-05-22T15:34:40", 
    "milestone": "Autumnal Equinox 2020", 
    "owner": "jvansanten", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20190621T18:02:31: 
* olivas changed priority from "normal" to "blocker"
* olivas changed milestone from "" to "Summer Solstice 2019"
* olivas commented:

> We don't release broken code.

**Comment by icecube-trac** [comment]
Trac update at 20190621T18:45:36: 
* olivas changed owner from "" to "jvansanten"
* olivas changed summary from "weighting: problem reading simulation steering files" to "[weighting] problem reading simulation steering files"
* olivas changed status from "new" to "assigned"

**Comment by icecube-trac** [comment]
Trac update at 20190621T22:22:37: olivas commented:

> It's time to start thinking about the next milestone.  Going to try something new, since waiting until the code sprints to attack tickets hasn't provided the results we were hoping for.
> 
> If you're the owner of this ticket, please acknowledge you're at least receiving email updates by 'accept'ing this ticket in 3 easy steps.  
> 
> 1) Click "Modify Ticket"
> 2) Click "accept"
> 3) Click "Submit changes"

**Comment by icecube-trac** [comment]
Trac update at 20190624T15:38:19: olivas commented:

> To the owner of this ticket.  Signal you're aware if this ticket, by 'accept'ing it.

**Comment by icecube-trac** [comment]
Trac update at 20191209T09:40:53: jvansanten commented:

> Can you detail how to reproduce this problem? The pasted snippet in the original report refers to a problem with `IceHive`, not `weighting`.

**Comment by icecube-trac** [comment]
Trac update at 20191209T09:46:49: flauber commented:

> Its basically the generalization of this ticket: https://code.icecube.wisc.edu/projects/icecube/ticket/2178
> 
> For some reason some steering file values are sometimes stored as strings instead of floats which leads to conversion errors in the weighting module. My local fix was to just wrap everything in int or float but I would very much like to track down the root cause as other software might have the same problem but silently fail. 
>

**Comment by icecube-trac** [comment]
Trac update at 20191209T10:15:29: 
* jvansanten changed status from "assigned" to "closed"
* jvansanten commented:

> Appears to have been fixed upstream by #2170


* jvansanten changed resolution from "" to "duplicate"

**Comment by icecube-trac** [comment]
Trac update at 20191209T11:18:15: 
* flauber changed resolution from "duplicate" to ""
* flauber commented:

> This has not been fixed upstream as the referenced ticket was only concerned with one dataset while the issue resides in multiple datasets up to date. So we can either open tickets for each and every broken steering file or we can modify the weighting module to deal with string instead of floats or ints in the first place. The later solution is pretty easy to implement but I am not sure about the side effects it might bring as well as other software which reads the steering file and might interpret strings differently than doubles or ints.
> 
> Independent of that, we should make sure that in the future steering files have the correct datatype to begin with. Most of these should be easy fixes but I am not deep enough in the material to see if these fixes make the situation better or worse in the long run. 
> 
> 


* flauber changed status from "closed" to "reopened"

**Comment by icecube-trac** [comment]
Trac update at 20191209T15:20:58: 
* jvansanten changed resolution from "" to "fixed"
* jvansanten changed status from "reopened" to "closed"
* jvansanten commented:

> In changeset 177779:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="177779"
> Explicitly cast most steering parameters to desired type
> 
> Along the way, add a test script that queries weighting for all
> datasets not related to Nancy's private simulation, IceTop, or pre-IC59
> simulations. It passes those, so maybe this fixes #2284 ?
> ```

**Comment by icecube-trac** [comment]
Trac update at 20191209T15:29:53: flauber commented:

> Thanks, that looks much more comprehensive than the changes I had planed and the test scripts is an awesome addition. Again, thanks a lot for helping with this. From the diff alone I would thing this fixes the issue, I will have to run some weighting next week and report back if any problem remains.

**Comment by icecube-trac** [comment]
Trac update at 20191220T18:43:06: 
* olivas changed milestone from "Winter Solstice 2019" to "Vernal Equinox 2020"
* olivas commented:

> Milestone Winter Solstice 2019 deleted

**Comment by icecube-trac** [comment]
Trac update at 20200624T12:31:42: 
* olivas changed milestone from "Vernal Equinox 2020" to "Autumnal Equinox 2020"
* olivas commented:

> Milestone Vernal Equinox 2020 deleted
