### ISSUE TITLE
[frame_object_diff] Test Scripts Error (Trac #2327)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2319]
When running tests script test_segment.py for frame_object_diff I receive this error. 

ERROR: test_std (__main__.SegmentTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_segments.py", line 54, in tearDown
    shutil.rmtree(self.tmpdir)
  File "/cvmfs/icecube.opensciencegrid.org/py2-v3.0.1/RHEL_7_x86_64/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/cvmfs/icecube.opensciencegrid.org/py2-v3.0.1/RHEL_7_x86_64/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/amedina/trunk/frame_object_diff/resources/test/tmpKrPXr_'

Migrated from https://code.icecube.wisc.edu/ticket/2327
```json
{
    "status": "closed", 
    "changetime": "2020-06-24T12:31:42", 
    "description": "When running tests script test_segment.py for frame_object_diff I receive this error. \n\nERROR: test_std (__main__.SegmentTests)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"test_segments.py\", line 54, in tearDown\n    shutil.rmtree(self.tmpdir)\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v3.0.1/RHEL_7_x86_64/lib/python2.7/shutil.py\", line 256, in rmtree\n    onerror(os.rmdir, path, sys.exc_info())\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v3.0.1/RHEL_7_x86_64/lib/python2.7/shutil.py\", line 254, in rmtree\n    os.rmdir(path)\nOSError: [Errno 39] Directory not empty: '/home/amedina/trunk/frame_object_diff/resources/test/tmpKrPXr_'\n", 
    "reporter": "amedina", 
    "cc": "", 
    "resolution": "worksforme", 
    "_ts": "1593001902142004", 
    "component": "combo core", 
    "summary": "[frame_object_diff] Test Scripts Error", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2019-06-18T23:58:24", 
    "milestone": "Autumnal Equinox 2020", 
    "owner": "olivas", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20190621T18:04:47: 
* olivas changed priority from "normal" to "blocker"
* olivas changed component from "other" to "icecube offline"
* olivas commented:

> We don't release broken code.


* olivas changed summary from "Test Scripts Error" to "[frame_object_diff] Test Scripts Error"
* olivas changed milestone from "" to "Summer Solstice 2019"

**Comment by icecube-trac** [comment]
Trac update at 20190621T22:22:37: olivas commented:

> It's time to start thinking about the next milestone.  Going to try something new, since waiting until the code sprints to attack tickets hasn't provided the results we were hoping for.
> 
> If you're the owner of this ticket, please acknowledge you're at least receiving email updates by 'accept'ing this ticket in 3 easy steps.  
> 
> 1) Click "Modify Ticket"
> 2) Click "accept"
> 3) Click "Submit changes"

**Comment by icecube-trac** [comment]
Trac update at 20190624T15:38:19: olivas commented:

> To the owner of this ticket.  Signal you're aware if this ticket, by 'accept'ing it.

**Comment by icecube-trac** [comment]
Trac update at 20190904T13:07:00: 
* olivas changed owner from "" to "olivas"
* olivas changed status from "new" to "accepted"

**Comment by icecube-trac** [comment]
Trac update at 20191207T13:01:56: 
* olivas changed resolution from "" to "worksforme"
* olivas changed status from "accepted" to "closed"
* olivas commented:

> I can't reproduce this.  frame_object_diff tests work fine for me.  I'm going to assume this was an intermittent, (perhaps) old test failures that's since resolved.

**Comment by icecube-trac** [comment]
Trac update at 20191220T18:43:06: 
* olivas changed milestone from "Winter Solstice 2019" to "Vernal Equinox 2020"
* olivas commented:

> Milestone Winter Solstice 2019 deleted

**Comment by icecube-trac** [comment]
Trac update at 20200624T12:31:42: 
* olivas commented:

> Milestone Vernal Equinox 2020 deleted


* olivas changed milestone from "Vernal Equinox 2020" to "Autumnal Equinox 2020"
