### ISSUE TITLE
[BadDomList] Test Scripts Error (Trac #2328)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2320]
When running BadDomListModule.py for BadDomList I receive this error:

ERROR (I3Module): BadDoms: Exception thrown (I3Module.cxx:123 in void I3Module::Do(void (I3Module::*)()))
{'I3LiveUrlRunDoms': '/home/amedina/trunk/BadDomList/resources/test/tmpmCRxu0/empty.%s.json', 'I3LiveUrlSnapshotExport': '/home/amedina/trunk/BadDomList/resources/test/tmpmCRxu0/empty.127797.json'}
INFO (I3Reader): Opened file /data/user/amedina/test-data/trunk/GCD/Level2_IC86.2015_data_Run00127797_21_242_GCD.i3.gz (I3Reader.cxx:179 in void I3Reader::OpenNextFile())
INFO (Python): Getting unconfigured OMs (BadDomListModule.py:157 in _GetUnconfiguredDoms)
ERROR (I3Module): BadDoms: Exception thrown (I3Module.cxx:123 in void I3Module::Do(void (I3Module::*)()))
Traceback (most recent call last):
  File "BadDomListModule.py", line 117, in <module>
    shutil.rmtree(tmp_dir)
  File "/cvmfs/icecube.opensciencegrid.org/py2-v3.0.1/RHEL_7_x86_64/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/cvmfs/icecube.opensciencegrid.org/py2-v3.0.1/RHEL_7_x86_64/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/home/amedina/trunk/BadDomList/resources/test/tmpmCRxu0'

Migrated from https://code.icecube.wisc.edu/ticket/2328
```json
{
    "status": "closed", 
    "changetime": "2020-06-24T12:31:42", 
    "description": "When running BadDomListModule.py for BadDomList I receive this error:\n\nERROR (I3Module): BadDoms: Exception thrown (I3Module.cxx:123 in void I3Module::Do(void (I3Module::*)()))\n{'I3LiveUrlRunDoms': '/home/amedina/trunk/BadDomList/resources/test/tmpmCRxu0/empty.%s.json', 'I3LiveUrlSnapshotExport': '/home/amedina/trunk/BadDomList/resources/test/tmpmCRxu0/empty.127797.json'}\nINFO (I3Reader): Opened file /data/user/amedina/test-data/trunk/GCD/Level2_IC86.2015_data_Run00127797_21_242_GCD.i3.gz (I3Reader.cxx:179 in void I3Reader::OpenNextFile())\nINFO (Python): Getting unconfigured OMs (BadDomListModule.py:157 in _GetUnconfiguredDoms)\nERROR (I3Module): BadDoms: Exception thrown (I3Module.cxx:123 in void I3Module::Do(void (I3Module::*)()))\nTraceback (most recent call last):\n  File \"BadDomListModule.py\", line 117, in <module>\n    shutil.rmtree(tmp_dir)\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v3.0.1/RHEL_7_x86_64/lib/python2.7/shutil.py\", line 256, in rmtree\n    onerror(os.rmdir, path, sys.exc_info())\n  File \"/cvmfs/icecube.opensciencegrid.org/py2-v3.0.1/RHEL_7_x86_64/lib/python2.7/shutil.py\", line 254, in rmtree\n    os.rmdir(path)\nOSError: [Errno 39] Directory not empty: '/home/amedina/trunk/BadDomList/resources/test/tmpmCRxu0'", 
    "reporter": "amedina", 
    "cc": "", 
    "resolution": "worksforme", 
    "_ts": "1593001902142004", 
    "component": "combo core", 
    "summary": "[BadDomList] Test Scripts Error", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2019-06-18T23:59:24", 
    "milestone": "Autumnal Equinox 2020", 
    "owner": "rsnihur", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20190621T18:06:04: 
* olivas changed component from "other" to "icecube offline"
* olivas changed priority from "normal" to "blocker"
* olivas changed summary from "Test Scripts Error" to "[BadDomList] Test Scripts Error"
* olivas changed milestone from "" to "Summer Solstice 2019"

**Comment by icecube-trac** [comment]
Trac update at 20190621T22:22:37: olivas commented:

> It's time to start thinking about the next milestone.  Going to try something new, since waiting until the code sprints to attack tickets hasn't provided the results we were hoping for.
> 
> If you're the owner of this ticket, please acknowledge you're at least receiving email updates by 'accept'ing this ticket in 3 easy steps.  
> 
> 1) Click "Modify Ticket"
> 2) Click "accept"
> 3) Click "Submit changes"

**Comment by icecube-trac** [comment]
Trac update at 20190624T15:38:19: olivas commented:

> To the owner of this ticket.  Signal you're aware if this ticket, by 'accept'ing it.

**Comment by icecube-trac** [comment]
Trac update at 20190904T13:07:34: 
* olivas changed owner from "" to "rsnihur"
* olivas changed status from "new" to "assigned"

**Comment by icecube-trac** [comment]
Trac update at 20191210T15:28:26: 
* rsnihur changed status from "assigned" to "closed"
* rsnihur commented:

> After consulting with the ticket reporter, neither of us could reproduce this error.


* rsnihur changed resolution from "" to "worksforme"

**Comment by icecube-trac** [comment]
Trac update at 20191220T18:43:06: 
* olivas changed milestone from "Winter Solstice 2019" to "Vernal Equinox 2020"
* olivas commented:

> Milestone Winter Solstice 2019 deleted

**Comment by icecube-trac** [comment]
Trac update at 20200624T12:31:42: 
* olivas commented:

> Milestone Vernal Equinox 2020 deleted


* olivas changed milestone from "Vernal Equinox 2020" to "Autumnal Equinox 2020"
