### ISSUE TITLE
[PROPOSAL] just_use_readonly_path causes test failures (Trac #2335)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2327]
I am not sure what the purpose of this option is but it causes a lot of test failures on my machine. Setting it to false in PROPOSAL/resources/config_icesim.json causes those test to pass. I recommend we change that file or some other remedy. 

Migrated from https://code.icecube.wisc.edu/ticket/2335
```json
{
    "status": "closed", 
    "changetime": "2019-06-28T15:35:02", 
    "description": "I am not sure what the purpose of this option is but it causes a lot of test failures on my machine. Setting it to false in PROPOSAL/resources/config_icesim.json causes those test to pass. I recommend we change that file or some other remedy. ", 
    "reporter": "kjmeagher", 
    "cc": "", 
    "resolution": "invalid", 
    "_ts": "1561736102787341", 
    "component": "combo simulation", 
    "summary": "[PROPOSAL] just_use_readonly_path causes test failures", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2019-06-26T21:18:01", 
    "milestone": "Autumnal Equinox 2019", 
    "owner": "jsoedingrekso", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20190627T02:46:46: jsoedingrekso commented:

> This is due to ticket #2321
> So one should use preprocessed tables, otherwise if always the wrong path is given, PROPOSAL just stores the tables in memory. This is somehow to prevent someone running into this without realising it.
> 
> If you use the Interpolation tables from `code.icecube.wisc.edu/test-data/releases/V00-00-01/` which are the tables in `/cvmfs/icecube.opensciencegrid.org/data/i3-test-data/` the tests will fail, because there the old tables are stored.
> 
> In `code.icecube.wisc.edu/test-data/trunk/` I put the new tables in r115, with which the tests are running.

**Comment by icecube-trac** [comment]
Trac update at 20190628T14:23:00: 
* olivas changed status from "new" to "assigned"
* olivas changed owner from "" to "jsoedingrekso"
* olivas commented:

> This causes failures in production as well.
> 
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
>     self.run()
>   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/olivas/cicada/cicada/ci/executor.py", line 69, in __call__
>     self.executor(self.run_logger)
>   File "/home/olivas/icecube_cicada/icecube_cicada/executors/icesim.py", line 257, in __call__
>     ppc.ExecuteOpts(stats)
>   File "/home/olivas/icecube/combo/trunk/build/lib/icecube/simprod/ipmodule.py", line 219, in ExecuteOpts
>     retval = self.Execute(stats)
>   File "/home/olivas/icecube/combo/trunk/build/lib/icecube/simprod/modules/ppc.py", line 224, in Execute
>     self.Configure(tray)
>   File "/home/olivas/icecube/combo/trunk/build/lib/icecube/simprod/modules/ppc.py", line 162, in Configure
>     **self.proposalparams
>   File "/home/olivas/icecube/combo/trunk/build/lib/I3Tray.py", line 224, in AddSegment
>     return _segment(self, _name, **kwargs)
>   File "/home/olivas/icecube/combo/trunk/build/lib/icecube/simprod/segments/PropagateMuons.py", line 67, in PropagateMuons
>     propagators = make_standard_propagators(**kwargs)
>   File "/home/olivas/icecube/combo/trunk/build/lib/icecube/simprod/segments/PropagateMuons.py", line 120, in make_standard_propagators
>     config_file=PROPOSAL_config_file)
> RuntimeError: The just_use_readonly_path option is enabled and the table is not in the readonly path. (in void PROPOSAL::Helper::InitializeInterpolation(std::__cxx11::string, PROPOSAL::Helper::InterpolantBuilderContainer&, const std::vector<PROPOSAL::Parametrization*>&, PROPOSAL::InterpolationDef))
> 


* olivas changed priority from "normal" to "blocker"

**Comment by icecube-trac** [comment]
Trac update at 20190628T14:59:04: 
* jsoedingrekso commented:

> Does this problem still occur if one uses the tables in `code.icecube.wisc.edu/test-data/trunk/`?


* jsoedingrekso changed status from "assigned" to "accepted"

**Comment by icecube-trac** [comment]
Trac update at 20190628T15:35:02: 
* olivas changed status from "accepted" to "closed"
* olivas commented:

> Ok.  Seems to work with the latest tables from the trunk of test-data.


* olivas changed resolution from "" to "invalid"
