### ISSUE TITLE
[simprod-scripts] MuonGun segment fails (Trac #2346)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2338]
Traceback (most recent call last):
  File "/build/buildslave/stheno/Ubuntu_18_04/source/simprod-scripts/resources/tests/generators/mgun-dc.py", line 31, in <module>
    if n.Execute({}) != 0:
  File "/build/buildslave/stheno/Ubuntu_18_04/build/lib/icecube/simprod/modules/muongun.py", line 212, in Execute
    tray.AddSegment(clsim.I3CLSimMakeHits, "makeCLSimHits",
AttributeError: 'module' object has no attribute 'I3CLSimMakeHits'

This is on the bots.  I'm pretty sure that fails only on machines w/o OpenCL installed.  This needs to be verified and there should be a proper ocl detection and clearer warning.

Migrated from https://code.icecube.wisc.edu/ticket/2346
```json
{
    "status": "closed", 
    "changetime": "2019-12-11T15:34:54", 
    "description": "Traceback (most recent call last):\n  File \"/build/buildslave/stheno/Ubuntu_18_04/source/simprod-scripts/resources/tests/generators/mgun-dc.py\", line 31, in <module>\n    if n.Execute({}) != 0:\n  File \"/build/buildslave/stheno/Ubuntu_18_04/build/lib/icecube/simprod/modules/muongun.py\", line 212, in Execute\n    tray.AddSegment(clsim.I3CLSimMakeHits, \"makeCLSimHits\",\nAttributeError: 'module' object has no attribute 'I3CLSimMakeHits'\n\nThis is on the bots.  I'm pretty sure that fails only on machines w/o OpenCL installed.  This needs to be verified and there should be a proper ocl detection and clearer warning.", 
    "reporter": "olivas", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1576078494294884", 
    "component": "combo simulation", 
    "summary": "[simprod-scripts] MuonGun segment fails", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2019-08-29T17:06:47", 
    "milestone": "", 
    "owner": "", 
    "type": "cleanup"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20191211T15:34:54: 
* olivas changed resolution from "" to "fixed"
* olivas changed status from "new" to "closed"
