### ISSUE TITLE
[wavedeform] Timing Test Fails (Trac #2379)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2371]
```text
$ ./wavedeform/resources/test/wavedeform_time_test.py 
INFO (I3InfiniteSource): Prefixing with filename/url /home/olivas/icecube/test-data/trunk/GCD/GeoCalibDetectorStatus_IC86.55697_corrected_V2.i3.gz (I3InfiniteSource.cxx:56 in virtual void I3InfiniteSource::Configure())
F.
======================================================================
FAIL: testLeadingEdgeTime (__main__.TimeCheck)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./wavedeform/resources/test/wavedeform_time_test.py", line 66, in testLeadingEdgeTime
    recofirst, margin, margin*recowidth, om))
AssertionError: False is not true : Sim time (197.029290) and reco time (249.747500) match to within 10 sigma (8.250000 ns) in OM OMKey(21,1,0)

----------------------------------------------------------------------
Ran 2 tests in 0.006s

FAILED (failures=1)
```

Migrated from https://code.icecube.wisc.edu/ticket/2379
```json
{
    "status": "closed", 
    "changetime": "2020-06-24T12:31:42", 
    "description": "{{{\n$ ./wavedeform/resources/test/wavedeform_time_test.py \nINFO (I3InfiniteSource): Prefixing with filename/url /home/olivas/icecube/test-data/trunk/GCD/GeoCalibDetectorStatus_IC86.55697_corrected_V2.i3.gz (I3InfiniteSource.cxx:56 in virtual void I3InfiniteSource::Configure())\nF.\n======================================================================\nFAIL: testLeadingEdgeTime (__main__.TimeCheck)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"./wavedeform/resources/test/wavedeform_time_test.py\", line 66, in testLeadingEdgeTime\n    recofirst, margin, margin*recowidth, om))\nAssertionError: False is not true : Sim time (197.029290) and reco time (249.747500) match to within 10 sigma (8.250000 ns) in OM OMKey(21,1,0)\n\n----------------------------------------------------------------------\nRan 2 tests in 0.006s\n\nFAILED (failures=1)\n}}}", 
    "reporter": "olivas", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1593001902142004", 
    "component": "combo core", 
    "summary": "[wavedeform] Timing Test Fails", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2019-12-10T14:35:56", 
    "milestone": "Autumnal Equinox 2020", 
    "owner": "jbraun", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20191210T14:39:44: olivas changed description from:

> $ ./wavedeform/resources/test/wavedeform_time_test.py 
> INFO (I3InfiniteSource): Prefixing with filename/url /home/olivas/icecube/test-data/trunk/GCD/GeoCalibDetectorStatus_IC86.55697_corrected_V2.i3.gz (I3InfiniteSource.cxx:56 in virtual void I3InfiniteSource::Configure())
> F.
> ======================================================================
> FAIL: testLeadingEdgeTime (__main__.TimeCheck)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "./wavedeform/resources/test/wavedeform_time_test.py", line 66, in testLeadingEdgeTime
>     recofirst, margin, margin*recowidth, om))
> AssertionError: False is not true : Sim time (197.029290) and reco time (249.747500) match to within 10 sigma (8.250000 ns) in OM OMKey(21,1,0)
> 
> ----------------------------------------------------------------------
> Ran 2 tests in 0.006s
> 
> FAILED (failures=1)
> 

to:

> {{{
> $ ./wavedeform/resources/test/wavedeform_time_test.py 
> INFO (I3InfiniteSource): Prefixing with filename/url /home/olivas/icecube/test-data/trunk/GCD/GeoCalibDetectorStatus_IC86.55697_corrected_V2.i3.gz (I3InfiniteSource.cxx:56 in virtual void I3InfiniteSource::Configure())
> F.
> ======================================================================
> FAIL: testLeadingEdgeTime (__main__.TimeCheck)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "./wavedeform/resources/test/wavedeform_time_test.py", line 66, in testLeadingEdgeTime
>     recofirst, margin, margin*recowidth, om))
> AssertionError: False is not true : Sim time (197.029290) and reco time (249.747500) match to within 10 sigma (8.250000 ns) in OM OMKey(21,1,0)
> 
> ----------------------------------------------------------------------
> Ran 2 tests in 0.006s
> 
> FAILED (failures=1)
> }}}

**Comment by icecube-trac** [comment]
Trac update at 20191210T17:58:53: 
* nwhitehorn changed owner from "jbraun" to "nwhitehorn"
* nwhitehorn changed status from "new" to "assigned"

**Comment by icecube-trac** [comment]
Trac update at 20191218T15:49:18: olivas commented:

> This only fails in Python3 (3.6.9).  Passes in Python2 (2.7.15).  Both tested on Ubuntu 18.04.

**Comment by icecube-trac** [comment]
Trac update at 20191218T18:45:12: jbraun changed owner from "nwhitehorn" to "jbraun"

**Comment by icecube-trac** [comment]
Trac update at 20191218T18:45:17: jbraun changed status from "assigned" to "accepted"

**Comment by icecube-trac** [comment]
Trac update at 20191218T18:45:48: 
* jbraun commented:

> In changeset 178080:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="178080"
> Replace non-sensical mean time test with something a bit more precise and less prone to random fluctuations.  Closes #2371.
> ```


* jbraun changed resolution from "" to "fixed"
* jbraun changed status from "accepted" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20191220T18:43:06: 
* olivas changed milestone from "Winter Solstice 2019" to "Vernal Equinox 2020"
* olivas commented:

> Milestone Winter Solstice 2019 deleted

**Comment by icecube-trac** [comment]
Trac update at 20200624T12:31:42: 
* olivas changed milestone from "Vernal Equinox 2020" to "Autumnal Equinox 2020"
* olivas commented:

> Milestone Vernal Equinox 2020 deleted
