### ISSUE TITLE
[filterscripts] grecofilter crashes with Python3 (Trac #2391)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2383]
I'm getting the following error and a throw:

```text
Traceback (most recent call last):
  File "/home/olivas/icecube/combo/trunk/build/lib/icecube/filterscripts/grecofilter.py", line 174, in FirstHit
    x, y, z, t, q = grecovariables.GetHitInformation(frame['I3Geometry'], hits, 1)
  File "/home/olivas/icecube/combo/trunk/build/lib/icecube/filterscripts/grecovariables.py", line 69, in GetHitInformation
    times, charges = np.array(map(lambda pulse: [pulse.time, pulse.charge], pulses)).T
TypeError: iteration over a 0-d array

The above exception was the direct cause of the following exception:

SystemError: <built-in method get of dict object at 0x7fbeaa2c5dc8> returned a result with an error set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/olivas/icecube/combo/trunk/build/filterscripts/resources/scripts/SimulationFiltering.py", line 395, in <module>
    main(opts)
  File "/home/olivas/icecube/combo/trunk/build/filterscripts/resources/scripts/SimulationFiltering.py", line 352, in main
    tray.Execute()
  File "/home/olivas/icecube/combo/trunk/build/lib/I3Tray.py", line 256, in Execute
    super(I3Tray, self).Execute()
SystemError: <built-in method get of dict object at 0x7fbeaa2c5dc8> returned a result with an error set
```

Setting the milestone for the Spring release, since we'll likely not be able to support Python3 with this release.

Migrated from https://code.icecube.wisc.edu/ticket/2391
```json
{
    "status": "closed", 
    "changetime": "2020-06-24T12:31:42", 
    "description": "I'm getting the following error and a throw:\n\n{{{\nTraceback (most recent call last):\n  File \"/home/olivas/icecube/combo/trunk/build/lib/icecube/filterscripts/grecofilter.py\", line 174, in FirstHit\n    x, y, z, t, q = grecovariables.GetHitInformation(frame['I3Geometry'], hits, 1)\n  File \"/home/olivas/icecube/combo/trunk/build/lib/icecube/filterscripts/grecovariables.py\", line 69, in GetHitInformation\n    times, charges = np.array(map(lambda pulse: [pulse.time, pulse.charge], pulses)).T\nTypeError: iteration over a 0-d array\n\nThe above exception was the direct cause of the following exception:\n\nSystemError: <built-in method get of dict object at 0x7fbeaa2c5dc8> returned a result with an error set\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/home/olivas/icecube/combo/trunk/build/filterscripts/resources/scripts/SimulationFiltering.py\", line 395, in <module>\n    main(opts)\n  File \"/home/olivas/icecube/combo/trunk/build/filterscripts/resources/scripts/SimulationFiltering.py\", line 352, in main\n    tray.Execute()\n  File \"/home/olivas/icecube/combo/trunk/build/lib/I3Tray.py\", line 256, in Execute\n    super(I3Tray, self).Execute()\nSystemError: <built-in method get of dict object at 0x7fbeaa2c5dc8> returned a result with an error set\n}}}\n\nSetting the milestone for the Spring release, since we'll likely not be able to support Python3 with this release.", 
    "reporter": "olivas", 
    "cc": "mjlarson@umd.edu", 
    "resolution": "fixed", 
    "_ts": "1593001902142004", 
    "component": "jeb + pnf", 
    "summary": "[filterscripts] grecofilter crashes with Python3", 
    "priority": "blocker", 
    "keywords": "", 
    "time": "2019-12-19T04:55:52", 
    "milestone": "Autumnal Equinox 2020", 
    "owner": "blaufuss", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20191219T23:13:07: blaufuss changed status from "new" to "accepted"

**Comment by icecube-trac** [comment]
Trac update at 20191219T23:13:34: blaufuss changed cc from "" to "mjlarson@umd.edu"

**Comment by icecube-trac** [comment]
Trac update at 20200116T20:02:36: 
* mjl5147 changed status from "accepted" to "closed"
* mjl5147 commented:

> In changeset 178499:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="178499"
> Fix the python3 map comprehension in the online greco scripts to close #2383
> ```


* mjl5147 changed resolution from "" to "fixed"

**Comment by icecube-trac** [comment]
Trac update at 20200624T12:31:42: 
* olivas commented:

> Milestone Vernal Equinox 2020 deleted


* olivas changed milestone from "Vernal Equinox 2020" to "Autumnal Equinox 2020"
