### ISSUE TITLE
CLSsim in py2-v3.1.1: math.isfinite does not exist (Trac #2393)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2385]
clsim/traysegments/common.py refers to 'math.isinfinite' which is not present in python 2.7. (should be 'math.isinf')

```text
NOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:496 in void I3Tray::Execute(unsigned int))
Traceback (most recent call last):
  File "simprod-scripts/resources/scripts/clsim.py", line 154, in <module>
    main()
  File "simprod-scripts/resources/scripts/clsim.py", line 150, in main
    usegslrng=params['usegslrng'])
  File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/simprod/util/simprodtray.py", line 143, in RunI3Tray
    configure_tray(tray, params, stats, logger)
  File "simprod-scripts/resources/scripts/clsim.py", line 111, in configure_tray
    HoleIceParameterization=params['holeiceparametrization'])
  File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/I3Tray.py", line 224, in AddSegment
    return _segment(self, _name, **kwargs)
  File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/I3CLSimMakeHits.py", line 34, in I3CLSimMakeHits
    return I3CLSimMakePhotons(tray, name, **kwargs)
  File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/I3CLSimMakePhotons.py", line 278, in I3CLSimMakePhotons
    IgnoreSubdetectors=IgnoreSubdetectors,
  File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/common.py", line 233, in setupDetector
    domAcceptance[k] = getWavelengthAcceptance(rde.get(k,float('nan')), spe_compensation_factor.get(k,float('nan')), domEfficiencyCorrection)
  File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/common.py", line 98, in memof
    cache[key] = result = func(*args)
  File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/common.py", line 214, in getWavelengthAcceptance
    if not math.isfinite(spe_comp):
AttributeError: 'module' object has no attribute 'isfinite'
```

Migrated from https://code.icecube.wisc.edu/ticket/2393
```json
{
    "status": "closed", 
    "changetime": "2020-06-24T12:31:42", 
    "description": "clsim/traysegments/common.py refers to 'math.isinfinite' which is not present in python 2.7. (should be 'math.isinf')\n\n{{{\nNOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:496 in void I3Tray::Execute(unsigned int))\nTraceback (most recent call last):\n  File \"simprod-scripts/resources/scripts/clsim.py\", line 154, in <module>\n    main()\n  File \"simprod-scripts/resources/scripts/clsim.py\", line 150, in main\n    usegslrng=params['usegslrng'])\n  File \"/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/simprod/util/simprodtray.py\", line 143, in RunI3Tray\n    configure_tray(tray, params, stats, logger)\n  File \"simprod-scripts/resources/scripts/clsim.py\", line 111, in configure_tray\n    HoleIceParameterization=params['holeiceparametrization'])\n  File \"/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/I3Tray.py\", line 224, in AddSegment\n    return _segment(self, _name, **kwargs)\n  File \"/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/I3CLSimMakeHits.py\", line 34, in I3CLSimMakeHits\n    return I3CLSimMakePhotons(tray, name, **kwargs)\n  File \"/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/I3CLSimMakePhotons.py\", line 278, in I3CLSimMakePhotons\n    IgnoreSubdetectors=IgnoreSubdetectors,\n  File \"/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/common.py\", line 233, in setupDetector\n    domAcceptance[k] = getWavelengthAcceptance(rde.get(k,float('nan')), spe_compensation_factor.get(k,float('nan')), domEfficiencyCorrection)\n  File \"/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/common.py\", line 98, in memof\n    cache[key] = result = func(*args)\n  File \"/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/common.py\", line 214, in getWavelengthAcceptance\n    if not math.isfinite(spe_comp):\nAttributeError: 'module' object has no attribute 'isfinite'\n}}}", 
    "reporter": "juancarlos", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1593001902142004", 
    "component": "combo simulation", 
    "summary": "CLSsim in py2-v3.1.1: math.isfinite does not exist", 
    "priority": "blocker", 
    "keywords": "clsim", 
    "time": "2019-12-19T17:06:21", 
    "milestone": "Autumnal Equinox 2020", 
    "owner": "jvansanten", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20191219T17:13:11: juancarlos changed summary from "CLSsim in py2-v3.1.1: math.isnfinite does not exist" to "CLSsim in py2-v3.1.1: math.isfinite does not exist"

**Comment by icecube-trac** [comment]
Trac update at 20191219T17:15:15: 
* olivas changed component from "analysis" to "simulation"
* olivas changed milestone from "" to "Winter Solstice 2019"
* olivas changed description from:

> clsim/traysegments/common.py refers to 'math.isinfinite' which is not present in python 2.7. (should be 'math.isinf')
> 
> NOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:496 in void I3Tray::Execute(unsigned int))
> Traceback (most recent call last):
>   File "simprod-scripts/resources/scripts/clsim.py", line 154, in <module>
>     main()
>   File "simprod-scripts/resources/scripts/clsim.py", line 150, in main
>     usegslrng=params['usegslrng'])
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/simprod/util/simprodtray.py", line 143, in RunI3Tray
>     configure_tray(tray, params, stats, logger)
>   File "simprod-scripts/resources/scripts/clsim.py", line 111, in configure_tray
>     HoleIceParameterization=params['holeiceparametrization'])
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/I3Tray.py", line 224, in AddSegment
>     return _segment(self, _name, **kwargs)
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/I3CLSimMakeHits.py", line 34, in I3CLSimMakeHits
>     return I3CLSimMakePhotons(tray, name, **kwargs)
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/I3CLSimMakePhotons.py", line 278, in I3CLSimMakePhotons
>     IgnoreSubdetectors=IgnoreSubdetectors,
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/common.py", line 233, in setupDetector
>     domAcceptance[k] = getWavelengthAcceptance(rde.get(k,float('nan')), spe_compensation_factor.get(k,float('nan')), domEfficiencyCorrection)
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/common.py", line 98, in memof
>     cache[key] = result = func(*args)
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/common.py", line 214, in getWavelengthAcceptance
>     if not math.isfinite(spe_comp):
> AttributeError: 'module' object has no attribute 'isfinite'

to:

> clsim/traysegments/common.py refers to 'math.isinfinite' which is not present in python 2.7. (should be 'math.isinf')
> 
> {{{
> NOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:496 in void I3Tray::Execute(unsigned int))
> Traceback (most recent call last):
>   File "simprod-scripts/resources/scripts/clsim.py", line 154, in <module>
>     main()
>   File "simprod-scripts/resources/scripts/clsim.py", line 150, in main
>     usegslrng=params['usegslrng'])
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/simprod/util/simprodtray.py", line 143, in RunI3Tray
>     configure_tray(tray, params, stats, logger)
>   File "simprod-scripts/resources/scripts/clsim.py", line 111, in configure_tray
>     HoleIceParameterization=params['holeiceparametrization'])
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/I3Tray.py", line 224, in AddSegment
>     return _segment(self, _name, **kwargs)
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/I3CLSimMakeHits.py", line 34, in I3CLSimMakeHits
>     return I3CLSimMakePhotons(tray, name, **kwargs)
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/I3CLSimMakePhotons.py", line 278, in I3CLSimMakePhotons
>     IgnoreSubdetectors=IgnoreSubdetectors,
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/common.py", line 233, in setupDetector
>     domAcceptance[k] = getWavelengthAcceptance(rde.get(k,float('nan')), spe_compensation_factor.get(k,float('nan')), domEfficiencyCorrection)
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/common.py", line 98, in memof
>     cache[key] = result = func(*args)
>   File "/home/juancarlos/work/icecube/icetray/combo/trunk/py2-v3.1.1/lib/icecube/clsim/traysegments/common.py", line 214, in getWavelengthAcceptance
>     if not math.isfinite(spe_comp):
> AttributeError: 'module' object has no attribute 'isfinite'
> }}}


* olivas commented:

> Thought I fixed this last night.

**Comment by icecube-trac** [comment]
Trac update at 20191219T17:20:34: 
* juancarlos changed resolution from "" to "fixed"
* juancarlos changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20191220T18:43:06: 
* olivas changed milestone from "Winter Solstice 2019" to "Vernal Equinox 2020"
* olivas commented:

> Milestone Winter Solstice 2019 deleted

**Comment by icecube-trac** [comment]
Trac update at 20200624T12:31:42: 
* olivas commented:

> Milestone Vernal Equinox 2020 deleted


* olivas changed milestone from "Vernal Equinox 2020" to "Autumnal Equinox 2020"
