### ISSUE TITLE
[PROPOSAL] fatal in decay (Trac #2397)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2389]
I found this fatal error running PROPOSAL via the script [https://code.icecube.wisc.edu/projects/icecube/browser/IceCube/meta-projects/combo/trunk/simprod-scripts/resources/scripts/clsim.py]:

```text
FATAL (PROPOSAL): Kaellen function is negative. Cannot caluclate momentum (Decay
Channel.cxx:88 in static double PROPOSAL::DecayChannel::Momentum(double, double,
 double))
ERROR (I3Module): propagator_propagator: Exception thrown (I3Module.cxx:123 in v
oid I3Module::Do(void (I3Module::*)()))
Traceback (most recent call last):
  File "/data/user/grenzi/combo-py3/src/simprod-scripts/resources/scripts/clsim.
py", line 188, in <module>
    main()
  File "/data/user/grenzi/combo-py3/src/simprod-scripts/resources/scripts/clsim.
py", line 184, in main
    usegslrng=params['usegslrng'])
  File "/data/user/grenzi/combo-py3/build/lib/icecube/simprod/util/simprodtray.py", line 150, in RunI3Tray
    _execute(tray, executionmaxcount)
  File "/data/user/grenzi/combo-py3/build/lib/icecube/simprod/util/simprodtray.py", line 53, in _execute
    tray.Execute()
  File "/data/user/grenzi/combo-py3/build/lib/I3Tray.py", line 256, in Execute
    super(I3Tray, self).Execute()
RuntimeError: Kaellen function is negative. Cannot caluclate momentum (in static double PROPOSAL::DecayChannel::Momentum(double, double, double))
```

The error seems to come from here at line 88 [https://code.icecube.wisc.edu/projects/icecube/browser/IceCube/meta-projects/combo/trunk/PROPOSAL/private/PROPOSAL/decay/DecayChannel.cxx]

```text
79      double DecayChannel::Momentum(double m1, double m2, double m3)
80	{
81	    double kaellen = (m1 - m2 - m3) * (m1 + m2 + m3) * (m1 - m2 + m3) * (m1 + m2 - m3);
82	
83	    if (kaellen > 0.0)
84	    {
85	        return std::sqrt(kaellen) / (2.0 * m1);
86	    } else
87	    {
88	        log_fatal("Kaellen function is negative. Cannot caluclate momentum");
89	        return 0.0;
90	    }
91	}
```

This error prevents the propagation process for all of the following frames. I think the right thing would be just skipping the single wrong one.

Migrated from https://code.icecube.wisc.edu/ticket/2397
```json
{
    "status": "closed", 
    "changetime": "2020-06-24T12:31:42", 
    "description": "I found this fatal error running PROPOSAL via the script [https://code.icecube.wisc.edu/projects/icecube/browser/IceCube/meta-projects/combo/trunk/simprod-scripts/resources/scripts/clsim.py]:\n\n\n{{{\nFATAL (PROPOSAL): Kaellen function is negative. Cannot caluclate momentum (Decay\nChannel.cxx:88 in static double PROPOSAL::DecayChannel::Momentum(double, double,\n double))\nERROR (I3Module): propagator_propagator: Exception thrown (I3Module.cxx:123 in v\noid I3Module::Do(void (I3Module::*)()))\nTraceback (most recent call last):\n  File \"/data/user/grenzi/combo-py3/src/simprod-scripts/resources/scripts/clsim.\npy\", line 188, in <module>\n    main()\n  File \"/data/user/grenzi/combo-py3/src/simprod-scripts/resources/scripts/clsim.\npy\", line 184, in main\n    usegslrng=params['usegslrng'])\n  File \"/data/user/grenzi/combo-py3/build/lib/icecube/simprod/util/simprodtray.py\", line 150, in RunI3Tray\n    _execute(tray, executionmaxcount)\n  File \"/data/user/grenzi/combo-py3/build/lib/icecube/simprod/util/simprodtray.py\", line 53, in _execute\n    tray.Execute()\n  File \"/data/user/grenzi/combo-py3/build/lib/I3Tray.py\", line 256, in Execute\n    super(I3Tray, self).Execute()\nRuntimeError: Kaellen function is negative. Cannot caluclate momentum (in static double PROPOSAL::DecayChannel::Momentum(double, double, double))\n}}}\n\nThe error seems to come from here at line 88 [https://code.icecube.wisc.edu/projects/icecube/browser/IceCube/meta-projects/combo/trunk/PROPOSAL/private/PROPOSAL/decay/DecayChannel.cxx]\n\n\n{{{\n79      double DecayChannel::Momentum(double m1, double m2, double m3)\n80\t{\n81\t    double kaellen = (m1 - m2 - m3) * (m1 + m2 + m3) * (m1 - m2 + m3) * (m1 + m2 - m3);\n82\t\n83\t    if (kaellen > 0.0)\n84\t    {\n85\t        return std::sqrt(kaellen) / (2.0 * m1);\n86\t    } else\n87\t    {\n88\t        log_fatal(\"Kaellen function is negative. Cannot caluclate momentum\");\n89\t        return 0.0;\n90\t    }\n91\t}\n}}}\n\n\nThis error prevents the propagation process for all of the following frames. I think the right thing would be just skipping the single wrong one.\n", 
    "reporter": "grenzi", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1593001902142004", 
    "component": "combo simulation", 
    "summary": "[PROPOSAL] fatal in decay", 
    "priority": "major", 
    "keywords": "", 
    "time": "2020-01-08T09:47:52", 
    "milestone": "Autumnal Equinox 2020", 
    "owner": "jsoedingrekso", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20200204T23:16:39: 
* olivas changed status from "new" to "assigned"
* olivas changed priority from "normal" to "major"
* olivas changed owner from "" to "jsoedingrekso"
* olivas changed milestone from "" to "Vernal Equinox 2020"

**Comment by icecube-trac** [comment]
Trac update at 20200217T19:53:56: olivas changed summary from "PROPOSAL - fatal in decay" to "[PROPOSAL] fatal in decay"

**Comment by icecube-trac** [comment]
Trac update at 20200220T08:47:35: 
* jsoedingrekso changed resolution from "" to "fixed"
* jsoedingrekso commented:

> In changeset 179002:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="179002"
> fix #2389 to handle numerically unstable kaellen function calculation
> ```


* jsoedingrekso changed status from "assigned" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20200220T08:54:09: jsoedingrekso commented:

> The real problem behind this is the random number generator (I guess).
> This just occurs, when two of the three random numbers sampled in PROPOSAL::ManyBodyPhaseSpace::CalculateKinematics are exactly the same, which is quite unlikely. This is more likely a hint for a wrong behaviour in the random number generator, than a PROPOSAL problem.

**Comment by icecube-trac** [comment]
Trac update at 20200624T12:31:42: 
* olivas changed milestone from "Vernal Equinox 2020" to "Autumnal Equinox 2020"
* olivas commented:

> Milestone Vernal Equinox 2020 deleted
