### ISSUE TITLE
dataio-shovel segfaults upon entering interactive mode (Trac #2405)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2397]
dataio-shovel segfaults upon entering interactive mode when using py3-v4.1.0.

Steps to reproduce:

```text
eval $(/cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/setup.sh)
/cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/metaprojects/combo/stable/env-shell.sh bash
dataio-shovel /cvmfs/icecube.opensciencegrid.org/data/i3-test-data/nugen_numu_ic80_dc6.002488.000000.processed.i3.gz
hit i
```

Stacktrace:

```text
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff4cc0cf0 in wcslen () from /usr/lib64/libc.so.6
(gdb) bt
https://code.icecube.wisc.edu/ticket/0  0x00007ffff4cc0cf0 in wcslen () from /usr/lib64/libc.so.6
#1  0x00007ffff530d7fa in PyUnicode_FromWideChar ()
    at /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/var/spack/stage/python-3.7.5-gkstg44cg4rxuyl2rpzhtdcfbteqsf5r/Python-3.7.5/Objects/unicodeobject.c:2057
#2  0x00007ffff529ffb9 in makeargvobject (argv=0x7fffffffc680, argc=1)
    at /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/var/spack/stage/python-3.7.5-gkstg44cg4rxuyl2rpzhtdcfbteqsf5r/Python-3.7.5/Python/sysmodule.c:2602
#3  PySys_SetArgvEx (argc=1, argv=0x7fffffffc680, updatepath=0)
    at /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/var/spack/stage/python-3.7.5-gkstg44cg4rxuyl2rpzhtdcfbteqsf5r/Python-3.7.5/Python/sysmodule.c:2617
#4  0x000000000042d06f in do_pyshell(char**, Model&, View&) ()
#5  0x000000000042ac35 in main ()
```

Migrated from https://code.icecube.wisc.edu/ticket/2405
```json
{
    "status": "closed", 
    "changetime": "2020-01-28T21:01:33", 
    "description": "dataio-shovel segfaults upon entering interactive mode when using py3-v4.1.0.\n\nSteps to reproduce:\n\n{{{\neval $(/cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/setup.sh)\n/cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/metaprojects/combo/stable/env-shell.sh bash\ndataio-shovel /cvmfs/icecube.opensciencegrid.org/data/i3-test-data/nugen_numu_ic80_dc6.002488.000000.processed.i3.gz\nhit i\n}}}\n\nStacktrace:\n{{{\nProgram received signal SIGSEGV, Segmentation fault.\n0x00007ffff4cc0cf0 in wcslen () from /usr/lib64/libc.so.6\n(gdb) bt\n#0  0x00007ffff4cc0cf0 in wcslen () from /usr/lib64/libc.so.6\n#1  0x00007ffff530d7fa in PyUnicode_FromWideChar ()\n    at /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/var/spack/stage/python-3.7.5-gkstg44cg4rxuyl2rpzhtdcfbteqsf5r/Python-3.7.5/Objects/unicodeobject.c:2057\n#2  0x00007ffff529ffb9 in makeargvobject (argv=0x7fffffffc680, argc=1)\n    at /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/var/spack/stage/python-3.7.5-gkstg44cg4rxuyl2rpzhtdcfbteqsf5r/Python-3.7.5/Python/sysmodule.c:2602\n#3  PySys_SetArgvEx (argc=1, argv=0x7fffffffc680, updatepath=0)\n    at /cvmfs/icecube.opensciencegrid.org/py3-v4.1.0/RHEL_7_x86_64/spack/var/spack/stage/python-3.7.5-gkstg44cg4rxuyl2rpzhtdcfbteqsf5r/Python-3.7.5/Python/sysmodule.c:2617\n#4  0x000000000042d06f in do_pyshell(char**, Model&, View&) ()\n#5  0x000000000042ac35 in main ()\n}}}\n", 
    "reporter": "chaack", 
    "cc": "sdharani", 
    "resolution": "fixed", 
    "_ts": "1580245293629345", 
    "component": "combo core", 
    "summary": "dataio-shovel segfaults upon entering interactive mode", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2020-01-28T08:25:21", 
    "milestone": "", 
    "owner": "david.schultz", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20200128T21:01:33: 
* david.schultz commented:

> In changeset 178679:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="178679"
> fix #2397 by not setting sys.argv. this appears to work fine
> ```


* david.schultz changed resolution from "" to "fixed"
* david.schultz changed status from "new" to "closed"
* david.schultz changed owner from "" to "david.schultz"
