### ISSUE TITLE
[cmake] python symlink including in builds directory breaks virtual environments (Trac #2424)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#2416]
I have been using a virtual environment to provide:
python 3 (as /usr/bin/env python)
needed libraries.

(note:  virtualenv is made using cvmfs v3-v4.0.1  python toolset

I generate the vritualenv first, and from the virtual env, I run cmake to ensure I'm getting  python 3.

But after build, when I try to run, libraries added to my local virtualenv are not available.

'which python' shows ./build/bin/python, which is a symlink to the original python in cvmfs and not the virtualenv one as it should be.  

This breaks all scripts that need libs from the virtual env. 

A work around is to delete the ./build/bin/python

* Is this even needed any longer?
* If is it, can we make it respect the virtualenv python that was there at cmake time?

Migrated from https://code.icecube.wisc.edu/ticket/2424
```json
{
    "status": "closed", 
    "changetime": "2020-07-15T18:16:26", 
    "description": "I have been using a virtual environment to provide:\npython 3 (as /usr/bin/env python)\nneeded libraries.\n\n(note:  virtualenv is made using cvmfs v3-v4.0.1  python toolset\n\nI generate the vritualenv first, and from the virtual env, I run cmake to ensure I'm getting  python 3.\n\nBut after build, when I try to run, libraries added to my local virtualenv are not available.\n\n'which python' shows ./build/bin/python, which is a symlink to the original python in cvmfs and not the virtualenv one as it should be.  \n\nThis breaks all scripts that need libs from the virtual env. \n\nA work around is to delete the ./build/bin/python\n\n* Is this even needed any longer?\n* If is it, can we make it respect the virtualenv python that was there at cmake time?\n\n", 
    "reporter": "blaufuss", 
    "cc": "", 
    "resolution": "wontfix", 
    "_ts": "1594836986417881", 
    "component": "combo core", 
    "summary": "[cmake] python symlink including in builds directory breaks virtual environments", 
    "priority": "major", 
    "keywords": "python 3, virtualenv", 
    "time": "2020-04-22T19:21:39", 
    "milestone": "Autumnal Equinox 2020", 
    "owner": "olivas", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20200629T19:54:29: 
* olivas changed summary from "python symlink including in builds directory breaks virtual environments" to "[cmake] python symlink including in builds directory breaks virtual environments"
* olivas changed owner from "" to "olivas"
* olivas changed status from "new" to "accepted"
* olivas changed milestone from "" to "Autumnal Equinox 2020"
* olivas changed priority from "normal" to "major"

**Comment by icecube-trac** [comment]
Trac update at 20200702T14:12:48: olivas commented:

> I'm having trouble reproducing.
> 
> Locally cmake picks up the python inside the virtual env as expected:
> 
> 
> ```text
> $ grep PYTHON_EXECUTABLE CMakeCache.txt
> PYTHON_EXECUTABLE:STRING=/home/olivas/icecube/combo/trunk/venv_build/venv_build/bin/python3
> $ which python
> /home/olivas/icecube/combo/trunk/venv_build/venv_build/bin/python
> ```
> 
> 
> I tried to create a venv in Madison, but with both py3-v4.1.0 and py3-v4.0.1 I get the same error:
> 
> 
> ```text
> olivas@cobalt08 /scratch/olivas/icecube/combo/trunk/venv_build $ python3 -m venv virtual_env
> Traceback (most recent call last):
>   File "/cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/lib/python3.6/runpy.py", line 183, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/lib/python3.6/runpy.py", line 142, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "/cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/lib/python3.6/runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "/cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/lib/python3.6/venv/__init__.py", line 7, in <module>
>     import logging
>   File "/cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/lib/python3.6/logging/__init__.py", line 26, in <module>
>     import sys, os, time, io, traceback, warnings, weakref, collections
>   File "/cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/lib/python3.6/traceback.py", line 5, in <module>
>     import linecache
>   File "/cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/lib/python3.6/linecache.py", line 11, in <module>
>     import tokenize
>   File "/cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/lib/python3.6/tokenize.py", line 33, in <module>
>     import re
>   File "/cvmfs/icecube.opensciencegrid.org/py3-v4.0.1/RHEL_7_x86_64/lib/python3.6/re.py", line 142, in <module>
>     class RegexFlag(enum.IntFlag):
> AttributeError: module 'enum' has no attribute 'IntFlag'
> ```

**Comment by icecube-trac** [comment]
Trac update at 20200702T14:20:28: olivas commented:

> For completeness, I want to reiterate the reasons for keeping this link.
> (I know this was discussed in Slack already)
> 
> Ubuntu 20.04 doesn't provide python2, only python3, and doesn't symlink python to python3, so any scripts we have with '#!/usr/bin/env python' will break.
> 
> The second, and I think more important, is that cmake is symlinking the python that it detected at build time:
> 
> execute_process(COMMAND ln -sf ${PYTHON_EXECUTABLE} ${CMAKE_BINARY_DIR}/bin/python)
> 
> So this should be pretty robust and also allowed us to remove the brittle version matching code that protected people from mixing python at runtime with a different build time python.
>

**Comment by icecube-trac** [comment]
Trac update at 20200714T21:04:25: 
* blaufuss commented:

> the link is clearly being set properly and if required to shim /usr/bin/env python, then I think I just need to continue my work around (rm $I3_BUILD/bin/python) to allow my virtual-env python  (which is the same version + extras) to by used instead.
> 
> 


* blaufuss changed resolution from "" to "wontfix"
* blaufuss changed status from "accepted" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20200714T21:10:58: nwhitehorn commented:

> How many situations does this help vs. break? It's largely been a nuisance for me, as well.

**Comment by icecube-trac** [comment]
Trac update at 20200715T18:16:26: olivas commented:

> Replying to [comment:5 nwhitehorn]:
> > How many situations does this help vs. break? It's largely been a nuisance for me, as well.
> 
> Can I get more details about the issues this causes, beyond what's in Slack?
