### ISSUE TITLE
HDF5Booker fails on IC-59 Level3 files (Trac #251)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#251]
Using th trunk of the analysis meta-project, the booker fails on IC-59 muon-Level3 files.

Error message:

Traceback (most recent call last):
  File "/data/i3home/hwissing/SGE/ic59/book/book_triggers.py", line 109, in <module>
    tray.Execute()
  File "/opt/tmp/hwissing/i3/meta-projects/analysis/trunk/RELEASE/lib/I3Tray.py", line 118, in Execute
    args[0].the_tray.Execute()
  File "/opt/tmp/hwissing/i3/meta-projects/analysis/trunk/src/booking/loot/booking/modules/H5Booker.py", line 184, in Physics
    self.rmerge(None, self.Tables[key].row, rslts)
  File "/opt/tmp/hwissing/i3/meta-projects/analysis/trunk/src/booking/loot/booking/modules/H5Booker.py", line 162, in rmerge
    dest[name] = vvalue
  File "tableExtension.pyx", line 1287, in tableExtension.Row.__setitem__
  File "/usr/lib/python2.5/site-packages/tables/misc/enum.py", line 320, in __call__
    "no enumerated value with that concrete value: %r" % (value,))
ValueError: no enumerated value with that concrete value: -858592688
Closing remaining open files: /opt/tmp/hwissing/TESTbook.h5... done

Booker works fine on Level2 files.

Migrated from https://code.icecube.wisc.edu/ticket/251
```json
{
    "status": "closed", 
    "changetime": "2012-05-30T14:20:29", 
    "description": "Using th trunk of the analysis meta-project, the booker fails on IC-59 muon-Level3 files.\n\nError message:\n\nTraceback (most recent call last):\n  File \"/data/i3home/hwissing/SGE/ic59/book/book_triggers.py\", line 109, in <module>\n    tray.Execute()\n  File \"/opt/tmp/hwissing/i3/meta-projects/analysis/trunk/RELEASE/lib/I3Tray.py\", line 118, in Execute\n    args[0].the_tray.Execute()\n  File \"/opt/tmp/hwissing/i3/meta-projects/analysis/trunk/src/booking/loot/booking/modules/H5Booker.py\", line 184, in Physics\n    self.rmerge(None, self.Tables[key].row, rslts)\n  File \"/opt/tmp/hwissing/i3/meta-projects/analysis/trunk/src/booking/loot/booking/modules/H5Booker.py\", line 162, in rmerge\n    dest[name] = vvalue\n  File \"tableExtension.pyx\", line 1287, in tableExtension.Row.__setitem__\n  File \"/usr/lib/python2.5/site-packages/tables/misc/enum.py\", line 320, in __call__\n    \"no enumerated value with that concrete value: %r\" % (value,))\nValueError: no enumerated value with that concrete value: -858592688\nClosing remaining open files: /opt/tmp/hwissing/TESTbook.h5... done\n\n\n\nBooker works fine on Level2 files.", 
    "reporter": "icecube", 
    "cc": "", 
    "resolution": "wontfix", 
    "_ts": "1338387629000000", 
    "component": "booking", 
    "summary": "HDF5Booker fails on IC-59 Level3 files", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2011-04-18T21:01:35", 
    "milestone": "", 
    "owner": "troy", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20120530T14:20:29: 
* kjmeagher changed status from "new" to "closed"
* kjmeagher changed resolution from "" to "wontfix"
* kjmeagher commented:

> HDF5Booker is depreciated
