### ISSUE TITLE
make tarball broken in V04-00-00 (Trac #302)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#301]
I run the following script 

--------------------------
#!/usr/bin/env python
from  I3Tray import *
--------------------------

at UMD on curry02.

output:
http://codepad.org/Xv5VfOK4
 
Modifying the generated env-shell.sh (L73) to include I3_PORTS in the LD_LIBRARY_PATH as

-------------------------------------
I3_PORTS=/data/sge_build/i3tools-v3

_LD_LIBRARY_PATH=$BASEDIR/lib:$I3_PORTS/lib:$_ROOTSYS/lib:$BASEDIR/lib/tools:$LD_LIBRARY_PATH
--------------------------------------

makes it work on curry02. 

On a UMD cluster node however the same script and environment produce:
http://codepad.org/tegpubDQ

Migrated from https://code.icecube.wisc.edu/ticket/302
```json
{
    "status": "closed", 
    "changetime": "2015-07-07T22:32:33", 
    "description": "I run the following script \n\n--------------------------\n#!/usr/bin/env python\nfrom  I3Tray import *\n--------------------------\n\nat UMD on curry02.\n\noutput:\nhttp://codepad.org/Xv5VfOK4\n \nModifying the generated env-shell.sh (L73) to include I3_PORTS in the LD_LIBRARY_PATH as\n\n-------------------------------------\nI3_PORTS=/data/sge_build/i3tools-v3\n\n_LD_LIBRARY_PATH=$BASEDIR/lib:$I3_PORTS/lib:$_ROOTSYS/lib:$BASEDIR/lib/tools:$LD_LIBRARY_PATH\n--------------------------------------\n\n\nmakes it work on curry02. \n\nOn a UMD cluster node however the same script and environment produce:\nhttp://codepad.org/tegpubDQ\n\n\n\n\n", 
    "reporter": "hwissing", 
    "cc": "", 
    "resolution": "worksforme", 
    "_ts": "1436308353324715", 
    "component": "combo reconstruction", 
    "summary": "make tarball broken in V04-00-00", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2011-08-26T18:58:22", 
    "milestone": "", 
    "owner": "dladieu", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20110826T20:17:43: blaufuss commented:

> sucking content from codepad:
> 
> http://codepad.org/Xv5VfOK4:
> 
> Traceback (most recent call last):
>   File "/data/i3home/hwissing/SGE/ic59/filter/l4/test.py", line 3, in <module>
>     from  I3Tray import *
>   File "/data/sge_build/tmp/hwissing/i3/icerec.releases.V04-00-00.r79219.Linux-x86_64.gcc-4.2.4/lib/I3Tray.py", line 5, in <module>
>     import icecube.icetray as icetray
>   File "/data/sge_build/tmp/hwissing/i3/icerec.releases.V04-00-00.r79219.Linux-x86_64.gcc-4.2.4/lib/icecube/icetray/__init__.py", line 2, in <module>
>     load_pybindings(__name__, __path__)
>   File "/data/sge_build/tmp/hwissing/i3/icerec.releases.V04-00-00.r79219.Linux-x86_64.gcc-4.2.4/lib/icecube/load_pybindings.py", line 53, in load_pybindings
>     m = imp.load_dynamic(name, path[0] + ".so")
> 
> 
> http://codepad.org/tegpubDQ:
> 
> 
> hwissing@cobol66:~$ ~/SGE/ic59/filter/l4/test.py
> Traceback (most recent call last):
>   File "/data/i3home/hwissing/SGE/ic59/filter/l4/test.py", line 3, in <module>
>     from  I3Tray import *
>   File "/data/sge_build/tmp/hwissing/i3/icerec.releases.V04-00-00.r79219.Linux-x86_64.gcc-4.2.4/lib/I3Tray.py", line 5, in <module>
>     import icecube.icetray as icetray
>   File "/data/sge_build/tmp/hwissing/i3/icerec.releases.V04-00-00.r79219.Linux-x86_64.gcc-4.2.4/lib/icecube/icetray/__init__.py", line 2, in <module>
>     load_pybindings(__name__, __path__)
>   File "/data/sge_build/tmp/hwissing/i3/icerec.releases.V04-00-00.r79219.Linux-x86_64.gcc-4.2.4/lib/icecube/load_pybindings.py", line 53, in load_pybindings
>     m = imp.load_dynamic(name, path[0] + ".so")
> ImportError: libpython2.5.so.1.0: cannot open shared object file: No such file or directory
>

**Comment by icecube-trac** [comment]
Trac update at 20110826T20:43:48: kislat changed milestone from "" to "IceRec V4"

**Comment by icecube-trac** [comment]
Trac update at 20110908T17:07:52: 
* blaufuss changed resolution from "" to "worksforme"
* blaufuss commented:

> Seems to work just fine in V04-00-01, which contains same cmake release. 
> 
> Perhaps a local issue due to in-progress upgrades at UMD?   Bad build?  Solar storm?
> 
> Not clear.  If resurfaces, please reopen ticket.


* blaufuss changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20150707T22:32:33: 
* olivas commented:

> Milestone IceRec V4 deleted


* olivas changed milestone from "IceRec V4" to ""
