### ISSUE TITLE
from icecube import superdst is broken (Trac #306)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#305]
In icerec V04-00-01:

trying to use the line:

from icecube import superdst
yield:

Traceback (most recent call last):
  File "./dst_test.py", line 13, in <module>
    from icecube import icetray, dataclasses, dataio, superdst
  File "/data/i3home/blaufuss/icework/icerec/V04-00-01/build_d/lib/icecube/superdst/__init__.py", line 4, in <module>
    load_pybindings(__name__,__path__)
  File "/data/i3home/blaufuss/icework/icerec/V04-00-01/build_d/lib/icecube/load_pybindings.py", line 53, in load_pybindings
    m = imp.load_dynamic(name, path[0] + ".so")
ImportError: /data/i3home/blaufuss/icework/icerec/V04-00-01/build_d/lib/icecube/superdst.so: cannot open shared object file: No such file or directory

A work around of changing to 

load("superdst")

exists

Migrated from https://code.icecube.wisc.edu/ticket/306
```json
{
    "status": "closed", 
    "changetime": "2011-09-09T14:52:28", 
    "description": "In icerec V04-00-01:\n\ntrying to use the line:\n\nfrom icecube import superdst\nyield:\n\n\nTraceback (most recent call last):\n  File \"./dst_test.py\", line 13, in <module>\n    from icecube import icetray, dataclasses, dataio, superdst\n  File \"/data/i3home/blaufuss/icework/icerec/V04-00-01/build_d/lib/icecube/superdst/__init__.py\", line 4, in <module>\n    load_pybindings(__name__,__path__)\n  File \"/data/i3home/blaufuss/icework/icerec/V04-00-01/build_d/lib/icecube/load_pybindings.py\", line 53, in load_pybindings\n    m = imp.load_dynamic(name, path[0] + \".so\")\nImportError: /data/i3home/blaufuss/icework/icerec/V04-00-01/build_d/lib/icecube/superdst.so: cannot open shared object file: No such file or directory\n\n\nA work around of changing to \n\nload(\"superdst\")\n\nexists", 
    "reporter": "blaufuss", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1315579948000000", 
    "component": "combo reconstruction", 
    "summary": "from icecube import superdst is broken", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2011-09-09T14:09:13", 
    "milestone": "", 
    "owner": "jacobi", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20110909T14:52:28: 
* jvansanten changed status from "new" to "closed"
* jvansanten commented:

> Fixed in r79784. The superdst pybindings were removed when I3SuperDST moved to dataclasses. 


* jvansanten changed resolution from "" to "fixed"
