### ISSUE TITLE
icetray release V11-12-00 (used in icerec trunk) does not compile module.cxx (Trac #337)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#336]
icerec trunk currently (svn revision 83556) uses icetray release V11-12-00.

On a relatively new linux distrubution (linux mint 12, based on ubuntu 11.11) with python 2.7.2+ and gcc 4.6.1-9ubuntu3, the code builds but will not run under python.

python -c "from icecube import icetray" results in this error:

 Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/boersma/Work/icetray/icerec/trunk/build-Release/lib/icecube/icetray/__init__.py", line 2, in <module>
load_pybindings(__name__, __path__)
File "/home/boersma/Work/icetray/icerec/trunk/build-Release/lib/icecube/load_pybindings.py", line 53, in load_pybindings
m = imp.load_dynamic(name, path[0] + ".so")
ImportError: dynamic module does not define init function (initicetray)

However, the trunk of offline-software works just fine. Inspection of the differences between icetray release and its current trunk reveals that there is a difference in the icetray/privatey/pybindings/CMakeLists.txt file: in the release, module.cxx (which contains the BOOST_PYTHON_MODULE snippet that defines the desired init function) is not mentioned and apparently does not get compiled. When I add module.cxx to that CMakeLists.txt file, then the error quoted above does not occur anymore.

The intriguing thing is that in prior releases module.cxx was also omitted, and also that the omission does not result in any error on other platforms, such as SL5 (standard install on RWTH Aachen 64bit desktops and grid nodes). Maybe it's something related to newer python versions.

In the other icerec projects it seems that always either module.cxx is mentioned in the private/pybindings/CMakeLists.txt file or the BOOST_PYTHON_MODULE snippet is included in some other cxx file.

Migrated from https://code.icecube.wisc.edu/ticket/337
```json
{
    "status": "closed", 
    "changetime": "2012-01-09T16:15:15", 
    "description": "icerec trunk currently (svn revision 83556) uses icetray release V11-12-00.\n\nOn a relatively new linux distrubution (linux mint 12, based on ubuntu 11.11) with python 2.7.2+ and gcc 4.6.1-9ubuntu3, the code builds but will not run under python.\n\npython -c \"from icecube import icetray\" results in this error:\n\n Traceback (most recent call last):\nFile \"<string>\", line 1, in <module>\nFile \"/home/boersma/Work/icetray/icerec/trunk/build-Release/lib/icecube/icetray/__init__.py\", line 2, in <module>\nload_pybindings(__name__, __path__)\nFile \"/home/boersma/Work/icetray/icerec/trunk/build-Release/lib/icecube/load_pybindings.py\", line 53, in load_pybindings\nm = imp.load_dynamic(name, path[0] + \".so\")\nImportError: dynamic module does not define init function (initicetray)\n\nHowever, the trunk of offline-software works just fine. Inspection of the differences between icetray release and its current trunk reveals that there is a difference in the icetray/privatey/pybindings/CMakeLists.txt file: in the release, module.cxx (which contains the BOOST_PYTHON_MODULE snippet that defines the desired init function) is not mentioned and apparently does not get compiled. When I add module.cxx to that CMakeLists.txt file, then the error quoted above does not occur anymore.\n\nThe intriguing thing is that in prior releases module.cxx was also omitted, and also that the omission does not result in any error on other platforms, such as SL5 (standard install on RWTH Aachen 64bit desktops and grid nodes). Maybe it's something related to newer python versions.\n\nIn the other icerec projects it seems that always either module.cxx is mentioned in the private/pybindings/CMakeLists.txt file or the BOOST_PYTHON_MODULE snippet is included in some other cxx file.", 
    "reporter": "boersma", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1326125715000000", 
    "component": "combo reconstruction", 
    "summary": "icetray release V11-12-00 (used in icerec trunk) does not compile module.cxx", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2012-01-04T15:17:44", 
    "milestone": "", 
    "owner": "blaufuss", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20120109T16:15:15: 
* blaufuss changed status from "new" to "closed"
* blaufuss changed resolution from "" to "fixed"
* blaufuss commented:

> new release going into the hopper
