### ISSUE TITLE
TypeError: expecting datetime, int, long, float, or None; got <class 'genshi.template.eval.Undefined'> (Trac #348)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#347]
I can't see the revision log for romeo trunk

==== How to Reproduce ====

While doing a GET operation on `/log/projects/romeo/trunk`, Trac issued an internal error.

''(please provide additional details here)''

Request parameters:

```text
{'path': u'/projects/romeo/trunk'}
```

User Agent was: `Mozilla/5.0 (X11; U; Linux i686; ja; rv:1.9.2.24) Gecko/20111107 Ubuntu/10.10 (maverick) Firefox/3.6.24`

==== System Information ====

|| '''Trac''' || `0.11.1` ||
|| '''Python''' || `2.5.5 (r255:77872, Nov 28 2010, 19:14:39) ` [[br]] `[GCC 4.4.5]` ||
|| '''setuptools''' || `0.6` ||
|| '''psycopg2''' || `2.2.1` ||
|| '''Genshi''' || `0.6` ||
|| '''mod_python''' || `3.3.1` ||
|| '''Pygments''' || `0.10` ||
|| '''Subversion''' || `1.5.1 (r32289)` ||
|| '''jQuery:''' || `1.2.6` ||

==== Python Traceback ====

```text
Traceback (most recent call last):
  File "/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/web/main.py", line 423, in _dispatch_request
    dispatcher.dispatch(req)
  File "/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/web/main.py", line 219, in dispatch
    data, content_type)
  File "/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/web/chrome.py", line 715, in render_template
    return stream.render(method, doctype=doctype)
  File "/usr/lib/pymodules/python2.5/genshi/core.py", line 183, in render
    return encode(generator, method=method, encoding=encoding, out=out)
  File "/usr/lib/pymodules/python2.5/genshi/output.py", line 57, in encode
    return _encode(''.join(list(iterator)))
  File "/usr/lib/pymodules/python2.5/genshi/output.py", line 339, in __call__
    for kind, data, pos in stream:
  File "/usr/lib/pymodules/python2.5/genshi/output.py", line 826, in __call__
    for kind, data, pos in stream:
  File "/usr/lib/pymodules/python2.5/genshi/output.py", line 670, in __call__
    for kind, data, pos in stream:
  File "/usr/lib/pymodules/python2.5/genshi/output.py", line 771, in __call__
    for kind, data, pos in chain(stream, [(None, None, None)]):
  File "/usr/lib/pymodules/python2.5/genshi/output.py", line 586, in __call__
    for ev in stream:
  File "/usr/lib/pymodules/python2.5/genshi/core.py", line 288, in _ensure
    for event in stream:
  File "/usr/lib/pymodules/python2.5/genshi/core.py", line 288, in _ensure
    for event in stream:
  File "/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/web/chrome.py", line 767, in _strip_accesskeys
    for kind, data, pos in stream:
  File "/usr/lib/pymodules/python2.5/genshi/core.py", line 288, in _ensure
    for event in stream:
  File "/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/web/chrome.py", line 756, in _generate
    for kind, data, pos in stream:
  File "/usr/lib/pymodules/python2.5/genshi/template/base.py", line 605, in _include
    for event in stream:
  File "/usr/lib/pymodules/python2.5/genshi/template/markup.py", line 378, in _match
    ctxt, start=idx + 1, **vars):
  File "/usr/lib/pymodules/python2.5/genshi/template/markup.py", line 378, in _match
    ctxt, start=idx + 1, **vars):
  File "/usr/lib/pymodules/python2.5/genshi/template/markup.py", line 327, in _match
    for event in stream:
  File "/usr/lib/pymodules/python2.5/genshi/template/base.py", line 545, in _flatten
    for kind, data, pos in stream:
  File "/usr/lib/pymodules/python2.5/genshi/core.py", line 288, in _ensure
    for event in stream:
  File "/usr/lib/pymodules/python2.5/genshi/path.py", line 588, in _generate
    subevent = next()
  File "/usr/lib/pymodules/python2.5/genshi/template/base.py", line 605, in _include
    for event in stream:
  File "/usr/lib/pymodules/python2.5/genshi/template/markup.py", line 316, in _strip
    event = next()
  File "/usr/lib/pymodules/python2.5/genshi/template/base.py", line 545, in _flatten
    for kind, data, pos in stream:
  File "/usr/lib/pymodules/python2.5/genshi/core.py", line 288, in _ensure
    for event in stream:
  File "/usr/lib/pymodules/python2.5/genshi/path.py", line 588, in _generate
    subevent = next()
  File "/usr/lib/pymodules/python2.5/genshi/template/base.py", line 605, in _include
    for event in stream:
  File "/usr/lib/pymodules/python2.5/genshi/template/markup.py", line 316, in _strip
    event = next()
  File "/usr/lib/pymodules/python2.5/genshi/template/base.py", line 565, in _flatten
    result = _eval_expr(data, ctxt, vars)
  File "/usr/lib/pymodules/python2.5/genshi/template/base.py", line 277, in _eval_expr
    retval = expr.evaluate(ctxt)
  File "/usr/lib/pymodules/python2.5/genshi/template/eval.py", line 178, in evaluate
    return eval(self.code, _globals, {'__data__': data})
  File "/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/versioncontrol/templates/revisionlog.html", line 134, in <Expression u'dateinfo(change.date)'>
    <td class="date" py:content="dateinfo(change.date)" />
  File "/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/timeline/web_ui.py", line 230, in dateinfo
    pretty_timedelta(date),
  File "/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/util/datefmt.py", line 71, in pretty_timedelta
    time1 = to_datetime(time1)
  File "/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/util/datefmt.py", line 51, in to_datetime
    type(t))
TypeError: expecting datetime, int, long, float, or None; got <class 'genshi.template.eval.Undefined'>

```
    

Migrated from https://code.icecube.wisc.edu/ticket/348
```json
{
    "status": "closed", 
    "changetime": "2019-01-11T20:08:32", 
    "description": "I can't see the revision log for romeo trunk\n\n\n==== How to Reproduce ====\n\nWhile doing a GET operation on `/log/projects/romeo/trunk`, Trac issued an internal error.\n\n''(please provide additional details here)''\n\n\nRequest parameters:\n{{{\n{'path': u'/projects/romeo/trunk'}\n}}}\n\n\nUser Agent was: `Mozilla/5.0 (X11; U; Linux i686; ja; rv:1.9.2.24) Gecko/20111107 Ubuntu/10.10 (maverick) Firefox/3.6.24`\n\n==== System Information ====\n\n|| '''Trac''' || `0.11.1` ||\n|| '''Python''' || `2.5.5 (r255:77872, Nov 28 2010, 19:14:39) ` [[br]] `[GCC 4.4.5]` ||\n|| '''setuptools''' || `0.6` ||\n|| '''psycopg2''' || `2.2.1` ||\n|| '''Genshi''' || `0.6` ||\n|| '''mod_python''' || `3.3.1` ||\n|| '''Pygments''' || `0.10` ||\n|| '''Subversion''' || `1.5.1 (r32289)` ||\n|| '''jQuery:''' || `1.2.6` ||\n\n==== Python Traceback ====\n{{{\nTraceback (most recent call last):\n  File \"/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/web/main.py\", line 423, in _dispatch_request\n    dispatcher.dispatch(req)\n  File \"/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/web/main.py\", line 219, in dispatch\n    data, content_type)\n  File \"/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/web/chrome.py\", line 715, in render_template\n    return stream.render(method, doctype=doctype)\n  File \"/usr/lib/pymodules/python2.5/genshi/core.py\", line 183, in render\n    return encode(generator, method=method, encoding=encoding, out=out)\n  File \"/usr/lib/pymodules/python2.5/genshi/output.py\", line 57, in encode\n    return _encode(''.join(list(iterator)))\n  File \"/usr/lib/pymodules/python2.5/genshi/output.py\", line 339, in __call__\n    for kind, data, pos in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/output.py\", line 826, in __call__\n    for kind, data, pos in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/output.py\", line 670, in __call__\n    for kind, data, pos in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/output.py\", line 771, in __call__\n    for kind, data, pos in chain(stream, [(None, None, None)]):\n  File \"/usr/lib/pymodules/python2.5/genshi/output.py\", line 586, in __call__\n    for ev in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/core.py\", line 288, in _ensure\n    for event in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/core.py\", line 288, in _ensure\n    for event in stream:\n  File \"/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/web/chrome.py\", line 767, in _strip_accesskeys\n    for kind, data, pos in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/core.py\", line 288, in _ensure\n    for event in stream:\n  File \"/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/web/chrome.py\", line 756, in _generate\n    for kind, data, pos in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/template/base.py\", line 605, in _include\n    for event in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/template/markup.py\", line 378, in _match\n    ctxt, start=idx + 1, **vars):\n  File \"/usr/lib/pymodules/python2.5/genshi/template/markup.py\", line 378, in _match\n    ctxt, start=idx + 1, **vars):\n  File \"/usr/lib/pymodules/python2.5/genshi/template/markup.py\", line 327, in _match\n    for event in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/template/base.py\", line 545, in _flatten\n    for kind, data, pos in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/core.py\", line 288, in _ensure\n    for event in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/path.py\", line 588, in _generate\n    subevent = next()\n  File \"/usr/lib/pymodules/python2.5/genshi/template/base.py\", line 605, in _include\n    for event in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/template/markup.py\", line 316, in _strip\n    event = next()\n  File \"/usr/lib/pymodules/python2.5/genshi/template/base.py\", line 545, in _flatten\n    for kind, data, pos in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/core.py\", line 288, in _ensure\n    for event in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/path.py\", line 588, in _generate\n    subevent = next()\n  File \"/usr/lib/pymodules/python2.5/genshi/template/base.py\", line 605, in _include\n    for event in stream:\n  File \"/usr/lib/pymodules/python2.5/genshi/template/markup.py\", line 316, in _strip\n    event = next()\n  File \"/usr/lib/pymodules/python2.5/genshi/template/base.py\", line 565, in _flatten\n    result = _eval_expr(data, ctxt, vars)\n  File \"/usr/lib/pymodules/python2.5/genshi/template/base.py\", line 277, in _eval_expr\n    retval = expr.evaluate(ctxt)\n  File \"/usr/lib/pymodules/python2.5/genshi/template/eval.py\", line 178, in evaluate\n    return eval(self.code, _globals, {'__data__': data})\n  File \"/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/versioncontrol/templates/revisionlog.html\", line 134, in <Expression u'dateinfo(change.date)'>\n    <td class=\"date\" py:content=\"dateinfo(change.date)\" />\n  File \"/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/timeline/web_ui.py\", line 230, in dateinfo\n    pretty_timedelta(date),\n  File \"/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/util/datefmt.py\", line 71, in pretty_timedelta\n    time1 = to_datetime(time1)\n  File \"/opt/trac/local/lib/python2.5/site-packages/Trac-0.11.1-py2.5.egg/trac/util/datefmt.py\", line 51, in to_datetime\n    type(t))\nTypeError: expecting datetime, int, long, float, or None; got <class 'genshi.template.eval.Undefined'>\n\n}}}\n    ", 
    "reporter": "mase", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1547237312321270", 
    "component": "combo simulation", 
    "summary": "TypeError: expecting datetime, int, long, float, or None; got <class 'genshi.template.eval.Undefined'>", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2012-01-30T03:41:32", 
    "milestone": "", 
    "owner": "nega", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20120229T06:31:07: olivas commented:

> This is reproducible by going to http://code.icecube.wisc.edu/projects/icecube/browser/projects/romeo/trunk and viewing the "Revision Log"  This seems to only happen to this one project.  You can see the last change as well as the log when using the command line.

**Comment by icecube-trac** [comment]
Trac update at 20120229T06:33:12: olivas commented:

> Same problem with the 'stand_alone' and 'resources' directory of that project.

**Comment by icecube-trac** [comment]
Trac update at 20120326T16:55:06: olivas changed owner from "olivas" to "nega"

**Comment by icecube-trac** [comment]
Trac update at 20120530T16:50:17: 
* nega changed resolution from "" to "fixed"
* nega changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20190111T20:08:32: nwhitehorn commented:

> In changeset 168440:
> 
> ```text
> #!CommitTicketReference repository="IceCube" revision="168440"
> Change python interpreter initialization in icetray.
> 
> Do not initialize python as part of static library initialization.
> Freestanding C++ programs that link to libicetray need to call
> the new init_icetray_lib() function from main().  Addresses #347.
> ```
