### ISSUE TITLE
adding services with the same name gives uninformative message (Trac #542)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#541]
from I3Tray import *

tray=I3Tray()

load("libI3Db")

tray.AddService( "I3DbOMKey2MBIDFactory","OmKey2MbId")
tray.AddService( "I3DbGeometryServiceFactory","OmKey2MbId")

tray.AddModule("TrashCan","trash")

tray.Execute()
tray.Finish()

#######################
the output is:

/opt/kjmeagher/simulation/V02-03-01RC/src/icetray/public/icetray/I3Context.h:96: FATAL: context already contains object named __tray_info_service
Traceback (most recent call last):
  File "bug.py", line 12, in <module>
    tray.Execute()
  File "/opt/kjmeagher/simulation/V02-03-01RC/release/lib/I3Tray.py", line 62, in Execute
    args[0].the_tray.Execute()
RuntimeError: context already contains object named __tray_info_service

should be more like:
Log Fatal: there is already a service with name "OmKey2MbId"

Migrated from https://code.icecube.wisc.edu/ticket/542
```json
{
    "status": "closed", 
    "changetime": "2011-04-14T19:16:40", 
    "description": "from I3Tray import *\n\ntray=I3Tray()\n\nload(\"libI3Db\")\n\ntray.AddService( \"I3DbOMKey2MBIDFactory\",\"OmKey2MbId\")\ntray.AddService( \"I3DbGeometryServiceFactory\",\"OmKey2MbId\")\n\ntray.AddModule(\"TrashCan\",\"trash\")\n\ntray.Execute()\ntray.Finish()\n\n#######################\nthe output is:\n\n/opt/kjmeagher/simulation/V02-03-01RC/src/icetray/public/icetray/I3Context.h:96: FATAL: context already contains object named __tray_info_service\nTraceback (most recent call last):\n  File \"bug.py\", line 12, in <module>\n    tray.Execute()\n  File \"/opt/kjmeagher/simulation/V02-03-01RC/release/lib/I3Tray.py\", line 62, in Execute\n    args[0].the_tray.Execute()\nRuntimeError: context already contains object named __tray_info_service\n\nshould be more like:\nLog Fatal: there is already a service with name \"OmKey2MbId\"\n", 
    "reporter": "anonymous", 
    "cc": "", 
    "resolution": "wont or cant fix", 
    "_ts": "1302808600000000", 
    "component": "booking", 
    "summary": "adding services with the same name gives uninformative message", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2009-03-12T20:09:02", 
    "milestone": "", 
    "owner": "troy", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20110414T19:16:40: 
* nega changed resolution from "" to "wont_or_cant_fix"
* nega changed status from "new" to "closed"
* nega commented:

> tableio now the standard, if still a problem there, re-open
