### ISSUE TITLE
icetray parameter tests failing on python 2.3.4 (Trac #560)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#559]
This maybe intentional/unavoidable:

icetray/scripts/parameter_abuse.py
failing on el4 machines:

[slave@akuma build_debug]$ ./icetray/resources/scripts/parameter_abuse.py 
Logging configured from file ./log4cplus.conf
/build/slave_build/manual/offline-software/src/icetray/public/icetray/I3Module.h:330: ERROR: Error in AllParametersModule module 'apm2', getting parameter 'intvec_param'
OK, threw as expected
Traceback (most recent call last):
  File "./icetray/resources/scripts/parameter_abuse.py", line 34, in ?
    exit(0)
TypeError: 'str' object is not callable

Migrated from https://code.icecube.wisc.edu/ticket/560
```json
{
    "status": "closed", 
    "changetime": "2014-11-23T03:37:56", 
    "description": "This maybe intentional/unavoidable:\n\nicetray/scripts/parameter_abuse.py\nfailing on el4 machines:\n\n[slave@akuma build_debug]$ ./icetray/resources/scripts/parameter_abuse.py \nLogging configured from file ./log4cplus.conf\n/build/slave_build/manual/offline-software/src/icetray/public/icetray/I3Module.h:330: ERROR: Error in AllParametersModule module 'apm2', getting parameter 'intvec_param'\nOK, threw as expected\nTraceback (most recent call last):\n  File \"./icetray/resources/scripts/parameter_abuse.py\", line 34, in ?\n    exit(0)\nTypeError: 'str' object is not callable\n", 
    "reporter": "blaufuss", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1416713876862109", 
    "component": "IceTray", 
    "summary": "icetray parameter tests failing on python 2.3.4", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2009-06-12T20:37:59", 
    "milestone": "", 
    "owner": "troy", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20090612T20:53:29: blaufuss commented:

> also on morax (el5, python 2.4.3)
> 
> [slave@morax build_debug]$ ./icetray/resources/scripts/parameter_abuse.py 
> Logging configured from file ./log4cplus.conf
> /build/slave_build/manual/offline-software/src/icetray/public/icetray/I3Module.h:330: ERROR: Error in AllParametersModule module 'apm2', getting parameter 'intvec_param'
> OK, threw as expected
> Traceback (most recent call last):
>   File "./icetray/resources/scripts/parameter_abuse.py", line 34, in ?
>     exit(0)
> TypeError: 'str' object is not callable
>

**Comment by icecube-trac** [comment]
Trac update at 20090618T14:24:00: 
* blaufuss commented:

> sys.exit(0) is needed.


* blaufuss changed resolution from "" to "fixed"
* blaufuss changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20141123T03:37:56: 
* olivas commented:

> Milestone v3-bugsquash deleted


* olivas changed milestone from "v3-bugsquash" to ""
