### ISSUE TITLE
I3Tray finish gets called due to exceptions in constructors/Configure methods (Trac #615)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#614]
An exception in service or module constructors causes I3Finish to be called without there being a driving module yet, which seems to confuse I3Finish and makes it throw its own exception. The resulting second exception could be confusing to users..

Here is an example of how this looks like on the standard output:

lilliput/private/minimizer/I3GSLMultiMin.cxx:105: ERROR: The "vector_bfgs2" minimizer is not available in your version of GSL. Update to version 1.14 or newer.
/lilliput/private/minimizer/I3GSLMultiMin.cxx:189: FATAL: Unknown minimizer algorithm "vector_bfgs2"!
Traceback (most recent call last):
  File "./aartfit.py", line 553, in <module>
    tray.Execute()
  File "/Users/claudio/Documents/Uni/IceTray/test/build.searecsim.release/lib/I3Tray.py", line 118, in Execute
    args[0].the_tray.Execute()
RuntimeError: Unknown minimizer algorithm "vector_bfgs2"!
I3Tray finishing...
/icetray/private/icetray/I3Tray.cxx:457: FATAL: Attempt to call finish, but there is no driving module.  Did you forget to call Execute()?
terminate called after throwing an instance of 'std::runtime_error'
  what():  Attempt to call finish, but there is no driving module.  Did you forget to call Execute()?
Abort trap

Migrated from https://code.icecube.wisc.edu/ticket/615
```json
{
    "status": "closed", 
    "changetime": "2012-10-31T20:57:48", 
    "description": "An exception in service or module constructors causes I3Finish to be called without there being a driving module yet, which seems to confuse I3Finish and makes it throw its own exception. The resulting second exception could be confusing to users..\n\n\n\nHere is an example of how this looks like on the standard output:\n\nlilliput/private/minimizer/I3GSLMultiMin.cxx:105: ERROR: The \"vector_bfgs2\" minimizer is not available in your version of GSL. Update to version 1.14 or newer.\n/lilliput/private/minimizer/I3GSLMultiMin.cxx:189: FATAL: Unknown minimizer algorithm \"vector_bfgs2\"!\nTraceback (most recent call last):\n  File \"./aartfit.py\", line 553, in <module>\n    tray.Execute()\n  File \"/Users/claudio/Documents/Uni/IceTray/test/build.searecsim.release/lib/I3Tray.py\", line 118, in Execute\n    args[0].the_tray.Execute()\nRuntimeError: Unknown minimizer algorithm \"vector_bfgs2\"!\nI3Tray finishing...\n/icetray/private/icetray/I3Tray.cxx:457: FATAL: Attempt to call finish, but there is no driving module.  Did you forget to call Execute()?\nterminate called after throwing an instance of 'std::runtime_error'\n  what():  Attempt to call finish, but there is no driving module.  Did you forget to call Execute()?\nAbort trap\n", 
    "reporter": "icecube", 
    "cc": "claudio.kopper@physik.uni-erlangen.de", 
    "resolution": "fixed", 
    "_ts": "1351717068000000", 
    "component": "IceTray", 
    "summary": "I3Tray finish gets called due to exceptions in constructors/Configure methods", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2010-07-30T10:11:17", 
    "milestone": "", 
    "owner": "troy", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20121031T20:57:48: 
* blaufuss changed status from "new" to "closed"
* blaufuss changed resolution from "" to "fixed"
* blaufuss commented:

> Fixed with new I3Tray and other hacks (r497)
> 
>
