### ISSUE TITLE
bad error when execute after config problem (Trac #616)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#615]
real error is caught and displayed, error displayed during Finish() is bogus.

% ./icetray/resources/scripts/return_numpy_bool.py  
Logging configured from file ./log4cplus.conf
/home/troy/Icecube/meta-projects/offline-software/trunk/clean/src/icetray/private/icetray/I3ConfigurationImpl.cxx:132: FATAL: root trying to connect outbox OutBox of count1 to tc, but it's already connected to falsemodule!
Traceback (most recent call last):
  File "./icetray/resources/scripts/return_numpy_bool.py", line 28, in <module>
    t.Execute(15)
  File "/home/troy/Icecube/meta-projects/offline-software/trunk/clean/debug/lib/I3Tray.py", line 116, in Execute
    args[0].the_tray.Execute(args[1])
RuntimeError: trying to connect outbox OutBox of count1 to tc, but it's already connected to falsemodule!
I3Tray finishing...
/home/troy/Icecube/meta-projects/offline-software/trunk/clean/src/icetray/private/icetray/I3Tray.cxx:457: FATAL: I3Tray Attempt to call finish, but there is no driving module.  Did you forget to call Execute()?
terminate called after throwing an instance of 'std::runtime_error'
  what():  Attempt to call finish, but there is no driving module.  Did you forget to call Execute()?
zsh: abort      ./icetray/resources/scripts/return_numpy_bool.py

Migrated from https://code.icecube.wisc.edu/ticket/616
```json
{
    "status": "closed", 
    "changetime": "2012-10-31T19:05:10", 
    "description": "real error is caught and displayed, error displayed during Finish() is bogus.\n\n% ./icetray/resources/scripts/return_numpy_bool.py  \nLogging configured from file ./log4cplus.conf\n/home/troy/Icecube/meta-projects/offline-software/trunk/clean/src/icetray/private/icetray/I3ConfigurationImpl.cxx:132: FATAL: root trying to connect outbox OutBox of count1 to tc, but it's already connected to falsemodule!\nTraceback (most recent call last):\n  File \"./icetray/resources/scripts/return_numpy_bool.py\", line 28, in <module>\n    t.Execute(15)\n  File \"/home/troy/Icecube/meta-projects/offline-software/trunk/clean/debug/lib/I3Tray.py\", line 116, in Execute\n    args[0].the_tray.Execute(args[1])\nRuntimeError: trying to connect outbox OutBox of count1 to tc, but it's already connected to falsemodule!\nI3Tray finishing...\n/home/troy/Icecube/meta-projects/offline-software/trunk/clean/src/icetray/private/icetray/I3Tray.cxx:457: FATAL: I3Tray Attempt to call finish, but there is no driving module.  Did you forget to call Execute()?\nterminate called after throwing an instance of 'std::runtime_error'\n  what():  Attempt to call finish, but there is no driving module.  Did you forget to call Execute()?\nzsh: abort      ./icetray/resources/scripts/return_numpy_bool.py\n", 
    "reporter": "troy", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1351710310000000", 
    "component": "IceTray", 
    "summary": "bad error when execute after config problem", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2010-08-16T21:21:48", 
    "milestone": "", 
    "owner": "olivas", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20120529T23:16:32: nega changed owner from "troy" to "olivas"

**Comment by icecube-trac** [comment]
Trac update at 20121031T19:05:10: 
* nega changed status from "new" to "closed"
* nega changed resolution from "" to "fixed"
* nega commented:

> fixed in I3Tray rewrite
