### ISSUE TITLE
"make inspect" fails (Trac #653)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#652]
on software.iwe:

```text
Traceback (most recent call last):
 File "/net/software/doc_build/offline-head/build/bin/icetray-inspect", line 140, in <module>
   module = __import__('icecube.%s' % modname, globals(), locals(), [modname])
 File "/net/software/doc_build/offline-head/build/lib/icecube/rootwriter/__init__.py", line 7, in <module>
   def I3ROOTWriter(tray, name, Output=None, **kwargs):
 File "/net/software/doc_build/offline-head/build/lib/icecube/icetray/traysegment.py", line 20, in traysegment
   if inspect.getdoc(function) is None:
AttributeError: 'module' object has no attribute 'getdoc'
make[3]: *** [rootwriter/CMakeFiles/rootwriter-rootwriter-inspect] Error 1
make[2]: *** [rootwriter/CMakeFiles/rootwriter-rootwriter-inspect.dir/all] Error 2
make[1]: *** [CMakeFiles/inspect.dir/rule] Error 2
make: *** [inspect] Error 2
```

on my laptop:

```text

[  0%] Generating html from icetray-inspect of WaveCalibrator
Logging configured from file /Users/nega/i3/offline-software/build/log4cplus.conf
WARN: Can't load pure-Python bits of WaveCalibrator (No module named tables); you'll only have the C++ library./Users/nega/i3/offline-software/build/CMakeFiles/WaveCalibrator-inspection.xml:4: parser error : Specification mandate value for attribute DOMSimulatorCalibrator
<function DOMSimulatorCalibrator at 0x11069fde8>
                                 ^
/Users/nega/i3/offline-software/build/CMakeFiles/WaveCalibrator-inspection.xml:4: parser error : attributes construct error
<function DOMSimulatorCalibrator at 0x11069fde8>
                                 ^
/Users/nega/i3/offline-software/build/CMakeFiles/WaveCalibrator-inspection.xml:4: parser error : Couldn't find end of Start Tag function line 4
<function DOMSimulatorCalibrator at 0x11069fde8>
                                 ^
unable to parse /Users/nega/i3/offline-software/build/CMakeFiles/WaveCalibrator-inspection.xml
make[3]: *** [WaveCalibrator/CMakeFiles/WaveCalibrator-WaveCalibrator-inspect] Error 6
make[2]: *** [WaveCalibrator/CMakeFiles/WaveCalibrator-WaveCalibrator-inspect.dir/all] Error 2
make[1]: *** [CMakeFiles/inspect.dir/rule] Error 2
make: *** [inspect] Error 2
```

Migrated from https://code.icecube.wisc.edu/ticket/653
```json
{
    "status": "closed", 
    "changetime": "2011-09-13T14:26:39", 
    "description": "on software.iwe:\n\n{{{\nTraceback (most recent call last):\n File \"/net/software/doc_build/offline-head/build/bin/icetray-inspect\", line 140, in <module>\n   module = __import__('icecube.%s' % modname, globals(), locals(), [modname])\n File \"/net/software/doc_build/offline-head/build/lib/icecube/rootwriter/__init__.py\", line 7, in <module>\n   def I3ROOTWriter(tray, name, Output=None, **kwargs):\n File \"/net/software/doc_build/offline-head/build/lib/icecube/icetray/traysegment.py\", line 20, in traysegment\n   if inspect.getdoc(function) is None:\nAttributeError: 'module' object has no attribute 'getdoc'\nmake[3]: *** [rootwriter/CMakeFiles/rootwriter-rootwriter-inspect] Error 1\nmake[2]: *** [rootwriter/CMakeFiles/rootwriter-rootwriter-inspect.dir/all] Error 2\nmake[1]: *** [CMakeFiles/inspect.dir/rule] Error 2\nmake: *** [inspect] Error 2\n}}}\n\non my laptop:\n{{{\n\n[  0%] Generating html from icetray-inspect of WaveCalibrator\nLogging configured from file /Users/nega/i3/offline-software/build/log4cplus.conf\nWARN: Can't load pure-Python bits of WaveCalibrator (No module named tables); you'll only have the C++ library./Users/nega/i3/offline-software/build/CMakeFiles/WaveCalibrator-inspection.xml:4: parser error : Specification mandate value for attribute DOMSimulatorCalibrator\n<function DOMSimulatorCalibrator at 0x11069fde8>\n                                 ^\n/Users/nega/i3/offline-software/build/CMakeFiles/WaveCalibrator-inspection.xml:4: parser error : attributes construct error\n<function DOMSimulatorCalibrator at 0x11069fde8>\n                                 ^\n/Users/nega/i3/offline-software/build/CMakeFiles/WaveCalibrator-inspection.xml:4: parser error : Couldn't find end of Start Tag function line 4\n<function DOMSimulatorCalibrator at 0x11069fde8>\n                                 ^\nunable to parse /Users/nega/i3/offline-software/build/CMakeFiles/WaveCalibrator-inspection.xml\nmake[3]: *** [WaveCalibrator/CMakeFiles/WaveCalibrator-WaveCalibrator-inspect] Error 6\nmake[2]: *** [WaveCalibrator/CMakeFiles/WaveCalibrator-WaveCalibrator-inspect.dir/all] Error 2\nmake[1]: *** [CMakeFiles/inspect.dir/rule] Error 2\nmake: *** [inspect] Error 2\n}}}", 
    "reporter": "nega", 
    "cc": "", 
    "resolution": "fixed", 
    "_ts": "1315923999000000", 
    "component": "IceTray", 
    "summary": "\"make inspect\" fails", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2011-09-13T14:18:03", 
    "milestone": "", 
    "owner": "jvansanten", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20110913T14:26:39: 
* jvansanten commented:

> This is an artifact of an old build; i3inspect.py used to be called inspect.py. rm $I3_SRC/icetray/python/inspect.pyc (or a fresh checkout) fixes the problem.
> 
> The second error is was fixed in r918.


* jvansanten changed status from "new" to "closed"
* jvansanten changed resolution from "" to "fixed"
