### ISSUE TITLE
o7_libarchive_read.py dataio test failing on SL6 with system libarchive (Trac #714)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#713]
Test is failing....

blaufuss@morax[build(I3)]% ./dataio/resources/test/o7_libarchive_read.py 
Warning in <TUnixSystem::SetDisplay>: DISPLAY not set, setting it to pa-pub.private.pa.umd.edu:0.0
tar: Removing leading `/' from member names
1 block
I3DOMLaunchSeriesMap.i3
I3DOMLaunchSeriesMap.i3.tar
WARN (icetray): (archive_filter) The compression scheme of file 'I3DOMLaunchSeriesMap.i3.tar' is not obvious from the name. Attempting autodetection... (open.cxx:244 in archive_filter::archive_filter(const std::string&))
I3DOMLaunchSeriesMap.i3.pax
WARN (icetray): (archive_filter) The compression scheme of file 'I3DOMLaunchSeriesMap.i3.pax' is not obvious from the name. Attempting autodetection... (open.cxx:244 in archive_filter::archive_filter(const std::string&))
I3DOMLaunchSeriesMap.i3.cpio
WARN (icetray): (archive_filter) The compression scheme of file 'I3DOMLaunchSeriesMap.i3.cpio' is not obvious from the name. Attempting autodetection... (open.cxx:244 in archive_filter::archive_filter(const std::string&))
I3DOMLaunchSeriesMap.i3.gz
I3DOMLaunchSeriesMap.i3.tar.gz
I3DOMLaunchSeriesMap.i3.pax.gz
I3DOMLaunchSeriesMap.i3.cpio.gz
I3DOMLaunchSeriesMap.i3.bz2
I3DOMLaunchSeriesMap.i3.tar.bz2
I3DOMLaunchSeriesMap.i3.pax.bz2
I3DOMLaunchSeriesMap.i3.cpio.bz2
I3DOMLaunchSeriesMap.i3.lzma
FATAL (icetray): archive_read_open() failed: Lzma decompression failed:  Unknown error (open.cxx:260 in std::streamsize archive_filter::read(Source&, archive_filter::char_type*, std::streamsize) [with Source = boost::iostreams::detail::linked_streambuf<char, std::char_traits<char> >])
Traceback (most recent call last):
  File "./dataio/resources/test/o7_libarchive_read.py", line 70, in <module>
    test_read(file)
  File "./dataio/resources/test/o7_libarchive_read.py", line 29, in test_read
    if list(fr.keys()) != ['object']:
AttributeError: 'NoneType' object has no attribute 'keys'

This seems to only happen when using the system libarchive  (using I3_PORTS libarchive seems to work.)    

Only reading .lzma and .xz files are impacted.  

Appears to be a version/interface conflict with the system provided libarchive and lzma libs from the system

Work around for issue:  install libarchive in I3_PORTS

Migrated from https://code.icecube.wisc.edu/ticket/714
```json
{
    "status": "closed", 
    "changetime": "2014-04-18T03:03:23", 
    "description": "Test is failing....\n\nblaufuss@morax[build(I3)]% ./dataio/resources/test/o7_libarchive_read.py \nWarning in <TUnixSystem::SetDisplay>: DISPLAY not set, setting it to pa-pub.private.pa.umd.edu:0.0\ntar: Removing leading `/' from member names\n1 block\nI3DOMLaunchSeriesMap.i3\nI3DOMLaunchSeriesMap.i3.tar\nWARN (icetray): (archive_filter) The compression scheme of file 'I3DOMLaunchSeriesMap.i3.tar' is not obvious from the name. Attempting autodetection... (open.cxx:244 in archive_filter::archive_filter(const std::string&))\nI3DOMLaunchSeriesMap.i3.pax\nWARN (icetray): (archive_filter) The compression scheme of file 'I3DOMLaunchSeriesMap.i3.pax' is not obvious from the name. Attempting autodetection... (open.cxx:244 in archive_filter::archive_filter(const std::string&))\nI3DOMLaunchSeriesMap.i3.cpio\nWARN (icetray): (archive_filter) The compression scheme of file 'I3DOMLaunchSeriesMap.i3.cpio' is not obvious from the name. Attempting autodetection... (open.cxx:244 in archive_filter::archive_filter(const std::string&))\nI3DOMLaunchSeriesMap.i3.gz\nI3DOMLaunchSeriesMap.i3.tar.gz\nI3DOMLaunchSeriesMap.i3.pax.gz\nI3DOMLaunchSeriesMap.i3.cpio.gz\nI3DOMLaunchSeriesMap.i3.bz2\nI3DOMLaunchSeriesMap.i3.tar.bz2\nI3DOMLaunchSeriesMap.i3.pax.bz2\nI3DOMLaunchSeriesMap.i3.cpio.bz2\nI3DOMLaunchSeriesMap.i3.lzma\nFATAL (icetray): archive_read_open() failed: Lzma decompression failed:  Unknown error (open.cxx:260 in std::streamsize archive_filter::read(Source&, archive_filter::char_type*, std::streamsize) [with Source = boost::iostreams::detail::linked_streambuf<char, std::char_traits<char> >])\nTraceback (most recent call last):\n  File \"./dataio/resources/test/o7_libarchive_read.py\", line 70, in <module>\n    test_read(file)\n  File \"./dataio/resources/test/o7_libarchive_read.py\", line 29, in test_read\n    if list(fr.keys()) != ['object']:\nAttributeError: 'NoneType' object has no attribute 'keys'\n\nThis seems to only happen when using the system libarchive  (using I3_PORTS libarchive seems to work.)    \n\nOnly reading .lzma and .xz files are impacted.  \n\nAppears to be a version/interface conflict with the system provided libarchive and lzma libs from the system\n\nWork around for issue:  install libarchive in I3_PORTS\n", 
    "reporter": "blaufuss", 
    "cc": "", 
    "resolution": "invalid", 
    "_ts": "1397790203000000", 
    "component": "dataio", 
    "summary": "o7_libarchive_read.py dataio test failing on SL6 with system libarchive", 
    "priority": "normal", 
    "keywords": "SL6 libarchive", 
    "time": "2013-07-11T17:25:03", 
    "milestone": "", 
    "owner": "nega", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20140418T03:03:23: 
* nega changed resolution from "" to "invalid"
* nega changed status from "new" to "closed"
* nega commented:

> Seems to be a localized issue on the old buildbot.
