### ISSUE TITLE
gulliver-modules::fancyfit test fails on SL5 32bit (Trac #746)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#740]
Python traceback:

```text
ERROR (I3FortyTwo): PLEASE INVESTIGATE (fortytwo.py:185 in Finish)
FATAL (I3FortyTwo): SOME CHECKS FAILED (fortytwo.py:186 in Finish)
ERROR (I3Module): <class 'fortytwo.I3FortyTwo'>_0000: Exception thrown (I3Module.cxx:113 in void I3Module::Do(void (I3Module::*)()))
Traceback (most recent call last):
  File "/build/buildslave/foraii/quick_icerec_SL5/source/gulliver-modules/resources/scripts/fancyfit.py", line 142, in ?
    tray.Finish()
  File "/build/buildslave/foraii/quick_icerec_SL5/source/gulliver-modules/resources/scripts/fortytwo.py", line 186, in Finish
    icetray.logging.log_fatal("SOME CHECKS FAILED",unit=u42)
  File "/build/buildslave/foraii/quick_icerec_SL5/build/lib/icecube/icetray/i3logging.py", line 150, in log_fatal
    raise RuntimeError(message + " (in " + tb[2] + ")")
RuntimeError: SOME CHECKS FAILED (in Finish)
```

More output at: http://builds.icecube.wisc.edu/builders/quick_icerec_SL5/builds/1103/steps/test/logs/stdio

Migrated from https://code.icecube.wisc.edu/ticket/746
```json
{
    "status": "closed", 
    "changetime": "2015-02-11T17:23:17", 
    "description": "Python traceback:\n\n{{{\nERROR (I3FortyTwo): PLEASE INVESTIGATE (fortytwo.py:185 in Finish)\nFATAL (I3FortyTwo): SOME CHECKS FAILED (fortytwo.py:186 in Finish)\nERROR (I3Module): <class 'fortytwo.I3FortyTwo'>_0000: Exception thrown (I3Module.cxx:113 in void I3Module::Do(void (I3Module::*)()))\nTraceback (most recent call last):\n  File \"/build/buildslave/foraii/quick_icerec_SL5/source/gulliver-modules/resources/scripts/fancyfit.py\", line 142, in ?\n    tray.Finish()\n  File \"/build/buildslave/foraii/quick_icerec_SL5/source/gulliver-modules/resources/scripts/fortytwo.py\", line 186, in Finish\n    icetray.logging.log_fatal(\"SOME CHECKS FAILED\",unit=u42)\n  File \"/build/buildslave/foraii/quick_icerec_SL5/build/lib/icecube/icetray/i3logging.py\", line 150, in log_fatal\n    raise RuntimeError(message + \" (in \" + tb[2] + \")\")\nRuntimeError: SOME CHECKS FAILED (in Finish)\n}}}\n\nMore output at: http://builds.icecube.wisc.edu/builders/quick_icerec_SL5/builds/1103/steps/test/logs/stdio\n", 
    "reporter": "nega", 
    "cc": "dataclass@icecube.wisc.edu", 
    "resolution": "wontfix", 
    "_ts": "1423675397463977", 
    "component": "combo reconstruction", 
    "summary": "gulliver-modules::fancyfit test fails on SL5 32bit", 
    "priority": "normal", 
    "keywords": "gulliver-modules tests", 
    "time": "2014-09-05T21:19:03", 
    "milestone": "", 
    "owner": "boersma", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20140905T22:05:44: 
* nega changed component from "booking" to "icerec"
* nega commented:

> This applies to OSX Mountain Lion

**Comment by icecube-trac** [comment]
Trac update at 20150211T17:23:17: 
* nega changed resolution from "" to "wontfix"
* nega commented:

> SL5 is deprecated, and no longer supported


* nega changed status from "new" to "closed"
