### ISSUE TITLE
gulliver-modules::simple_cascade test fails on SL5 32bit (Trac #748)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#742]
```text
INFO (I3FortyTwo): picklefilename=/build/buildslave/foraii/quick_icerec_SL5/source/gulliver-modules/resources/scripts/42.dat (fortytwo.py:108 in Configure)
INFO (I3FortyTwo): mode=check (fortytwo.py:120 in Configure)
NOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:533 in void I3Tray::Finish())
ERROR (I3FortyTwo): SOME CHECKS FAILED (fortytwo.py:183 in Finish)
ERROR (I3FortyTwo): Frame 1: psafit value/reference: status=0/0(OK?)
type=0/0(OK?)
shape=30/30(OK?)
zenith=0.551601876475/0.551601876475(OK?)
azimuth=5.5094947668/5.5094947668(OK?)
x=147.807816063/147.809345113(OK?)
y=444.018614978/444.016519525(OK?)
z=414.356903999/414.353615041(OK?)
t=5281.68007965/5281.71691514(OK?)
L=nan/nan(OK?)
log10(E)=6.09895662053/5.12329747713(PROBLEM!)

Frame 1: mpefitFitParams value/reference: logl=288.918192193/288.918192192(OK?)
rlogl=9.02869350603/9.02869350602(OK?)
ndof=32/32(OK?)
nmini=211/214(PROBLEM!)

psafitFitParams value/reference: logl=286.710154138/286.710078665(OK?)
rlogl=8.19171868965/8.19171653329(OK?)
ndof=35/35(OK?)
nmini=28/38(PROBLEM!)
 (fortytwo.py:184 in Finish)
ERROR (I3FortyTwo): PLEASE INVESTIGATE (fortytwo.py:185 in Finish)
FATAL (I3FortyTwo): SOME CHECKS FAILED (fortytwo.py:186 in Finish)
ERROR (I3Module): <class 'fortytwo.I3FortyTwo'>_0000: Exception thrown (I3Module.cxx:113 in void I3Module::Do(void (I3Module::*)()))
Traceback (most recent call last):
  File "/build/buildslave/foraii/quick_icerec_SL5/source/gulliver-modules/resources/scripts/simple_cascade.py", line 176, in ?
    tray.Finish()
  File "/build/buildslave/foraii/quick_icerec_SL5/source/gulliver-modules/resources/scripts/fortytwo.py", line 186, in Finish
    icetray.logging.log_fatal("SOME CHECKS FAILED",unit=u42)
  File "/build/buildslave/foraii/quick_icerec_SL5/build/lib/icecube/icetray/i3logging.py", line 150, in log_fatal
    raise RuntimeError(message + " (in " + tb[2] + ")")
RuntimeError: SOME CHECKS FAILED (in Finish)
INFO (I3Gulliver): (spefit) nr. of proper llh function calls by minimizer: 2711 (I3Gulliver.cxx:31 in virtual I3Gulliver::~I3Gulliver())
INFO (I3Gulliver): (mpefit) nr. of proper llh function calls by minimizer: 2285 (I3Gulliver.cxx:31 in virtual I3Gulliver::~I3Gulliver())
INFO (I3Gulliver): (psafit) nr. of proper llh function calls by minimizer: 364 (I3Gulliver.cxx:31 in virtual I3Gulliver::~I3Gulliver())
```

Migrated from https://code.icecube.wisc.edu/ticket/748
```json
{
    "status": "closed", 
    "changetime": "2015-02-11T17:23:53", 
    "description": "{{{\nINFO (I3FortyTwo): picklefilename=/build/buildslave/foraii/quick_icerec_SL5/source/gulliver-modules/resources/scripts/42.dat (fortytwo.py:108 in Configure)\nINFO (I3FortyTwo): mode=check (fortytwo.py:120 in Configure)\nNOTICE (I3Tray): I3Tray finishing... (I3Tray.cxx:533 in void I3Tray::Finish())\nERROR (I3FortyTwo): SOME CHECKS FAILED (fortytwo.py:183 in Finish)\nERROR (I3FortyTwo): Frame 1: psafit value/reference: status=0/0(OK?)\ntype=0/0(OK?)\nshape=30/30(OK?)\nzenith=0.551601876475/0.551601876475(OK?)\nazimuth=5.5094947668/5.5094947668(OK?)\nx=147.807816063/147.809345113(OK?)\ny=444.018614978/444.016519525(OK?)\nz=414.356903999/414.353615041(OK?)\nt=5281.68007965/5281.71691514(OK?)\nL=nan/nan(OK?)\nlog10(E)=6.09895662053/5.12329747713(PROBLEM!)\n\nFrame 1: mpefitFitParams value/reference: logl=288.918192193/288.918192192(OK?)\nrlogl=9.02869350603/9.02869350602(OK?)\nndof=32/32(OK?)\nnmini=211/214(PROBLEM!)\n\npsafitFitParams value/reference: logl=286.710154138/286.710078665(OK?)\nrlogl=8.19171868965/8.19171653329(OK?)\nndof=35/35(OK?)\nnmini=28/38(PROBLEM!)\n (fortytwo.py:184 in Finish)\nERROR (I3FortyTwo): PLEASE INVESTIGATE (fortytwo.py:185 in Finish)\nFATAL (I3FortyTwo): SOME CHECKS FAILED (fortytwo.py:186 in Finish)\nERROR (I3Module): <class 'fortytwo.I3FortyTwo'>_0000: Exception thrown (I3Module.cxx:113 in void I3Module::Do(void (I3Module::*)()))\nTraceback (most recent call last):\n  File \"/build/buildslave/foraii/quick_icerec_SL5/source/gulliver-modules/resources/scripts/simple_cascade.py\", line 176, in ?\n    tray.Finish()\n  File \"/build/buildslave/foraii/quick_icerec_SL5/source/gulliver-modules/resources/scripts/fortytwo.py\", line 186, in Finish\n    icetray.logging.log_fatal(\"SOME CHECKS FAILED\",unit=u42)\n  File \"/build/buildslave/foraii/quick_icerec_SL5/build/lib/icecube/icetray/i3logging.py\", line 150, in log_fatal\n    raise RuntimeError(message + \" (in \" + tb[2] + \")\")\nRuntimeError: SOME CHECKS FAILED (in Finish)\nINFO (I3Gulliver): (spefit) nr. of proper llh function calls by minimizer: 2711 (I3Gulliver.cxx:31 in virtual I3Gulliver::~I3Gulliver())\nINFO (I3Gulliver): (mpefit) nr. of proper llh function calls by minimizer: 2285 (I3Gulliver.cxx:31 in virtual I3Gulliver::~I3Gulliver())\nINFO (I3Gulliver): (psafit) nr. of proper llh function calls by minimizer: 364 (I3Gulliver.cxx:31 in virtual I3Gulliver::~I3Gulliver())\n}}}", 
    "reporter": "nega", 
    "cc": "dataclass@icecube.wisc.edu", 
    "resolution": "wontfix", 
    "_ts": "1423675433767817", 
    "component": "combo reconstruction", 
    "summary": "gulliver-modules::simple_cascade test fails on SL5 32bit", 
    "priority": "normal", 
    "keywords": "gulliver-modules tests", 
    "time": "2014-09-05T21:23:43", 
    "milestone": "", 
    "owner": "boersma", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20140905T22:07:32: nega commented:

> This applies to OSX Mountain Lion

**Comment by icecube-trac** [comment]
Trac update at 20150211T17:23:53: 
* nega changed status from "new" to "closed"
* nega changed resolution from "" to "wontfix"
* nega commented:

> SL5 is deprecated, and no longer supported
