### ISSUE TITLE
lilliput::python_wrappers.py use incompatible syntax for python 2.4 (Trac #754)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#748]
```text
[buildslave@foraii build]$ python -V
Python 2.4.3
[buildslave@foraii build]$ !lsb
lsb_release -sd
"Scientific Linux release 5.10 (Boron)"
[buildslave@foraii build]$ 
```

```text
289/298 Test #288: lilliput::python_wrappers.py ...................................***Failed    2.30 sec
Traceback (most recent call last):
  File "/build/buildslave/foraii/quick_icerec_SL5/source/lilliput/resources/scripts/python_wrappers.py", line 5, in ?
    from icecube.common_variables import hit_statistics
  File "/build/buildslave/foraii/quick_icerec_SL5/build/lib/icecube/common_variables/__init__.py", line 25
    from .load_pybindings_enhanced import load_pybindings
         ^
SyntaxError: invalid syntax
```

Migrated from https://code.icecube.wisc.edu/ticket/754
```json
{
    "status": "closed", 
    "changetime": "2014-09-30T19:56:25", 
    "description": "{{{\n[buildslave@foraii build]$ python -V\nPython 2.4.3\n[buildslave@foraii build]$ !lsb\nlsb_release -sd\n\"Scientific Linux release 5.10 (Boron)\"\n[buildslave@foraii build]$ \n}}}\n{{{\n289/298 Test #289: lilliput::python_wrappers.py ...................................***Failed    2.30 sec\nTraceback (most recent call last):\n  File \"/build/buildslave/foraii/quick_icerec_SL5/source/lilliput/resources/scripts/python_wrappers.py\", line 5, in ?\n    from icecube.common_variables import hit_statistics\n  File \"/build/buildslave/foraii/quick_icerec_SL5/build/lib/icecube/common_variables/__init__.py\", line 25\n    from .load_pybindings_enhanced import load_pybindings\n         ^\nSyntaxError: invalid syntax\n}}}", 
    "reporter": "nega", 
    "cc": "dataclass@icecube.wisc.edu", 
    "resolution": "fixed", 
    "_ts": "1412106985532289", 
    "component": "combo reconstruction", 
    "summary": "lilliput::python_wrappers.py use incompatible syntax for python 2.4", 
    "priority": "normal", 
    "keywords": "lilliput python tests", 
    "time": "2014-09-05T21:47:53", 
    "milestone": "", 
    "owner": "boersma", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20140905T21:52:18: david.schultz commented:

> Needs something like this in CMakeLists.txt:
> 
> 
> ```text
> if (PYTHON_NUMERIC_VERSION LESS 20600)
>     colormsg (YELLOW "*** python v2.6 or greater is required... skipping")
> else (PYTHON_NUMERIC_VERSION LESS 20600)
> 
> 
> endif (PYTHON_NUMERIC_VERSION LESS 20600)
> ```
>

**Comment by icecube-trac** [comment]
Trac update at 20140930T19:56:25: 
* meike.dewith changed status from "new" to "closed"
* meike.dewith changed resolution from "" to "fixed"
* meike.dewith commented:

> Solved in r123227 by mwolf
