### ISSUE TITLE
wimpsim-reader can't find a RandomService on multiple platforms (Trac #756)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#750]
```text
        Start  21: wimpsim-reader::test_earth.py
 21/237 Test  #21: wimpsim-reader::test_earth.py ..................................***Failed    2.04 sec
Traceback (most recent call last):
  File "/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/source/wimpsim-reader/resources/test/test_earth.py", line 292, in <module>
    DoUnitTestEarth(tray, "DoUnitTestEarth", params)
  File "/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/source/wimpsim-reader/resources/test/test_earth.py", line 212, in DoUnitTestEarth
    from icecube import icectray, dataclasses, dataio
ImportError: cannot import name icectray

        Start  22: wimpsim-reader::test_earth_event.py
 22/237 Test  #22: wimpsim-reader::test_earth_event.py ............................   Passed    1.96 sec
        Start  23: wimpsim-reader::test_sun.py
 23/237 Test  #23: wimpsim-reader::test_sun.py ....................................***Failed    1.95 sec
FATAL (I3WimpSimReader): No Random Service configured! (I3WimpSimReader.cxx:148 in virtual void I3WimpSimReader::Configure())
ERROR (I3Tray): Exception thrown while configuring module "wimpsim-reader". (I3Tray.cxx:384 in void I3Tray::Configure())
wimpsim-reader (I3WimpSimReader)
  EndMJD
    Description :  MJD to end simulation; if unspecified: read everything
    Default     :  nan
    Configured  :  56059.25

  FileNameList
    Description :  The WimpSim file to read from
    Default     :  []
    Configured  :  ['/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/source/wimpsim-reader/resources/test_data_sun.dat']

  InfoFileName
    Description :  write Information to this textfile
    Default     :  ''

  InjectionRadius
    Description :  If >0, events will be injected in cylinder with zmin, zmax height
    Default     :  nan
    Configured  :  700.0

  LowerZenCut
    Description :  optional lower Zenith Cut in [rad]
    Default     :  0.0
    Configured  :  0.0

  NEvents
    Description :  Number of events to issue, if unconfigured read everything
    Default     :  0
    Configured  :  0

  Oversampling
    Description :  N oversamplings
    Default     :  0
    Configured  :  0

  PositionLimits
    Description :  Array of xmin,xmax,ymin,ymax,zmin,zmax
    Default     :  [-800.0, 800.0, -800.0, 800.0, -800.0, 800.0]
    Configured  :  [-800, 800, -800, 800, -800, 800]

  RandomService
    Description :  The RandomService in the context
    Default     :  None

  RandomServiceName
    Description :  Name of the RandomService to be used
    Default     :  'I3RandomService'
    Configured  :  'Random'

  SensitiveHeight
    Description :  Muon box activated height
    Default     :  nan
    Configured  :  1300.0

  SensitiveRadius
    Description :  Muon box activated radius
    Default     :  nan
    Configured  :  700.0

  StartMJD
    Description :  MJD to start simulation; if unspecified: read everything
    Default     :  nan
    Configured  :  55694

  UpperZenCut
    Description :  optional upper Zenith Cut in [rad]
    Default     :  3.141592653589793
    Configured  :  3.141592653589793

  UseElectrons
    Description :  Read and simulate electron vertices
    Default     :  False
    Configured  :  True

  UseMuons
    Description :  Read and simulate muon vertices
    Default     :  True
    Configured  :  True

  UseNC
    Description :  Read and simulate NeutralCurrent vertices
    Default     :  False
    Configured  :  True

  UseTaus
    Description :  Read and simulate tau vertices
    Default     :  False
    Configured  :  True

Traceback (most recent call last):
  File "/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/source/wimpsim-reader/resources/test/test_sun.py", line 305, in <module>
    tray.Execute()
  File "/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/build/lib/I3Tray.py", line 231, in Execute
    super(I3Tray, self).Execute()
RuntimeError: No Random Service configured! (in virtual void I3WimpSimReader::Configure())
```

Migrated from https://code.icecube.wisc.edu/ticket/756
```json
{
    "status": "closed", 
    "changetime": "2014-09-20T08:34:18", 
    "description": "{{{\n        Start  21: wimpsim-reader::test_earth.py\n 21/237 Test  #21: wimpsim-reader::test_earth.py ..................................***Failed    2.04 sec\nTraceback (most recent call last):\n  File \"/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/source/wimpsim-reader/resources/test/test_earth.py\", line 292, in <module>\n    DoUnitTestEarth(tray, \"DoUnitTestEarth\", params)\n  File \"/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/source/wimpsim-reader/resources/test/test_earth.py\", line 212, in DoUnitTestEarth\n    from icecube import icectray, dataclasses, dataio\nImportError: cannot import name icectray\n\n        Start  22: wimpsim-reader::test_earth_event.py\n 22/237 Test  #22: wimpsim-reader::test_earth_event.py ............................   Passed    1.96 sec\n        Start  23: wimpsim-reader::test_sun.py\n 23/237 Test  #23: wimpsim-reader::test_sun.py ....................................***Failed    1.95 sec\nFATAL (I3WimpSimReader): No Random Service configured! (I3WimpSimReader.cxx:148 in virtual void I3WimpSimReader::Configure())\nERROR (I3Tray): Exception thrown while configuring module \"wimpsim-reader\". (I3Tray.cxx:384 in void I3Tray::Configure())\nwimpsim-reader (I3WimpSimReader)\n  EndMJD\n    Description :  MJD to end simulation; if unspecified: read everything\n    Default     :  nan\n    Configured  :  56059.25\n\n  FileNameList\n    Description :  The WimpSim file to read from\n    Default     :  []\n    Configured  :  ['/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/source/wimpsim-reader/resources/test_data_sun.dat']\n\n  InfoFileName\n    Description :  write Information to this textfile\n    Default     :  ''\n\n  InjectionRadius\n    Description :  If >0, events will be injected in cylinder with zmin, zmax height\n    Default     :  nan\n    Configured  :  700.0\n\n  LowerZenCut\n    Description :  optional lower Zenith Cut in [rad]\n    Default     :  0.0\n    Configured  :  0.0\n\n  NEvents\n    Description :  Number of events to issue, if unconfigured read everything\n    Default     :  0\n    Configured  :  0\n\n  Oversampling\n    Description :  N oversamplings\n    Default     :  0\n    Configured  :  0\n\n  PositionLimits\n    Description :  Array of xmin,xmax,ymin,ymax,zmin,zmax\n    Default     :  [-800.0, 800.0, -800.0, 800.0, -800.0, 800.0]\n    Configured  :  [-800, 800, -800, 800, -800, 800]\n\n  RandomService\n    Description :  The RandomService in the context\n    Default     :  None\n\n  RandomServiceName\n    Description :  Name of the RandomService to be used\n    Default     :  'I3RandomService'\n    Configured  :  'Random'\n\n  SensitiveHeight\n    Description :  Muon box activated height\n    Default     :  nan\n    Configured  :  1300.0\n\n  SensitiveRadius\n    Description :  Muon box activated radius\n    Default     :  nan\n    Configured  :  700.0\n\n  StartMJD\n    Description :  MJD to start simulation; if unspecified: read everything\n    Default     :  nan\n    Configured  :  55694\n\n  UpperZenCut\n    Description :  optional upper Zenith Cut in [rad]\n    Default     :  3.141592653589793\n    Configured  :  3.141592653589793\n\n  UseElectrons\n    Description :  Read and simulate electron vertices\n    Default     :  False\n    Configured  :  True\n\n  UseMuons\n    Description :  Read and simulate muon vertices\n    Default     :  True\n    Configured  :  True\n\n  UseNC\n    Description :  Read and simulate NeutralCurrent vertices\n    Default     :  False\n    Configured  :  True\n\n  UseTaus\n    Description :  Read and simulate tau vertices\n    Default     :  False\n    Configured  :  True\n\nTraceback (most recent call last):\n  File \"/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/source/wimpsim-reader/resources/test/test_sun.py\", line 305, in <module>\n    tray.Execute()\n  File \"/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/build/lib/I3Tray.py\", line 231, in Execute\n    super(I3Tray, self).Execute()\nRuntimeError: No Random Service configured! (in virtual void I3WimpSimReader::Configure())\n}}}", 
    "reporter": "nega", 
    "cc": "dataclass@icecube.wisc.edu", 
    "resolution": "fixed", 
    "_ts": "1411202058919605", 
    "component": "combo simulation", 
    "summary": "wimpsim-reader can't find a RandomService on multiple platforms", 
    "priority": "normal", 
    "keywords": "wimpsim-reader tests randomservice", 
    "time": "2014-09-06T18:17:44", 
    "milestone": "", 
    "owner": "mzoll", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20140908T07:43:47: mzoll commented:

> 
> This is a problem of teh RandomService-Facility, where there is still not a uniform policy how this service should be passed on to the modules, concerning:
> *ParameterName in the Modules
> *passing by reference / passing by name
> *the scope of this thing: living in icetray(-context) or as bullet-in
> 
> well i have fixed it now for the most common usecase
> 
> 
> Replying to [ticket:756 nega]:
> > 
> ```text
> >         Start  21: wimpsim-reader::test_earth.py
> >  21/237 Test  #21: wimpsim-reader::test_earth.py ..................................***Failed    2.04 sec
> > Traceback (most recent call last):
> >   File "/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/source/wimpsim-reader/resources/test/test_earth.py", line 292, in <module>
> >     DoUnitTestEarth(tray, "DoUnitTestEarth", params)
> >   File "/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/source/wimpsim-reader/resources/test/test_earth.py", line 212, in DoUnitTestEarth
> >     from icecube import icectray, dataclasses, dataio
> > ImportError: cannot import name icectray
> > 
> >         Start  22: wimpsim-reader::test_earth_event.py
> >  22/237 Test  #22: wimpsim-reader::test_earth_event.py ............................   Passed    1.96 sec
> >         Start  23: wimpsim-reader::test_sun.py
> >  23/237 Test  #23: wimpsim-reader::test_sun.py ....................................***Failed    1.95 sec
> > FATAL (I3WimpSimReader): No Random Service configured! (I3WimpSimReader.cxx:148 in virtual void I3WimpSimReader::Configure())
> > ERROR (I3Tray): Exception thrown while configuring module "wimpsim-reader". (I3Tray.cxx:384 in void I3Tray::Configure())
> > wimpsim-reader (I3WimpSimReader)
> >   EndMJD
> >     Description :  MJD to end simulation; if unspecified: read everything
> >     Default     :  nan
> >     Configured  :  56059.25
> > 
> >   FileNameList
> >     Description :  The WimpSim file to read from
> >     Default     :  []
> >     Configured  :  ['/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/source/wimpsim-reader/resources/test_data_sun.dat']
> > 
> >   InfoFileName
> >     Description :  write Information to this textfile
> >     Default     :  ''
> > 
> >   InjectionRadius
> >     Description :  If >0, events will be injected in cylinder with zmin, zmax height
> >     Default     :  nan
> >     Configured  :  700.0
> > 
> >   LowerZenCut
> >     Description :  optional lower Zenith Cut in [rad]
> >     Default     :  0.0
> >     Configured  :  0.0
> > 
> >   NEvents
> >     Description :  Number of events to issue, if unconfigured read everything
> >     Default     :  0
> >     Configured  :  0
> > 
> >   Oversampling
> >     Description :  N oversamplings
> >     Default     :  0
> >     Configured  :  0
> > 
> >   PositionLimits
> >     Description :  Array of xmin,xmax,ymin,ymax,zmin,zmax
> >     Default     :  [-800.0, 800.0, -800.0, 800.0, -800.0, 800.0]
> >     Configured  :  [-800, 800, -800, 800, -800, 800]
> > 
> >   RandomService
> >     Description :  The RandomService in the context
> >     Default     :  None
> > 
> >   RandomServiceName
> >     Description :  Name of the RandomService to be used
> >     Default     :  'I3RandomService'
> >     Configured  :  'Random'
> > 
> >   SensitiveHeight
> >     Description :  Muon box activated height
> >     Default     :  nan
> >     Configured  :  1300.0
> > 
> >   SensitiveRadius
> >     Description :  Muon box activated radius
> >     Default     :  nan
> >     Configured  :  700.0
> > 
> >   StartMJD
> >     Description :  MJD to start simulation; if unspecified: read everything
> >     Default     :  nan
> >     Configured  :  55694
> > 
> >   UpperZenCut
> >     Description :  optional upper Zenith Cut in [rad]
> >     Default     :  3.141592653589793
> >     Configured  :  3.141592653589793
> > 
> >   UseElectrons
> >     Description :  Read and simulate electron vertices
> >     Default     :  False
> >     Configured  :  True
> > 
> >   UseMuons
> >     Description :  Read and simulate muon vertices
> >     Default     :  True
> >     Configured  :  True
> > 
> >   UseNC
> >     Description :  Read and simulate NeutralCurrent vertices
> >     Default     :  False
> >     Configured  :  True
> > 
> >   UseTaus
> >     Description :  Read and simulate tau vertices
> >     Default     :  False
> >     Configured  :  True
> > 
> > Traceback (most recent call last):
> >   File "/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/source/wimpsim-reader/resources/test/test_sun.py", line 305, in <module>
> >     tray.Execute()
> >   File "/build/buildslave/yaoguai/quick_simulation_ubuntu_12_04/build/lib/I3Tray.py", line 231, in Execute
> >     super(I3Tray, self).Execute()
> > RuntimeError: No Random Service configured! (in virtual void I3WimpSimReader::Configure())
> > ```
>

**Comment by icecube-trac** [comment]
Trac update at 20140920T08:34:18: 
* mzoll changed resolution from "" to "fixed"
* mzoll changed status from "new" to "closed"
