### ISSUE TITLE
steamshovel - crash on ubuntu 14.04 (Trac #892)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#886]
crash on Ubuntu 14.04 using
/cvmfs/icecube.opensciencegrid.org/standard/Ubuntu_14_x86_64/metaprojects/offline-software/V14-07-00/

Steps to produce:
1. start steamshovel
2. click on P frame
3. crash

Backtrace:

```text
(gdb) bt
https://code.icecube.wisc.edu/ticket/0  subtype_dealloc (self=0x7fffdb460e10) at Objects/typeobject.c:955
#1  0x00007ffff5772fc2 in boost::python::converter::shared_ptr_deleter::operator()(void const*) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/i3ports/lib/boost-1.38.0/libboost_python-mt.so
#2  0x000000000045ceae in boost::detail::sp_counted_base::release() ()
#3  0x00007ffff197bc93 in Scenario::findUsableArtistsByKeys(std::vector<std::string, std::allocator<std::string> > const&, bool) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/offline-software/trunk/lib/libshovelart.so
#4  0x0000000000488786 in ScenarioFrameModel::inputsChanged(boost::shared_ptr<I3Frame>) ()
#5  0x0000000000489ab9 in ScenarioFrameModel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#6  0x00007ffff1d5868a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4
#7  0x00007ffff1975245 in Scenario::inputsChanged(boost::shared_ptr<I3Frame>)
    ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/offline-software/trunk/lib/libshovelart.so
#8  0x00007ffff1977d94 in Scenario::setFrame(boost::shared_ptr<I3Frame>) ()
---Type <return> to continue, or q <return> to quit---
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/offline-software/trunk/lib/libshovelart.so
#9  0x000000000046a1ab in I3GLWidget::selectNewFrame(boost::shared_ptr<I3Frame>, int) ()
#10 0x000000000046faee in I3GLWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#11 0x00007ffff1d5868a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4
#12 0x0000000000475cd6 in FileService::frameSelected(boost::shared_ptr<I3Frame>, int) ()
#13 0x0000000000475e5c in FileService::selectFrameByIdx(unsigned int) ()
#14 0x00007ffff281ff6f in QGraphicsItem::sceneEvent(QEvent*) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#15 0x00007ffff2846faf in ?? ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#16 0x00007ffff28526d6 in ?? ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#17 0x00007ffff2852b69 in QGraphicsScene::mousePressEvent(QGraphicsSceneMouseEve---Type <return> to continue, or q <return> to quit---
nt*) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#18 0x00007ffff285b9b0 in QGraphicsScene::event(QEvent*) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#19 0x00007ffff22a8f7c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#20 0x00007ffff22af540 in QApplication::notify(QObject*, QEvent*) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#21 0x000000000047923b in SteamshovelApp::notify(QObject*, QEvent*) ()
#22 0x00007ffff1d44a0d in QCoreApplication::notifyInternal(QObject*, QEvent*)
    ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4
#23 0x00007ffff287230f in QGraphicsView::mousePressEvent(QMouseEvent*) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#24 0x00007ffff22f82a8 in QWidget::event(QEvent*) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.---Type <return> to continue, or q <return> to quit---
so.4
#25 0x00007ffff2671f7e in QFrame::event(QEvent*) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#26 0x00007ffff2873069 in QGraphicsView::viewportEvent(QEvent*) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#27 0x00007ffff1d44b76 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4
#28 0x00007ffff22a8f5c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#29 0x00007ffff22af67d in QApplication::notify(QObject*, QEvent*) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#30 0x000000000047923b in SteamshovelApp::notify(QObject*, QEvent*) ()
#31 0x00007ffff1d44a0d in QCoreApplication::notifyInternal(QObject*, QEvent*)
    ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4
---Type <return> to continue, or q <return> to quit---
#32 0x00007ffff22aee33 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#33 0x00007ffff231ff9b in ?? ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#34 0x00007ffff231ea41 in QApplication::x11ProcessEvent(_XEvent*) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#35 0x00007ffff2345040 in ?? ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4
#36 0x00007ffff1d436df in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4
#37 0x00007ffff1d439d5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4
#38 0x00007ffff1d48a89 in QCoreApplication::exec() ()
   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore---Type <return> to continue, or q <return> to quit---
.so.4
#39 0x000000000045890e in main ()
(gdb) 
```

Migrated from https://code.icecube.wisc.edu/ticket/892
```json
{
    "status": "closed", 
    "changetime": "2015-03-05T05:14:55", 
    "description": "crash on Ubuntu 14.04 using\n/cvmfs/icecube.opensciencegrid.org/standard/Ubuntu_14_x86_64/metaprojects/offline-software/V14-07-00/\n\nSteps to produce:\n1. start steamshovel\n2. click on P frame\n3. crash\n\nBacktrace:\n{{{\n(gdb) bt\n#0  subtype_dealloc (self=0x7fffdb460e10) at Objects/typeobject.c:955\n#1  0x00007ffff5772fc2 in boost::python::converter::shared_ptr_deleter::operator()(void const*) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/i3ports/lib/boost-1.38.0/libboost_python-mt.so\n#2  0x000000000045ceae in boost::detail::sp_counted_base::release() ()\n#3  0x00007ffff197bc93 in Scenario::findUsableArtistsByKeys(std::vector<std::string, std::allocator<std::string> > const&, bool) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/offline-software/trunk/lib/libshovelart.so\n#4  0x0000000000488786 in ScenarioFrameModel::inputsChanged(boost::shared_ptr<I3Frame>) ()\n#5  0x0000000000489ab9 in ScenarioFrameModel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()\n#6  0x00007ffff1d5868a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4\n#7  0x00007ffff1975245 in Scenario::inputsChanged(boost::shared_ptr<I3Frame>)\n    ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/offline-software/trunk/lib/libshovelart.so\n#8  0x00007ffff1977d94 in Scenario::setFrame(boost::shared_ptr<I3Frame>) ()\n---Type <return> to continue, or q <return> to quit---\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/metaprojects/offline-software/trunk/lib/libshovelart.so\n#9  0x000000000046a1ab in I3GLWidget::selectNewFrame(boost::shared_ptr<I3Frame>, int) ()\n#10 0x000000000046faee in I3GLWidget::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()\n#11 0x00007ffff1d5868a in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4\n#12 0x0000000000475cd6 in FileService::frameSelected(boost::shared_ptr<I3Frame>, int) ()\n#13 0x0000000000475e5c in FileService::selectFrameByIdx(unsigned int) ()\n#14 0x00007ffff281ff6f in QGraphicsItem::sceneEvent(QEvent*) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#15 0x00007ffff2846faf in ?? ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#16 0x00007ffff28526d6 in ?? ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#17 0x00007ffff2852b69 in QGraphicsScene::mousePressEvent(QGraphicsSceneMouseEve---Type <return> to continue, or q <return> to quit---\nnt*) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#18 0x00007ffff285b9b0 in QGraphicsScene::event(QEvent*) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#19 0x00007ffff22a8f7c in QApplicationPrivate::notify_helper(QObject*, QEvent*)\n    ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#20 0x00007ffff22af540 in QApplication::notify(QObject*, QEvent*) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#21 0x000000000047923b in SteamshovelApp::notify(QObject*, QEvent*) ()\n#22 0x00007ffff1d44a0d in QCoreApplication::notifyInternal(QObject*, QEvent*)\n    ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4\n#23 0x00007ffff287230f in QGraphicsView::mousePressEvent(QMouseEvent*) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#24 0x00007ffff22f82a8 in QWidget::event(QEvent*) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.---Type <return> to continue, or q <return> to quit---\nso.4\n#25 0x00007ffff2671f7e in QFrame::event(QEvent*) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#26 0x00007ffff2873069 in QGraphicsView::viewportEvent(QEvent*) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#27 0x00007ffff1d44b76 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4\n#28 0x00007ffff22a8f5c in QApplicationPrivate::notify_helper(QObject*, QEvent*)\n    ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#29 0x00007ffff22af67d in QApplication::notify(QObject*, QEvent*) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#30 0x000000000047923b in SteamshovelApp::notify(QObject*, QEvent*) ()\n#31 0x00007ffff1d44a0d in QCoreApplication::notifyInternal(QObject*, QEvent*)\n    ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4\n---Type <return> to continue, or q <return> to quit---\n#32 0x00007ffff22aee33 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#33 0x00007ffff231ff9b in ?? ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#34 0x00007ffff231ea41 in QApplication::x11ProcessEvent(_XEvent*) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#35 0x00007ffff2345040 in ?? ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtGui.so.4\n#36 0x00007ffff1d436df in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4\n#37 0x00007ffff1d439d5 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore.so.4\n#38 0x00007ffff1d48a89 in QCoreApplication::exec() ()\n   from /cvmfs/icecube.opensciencegrid.org/py2-v1/Ubuntu_14_x86_64/lib/libQtCore---Type <return> to continue, or q <return> to quit---\n.so.4\n#39 0x000000000045890e in main ()\n(gdb) \n}}}", 
    "reporter": "david.schultz", 
    "cc": "blaufuss", 
    "resolution": "fixed", 
    "_ts": "1425532495903787", 
    "component": "combo core", 
    "summary": "steamshovel - crash on ubuntu 14.04", 
    "priority": "major", 
    "keywords": "steamshovel", 
    "time": "2015-03-03T21:21:22", 
    "milestone": "", 
    "owner": "david.schultz", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20150305T05:14:55: 
* david.schultz commented:

> Adding a ```scripting::ScopedGIL``` to the function ```Scenario::fundUsableArtistsByKeys()``` allows me to advance past the first python artist, but not through all of them.
> 
> Grabbing the GIL in more places seems to fix the problem. This is incentive to actually do full support for the GIL in icetray.
> 
> Fixed? in r129822/IceCube.


* david.schultz changed status from "new" to "closed"
* david.schultz changed resolution from "" to "fixed"
