### ISSUE TITLE
PROPOSAL build fail due to missing tables in I3_TESTDATA (Trac #923)

### ISSUE THREAD

**Issue by icecube-trac** [icecube-trac/tix2#917]
when trying to build PROPOSAL in DEBUG mode compiler will fail due to missing directory in I3_TESTDATA that is tried to be accessed before tables were built:

```text
[ 50%] Generating resources/tables/.tables.auto_generated
FATAL (I3PropagatorService): /usr/local/test-data/PROPOSAL/resources/tables does not exist (I3PropagatorServicePROPOSAL.cxx:117 in static std::string I3PropagatorServicePROPOSAL::GetDefaultTableDir())
Traceback (most recent call last):
  File "resources/tables/generate_tables.py", line 6, in <module>
    from icecube.PROPOSAL import I3PropagatorServicePROPOSAL
RuntimeError: /usr/local/test-data/PROPOSAL/resources/tables does not exist (in static std::string I3PropagatorServicePROPOSAL::GetDefaultTableDir())
make[2]: *** [PROPOSAL/resources/tables/.tables.auto_generated] Error 1
make[1]: *** [PROPOSAL/CMakeFiles/PROPOSAL-tables.dir/all] Error 2
make: *** [all] Error 2
```

Migrated from https://code.icecube.wisc.edu/ticket/923
```json
{
    "status": "closed", 
    "changetime": "2015-04-13T16:20:55", 
    "description": "when trying to build PROPOSAL in DEBUG mode compiler will fail due to missing directory in I3_TESTDATA that is tried to be accessed before tables were built:\n\n{{{\n[ 50%] Generating resources/tables/.tables.auto_generated\nFATAL (I3PropagatorService): /usr/local/test-data/PROPOSAL/resources/tables does not exist (I3PropagatorServicePROPOSAL.cxx:117 in static std::string I3PropagatorServicePROPOSAL::GetDefaultTableDir())\nTraceback (most recent call last):\n  File \"resources/tables/generate_tables.py\", line 6, in <module>\n    from icecube.PROPOSAL import I3PropagatorServicePROPOSAL\nRuntimeError: /usr/local/test-data/PROPOSAL/resources/tables does not exist (in static std::string I3PropagatorServicePROPOSAL::GetDefaultTableDir())\nmake[2]: *** [PROPOSAL/resources/tables/.tables.auto_generated] Error 1\nmake[1]: *** [PROPOSAL/CMakeFiles/PROPOSAL-tables.dir/all] Error 2\nmake: *** [all] Error 2\n}}}", 
    "reporter": "musner", 
    "cc": "", 
    "resolution": "invalid", 
    "_ts": "1428942055132091", 
    "component": "combo simulation", 
    "summary": "PROPOSAL build fail due to missing tables in I3_TESTDATA", 
    "priority": "normal", 
    "keywords": "", 
    "time": "2015-04-10T11:11:48", 
    "milestone": "", 
    "owner": "nega", 
    "type": "defect"
}
```

**Comment by icecube-trac** [comment]
Trac update at 20150410T14:26:39: nega commented:

> run `make rsync`

**Comment by icecube-trac** [comment]
Trac update at 20150413T12:34:48: musner commented:

> right, then someone with write permissions should do that for the I3_TEST_DATA located in cvmfs, because as it is, this still does not compile on any of the cobalt nodes:
> 
> 
> ```text
> [ 47%] Generating resources/tables/.tables.auto_generated
> FATAL (I3PropagatorService): /cvmfs/icecube.opensciencegrid.org/standard/RHEL_6_x86_64/i3ports/test-data/PROPOSAL/resources/tables does not exist (I3PropagatorServicePROPOSAL.cxx:117 in static std::string I3PropagatorServicePROPOSAL::GetDefaultTableDir())
> Traceback (most recent call last):
>   File "resources/tables/generate_tables.py", line 6, in <module>
>     from icecube.PROPOSAL import I3PropagatorServicePROPOSAL
> RuntimeError: /cvmfs/icecube.opensciencegrid.org/standard/RHEL_6_x86_64/i3ports/test-data/PROPOSAL/resources/tables does not exist (in static std::string I3PropagatorServicePROPOSAL::GetDefaultTableDir())
> make[2]: *** [PROPOSAL/resources/tables/.tables.auto_generated] Error 1
> make[1]: *** [PROPOSAL/CMakeFiles/PROPOSAL-tables.dir/all] Error 2
> make: *** [all] Error 2
> ```

**Comment by icecube-trac** [comment]
Trac update at 20150413T14:54:50: 
* nega commented:

> Send a note to [mailto:helpdesk@icecube.wisc.edu]. In the interim set `I3_TESTDATA` to a directory you can write to and run `make rsync`.


* nega changed resolution from "" to "invalid"
* nega changed status from "new" to "closed"

**Comment by icecube-trac** [comment]
Trac update at 20150413T16:20:55: nega changed description from:

> when trying to build PROPOSAL in DEBUG mode compiler will fail due to missing directory in I3_TESTDATA that is tried to be accessed before tables were built:
> 
> [ 50%] Generating resources/tables/.tables.auto_generated
> FATAL (I3PropagatorService): /usr/local/test-data/PROPOSAL/resources/tables does not exist (I3PropagatorServicePROPOSAL.cxx:117 in static std::string I3PropagatorServicePROPOSAL::GetDefaultTableDir())
> Traceback (most recent call last):
>   File "resources/tables/generate_tables.py", line 6, in <module>
>     from icecube.PROPOSAL import I3PropagatorServicePROPOSAL
> RuntimeError: /usr/local/test-data/PROPOSAL/resources/tables does not exist (in static std::string I3PropagatorServicePROPOSAL::GetDefaultTableDir())
> make[2]: *** [PROPOSAL/resources/tables/.tables.auto_generated] Error 1
> make[1]: *** [PROPOSAL/CMakeFiles/PROPOSAL-tables.dir/all] Error 2
> make: *** [all] Error 2

to:

> when trying to build PROPOSAL in DEBUG mode compiler will fail due to missing directory in I3_TESTDATA that is tried to be accessed before tables were built:
> 
> {{{
> [ 50%] Generating resources/tables/.tables.auto_generated
> FATAL (I3PropagatorService): /usr/local/test-data/PROPOSAL/resources/tables does not exist (I3PropagatorServicePROPOSAL.cxx:117 in static std::string I3PropagatorServicePROPOSAL::GetDefaultTableDir())
> Traceback (most recent call last):
>   File "resources/tables/generate_tables.py", line 6, in <module>
>     from icecube.PROPOSAL import I3PropagatorServicePROPOSAL
> RuntimeError: /usr/local/test-data/PROPOSAL/resources/tables does not exist (in static std::string I3PropagatorServicePROPOSAL::GetDefaultTableDir())
> make[2]: *** [PROPOSAL/resources/tables/.tables.auto_generated] Error 1
> make[1]: *** [PROPOSAL/CMakeFiles/PROPOSAL-tables.dir/all] Error 2
> make: *** [all] Error 2
> }}}
